# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import PyXmlIO
import NodegraphAPI.Xio as Xio
from NodegraphAPI.Version.Updater import Updater as Updater
from typing import ClassVar

_Version: tuple

class Updater4013(Updater):
    VERSION: ClassVar[tuple] = ...
    def _Updater4013__upgradeLightPackageGroupNode(self, groupNode: PyXmlIO.Element): ...
    def _Updater4013__upgradeMasterMaterialPackageGroupNode(self, groupNode: PyXmlIO.Element): ...
    def _Updater4013__upgradeRigPackageGroupNode(self, groupNode: PyXmlIO.Element): ...
    def _Updater4013__upgradeSkyDomePackageGroupNode(self, groupNode: PyXmlIO.Element): ...
    def upgrade_GafferThree(self, gafferThreeNode: PyXmlIO.Element): ...