# mypy: disable-error-code="misc, override, no-redef"

import pxr.Gf as Gf
import pxr.Ts as Ts
from pxr.Ts.TsTest_Comparator import TsTest_Comparator as TsTest_Comparator
from pxr.Ts.TsTest_Grapher import TsTest_Grapher as TsTest_Grapher

class _Baseliner:
    def __init__(self, testName, splineData, samples, precision) -> None: ...
    def Validate(self): ...
    def _ReadBaseline(self, infile, path): ...
    def _ValidateInputs(self): ...
    def _ValidateValues(self): ...
    def _WriteBaseline(self): ...
    def _WriteCandidates(self): ...
    def _WriteDiffGraph(self): ...
    def _WriteSingleGraph(self): ...

def TsTest_CompareBaseline(testName, splineData, samples, precision: int = ...): ...
