from PySide2 import QtWidgets

class PatchSelectorDialog(QtWidgets.QDialog):
    def __init__(self, parent, geoEntity) -> None: ...
    @property
    def selectedPatches(self): ...
    @selectedPatches.setter
    def selectedPatches(self, selectedPatches) -> None: ...
