import pxr.Ar as Ar
import pxr.Glf as Glf
import PySide6.QtCore
import pxr.Sdf as Sdf
import pxr.Tf as Tf
import pxr.Usd as Usd
import pxr.UsdAppUtils as UsdAppUtils
import pxr.UsdGeom as UsdGeom
import pxr.UsdImagingGL as UsdImagingGL
import pxr.UsdShade as UsdShade
import pxr.UsdUtils as UsdUtils
import pxr.Usdviewq.adjustDefaultMaterial as adjustDefaultMaterial
import pxr.Usdviewq.adjustFreeCamera as adjustFreeCamera
import pxr.Usdviewq.plugin as plugin
import pxr.Usdviewq.preferences as preferences
import pxr.Usdviewq.prettyPrint as prettyPrint
from pxr.UsdAppUtils.complexityArgs import RefinementComplexities as RefinementComplexities
from pxr.UsdUtils.constantsGroup import ConstantsGroup as ConstantsGroup
from pxr.Usdviewq import Utils as Utils
from pxr.Usdviewq.attributeViewContextMenu import AttributeViewContextMenu as AttributeViewContextMenu
from pxr.Usdviewq.common import BusyContext as BusyContext, CameraMaskModes as CameraMaskModes, ClearColors as ClearColors, ColorCorrectionModes as ColorCorrectionModes, Drange as Drange, DumpMallocTags as DumpMallocTags, GetAssetCreationTime as GetAssetCreationTime, GetEnclosingModelPrim as GetEnclosingModelPrim, GetPrimsLoadability as GetPrimsLoadability, GetPropertyColor as GetPropertyColor, GetPropertyTextFont as GetPropertyTextFont, GetRootLayerStackInfo as GetRootLayerStackInfo, GetValueAndDisplayString as GetValueAndDisplayString, HasSessionVis as HasSessionVis, HighlightColors as HighlightColors, InvisRootPrims as InvisRootPrims, KeyboardShortcuts as KeyboardShortcuts, LayerInfo as LayerInfo, PickModes as PickModes, PrimNotFoundException as PrimNotFoundException, PrintWarning as PrintWarning, PropTreeWidgetTypeIsRel as PropTreeWidgetTypeIsRel, PropertyViewDataRoles as PropertyViewDataRoles, PropertyViewIcons as PropertyViewIcons, PropertyViewIndex as PropertyViewIndex, RenderModes as RenderModes, ResetSessionVisibility as ResetSessionVisibility, SelectionHighlightModes as SelectionHighlightModes, ShadedRenderModes as ShadedRenderModes, Timer as Timer, UIBaseColors as UIBaseColors, UIFonts as UIFonts, UIPropertyValueSourceColors as UIPropertyValueSourceColors
from pxr.Usdviewq.configController import ConfigController as ConfigController
from pxr.Usdviewq.customAttributes import BoundingBoxAttribute as BoundingBoxAttribute, CustomAttribute as CustomAttribute, LocalToWorldXformAttribute as LocalToWorldXformAttribute, ResolvedBoundMaterial as ResolvedBoundMaterial, _GetCustomAttributes as _GetCustomAttributes
from pxr.Usdviewq.headerContextMenu import HeaderContextMenu as HeaderContextMenu
from pxr.Usdviewq.layerStackContextMenu import LayerStackContextMenu as LayerStackContextMenu
from pxr.Usdviewq.legendUtil import ToggleLegendWithBrowser as ToggleLegendWithBrowser
from pxr.Usdviewq.mainWindowUI import Ui_MainWindow as Ui_MainWindow
from pxr.Usdviewq.primContextMenu import PrimContextMenu as PrimContextMenu
from pxr.Usdviewq.primTreeWidget import PrimTreeWidget as PrimTreeWidget
from pxr.Usdviewq.primViewItem import PrimViewColumnIndex as PrimViewColumnIndex, PrimViewItem as PrimViewItem
from pxr.Usdviewq.pythonInterpreter import Myconsole as Myconsole
from pxr.Usdviewq.rootDataModel import ChangeNotice as ChangeNotice, RootDataModel as RootDataModel
from pxr.Usdviewq.selectionDataModel import SelectionDataModel as SelectionDataModel
from pxr.Usdviewq.settings import ConfigManager as ConfigManager, StateSource as StateSource
from pxr.Usdviewq.stageView import StageView as StageView
from pxr.Usdviewq.usdviewApi import UsdviewApi as UsdviewApi
from pxr.Usdviewq.variantComboBox import VariantComboBox as VariantComboBox
from pxr.Usdviewq.viewSettingsDataModel import ViewSettingsDataModel as ViewSettingsDataModel
from typing import Any, Callable, ClassVar

class AppController(PySide6.QtCore.QObject):
    __init__: ClassVar[Callable] = ...
    GrabViewportShot: ClassVar[Callable] = ...
    GrabWindowShot: ClassVar[Callable] = ...
    _HUDInfoChanged: ClassVar[Callable] = ...
    _UpdateTimeSamples: ClassVar[Callable] = ...
    _accountForFlattening: ClassVar[Callable] = ...
    _addRichTextIndicators: ClassVar[Callable] = ...
    _adjustDefaultMaterial: ClassVar[Callable] = ...
    _adjustFreeCamera: ClassVar[Callable] = ...
    _advanceFrame: ClassVar[Callable] = ...
    _advanceFrameForPlayback: ClassVar[Callable] = ...
    _ambientOnlyClicked: ClassVar[Callable] = ...
    _applyMoreRendererSettings: ClassVar[Callable] = ...
    _applyStageOpenLayerMutes: ClassVar[Callable] = ...
    _attrViewFindNext: ClassVar[Callable] = ...
    _cacheViewerModeEscapeSizes: ClassVar[Callable] = ...
    _calculateGeomCounts: ClassVar[Callable] = ...
    _cameraSelectionChanged: ClassVar[Callable] = ...
    _changeBgColor: ClassVar[Callable] = ...
    _changeColorCorrection: ClassVar[Callable] = ...
    _changeComplexity: ClassVar[Callable] = ...
    _changeHighlightColor: ClassVar[Callable] = ...
    _changeInterpolationType: ClassVar[Callable] = ...
    _changePickMode: ClassVar[Callable] = ...
    _changePrimViewDepth: ClassVar[Callable] = ...
    _changeRenderMode: ClassVar[Callable] = ...
    _changeSelHighlightMode: ClassVar[Callable] = ...
    _cleanAndClose: ClassVar[Callable] = ...
    _cleanStr: ClassVar[Callable] = ...
    _clearCaches: ClassVar[Callable] = ...
    _clearGeomCountsForPrimPath: ClassVar[Callable] = ...
    _closeStage: ClassVar[Callable] = ...
    _comparePaths: ClassVar[Callable] = ...
    _compositionTreeContextMenu: ClassVar[Callable] = ...
    _computeDisplayPredicate: ClassVar[Callable] = ...
    _configureColorManagement: ClassVar[Callable] = ...
    _configurePauseAction: ClassVar[Callable] = ...
    _configurePlugins: ClassVar[Callable] = ...
    _configureRendererAovs: ClassVar[Callable] = ...
    _configureRendererCommands: ClassVar[Callable] = ...
    _configureRendererPlugins: ClassVar[Callable] = ...
    _configureRendererSettings: ClassVar[Callable] = ...
    _configureStopAction: ClassVar[Callable] = ...
    _copyViewerImage: ClassVar[Callable] = ...
    _currentPathChanged: ClassVar[Callable] = ...
    _decrementComplexity: ClassVar[Callable] = ...
    _disableOCIOAction: ClassVar[Callable] = ...
    _displayPurposeChanged: ClassVar[Callable] = ...
    _drawFirstImage: ClassVar[Callable] = ...
    _expandPrims: ClassVar[Callable] = ...
    _expandToDepth: ClassVar[Callable] = ...
    _findClosestFrameIndex: ClassVar[Callable] = ...
    _findIndentPos: ClassVar[Callable] = ...
    _findPrims: ClassVar[Callable] = ...
    _formatMetadataValueView: ClassVar[Callable] = ...
    _frameSelection: ClassVar[Callable] = ...
    _frameStringChanged: ClassVar[Callable] = ...
    _getCommonPrims: ClassVar[Callable] = ...
    _getExpandedPrimViewPrims: ClassVar[Callable] = ...
    _getFilteredChildren: ClassVar[Callable] = ...
    _getGeomCounts: ClassVar[Callable] = ...
    _getHUDStatKeys: ClassVar[Callable] = ...
    _getItemAtPath: ClassVar[Callable] = ...
    _getPathsFromItems: ClassVar[Callable] = ...
    _getPrimFromPropString: ClassVar[Callable] = ...
    _getPrimsFromPaths: ClassVar[Callable] = ...
    _getPropertiesDict: ClassVar[Callable] = ...
    _getSaveFileName: ClassVar[Callable] = ...
    _getSelectedObject: ClassVar[Callable] = ...
    _incrementComplexity: ClassVar[Callable] = ...
    _invokeRendererCommand: ClassVar[Callable] = ...
    _isHUDVisible: ClassVar[Callable] = ...
    _isMatch: ClassVar[Callable] = ...
    _itemClicked: ClassVar[Callable] = ...
    _itemPressed: ClassVar[Callable] = ...
    _layerStackContextMenu: ClassVar[Callable] = ...
    _limitToolTipSize: ClassVar[Callable] = ...
    _limitValueDisplaySize: ClassVar[Callable] = ...
    _makeTimer: ClassVar[Callable] = ...
    _maxToolTipHeight: ClassVar[Callable] = ...
    _maxToolTipWidth: ClassVar[Callable] = ...
    _moreRendererSettings: ClassVar[Callable] = ...
    _onCompositionSelectionChanged: ClassVar[Callable] = ...
    _onDomeLightClicked: ClassVar[Callable] = ...
    _onDomeLightTexturesVisibleClicked: ClassVar[Callable] = ...
    _onPrimsChanged: ClassVar[Callable] = ...
    _openFile: ClassVar[Callable] = ...
    _openSettings: ClassVar[Callable] = ...
    _openStage: ClassVar[Callable] = ...
    _otherAov: ClassVar[Callable] = ...
    _outputBaseDirectory: ClassVar[method] = ...
    _pickCameraMaskColor: ClassVar[Callable] = ...
    _pickCameraReticlesColor: ClassVar[Callable] = ...
    _playClicked: ClassVar[Callable] = ...
    _populateChildren: ClassVar[Callable] = ...
    _populateItem: ClassVar[Callable] = ...
    _populatePropertyInspector: ClassVar[Callable] = ...
    _populateRoots: ClassVar[Callable] = ...
    _primLegendToggleCollapse: ClassVar[Callable] = ...
    _primSelectionChanged: ClassVar[Callable] = ...
    _primViewContextMenu: ClassVar[Callable] = ...
    _primViewExpanded: ClassVar[Callable] = ...
    _primViewFindNext: ClassVar[Callable] = ...
    _primViewHeaderContextMenu: ClassVar[Callable] = ...
    _primsFromSelectionRanges: ClassVar[Callable] = ...
    _propSelectionChanged: ClassVar[Callable] = ...
    _propertyLegendToggleCollapse: ClassVar[Callable] = ...
    _propertyViewContextMenu: ClassVar[Callable] = ...
    _propertyViewCurrentItemChanged: ClassVar[Callable] = ...
    _propertyViewDeselectItem: ClassVar[Callable] = ...
    _propertyViewHeaderContextMenu: ClassVar[Callable] = ...
    _propertyViewSelectionChanged: ClassVar[Callable] = ...
    _rangeBeginChanged: ClassVar[Callable] = ...
    _rangeEndChanged: ClassVar[Callable] = ...
    _redrawOptionToggled: ClassVar[Callable] = ...
    _refreshAttributeValue: ClassVar[Callable] = ...
    _refreshBBox: ClassVar[Callable] = ...
    _refreshBBoxMenu: ClassVar[Callable] = ...
    _refreshCameraGuidesMenu: ClassVar[Callable] = ...
    _refreshCameraListAndMenu: ClassVar[Callable] = ...
    _refreshCameraMaskMenu: ClassVar[Callable] = ...
    _refreshCameraMenu: ClassVar[Callable] = ...
    _refreshCameraReticlesMenu: ClassVar[Callable] = ...
    _refreshClearColorsMenu: ClassVar[Callable] = ...
    _refreshColorCorrectionModeMenu: ClassVar[Callable] = ...
    _refreshComplexityMenu: ClassVar[Callable] = ...
    _refreshDisplayPurposesMenu: ClassVar[Callable] = ...
    _refreshHUDMenu: ClassVar[Callable] = ...
    _refreshLightsMenu: ClassVar[Callable] = ...
    _refreshPickModeMenu: ClassVar[Callable] = ...
    _refreshPrimViewSelection: ClassVar[Callable] = ...
    _refreshRedrawOnScrub: ClassVar[Callable] = ...
    _refreshRenderModeMenu: ClassVar[Callable] = ...
    _refreshRolloverPrimInfoMenu: ClassVar[Callable] = ...
    _refreshSelectionHighlightColorMenu: ClassVar[Callable] = ...
    _refreshSelectionHighlightingMenu: ClassVar[Callable] = ...
    _refreshShowPrimMenu: ClassVar[Callable] = ...
    _refreshViewMenu: ClassVar[Callable] = ...
    _refreshViewMenubar: ClassVar[Callable] = ...
    _reloadFixedUI: ClassVar[Callable] = ...
    _reloadStage: ClassVar[Callable] = ...
    _reloadVaryingUI: ClassVar[Callable] = ...
    _rendererAovChanged: ClassVar[Callable] = ...
    _rendererPluginChanged: ClassVar[Callable] = ...
    _rendererSettingsFlagChanged: ClassVar[Callable] = ...
    _reopenStage: ClassVar[Callable] = ...
    _resetGUI: ClassVar[Callable] = ...
    _resetMoreRendererSettings: ClassVar[Callable] = ...
    _resetPrimView: ClassVar[Callable] = ...
    _resetPrimViewVis: ClassVar[Callable] = ...
    _resetSettings: ClassVar[Callable] = ...
    _resetView: ClassVar[Callable] = ...
    _resizePrimView: ClassVar[Callable] = ...
    _retreatFrame: ClassVar[Callable] = ...
    _saveFlattenedAs: ClassVar[Callable] = ...
    _saveOverridesAs: ClassVar[Callable] = ...
    _saveViewerImage: ClassVar[Callable] = ...
    _scheduleResizePrimView: ClassVar[Callable] = ...
    _selectionChanged: ClassVar[Callable] = ...
    _setComplexity: ClassVar[Callable] = ...
    _setFrameIndex: ClassVar[Callable] = ...
    _setPlayShortcut: ClassVar[Callable] = ...
    _setPlaybackAvailability: ClassVar[Callable] = ...
    _setSelectedPrimsActivation: ClassVar[Callable] = ...
    _setStyleSheetUsingState: ClassVar[Callable] = ...
    _setUseExtentsHint: ClassVar[Callable] = ...
    _setupCustomFont: ClassVar[Callable] = ...
    _showDebugFlags: ClassVar[Callable] = ...
    _showHUDChanged: ClassVar[Callable] = ...
    _showHUD_ComplexityChanged: ClassVar[Callable] = ...
    _showHUD_GPUstatsChanged: ClassVar[Callable] = ...
    _showHUD_InfoChanged: ClassVar[Callable] = ...
    _showHUD_PerformanceChanged: ClassVar[Callable] = ...
    _showHydraSceneBrowser: ClassVar[Callable] = ...
    _showInterpreter: ClassVar[Callable] = ...
    _showPrimContextMenu: ClassVar[Callable] = ...
    _sliderMoved: ClassVar[Callable] = ...
    _startQtShutdownTimer: ClassVar[Callable] = ...
    _stepSizeChanged: ClassVar[Callable] = ...
    _stopQtShutdownTimer: ClassVar[Callable] = ...
    _storeAndReturnViewState: ClassVar[Callable] = ...
    _tallyPrimStats: ClassVar[Callable] = ...
    _toggleAutoComputeClippingPlanes: ClassVar[Callable] = ...
    _toggleCullBackfaces: ClassVar[Callable] = ...
    _toggleDisplayCameraOracles: ClassVar[Callable] = ...
    _toggleDisplayGuide: ClassVar[Callable] = ...
    _toggleDisplayPrimId: ClassVar[Callable] = ...
    _toggleDisplayProxy: ClassVar[Callable] = ...
    _toggleDisplayRender: ClassVar[Callable] = ...
    _toggleEnableSceneLights: ClassVar[Callable] = ...
    _toggleEnableSceneMaterials: ClassVar[Callable] = ...
    _toggleFramedView: ClassVar[Callable] = ...
    _togglePause: ClassVar[Callable] = ...
    _togglePreferences: ClassVar[Callable] = ...
    _toggleRolloverPrimInfo: ClassVar[Callable] = ...
    _toggleShowAABBox: ClassVar[Callable] = ...
    _toggleShowAbstractPrims: ClassVar[Callable] = ...
    _toggleShowBBoxPlayback: ClassVar[Callable] = ...
    _toggleShowBBoxes: ClassVar[Callable] = ...
    _toggleShowInactivePrims: ClassVar[Callable] = ...
    _toggleShowOBBox: ClassVar[Callable] = ...
    _toggleShowPrimDisplayName: ClassVar[Callable] = ...
    _toggleShowPrototypePrims: ClassVar[Callable] = ...
    _toggleShowUndefinedPrims: ClassVar[Callable] = ...
    _toggleStop: ClassVar[Callable] = ...
    _toggleViewerMode: ClassVar[Callable] = ...
    _trimWidth: ClassVar[Callable] = ...
    _updateCameraMaskMenu: ClassVar[Callable] = ...
    _updateCameraMaskOutlineMenu: ClassVar[Callable] = ...
    _updateCameraReticlesInsideMenu: ClassVar[Callable] = ...
    _updateCameraReticlesOutsideMenu: ClassVar[Callable] = ...
    _updateCompositionView: ClassVar[Callable] = ...
    _updateEditMenu: ClassVar[Callable] = ...
    _updateForStageChanges: ClassVar[Callable] = ...
    _updateGUIForFrameChange: ClassVar[Callable] = ...
    _updateHUDGeomCounts: ClassVar[Callable] = ...
    _updateHUDPrimStats: ClassVar[Callable] = ...
    _updateLayerStackView: ClassVar[Callable] = ...
    _updateMetadataView: ClassVar[Callable] = ...
    _updateNavigationMenu: ClassVar[Callable] = ...
    _updateOnFrameChange: ClassVar[Callable] = ...
    _updatePrimPathText: ClassVar[Callable] = ...
    _updatePrimView: ClassVar[Callable] = ...
    _updatePrimViewSelection: ClassVar[Callable] = ...
    _updatePropertiesFromPropertyView: ClassVar[Callable] = ...
    _updatePropertyInspector: ClassVar[Callable] = ...
    _updatePropertyView: ClassVar[Callable] = ...
    _updatePropertyViewInternal: ClassVar[Callable] = ...
    _updatePropertyViewSelection: ClassVar[Callable] = ...
    _viewSettingChanged: ClassVar[Callable] = ...
    activateSelectedPrims: ClassVar[Callable] = ...
    clearSettings: ClassVar[method] = ...
    deactivateSelectedPrims: ClassVar[Callable] = ...
    editComplete: ClassVar[Callable] = ...
    getActiveCamera: ClassVar[Callable] = ...
    getSelectedItems: ClassVar[Callable] = ...
    invisSelectedPrims: ClassVar[Callable] = ...
    isViewerMode: ClassVar[Callable] = ...
    loadSelectedPrims: ClassVar[Callable] = ...
    onPrimSelected: ClassVar[Callable] = ...
    onRollover: ClassVar[Callable] = ...
    onStageViewMouseDrag: ClassVar[Callable] = ...
    processNavKeyEvent: ClassVar[Callable] = ...
    removeVisSelectedPrims: ClassVar[Callable] = ...
    resetSessionVisibility: ClassVar[Callable] = ...
    saveFrame: ClassVar[Callable] = ...
    selectBindingRelForPurpose: ClassVar[Callable] = ...
    selectBoundFullMaterial: ClassVar[Callable] = ...
    selectBoundMaterialForPurpose: ClassVar[Callable] = ...
    selectBoundPreviewMaterial: ClassVar[Callable] = ...
    selectEnclosingModel: ClassVar[Callable] = ...
    selectFullBindingRel: ClassVar[Callable] = ...
    selectPreviewBindingRel: ClassVar[Callable] = ...
    selectPseudoroot: ClassVar[Callable] = ...
    setFrame: ClassVar[Callable] = ...
    setFrameField: ClassVar[Callable] = ...
    setViewerMode: ClassVar[Callable] = ...
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...
    statusMessage: ClassVar[Callable] = ...
    unloadSelectedPrims: ClassVar[Callable] = ...
    updateGUI: ClassVar[Callable] = ...
    visOnlySelectedPrims: ClassVar[Callable] = ...
    visSelectedPrims: ClassVar[Callable] = ...
    __del__: ClassVar[Callable] = ...

class Blocker:
    __init__: ClassVar[Callable] = ...
    blocked: ClassVar[Callable] = ...
    __enter__: ClassVar[Callable] = ...
    __exit__: ClassVar[Callable] = ...

class HUDEntries(ConstantsGroup):
    CV: ClassVar[str] = ...
    FACE: ClassVar[str] = ...
    GETBOUNDS: ClassVar[str] = ...
    NOTYPE: ClassVar[str] = ...
    PLAYBACK: ClassVar[str] = ...
    PRIM: ClassVar[str] = ...
    RENDER: ClassVar[str] = ...
    VERT: ClassVar[str] = ...
    _all: ClassVar[tuple] = ...

class LayerStackViewColumnIndex(ConstantsGroup):
    LAYER: ClassVar[int] = ...
    OFFSET: ClassVar[int] = ...
    PATH: ClassVar[int] = ...
    VALUE: ClassVar[int] = ...
    _all: ClassVar[tuple] = ...

class MainWindow(PySide6.QtWidgets.QMainWindow):
    __init__: ClassVar[Callable] = ...
    closeEvent: ClassVar[Callable] = ...
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...

class PropertyIndex(ConstantsGroup):
    COMPOSITION: ClassVar[int] = ...
    LAYERSTACK: ClassVar[int] = ...
    METADATA: ClassVar[int] = ...
    VALUE: ClassVar[int] = ...
    _all: ClassVar[tuple] = ...

class UIDefaults(ConstantsGroup):
    ATTRIBUTE_INSPECTOR_WIDTH: ClassVar[int] = ...
    ATTRIBUTE_VIEW_WIDTH: ClassVar[int] = ...
    BOTTOM_HEIGHT: ClassVar[int] = ...
    PRIM_VIEW_WIDTH: ClassVar[int] = ...
    STAGE_VIEW_WIDTH: ClassVar[int] = ...
    TOP_HEIGHT: ClassVar[int] = ...
    _all: ClassVar[tuple] = ...

class UIStateProxySource(StateSource):
    __init__: ClassVar[Callable] = ...
    onSaveState: ClassVar[Callable] = ...

class UsdviewDataModel(RootDataModel):
    __init__: ClassVar[Callable] = ...
    _emitPrimsChanged: ClassVar[Callable] = ...
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...
    @property
    def selection(self) -> Any: ...
    @property
    def viewSettings(self) -> Any: ...