import PySide6.QtCore
from pxr.Usdviewq.common import KeyboardShortcuts as KeyboardShortcuts
from typing import Callable, ClassVar

class AppEventFilter(PySide6.QtCore.QObject):
    __init__: ClassVar[Callable] = ...
    IsNavKey: ClassVar[Callable] = ...
    JealousFocus: ClassVar[Callable] = ...
    NavigableOrTopLevelObject: ClassVar[Callable] = ...
    SetFocusFromMousePos: ClassVar[Callable] = ...
    TopLevelWindow: ClassVar[Callable] = ...
    WantsNavKeys: ClassVar[Callable] = ...
    _IsWindow: ClassVar[Callable] = ...
    eventFilter: ClassVar[Callable] = ...
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...