import PySide6.QtWidgets
from typing import Any, Callable, ClassVar

_GetLengthOfRange: Callable
_GetSliceFromString: Callable
_IntOrNone: Callable

class ArrayAttributeView(PySide6.QtWidgets.QWidget):
    __init__: ClassVar[Callable] = ...
    CanView: ClassVar[Callable] = ...
    CopyAll: ClassVar[Callable] = ...
    CopySelected: ClassVar[Callable] = ...
    SelectAll: ClassVar[Callable] = ...
    SetAttribute: ClassVar[Callable] = ...
    _CopyValsToClipboard: ClassVar[Callable] = ...
    _SetupContextMenu: ClassVar[Callable] = ...
    _ShowContextMenu: ClassVar[Callable] = ...
    keyPressEvent: ClassVar[Callable] = ...
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...

class _ArrayAttributeModel(PySide6.QtCore.QAbstractListModel):
    __init__: ClassVar[Callable] = ...
    GetArrayData: ClassVar[Callable] = ...
    GetScalarTypeName: ClassVar[Callable] = ...
    RawDataRole: ClassVar[int] = ...
    SetArrayDataAndTypeName: ClassVar[Callable] = ...
    SetSlice: ClassVar[Callable] = ...
    TryToFetchMore: ClassVar[Callable] = ...
    _Reset: ClassVar[Callable] = ...
    canFetchMore: ClassVar[Callable] = ...
    columnCount: ClassVar[Callable] = ...
    data: ClassVar[Callable] = ...
    fetchMore: ClassVar[Callable] = ...
    index: ClassVar[Callable] = ...
    parent: ClassVar[Callable] = ...
    rowCount: ClassVar[Callable] = ...
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...

class _SliceLineEdit(PySide6.QtWidgets.QLineEdit):
    class Validator(PySide6.QtGui.QValidator):
        staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...
        validate: ClassVar[Callable] = ...
    __init__: ClassVar[Callable] = ...
    _OnEditingFinished: ClassVar[Callable] = ...
    setText: ClassVar[Callable] = ...
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...
    def SliceChanged(self, *args, **kwargs) -> Any: ...