# mypy: disable-error-code="misc, override, no-redef"

import PySide6.QtCore
import PySide6.QtWidgets
import pxr.Sdf as Sdf
import pxr.Usdviewq.usdviewContextMenuItem
from pxr.Usdviewq.common import PrimNotFoundException as PrimNotFoundException, PropertyNotFoundException as PropertyNotFoundException, PropertyViewDataRoles as PropertyViewDataRoles, PropertyViewIndex as PropertyViewIndex
from pxr.Usdviewq.usdviewContextMenuItem import UsdviewContextMenuItem as UsdviewContextMenuItem
from typing import ClassVar

class AttributeViewContextMenu(PySide6.QtWidgets.QMenu):
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent, item, dataModel): ...

class AttributeViewContextMenuItem(pxr.Usdviewq.usdviewContextMenuItem.UsdviewContextMenuItem):
    def __init__(self, dataModel, item): ...
    def GetText(self): ...
    def IsEnabled(self): ...
    def RunCommand(self): ...
    def ShouldDisplay(self): ...

class CopyAllTargetPathsMenuItem(SelectAllTargetPathsMenuItem):
    def GetText(self): ...
    def RunCommand(self): ...

class CopyAttributeNameMenuItem(AttributeViewContextMenuItem):
    def GetText(self): ...
    def RunCommand(self): ...
    def ShouldDisplay(self): ...

class CopyAttributeValueMenuItem(AttributeViewContextMenuItem):
    def GetText(self): ...
    def RunCommand(self): ...
    def ShouldDisplay(self): ...

class CopyTargetPathMenuItem(AttributeViewContextMenuItem):
    def GetSelectedOfType(self): ...
    def GetText(self): ...
    def RunCommand(self): ...
    def ShouldDisplay(self): ...

class SelectAllTargetPathsMenuItem(AttributeViewContextMenuItem):
    def GetText(self): ...
    def IsEnabled(self): ...
    def RunCommand(self): ...
    def ShouldDisplay(self): ...

class SelectTargetPathMenuItem(CopyTargetPathMenuItem):
    def GetText(self): ...
    def RunCommand(self): ...

def _GetContextMenuItems(item, dataModel): ...
def _GetTargetPathsForItem(item): ...
def _selectPrimsAndProps(dataModel, paths): ...
