import PySide6.QtWidgets
import pxr.Sdf as Sdf
from pxr.Usdviewq.common import PrimNotFoundException as PrimNotFoundException, PropertyNotFoundException as PropertyNotFoundException, PropertyViewDataRoles as PropertyViewDataRoles, PropertyViewIndex as PropertyViewIndex
from pxr.Usdviewq.usdviewContextMenuItem import UsdviewContextMenuItem as UsdviewContextMenuItem
from typing import Callable, ClassVar

_GetContextMenuItems: Callable
_GetTargetPathsForItem: Callable
_selectPrimsAndProps: Callable

class AttributeViewContextMenu(PySide6.QtWidgets.QMenu):
    __init__: ClassVar[Callable] = ...
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...

class AttributeViewContextMenuItem(UsdviewContextMenuItem):
    __init__: ClassVar[Callable] = ...
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...
    ShouldDisplay: ClassVar[Callable] = ...

class CopyAllTargetPathsMenuItem(SelectAllTargetPathsMenuItem):
    GetText: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class CopyAttributeNameMenuItem(AttributeViewContextMenuItem):
    GetText: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...
    ShouldDisplay: ClassVar[Callable] = ...

class CopyAttributeValueMenuItem(AttributeViewContextMenuItem):
    GetText: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...
    ShouldDisplay: ClassVar[Callable] = ...

class CopyTargetPathMenuItem(AttributeViewContextMenuItem):
    GetSelectedOfType: ClassVar[Callable] = ...
    GetText: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...
    ShouldDisplay: ClassVar[Callable] = ...

class SelectAllTargetPathsMenuItem(AttributeViewContextMenuItem):
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...
    ShouldDisplay: ClassVar[Callable] = ...

class SelectTargetPathMenuItem(CopyTargetPathMenuItem):
    GetText: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...