import PySide6.QtWidgets
import pxr.Usd as Usd
from pxr.Usdviewq.attributeValueEditorUI import Ui_AttributeValueEditor as Ui_AttributeValueEditor
from pxr.Usdviewq.common import GetPropertyColor as GetPropertyColor, UIPropertyValueSourceColors as UIPropertyValueSourceColors
from pxr.Usdviewq.scalarTypes import ToString as ToString
from typing import Any, Callable, ClassVar

class AttributeValueEditor(PySide6.QtWidgets.QWidget):
    __init__: ClassVar[Callable] = ...
    _FindView: ClassVar[Callable] = ...
    clear: ClassVar[Callable] = ...
    populate: ClassVar[Callable] = ...
    refresh: ClassVar[Callable] = ...
    setAppController: ClassVar[Callable] = ...
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...
    def editComplete(self, *args, **kwargs) -> Any: ...