import PySide6.QtWidgets
import pxr.Tf as Tf
from typing import Callable, ClassVar

_GetDebugFlagsWithPrefix: Callable

class DebugFlagsWidget(PySide6.QtWidgets.QWidget):
    __init__: ClassVar[Callable] = ...
    _onDebugFlagChecked: ClassVar[Callable] = ...
    _onFlagSelectionChanged: ClassVar[Callable] = ...
    _populateDebugFlagsListView: ClassVar[Callable] = ...
    _populateDebugFlagsTableView: ClassVar[Callable] = ...
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...