# mypy: disable_error_code = misc
import PySide6.QtWidgets
from pxr.Usdviewq.usdviewContextMenuItem import UsdviewContextMenuItem as UsdviewContextMenuItem
from typing import Any, ClassVar

class HeaderContextMenu(PySide6.QtWidgets.QMenu):
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent): ...
    def _prepForShow(self): ...

class HeaderContextMenuItem(UsdviewContextMenuItem):
    action: Any
    def __init__(self, parent, column): ...
    def GetText(self): ...
    def IsChecked(self): ...
    def IsEnabled(self): ...
    def RunCommand(self): ...

def _GetContextMenuItems(parent): ...