import pxr.Ar as Ar
import PySide6.QtWidgets
from pxr.UsdUtils.toolPaths import FindUsdBinary as FindUsdBinary
from pxr.Usdviewq.usdviewContextMenuItem import UsdviewContextMenuItem as UsdviewContextMenuItem
from typing import Callable, ClassVar

_GetContextMenuItems: Callable

class CopyLayerIdentifierMenuItem(LayerStackContextMenuItem):
    GetText: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class CopyLayerPathMenuItem(LayerStackContextMenuItem):
    GetText: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class CopyPathMenuItem(LayerStackContextMenuItem):
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class LayerStackContextMenu(PySide6.QtWidgets.QMenu):
    __init__: ClassVar[Callable] = ...
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...

class LayerStackContextMenuItem(UsdviewContextMenuItem):
    __init__: ClassVar[Callable] = ...
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class MuteOrUnmuteLayerMenuItem(LayerStackContextMenuItem):
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class OpenLayerMenuItem(LayerStackContextMenuItem):
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class UsdviewLayerMenuItem(LayerStackContextMenuItem):
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...