from pxr.Usdviewq.usdviewContextMenuItem import UsdviewContextMenuItem as UsdviewContextMenuItem
from typing import Callable, ClassVar

_GetContextMenuItems: Callable

class ActiveMenuItem(PrimContextMenuItem):
    GetText: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class CopyModelPathMenuItem(PrimContextMenuItem):
    __init__: ClassVar[Callable] = ...
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class CopyPrimPathMenuItem(PrimContextMenuItem):
    GetText: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class IsolateAssetMenuItem(PrimContextMenuItem):
    __init__: ClassVar[Callable] = ...
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class IsolateCopyPrimMenuItem(PrimContextMenuItem):
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class JumpToEnclosingModelItem(PrimContextMenuItem):
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class LoadOrUnloadMenuItem(PrimContextMenuItem):
    __init__: ClassVar[Callable] = ...
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class PrimContextMenuItem(UsdviewContextMenuItem):
    __init__: ClassVar[Callable] = ...
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    IsSeparator: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class RemoveVisMenuItem(PrimContextMenuItem):
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class SelectBoundFullMaterialMenuItem(PrimContextMenuItem):
    __init__: ClassVar[Callable] = ...
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class SelectBoundPreviewMaterialMenuItem(PrimContextMenuItem):
    __init__: ClassVar[Callable] = ...
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class SeparatorMenuItem(PrimContextMenuItem):
    IsSeparator: ClassVar[Callable] = ...

class SetAsActiveCamera(PrimContextMenuItem):
    __init__: ClassVar[Callable] = ...
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class ToggleVisibilityMenuItem(PrimContextMenuItem):
    __init__: ClassVar[Callable] = ...
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...

class VisOnlyMenuItem(PrimContextMenuItem):
    GetText: ClassVar[Callable] = ...
    IsEnabled: ClassVar[Callable] = ...
    RunCommand: ClassVar[Callable] = ...