# mypy: disable-error-code="misc, override, no-redef"

import PySide6.QtCore
import PySide6.QtWidgets
from pxr.Usdviewq.common import ItalicizeLabelText as ItalicizeLabelText, PropertyViewIcons as PropertyViewIcons, UIBaseColors as UIBaseColors, UIPropertyValueSourceColors as UIPropertyValueSourceColors
from pxr.Usdviewq.propertyLegendUI import Ui_PropertyLegend as Ui_PropertyLegend
from typing import ClassVar

class PropertyLegend(PySide6.QtWidgets.QWidget):
    staticMetaObject: ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent): ...
    def GetHeight(self): ...
    def GetResetHeight(self): ...
    def IsMinimized(self): ...
    def ToggleMinimized(self): ...
