# mypy: disable-error-code="misc, override, no-redef"

import pxr.Gf as Gf
from _typeshed import Incomplete
from typing import Any

class UsdviewApi:
    viewerMode: Any
    def __init__(self, appController): ...
    def AddPrimToSelection(self, prim): ...
    def ClearPrimSelection(self): ...
    def ComputeModelsFromSelection(self): ...
    def ComputeSelectedPrimsOfType(self, schemaType): ...
    def GetSettings(self): ...
    def GetViewportCurrentRendererId(self): ...
    def GetViewportRendererNames(self): ...
    def GrabViewportShot(self): ...
    def GrabWindowShot(self): ...
    def PrintStatus(self, msg): ...
    def SetViewportRenderer(self, plugId): ...
    def UpdateGUI(self): ...
    def UpdateViewport(self): ...
    def _ExportSession(self, stagePath, defcamName: str = ..., imgWidth: Incomplete | None = ..., imgHeight: Incomplete | None = ...): ...
    @property
    def cameraPrim(self) -> Any: ...
    @property
    def configDir(self) -> Any: ...
    @property
    def currentGfCamera(self) -> Any: ...
    @property
    def dataModel(self) -> Any: ...
    @property
    def frame(self) -> Any: ...
    @property
    def layer(self) -> Any: ...
    @property
    def prim(self) -> Any: ...
    @property
    def property(self) -> Any: ...
    @property
    def qMainWindow(self) -> Any: ...
    @property
    def selectedInstances(self) -> Any: ...
    @property
    def selectedPaths(self) -> Any: ...
    @property
    def selectedPoint(self) -> Any: ...
    @property
    def selectedPrims(self) -> Any: ...
    @property
    def spec(self) -> Any: ...
    @property
    def stage(self) -> Any: ...
    @property
    def stageIdentifier(self) -> Any: ...
    @property
    def viewportSize(self) -> Any: ...
