import dataclasses
from _typeshed import Incomplete
from substance_painter.async_utils import StopSource as StopSource
from substance_painter.properties import Property as Property, PropertyValue as PropertyValue
from substance_painter.textureset import MeshMapUsage as MeshMapUsage, TextureSet as TextureSet, UVTile as UVTile

from _substance_painter.baking import BakingStatus as BakingStatus
from _substance_painter.baking import CurvatureMethod as CurvatureMethod

@dataclasses.dataclass(frozen=True)
class BakingParameters:
    material_id: int
    @staticmethod
    def from_texture_set(texture_set: TextureSet) -> BakingParameters: ...
    @staticmethod
    def from_texture_set_name(texture_set_name: str) -> BakingParameters: ...
    def texture_set(self) -> TextureSet: ...
    def common(self) -> dict[str, Property]: ...
    def baker(self, baked_map: MeshMapUsage) -> dict[str, Property]: ...
    @staticmethod
    def set(property_values: dict[Property, PropertyValue]) -> None: ...
    def get_curvature_method(self) -> CurvatureMethod: ...
    def set_curvature_method(self, method: CurvatureMethod): ...
    def is_baker_enabled(self, usage: MeshMapUsage) -> bool: ...
    def set_baker_enabled(self, usage: MeshMapUsage, enable: bool) -> None: ...
    def get_enabled_bakers(self) -> list[MeshMapUsage]: ...
    def set_enabled_bakers(self, enabled_usages: list[MeshMapUsage]) -> None: ...
    def is_textureset_enabled(self) -> bool: ...
    def set_textureset_enabled(self, enable: bool) -> None: ...
    def is_uv_tile_enabled(self, uv_tile: UVTile) -> bool: ...
    def set_uv_tile_enabled(self, uv_tile: UVTile, enable: bool) -> None: ...
    def get_enabled_uv_tiles(self) -> list[UVTile]: ...
    def set_enabled_uv_tiles(self, enabled_uv_tiles: list[UVTile]) -> None: ...

def set_linked_group(group: list[TextureSet], reference: TextureSet, usage: MeshMapUsage) -> None: ...
def set_linked_group_common_parameters(group: list[TextureSet], reference: TextureSet) -> None: ...
def unlink_all(usage: MeshMapUsage) -> None: ...
def unlink_all_common_parameters() -> None: ...
def get_link_group(usage: MeshMapUsage) -> list[TextureSet]: ...
def get_link_group_common_parameters() -> list[TextureSet]: ...
def get_linked_texture_sets(texture_set: TextureSet, usage: MeshMapUsage) -> list[TextureSet]: ...
def get_linked_texture_sets_common_parameters(texture_set: TextureSet) -> list[TextureSet]: ...
def bake_async(texture_set: TextureSet) -> StopSource: ...
def bake_selected_textures_async() -> StopSource: ...
