import dataclasses
import substance_painter
import substance_painter.resource
import types
from .colormanagement import Color as Color
from _typeshed import Incomplete
from enum import Enum
from substance_painter import levels as levels
from substance_painter._utility import ReadOnlyUid as ReadOnlyUid
from substance_painter.levels import LevelsParams as LevelsParams
from substance_painter.source import ActiveChannelsMixin as ActiveChannelsMixin, SourceEditorMixin as SourceEditorMixin, SourceSubstance as SourceSubstance
from substance_painter.textureset import ChannelType as ChannelType, Stack as Stack, TextureSet as TextureSet, UVTile as UVTile

from _substance_painter.layerstack import BlendingMode as BlendingMode
from _substance_painter.layerstack import NodeType as NodeType

class NodeStack(Enum):
    Substack = ...
    Content = ...
    Mask = ...

from _substance_painter.layerstack import MaskBackground as MaskBackground
from _substance_painter.layerstack import ColorSelectionBackgroundColor as ColorSelectionBackgroundColor
from _substance_painter.layerstack import GeometryMaskType as GeometryMaskType
from _substance_painter.layerstack import ProjectionMode as ProjectionMode
from _substance_painter.layerstack import FilteringMode as FilteringMode
from _substance_painter.layerstack import UVWrapMode as UVWrapMode
from _substance_painter.layerstack import ShapeCropMode as ShapeCropMode
from _substance_painter.layerstack import ScaleMode as ScaleMode
from _substance_painter.layerstack import CompareMaskEffectOperand as CompareMaskEffectOperand
from _substance_painter.layerstack import CompareMaskEffectOperation as CompareMaskEffectOperation
from _substance_painter.layerstack import SelectionType as SelectionType

class ScopedModification:
    name: Incomplete
    def __init__(self, name) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, exc_traceback: types.TracebackType | None) -> None: ...

class FillParamsEditorMixin:
    def get_projection_mode(self) -> ProjectionMode: ...
    def set_projection_mode(self, projection_mode: ProjectionMode): ...
    def get_projection_parameters(self) -> ProjectionParams | None: ...
    def set_projection_parameters(self, projection_parameters: ProjectionParams): ...

class Node(ReadOnlyUid):
    def __eq__(self, other): ...
    def __hash__(self): ...
    def get_type(self) -> NodeType: ...
    def get_texture_set(self) -> TextureSet: ...
    def is_visible(self) -> bool: ...
    def set_visible(self, visible: bool): ...
    def get_name(self) -> str: ...
    def set_name(self, name: str): ...
    def is_in_mask_stack(self) -> bool: ...
    def has_blending(self) -> bool: ...
    def get_blending_mode(self, channel: ChannelType | None = None) -> BlendingMode: ...
    def set_blending_mode(self, blending_mode: BlendingMode, channel: ChannelType | None = None): ...
    def get_opacity(self, channel: ChannelType | None = None) -> float: ...
    def set_opacity(self, opacity: float, channel: ChannelType | None = None): ...
    def get_stack(self) -> Stack: ...
    def get_parent(self) -> Node: ...
    def get_next_sibling(self) -> Node: ...
    def get_previous_sibling(self) -> Node: ...

class LayerNode(Node):
    def content_effects(self) -> list[EffectNode]: ...
    def mask_effects(self) -> list[EffectNode]: ...
    def instances(self) -> list[LayerNode]: ...
    def get_geometry_mask_type(self) -> GeometryMaskType: ...
    def set_geometry_mask_type(self, geometry_mask_type: GeometryMaskType): ...
    def get_geometry_mask_enabled_meshes(self) -> list[str]: ...
    def set_geometry_mask_enabled_meshes(self, mesh_names: list[str]): ...
    def get_geometry_mask_enabled_uv_tiles(self) -> list[UVTile]: ...
    def set_geometry_mask_enabled_uv_tiles(self, uv_tiles: list[UVTile]): ...
    def has_mask(self) -> bool: ...
    def add_mask(self, background: MaskBackground): ...
    def remove_mask(self) -> None: ...
    def get_mask_background(self) -> MaskBackground: ...
    def set_mask_background(self, background: MaskBackground): ...
    def is_mask_enabled(self) -> bool: ...
    def enable_mask(self, enabled: bool): ...

class GroupLayerNode(LayerNode):
    def sub_layers(self) -> list[LayerNode]: ...
    def is_collapsed(self) -> bool: ...
    def set_collapsed(self, collapsed: bool): ...

class PaintLayerNode(LayerNode): ...

class InstanceLayerNode(LayerNode):
    def instance_source(self) -> LayerNode: ...

class FillLayerNode(FillParamsEditorMixin, SourceEditorMixin, LayerNode): ...
HierarchicalNode = LayerNode | GroupLayerNode | PaintLayerNode | InstanceLayerNode | FillLayerNode

class GeneratorEffectNode(ActiveChannelsMixin, Node):
    def get_source(self) -> SourceSubstance: ...
    def set_source(self, res: substance_painter.resource.ResourceID) -> SourceSubstance: ...
    def remove_source(self) -> None: ...

class PaintEffectNode(Node): ...
class FillEffectNode(FillParamsEditorMixin, SourceEditorMixin, Node): ...

class LevelsEffectNode(Node):
    @property
    def affected_channel(self) -> ChannelType: ...
    @affected_channel.setter
    def affected_channel(self, channel: ChannelType) -> None: ...
    def get_parameters(self) -> LevelsParams: ...
    def set_parameters(self, params: LevelsParams) -> None: ...

@dataclasses.dataclass
class CompareMaskEffectParams:
    channel: ChannelType
    left_operand: CompareMaskEffectOperand
    right_operand: CompareMaskEffectOperand
    operation: CompareMaskEffectOperation
    constant: float
    tolerance: float
    hardness: float

class CompareMaskEffectNode(Node):
    def get_parameters(self) -> CompareMaskEffectParams: ...
    def set_parameters(self, params: CompareMaskEffectParams) -> None: ...

class FilterEffectNode(ActiveChannelsMixin, Node):
    def get_source(self) -> SourceSubstance: ...
    def set_source(self, res: substance_painter.resource.ResourceID) -> SourceSubstance: ...
    def remove_source(self) -> None: ...

@dataclasses.dataclass
class ColorSelectionEffectParams:
    id_mask: substance_painter.resource.ResourceID | None
    output_value: float
    hardness: float
    tolerance: float
    background_color: ColorSelectionBackgroundColor
    colors: list[Color]

class ColorSelectionEffectNode(Node):
    def get_parameters(self) -> ColorSelectionEffectParams: ...
    def set_parameters(self, params: ColorSelectionEffectParams) -> None: ...

class AnchorPointEffectNode(Node): ...
EffectNode = GeneratorEffectNode | PaintEffectNode | FillEffectNode | LevelsEffectNode | CompareMaskEffectNode | FilterEffectNode | ColorSelectionEffectNode | AnchorPointEffectNode

def get_root_layer_nodes(stack: Stack) -> list[HierarchicalNode]: ...
def get_node_by_uid(node_id: int) -> list[HierarchicalNode | EffectNode]: ...
def get_selected_nodes(stack: Stack) -> list[HierarchicalNode | EffectNode]: ...
def set_selected_nodes(nodes: list[EffectNode] | list[LayerNode]): ...
def get_selection_type(layer: LayerNode) -> SelectionType: ...
def set_selection_type(layer: LayerNode, layer_selection_type: SelectionType): ...
def delete_node(node: Node): ...

@dataclasses.dataclass
class UVTransformationParams:
    scale_mode: ScaleMode = ...
    scale: list[float] = ...
    rotation: float = ...
    offset: list[float] = ...

@dataclasses.dataclass
class Projection3DParams:
    offset: list[float] = ...
    rotation: list[float] = ...
    scale: list[float] = ...

@dataclasses.dataclass
class ProjectionCullingParams:
    enabled: bool = ...
    hardness: float = ...

@dataclasses.dataclass
class UVProjectionParams:
    filtering_mode: FilteringMode = ...
    uv_wrapping_mode: UVWrapMode = ...
    uv_transformation: UVTransformationParams = dataclasses.field(default_factory=UVTransformationParams)

@dataclasses.dataclass
class TriplanarProjectionParams:
    filtering_mode: FilteringMode = ...
    shape_crop_mode: ShapeCropMode = ...
    hardness: float = ...
    uv_transformation: UVTransformationParams = dataclasses.field(default_factory=UVTransformationParams)
    projection_3d: Projection3DParams = dataclasses.field(default_factory=Projection3DParams)

@dataclasses.dataclass
class PlanarProjectionParams:
    filtering_mode: FilteringMode = ...
    uv_wrapping_mode: UVWrapMode = ...
    shape_crop_mode: ShapeCropMode = ...
    depth_culling: ProjectionCullingParams = dataclasses.field(default_factory=ProjectionCullingParams)
    backface_culling: ProjectionCullingParams = dataclasses.field(default_factory=ProjectionCullingParams)
    backface_culling_angle: float = ...
    uv_transformation: UVTransformationParams = dataclasses.field(default_factory=UVTransformationParams)
    projection_3d: Projection3DParams = dataclasses.field(default_factory=Projection3DParams)

@dataclasses.dataclass
class WarpProjectionParams:
    filtering_mode: FilteringMode = ...
    uv_wrapping_mode: UVWrapMode = ...
    shape_crop_mode: ShapeCropMode = ...
    projection_depth: float = ...
    depth_culling: ProjectionCullingParams = dataclasses.field(default_factory=ProjectionCullingParams)
    uv_transformation: UVTransformationParams = dataclasses.field(default_factory=UVTransformationParams)
    projection_3d: Projection3DParams = dataclasses.field(default_factory=Projection3DParams)

@dataclasses.dataclass
class SphericalProjectionParams:
    filtering_mode: FilteringMode = ...
    uv_wrapping_mode: UVWrapMode = ...
    shape_crop_mode: ShapeCropMode = ...
    uv_transformation: UVTransformationParams = dataclasses.field(default_factory=UVTransformationParams)
    projection_3d: Projection3DParams = dataclasses.field(default_factory=Projection3DParams)

@dataclasses.dataclass
class CylindricalProjectionParams:
    filtering_mode: FilteringMode = ...
    uv_wrapping_mode: UVWrapMode = ...
    shape_crop_mode: ShapeCropMode = ...
    angle: float = ...
    backface_culling: ProjectionCullingParams = dataclasses.field(default_factory=ProjectionCullingParams)
    uv_transformation: UVTransformationParams = dataclasses.field(default_factory=UVTransformationParams)
    projection_3d: Projection3DParams = dataclasses.field(default_factory=Projection3DParams)

@dataclasses.dataclass
class UVSetToUVSetProjectionParams:
    source_uv_set: int = ...
    filtering_mode: FilteringMode = ...
    uv_wrapping_mode: UVWrapMode = ...
    uv_transformation: UVTransformationParams = dataclasses.field(default_factory=UVTransformationParams)
ProjectionParams = UVProjectionParams | TriplanarProjectionParams | PlanarProjectionParams | WarpProjectionParams | SphericalProjectionParams | CylindricalProjectionParams | UVSetToUVSetProjectionParams

@dataclasses.dataclass(frozen=True)
class InsertPosition:
    node_id: int
    node_stack: int | None
    @staticmethod
    def from_textureset_stack(stack: substance_painter.textureset.Stack) -> InsertPosition: ...
    @staticmethod
    def above_node(node: Node) -> InsertPosition: ...
    @staticmethod
    def below_node(node: Node) -> InsertPosition: ...
    @staticmethod
    def inside_node(node: Node, node_stack: NodeStack) -> InsertPosition: ...

def insert_fill(position: InsertPosition) -> FillLayerNode | FillEffectNode: ...
def insert_paint(position: InsertPosition) -> PaintLayerNode | PaintEffectNode: ...
def insert_group(position: InsertPosition) -> GroupLayerNode: ...
def instantiate(position: InsertPosition, layer: LayerNode) -> InstanceLayerNode: ...
def insert_levels_effect(position: InsertPosition) -> LevelsEffectNode: ...
def insert_compare_mask_effect(position: InsertPosition) -> CompareMaskEffectNode: ...
def insert_filter_effect(position: InsertPosition, filter_substance: substance_painter.resource.ResourceID | None = None) -> FilterEffectNode: ...
def insert_generator_effect(position: InsertPosition, generator_substance: substance_painter.resource.ResourceID | None = None) -> GeneratorEffectNode: ...
def insert_anchor_point_effect(position: InsertPosition, name: str) -> AnchorPointEffectNode: ...
def insert_color_selection_effect(position: InsertPosition) -> ColorSelectionEffectNode: ...
def insert_smart_material(position: InsertPosition, smart_material: substance_painter.resource.ResourceID) -> GroupLayerNode: ...
def insert_smart_mask(position: InsertPosition, smart_mask: substance_painter.resource.ResourceID) -> list[EffectNode]: ...
