import _substance_painter.resource
import dataclasses
import enum

class ResourceLocation(enum.Enum):
    SESSION = ...
    PROJECT = ...
    SHELF = ...

@dataclasses.dataclass(frozen=True)
class ResourceID:
    context: str
    name: str
    version: str = ...
    @classmethod
    def from_url(cls, url: str): ...
    @classmethod
    def from_project(cls, name: str, version: str = None): ...  # type: ignore[assignment]
    @classmethod
    def from_session(cls, name: str, version: str = None): ...  # type: ignore[assignment]
    def url(self) -> str: ...
    def location(self) -> ResourceLocation: ...

class Usage(enum.Enum):
    ALPHA = ...
    BASE_MATERIAL = ...
    BRUSH = ...
    COLOR_LUT = ...
    EMITTER = ...
    ENVIRONMENT = ...
    EXPORT = ...
    FILTER = ...
    FONT = ...
    GENERATOR = ...
    PARTICLE = ...
    PROCEDURAL = ...
    RECEIVER = ...
    SHADER = ...
    SMART_MASK = ...
    SMART_MATERIAL = ...
    TEXTURE = ...
    TOOL = ...

class Type(enum.Enum):
    ABR_PACKAGE = ...
    BRUSH = ...
    EXPORT = ...
    FONT = ...
    IMAGE = ...
    PRESET = ...
    RESOURCE = ...
    SCRIPT = ...
    SHADER = ...
    SMART_MASK = ...
    SMART_MATERIAL = ...
    SUBSTANCE = ...
    SUBSTANCE_PACKAGE = ...
    VECTORIAL = ...

@dataclasses.dataclass(frozen=True)
class Resource:
    handle: _substance_painter.resource.ResourceHandle
    def __eq__(self, other): ...
    def __hash__(self): ...
    def identifier(self) -> ResourceID: ...
    def location(self) -> ResourceLocation: ...
    @staticmethod
    def retrieve(identifier: ResourceID): ...
    def set_custom_preview(self, preview_image: str) -> None: ...
    def category(self) -> str: ...
    def usages(self) -> list[Usage]: ...
    def gui_name(self) -> str: ...
    def type(self) -> Type: ...
    def tags(self) -> list[str]: ...
    def internal_properties(self) -> dict: ...
    def children(self) -> list['Resource']: ...
    def parent(self) -> Resource | None: ...
    def reset_preview(self) -> None: ...
    def show_in_ui(self) -> None: ...

def show_resources_in_ui(resources: list[Resource]) -> None: ...
def import_project_resource(file_path: str, resource_usage: Usage, name: str = None, group: str = None) -> Resource: ...  # type: ignore[assignment]
def import_session_resource(file_path: str, resource_usage: Usage, name: str = None, group: str = None) -> Resource: ...  # type: ignore[assignment]

class StandardQuery:
    ALL_RESOURCES: str
    PROJECT_RESOURCES: str
    SESSION_RESOURCES: str
    SHELVES_RESOURCES: str

def search(query: str) -> list[Resource]: ...
def list_layer_stack_resources() -> list[ResourceID]: ...
def update_layer_stack_resource(old_resource_id: ResourceID, new_resource: Resource) -> list[ResourceID]: ...

@dataclasses.dataclass(frozen=True)
class Shelf:
    def name(self) -> str: ...
    def path(self) -> str: ...
    def resources(self, query: str = ...) -> list[Resource]: ...
    def can_import_resources(self) -> bool: ...
    def import_resource(self, file_path: str, resource_usage: Usage, name: str = None, group: str = None, uuid: str = None) -> Resource: ...  # type: ignore[assignment]
    def is_crawling(self) -> bool: ...

class Shelves:
    @staticmethod
    def all() -> list[Shelf]: ...
    @staticmethod
    def exists(name: str) -> bool: ...
    @staticmethod
    def add(name: str, path: str) -> Shelf: ...
    @staticmethod
    def remove(name: str): ...
    @staticmethod
    def refresh_all() -> None: ...
    @staticmethod
    def user_shelf() -> Shelf: ...
    @staticmethod
    def application_shelf() -> Shelf: ...
