# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import AssetAPI as AssetAPI
import NodegraphAPI as NodegraphAPI
import Nodes2DAPI as Nodes2DAPI
import PyXmlIO as PyXmlIO
import Utils as Utils
from typing import Set, Tuple

def AddInput(node): ...
def AddPostScript(node): ...
def DeleteInput(node, index): ...
def DeletePostScript(node, index): ...
def EnableFirstInput(node): ...
def GetActiveViewMask(node): ...
def IsParameterTreeOutOfDate(node): ...
def ReorderInput(node, index, newIndex): ...
def ReorderPostScript(node, index, newIndex): ...
def SyncAllOutputPorts(): ...
def SyncOutputPorts(node): ...
def SyncParametersToPorts(node): ...
