from _typeshed import Incomplete

class Issue:
    def __init__(self, description, type: str = 'warning', resolveCallback: Incomplete | None = None) -> None: ...
    @property
    def description(self): ...
    @property
    def type(self): ...
    def __hash__(self): ...
    def __eq__(self, o): ...
    def resolve(self) -> None: ...
