#!/usr/bin/env python
"""Generate tests/mypy_plugin_cases.py from tests/test_generic_signals.py.

test_generic_signals.py is the single source for both files: it carries the
``# type: ignore[...]`` comments the plain (stubs-only) mypy run expects,
plus two markers describing how the ignores change when the
types_pyside6_mypy_plugin plugin is enabled:

- ``# REMOVE`` after a ``# type: ignore[...]`` comment: the ignore is
  stripped from the generated file (a stubs-only false positive that the
  plugin fixes).
- ``# ADD: ignore[code]``: the generated line gains
  ``# type: ignore[code]`` (an error only the plugin reports).
- ``# REPLACE: ignore[code]`` after a ``# type: ignore[...]`` comment: the
  ignore's error code becomes ``code`` in the generated file (the plugin
  reports a different error on the same line).

Markers are recognized only at the end of a line, directly after the
``# type: ignore[...]`` comment when there is one.

Run this script directly to regenerate mypy_plugin_cases.py;
test_mypy_plugin.py fails while the generated file is stale.
"""

import pathlib
import re

HERE = pathlib.Path(__file__).parent
SOURCE = HERE / "test_generic_signals.py"
TARGET = HERE / "mypy_plugin_cases.py"

HEADER = (
    "# GENERATED by tests/gen_mypy_plugin_cases.py"
    " from tests/test_generic_signals.py -- do not edit by hand.\n"
)

IGNORE_COMMENT = re.compile(r"\s*# type: ignore\[[^]]+\]")
REMOVE_MARKER = re.compile(r"\s*# REMOVE$")
ADD_MARKER = re.compile(r"\s*# ADD: ignore\[([^]]+)\]$")
REPLACE_MARKER = re.compile(r"\s*# REPLACE: ignore\[([^]]+)\]$")


def _strip_ignore(line: str, lineno: int, marker: str) -> str:
    stripped = IGNORE_COMMENT.sub("", line)
    if stripped == line:
        raise ValueError(
            f"{SOURCE.name}:{lineno}: # {marker} marker without a"
            f" # type: ignore comment"
        )
    return stripped


def generate(source: str) -> str:
    """Transform test_generic_signals.py source into mypy_plugin_cases.py."""
    lines = []
    for lineno, line in enumerate(source.splitlines(), start=1):
        if REMOVE_MARKER.search(line):
            line = _strip_ignore(REMOVE_MARKER.sub("", line), lineno, "REMOVE")
        elif replace := REPLACE_MARKER.search(line):
            line = _strip_ignore(REPLACE_MARKER.sub("", line), lineno, "REPLACE")
            line = f"{line}  # type: ignore[{replace.group(1)}]"
        elif add := ADD_MARKER.search(line):
            line = ADD_MARKER.sub("", line)
            if IGNORE_COMMENT.search(line):
                raise ValueError(
                    f"{SOURCE.name}:{lineno}: # ADD marker on a line that"
                    f" already has a # type: ignore comment (use # REPLACE)"
                )
            line = f"{line}  # type: ignore[{add.group(1)}]"
        lines.append(line)
    return HEADER + "\n".join(lines) + "\n"


def main() -> None:
    TARGET.write_text(generate(SOURCE.read_text()))
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
