#!/usr/bin/env python
"""Generate a tests/mypy_plugin_<test file>.py twin of a test file.

The test files to convert are the ones listed in
``test_mypy_plugin.SOURCES``, which is also what checks the results -- pass
paths on the command line to convert something else.

Each source file is the single source for both files: it carries the
``# type: ignore[...]`` comments the plain (stubs-only) mypy run expects,
plus two markers describing how the ignores change when the
types_pyside6_mypy_plugin plugin is enabled:

- ``# REMOVE`` after a ``# type: ignore[...]`` comment: the ignore is
  stripped from the generated file (a stubs-only false positive that the
  plugin fixes).
- ``# ADD: ignore[code]``: the generated line gains
  ``# type: ignore[code]`` (an error only the plugin reports).
- ``# REPLACE: ignore[code]`` after a ``# type: ignore[...]`` comment: the
  ignore's error code becomes ``code`` in the generated file (the plugin
  reports a different error on the same line).

Markers are recognized only at the end of a line, directly after the
``# type: ignore[...]`` comment when there is one.

Run this script directly to regenerate the generated files;
test_mypy_plugin.py fails while any of them is stale.
"""

import pathlib
import re
import sys
import typing

PREFIX = "mypy_plugin_"

HEADER = (
    "# GENERATED by tests/gen_mypy_plugin_cases.py"
    " from tests/{source} -- do not edit by hand.\n"
)

IGNORE_COMMENT = re.compile(r"\s*# type: ignore\[[^]]+\]")
REMOVE_MARKER = re.compile(r"\s*# REMOVE$")
ADD_MARKER = re.compile(r"\s*# ADD: ignore\[([^]]+)\]$")
REPLACE_MARKER = re.compile(r"\s*# REPLACE: ignore\[([^]]+)\]$")


def target_path(source: pathlib.Path) -> pathlib.Path:
    """The generated twin of a source file, e.g.
    ``test_native_signals.py`` -> ``mypy_plugin_test_native_signals.py``.
    """
    return source.with_name(PREFIX + source.name)


def _strip_ignore(line: str, name: str, lineno: int, marker: str) -> str:
    stripped = IGNORE_COMMENT.sub("", line)
    if stripped == line:
        raise ValueError(
            f"{name}:{lineno}: # {marker} marker without a # type: ignore comment"
        )
    return stripped


def generate(source: str, name: str) -> str:
    """Transform the source of `name` into the content of its twin."""
    lines = []
    for lineno, line in enumerate(source.splitlines(), start=1):
        if REMOVE_MARKER.search(line):
            line = _strip_ignore(REMOVE_MARKER.sub("", line), name, lineno, "REMOVE")
        elif replace := REPLACE_MARKER.search(line):
            line = _strip_ignore(REPLACE_MARKER.sub("", line), name, lineno, "REPLACE")
            line = f"{line}  # type: ignore[{replace.group(1)}]"
        elif add := ADD_MARKER.search(line):
            line = ADD_MARKER.sub("", line)
            if IGNORE_COMMENT.search(line):
                raise ValueError(
                    f"{name}:{lineno}: # ADD marker on a line that"
                    f" already has a # type: ignore comment (use # REPLACE)"
                )
            line = f"{line}  # type: ignore[{add.group(1)}]"
        lines.append(line)
    return HEADER.format(source=name) + "\n".join(lines) + "\n"


def main(sources: "typing.Optional[list[pathlib.Path]]" = None) -> None:
    if not sources:
        # test_mypy_plugin.py owns the list: it is what checks the generated
        # files, both with and without the plugin.
        import test_mypy_plugin

        sources = test_mypy_plugin.SOURCES
    for source in sources:
        target = target_path(source)
        target.write_text(generate(source.read_text(), source.name))
        print(f"wrote {target}")


if __name__ == "__main__":
    main([pathlib.Path(arg) for arg in sys.argv[1:]])
