"""Type-checking assertions for types_pyside6_mypy_plugin with object_as_any = false.

Checked by tests/test_mypy_plugin.py with the plugin enabled but the
``object_as_any`` option turned off (tests/mypy-plugin-no-object.ini, and the
equivalent pyproject.toml table generated by the test).  With the rewrite
disabled, ``Signal(object)`` infers as ``Signal[tuple[object]]`` again, while
the plugin's signal index validation and narrowing remain active.
"""

import typing

from PySide6 import QtCore


class CustomData:
    """Stand-in for a complex type emitted through a Signal(object) signal."""


class ObjectSignals(QtCore.QObject):
    signal_obj = QtCore.Signal(object)
    signal_any = QtCore.Signal(typing.Any)
    signal7: "QtCore.Signal[tuple[int, int], tuple[str], tuple[float, float]]" = (
        QtCore.Signal((int, int), (str,), (float, float))
    )

    def _check(self) -> None:
        # with object_as_any = false the rewrite is off: the signal argument
        # is plain `object`, which no more-specific slot is compatible with
        self.signal_obj.connect(self.slot_data)  # type: ignore[call-overload]
        self.signal_obj.connect(self.slot_obj)
        self.signal_obj.emit(CustomData())
        # ... and `typing.Any` is the nominal class, not the special form
        self.signal_any.connect(self.slot_data)  # type: ignore[call-overload]
        self.signal_any.emit(CustomData())  # type: ignore[arg-type]

        # the option does not affect signal index validation and narrowing
        self.signal7[str].connect(self.slot_str)
        self.signal7[str].connect(self.slot_data)  # type: ignore[call-overload]
        self.signal7[str, str]  # type: ignore[index]

    def slot_data(self, arg1: CustomData) -> None:
        pass

    def slot_obj(self, arg1: object) -> None:
        pass

    def slot_str(self, arg1: str) -> None:
        pass
