# GENERATED by tests/gen_mypy_plugin_cases.py from tests/test_generic_signals.py -- do not edit by hand.
"""Runtime and static checks for the generic Signal/SignalInstance stubs.

This file is the single source for a pair of files whose executable content
is identical and whose ``# type: ignore[...]`` comments differ:

- ``tests/test_generic_signals.py`` carries the ignores the *plain* mypy run
  (stubs only) expects; it is executed by pytest.
- ``tests/mypy_plugin_cases.py`` is generated from it by
  ``tests/gen_mypy_plugin_cases.py`` and carries the ignores expected with
  the types_pyside6_mypy_plugin plugin enabled; it is excluded from the
  plain mypy run and checked by ``tests/test_mypy_plugin.py`` with the
  plugin on.  (pytest does not collect it.)

Three markers direct the generator; run ``gen_mypy_plugin_cases.py`` after
changing this file (test_mypy_plugin.py fails while the generated file is
stale):

- an ignore followed by a ``# REMOVE`` marker is stripped from the
  generated file: the error is a stubs-only false positive that the plugin
  fixes;
- an ``# ADD: ignore[code]`` marker appends that ignore to the generated
  line: the error is reported only with the plugin;
- an ignore followed by a ``# REPLACE: ignore[code]`` marker changes its
  error code in the generated file: the plugin reports a different error
  on that line.

mypy runs in strict mode with ``warn_unused_ignores``, so an ignore comment
asserts that mypy reports exactly that error on that line, and the markers
document exactly what the plugin changes.  In particular, a marked call in
a ``with pytest.raises(...)`` block demonstrates a runtime error that only
the plugin catches.

The tests double as documentation of what actually happens at runtime
(PySide6 6.11):

- subscripting a signal with an unknown signature raises IndexError;
- emitting with the wrong number of arguments raises TypeError;
- emitting with a wrong argument *type* does not raise: Qt coerces the value
  (possibly to garbage), so a type checker is the only guard;
- connecting a Python callable never raises, even when the callable can
  never be invoked with the signal's arguments (the error is printed and
  swallowed at emit time), so again a type checker is the only guard;
- connecting a *signal* to a signal that requires more arguments raises
  RuntimeError;
- unsubscripted connect()/emit() use only the default (first) signature of a
  multi-signature signal: PySide does not dispatch across signatures by
  argument types.
"""

import typing

import pytest

from PySide6 import QtCore


class CustomData:
    """Stand-in for a complex type emitted through a Signal(object) signal."""


class Emitter(QtCore.QObject):
    # The types of these signals are inferred from the constructor arguments,
    # so no explicit annotations are required.  Signal and SignalInstance are
    # parametrized by one or more signatures, where each signature is a tuple
    # of argument types.
    signal1 = QtCore.Signal()
    signal2 = QtCore.Signal(int)
    signal3 = QtCore.Signal(int, str)
    # Signals support multiple signatures when passed as tuples.  Inference
    # is supported for up to two signatures with up to two arguments each.
    signal4 = QtCore.Signal((int,), (str,))
    signal5 = QtCore.Signal((int, int), (str, str))
    signal6 = QtCore.Signal((int,), (int, int))
    # Other configurations must be annotated manually.  WARNING:
    # QtCore.Signal is not subscriptable at runtime, so manual annotations
    # must be forward references (wrapped in quotes).
    signal7: "QtCore.Signal[tuple[int, int], tuple[str], tuple[float, float]]" = (
        QtCore.Signal((int, int), (str,), (float, float))
    )
    # Signal(object) is the idiomatic way to declare a signal that emits an
    # arbitrary value (Qt registers it as PyObject and passes any value
    # through unchanged).  typing.Any is a real, instantiable class at
    # runtime since Python 3.11 and PySide6 likewise registers it as
    # PyObject.
    signal_obj = QtCore.Signal(object)
    signal_any = QtCore.Signal(typing.Any)
    signal_int_obj = QtCore.Signal(int, object)


class Receiver(QtCore.QObject):
    """Records every slot invocation so tests can assert delivery."""

    def __init__(self) -> None:
        super().__init__()
        self.calls: "list[tuple[object, ...]]" = []

    @QtCore.Slot()
    def slot1(self) -> None:
        self.calls.append(())

    @QtCore.Slot()
    def slot2a(self, arg1: int) -> None:
        self.calls.append((arg1,))

    @QtCore.Slot()
    def slot2b(self, arg1: str) -> None:
        self.calls.append((arg1,))

    @QtCore.Slot(int)
    @QtCore.Slot(str)
    def slot2c(self, arg1: "int | str") -> None:
        self.calls.append((arg1,))

    @QtCore.Slot()
    def slot3(self, arg1: "int | str", arg2: "int | str") -> None:
        self.calls.append((arg1, arg2))

    @QtCore.Slot()
    def slot4(self, arg1: "int | str", arg2: "int | str | None" = None) -> None:
        self.calls.append((arg1, arg2))

    def slot_data(self, arg1: CustomData) -> None:
        self.calls.append((arg1,))


def test_connect() -> None:
    """Qt allows connecting slots that accept fewer arguments than the signal
    emits.  Connecting a Python callable never raises at runtime -- even one
    that can never be invoked with the signal's arguments (Qt prints and
    swallows the error at emit time) -- so the static errors below are the
    only guard.
    """
    e = Emitter()
    r = Receiver()

    e.signal1.connect(r.slot1)
    # All remaining slots require an argument that signal1 will never pass.
    e.signal1.connect(r.slot2a)  # type: ignore[arg-type]
    e.signal1.connect(r.slot2b)  # type: ignore[arg-type]
    e.signal1.connect(r.slot2c)  # type: ignore[arg-type]
    e.signal1.connect(r.slot3)  # type: ignore[arg-type]
    e.signal1.connect(r.slot4)  # type: ignore[arg-type]

    e.signal2.connect(r.slot1)
    e.signal2.connect(r.slot2a)
    # Argument has the wrong type.  Qt happens to be able to coerce an int to
    # str, but we want users to be explicit.
    e.signal2.connect(r.slot2b)  # type: ignore[call-overload]
    e.signal2.connect(r.slot2c)
    # Is missing a required argument.
    e.signal2.connect(r.slot3)  # type: ignore[call-overload]
    e.signal2.connect(r.slot4)

    e.signal3.connect(r.slot1)
    e.signal3.connect(r.slot2a)
    # Argument 1 has the wrong type.
    e.signal3.connect(r.slot2b)  # type: ignore[call-overload]
    e.signal3.connect(r.slot2c)
    e.signal3.connect(r.slot3)
    e.signal3.connect(r.slot4)


def test_connect_multi_signature() -> None:
    """Unsubscripted connect() uses only the default (first) signature: the
    slot will only ever be invoked with the default signature's arguments,
    so that is what the slot is checked against.  Use indexing to connect to
    a specific signature.
    """
    e = Emitter()
    r = Receiver()

    e.signal4.connect(r.slot1)
    e.signal4.connect(r.slot2a)
    # Argument 1 has the wrong type in the default Signal signature.
    e.signal4.connect(r.slot2b)  # type: ignore[call-overload]
    e.signal4.connect(r.slot2c)
    # Is missing a required argument.
    e.signal4.connect(r.slot3)  # type: ignore[call-overload]
    e.signal4.connect(r.slot4)

    e.signal5.connect(r.slot1)
    e.signal5.connect(r.slot2a)
    e.signal5.connect(r.slot2b)  # type: ignore[call-overload]
    e.signal5.connect(r.slot2c)
    e.signal5.connect(r.slot3)
    e.signal5.connect(r.slot4)

    e.signal6.connect(r.slot1)
    e.signal6.connect(r.slot2a)
    e.signal6.connect(r.slot2b)  # type: ignore[call-overload]
    e.signal6.connect(r.slot2c)
    # The default Signal signature is missing an argument.
    e.signal6.connect(r.slot3)  # type: ignore[call-overload]
    e.signal6.connect(r.slot4)

    # Indexing selects a specific signature to connect to.
    e.signal5[int, int].connect(r.slot1)
    e.signal5[int, int].connect(r.slot2a)
    # Argument 1 has the wrong type.
    e.signal5[int, int].connect(r.slot2b)  # type: ignore[call-overload]
    e.signal5[int, int].connect(r.slot2c)
    e.signal5[int, int].connect(r.slot3)
    e.signal5[int, int].connect(r.slot4)

    e.signal5[str, str].connect(r.slot1)
    # Argument 1 has the wrong type.
    e.signal5[str, str].connect(r.slot2a)  # type: ignore[call-overload]
    e.signal5[str, str].connect(r.slot2b)
    e.signal5[str, str].connect(r.slot2c)
    e.signal5[str, str].connect(r.slot3)
    e.signal5[str, str].connect(r.slot4)

    # A middle signature of a three-signature signal: the stubs can only
    # validate an index against the first or last signature; the plugin
    # validates it against every declared signature and checks the slot
    # against the one it selects.
    # stubs-only false positive on the index; fixed by the plugin:
    e.signal7[str].connect(r.slot2b)
    # an error both ways: the stubs report the (valid) index, the plugin
    # reports the incompatible slot:
    e.signal7[str].connect(r.slot2a)  # type: ignore[call-overload]


def test_connect_signal_to_signal() -> None:
    """Signals can be connected to other signals: emitting the first signal
    emits the connected signal with the same arguments, so the connected
    signal's arguments are checked like a slot's.  Unlike Python callables,
    connecting a signal that requires more arguments raises at runtime.
    """
    e = Emitter()
    r = Receiver()

    e.signal2.connect(e.signal1)  # receiving signal takes fewer args
    e.signal3.connect(e.signal2)  # prefix of the emitted args
    e.signal5[str, str].connect(e.signal4[str])

    # chained delivery: signal3 -> signal2 -> slot
    r.calls.clear()
    e.signal2.connect(r.slot2a)
    e.signal3.emit(1, "one")
    assert r.calls == [(1,)]

    # The receiving signal requires more arguments than are emitted.
    with pytest.raises(RuntimeError):
        e.signal1.connect(e.signal2)  # type: ignore[arg-type]
    with pytest.raises(RuntimeError):
        e.signal2.connect(e.signal3)  # type: ignore[arg-type]


def test_emit() -> None:
    e = Emitter()
    r = Receiver()

    e.signal1.connect(r.slot1)
    e.signal1.emit()
    assert r.calls == [()]

    r.calls.clear()
    e.signal2.connect(r.slot2a)
    e.signal2.emit(2)
    assert r.calls == [(2,)]

    r.calls.clear()
    e.signal3.connect(r.slot3)
    e.signal3.emit(3, "three")
    assert r.calls == [(3, "three")]


def test_emit_multi_signature() -> None:
    """Unsubscripted emit() emits only the default (first) signature; other
    signatures are emitted by selecting them with an index.  Slots connected
    to one signature do not receive emits of another.
    """
    e = Emitter()
    r = Receiver()

    e.signal4.connect(r.slot2a)  # connected to the default (int) signature
    e.signal4[str].connect(r.slot2b)
    e.signal4.emit(4)
    e.signal4[int].emit(5)
    e.signal4[str].emit("six")
    assert r.calls == [(4,), (5,), ("six",)]

    r.calls.clear()
    e.signal5[str, str].connect(r.slot3)
    e.signal5.emit(1, 2)  # default signature: not received by r.slot3
    e.signal5[int, int].emit(3, 4)
    e.signal5[str, str].emit("one", "two")
    assert r.calls == [("one", "two")]

    r.calls.clear()
    e.signal6.emit(1)
    e.signal6[int].emit(2)
    e.signal6[int, int].emit(3, 4)

    # signal7's middle signature: stubs-only false positives on the index,
    # fixed by the plugin, which then checks the connect and emit against
    # the selected signature:
    e.signal7[str].connect(r.slot2b)
    e.signal7[str].emit("seven")
    assert r.calls == [("seven",)]


def test_emit_wrong_arity() -> None:
    """Emitting with the wrong number of arguments raises TypeError."""
    e = Emitter()

    with pytest.raises(TypeError):
        e.signal2.emit()  # type: ignore[call-arg]
    with pytest.raises(TypeError):
        e.signal2.emit(1, 2)  # type: ignore[call-arg]
    with pytest.raises(TypeError):
        e.signal3.emit(1)  # type: ignore[call-arg]
    # Matches neither of signal5's signatures; it is reported against the
    # default signature, which is all that unsubscripted emit() dispatches
    # to at runtime.
    with pytest.raises(TypeError):
        e.signal5.emit("bad")  # type: ignore[arg-type, call-arg]
    # The wrong number of arguments for the signature selected by the index.
    with pytest.raises(TypeError):
        e.signal5[str, str].emit("one")  # type: ignore[call-arg]
    # ... including a signature the stubs cannot validate: the stubs report
    # the error against the (valid) subscript and leave the emit unchecked;
    # the plugin reports the real error, the emit arity.
    with pytest.raises(TypeError):
        e.signal7[str].emit("one", "two")  # type: ignore[call-arg]


def test_emit_wrong_type() -> None:
    """Emitting a wrong argument *type* does not raise: Qt coerces the value,
    possibly to garbage (e.g. str -> int becomes 0), so mypy's error is the
    only real guard.  Nothing is connected here, so no garbage is delivered.
    """
    e = Emitter()

    e.signal2.emit("x")  # type: ignore[arg-type]
    e.signal5[int, int].emit("one", "two")  # type: ignore[arg-type]
    e.signal5[str, str].emit(1, 2)  # type: ignore[arg-type]


def test_getitem() -> None:
    """Subscripting selects a declared signature; an index that matches no
    declared signature raises IndexError.  Runtime lookup is by exact
    signature: a subclass (bool for int) does not match.
    """
    e = Emitter()

    e.signal2[int]
    e.signal2[(int,)]  # a 1-tuple selects a 1-argument signature too
    e.signal4[int]
    e.signal4[str]
    e.signal5[int, int]
    e.signal5[str, str]
    # signal7's middle signature is valid at runtime; the stubs can only
    # validate an index against the first or last signature.
    # stubs-only false positive; fixed by the plugin:
    e.signal7[str]
    e.signal7[int, int]
    e.signal7[float, float]

    # signal1 has no arguments.
    with pytest.raises(IndexError):
        e.signal1[int]  # type: ignore[index]
    # An index with multiple types that matches no signature: the stubs let
    # this fall through to an unchecked catch-all, so only the plugin
    # catches it.
    with pytest.raises(IndexError):
        e.signal1[int, str]  # type: ignore[index]
    # signal2 has an `int` signature.
    with pytest.raises(IndexError):
        e.signal2[str]  # type: ignore[index]
    # A subclass does not match the declared signature at runtime; the stubs
    # match type[bool] against type[int] covariantly, so only the plugin
    # catches it.
    with pytest.raises(IndexError):
        e.signal2[bool]  # type: ignore[index]
    # signal3 has two arguments; an index must match a full signature.
    with pytest.raises(IndexError):
        e.signal3[int]  # type: ignore[index]
    with pytest.raises(IndexError):
        e.signal4[float]  # type: ignore[index]
    # More multi-type indexes that match no signature (see signal1 above).
    with pytest.raises(IndexError):
        e.signal5[int, str]  # type: ignore[index]
    with pytest.raises(IndexError):
        e.signal7[str, str]  # type: ignore[index]


def test_object_signals() -> None:
    """Signal(object) / Signal(typing.Any) pass any value through unchanged,
    and any slot may be connected.  The stubs cannot express this (`object`
    in a slot argument is contravariant), so without the plugin connecting a
    slot with any narrower argument type is a false positive; the plugin
    rewrites `object`/`typing.Any` signal arguments to mean `typing.Any`.
    """
    e = Emitter()
    r = Receiver()

    data = CustomData()

    e.signal_obj.connect(r.slot1)
    # stubs-only false positive (a slot narrower than `object` is
    # contravariantly incompatible); fixed by the plugin:
    e.signal_obj.connect(r.slot_data)
    e.signal_obj.emit(data)
    assert r.calls == [(), (data,)]

    r.calls.clear()
    # the same stubs-only false positive for Signal(typing.Any), plus one on
    # emit (mypy treats the value `typing.Any` as a nominal class); both
    # fixed by the plugin:
    e.signal_any.connect(r.slot_data)
    e.signal_any.emit(data)
    assert r.calls == [(data,)]

    # The `object` argument makes connecting slot3 a stubs-only false
    # positive (fixed by the plugin); the `int` argument is still strictly
    # checked, with or without it.
    e.signal_int_obj.connect(r.slot3)
    e.signal_int_obj.emit(1, data)
    e.signal_int_obj.emit("one", data)  # type: ignore[arg-type]


def test_disconnect() -> None:
    """disconnect() never raises for a Python callable: it returns False (and
    warns) when the slot was not connected.
    """
    e = Emitter()
    r = Receiver()

    e.signal2.connect(r.slot2a)
    assert e.signal2.disconnect(r.slot2a) is True
    assert e.signal2.disconnect(r.slot2a) is False

    # disconnect() accepts the same slots that connect() accepts, including
    # slots taking fewer arguments than the signal emits.
    e.signal2.connect(r.slot1)
    assert e.signal2.disconnect(r.slot1) is True
