from . import otio_json as otio_json
from .. import exceptions as exceptions, url_utils as url_utils

def read_from_file(filepath, extract_to_directory=None): ...
def write_to_file(input_otio, filepath, media_policy=..., dryrun: bool = False): ...
