from _typeshed import Incomplete

class ImportSession:
    def __init__(self, filePath, finishedCallback=...) -> None: ...
    IMPORT_TYPES: Incomplete
    filePath: Incomplete
    finishedCallback: Incomplete
    sessionType: Incomplete
    project: Incomplete
    def merge(self, geoEntities: Incomplete | None = ...) -> None: ...
    def start(self) -> None: ...
    def cancel(self) -> None: ...
