# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import QT4GLLayerStack.LayerStack as LayerStack

class CheckerboardLayer(LayerStack.Layer):
    def __init__(self, *args, **kwargs): ...
    def _CheckerboardLayer__buildDisplayList(self, width, height): ...
    def paintGL(self): ...
    def resizeGL(self): ...
    def setVisible(self, visible): ...