# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

from typing import Set, Tuple

_MAX_EYEPOINT_VALUE: int
_MAX_VIEWSCALE_VALUE: float
_MIN_VIEWSCALE_VALUE: float

def CapEyePoint(eyePoint): ...
def CapViewScale(viewScale): ...
def lerp(a, b, x): ...
def smoothstep(t): ...
