from _typeshed import Incomplete
from pathlib import Path

DESCRIPTION: str
OPERATION_HELP: Incomplete
UIC_CMD: str
RCC_CMD: str
LRELEASE_CMD: str
LUPDATE_CMD: str
QMLTYPEREGISTRAR_CMD: str
QMLLINT_CMD: str
QSB_CMD: str
DEPLOY_CMD: str

def _sort_sources(files: list[Path]) -> list[Path]: ...

class Project:
    project: Incomplete
    cl_options: Incomplete
    _qml_module_sources: list[Path]
    _qml_module_dir: Path | None
    _qml_dir_file: Path | None
    _qml_project_data: Incomplete
    def __init__(self, project_file: Path) -> None: ...
    def _qml_module_check(self) -> None: ...
    def _get_artifacts(self, file: Path, output_path: Path | None = None) -> tuple[list[Path], list[str] | None]: ...
    def _regenerate_qmldir(self) -> None: ...
    def _build_file(self, source: Path, output_path: Path | None = None): ...
    def build_design_studio_resources(self) -> None: ...
    def build(self) -> None: ...
    def run(self) -> int: ...
    def _clean_file(self, source: Path): ...
    def clean(self) -> None: ...
    def _qmllint(self) -> None: ...
    def qmllint(self) -> None: ...
    def deploy(self) -> None: ...
    def lupdate(self) -> None: ...

def main(mode: str = None, dry_run: bool = False, quiet: bool = False, force: bool = False, qml_module: bool = None, project_dir: str = None, project_path: str = None, legacy_pyproject: bool = False): ...  # type: ignore[assignment]
