VIRTUAL_ENV: str

def is_pyenv_python(): ...
def is_virtual_env(): ...
def init_virtual_env() -> None: ...
def main() -> None: ...
def qt_tool_wrapper(qt_tool, args, libexec: bool = False) -> None: ...
def pyside_script_wrapper(script_name) -> None: ...
def ui_tool_binary(binary): ...
def lrelease() -> None: ...
def lupdate() -> None: ...
def uic() -> None: ...
def rcc() -> None: ...
def qmltyperegistrar() -> None: ...
def qmlimportscanner() -> None: ...
def qmlcachegen() -> None: ...
def qmllint() -> None: ...
def qmlformat() -> None: ...
def qmlls() -> None: ...
def assistant() -> None: ...
def _extend_path_var(var, value, prepend: bool = False) -> None: ...
def designer() -> None: ...
def linguist() -> None: ...
def genpyi() -> None: ...
def metaobjectdump() -> None: ...
def _check_requirements(requirements_file): ...
def project() -> None: ...
def qml() -> None: ...
def qtpy2cpp() -> None: ...
def deploy() -> None: ...
def android_deploy() -> None: ...
def qsb() -> None: ...
def balsam() -> None: ...
def balsamui() -> None: ...
def svgtoqml() -> None: ...
