DISPLAY_CHECKBOX_NAME: str
PRECISION_SLIDER_NAME: str
COLOR_SLIDER_NAME: str
USE_RAMP_CHECKBOX_NAME: str
RAMP_LAYOUT_NAME: str
COLOR_RAMP_NAME: str
KEY_COLOR_SLIDER_NAME: str
MIN_COLOR_BTN_NAME: str
MAX_COLOR_BTN_NAME: str

def artAttrCreateNumericWeightProperties(parent) -> None: ...
def artAttrUpdateNumericWeightValues(context): ...
def onDisplayEnabledChanged(newValue, context) -> None: ...
def onPrecisionChanged(newValue, context) -> None: ...
def onColorChanged(context) -> None: ...
def onUseRampChanged(newValue, context) -> None: ...
def updateRamp(context) -> None: ...
def onRampSelectedKeyChanged() -> None: ...
def onRampKeyColorChanged(context) -> None: ...
def setMinColorCallback(context) -> None: ...
def setMaxColorCallback(context) -> None: ...
