from maya import cmds as cmds, mel as mel

def getFirstParent(customSet): ...
def buildSetTree(sets): ...
def buildMenuItem(name, commandStr) -> None: ...
def buildCustomSetSubMenu(tree, sets, commands) -> None: ...
def buildCustomSetsMenu(sets, commands) -> None: ...
def setColorIndex(setName, idx) -> None: ...
def resetColors(setTree, currentIdx): ...
def resetAllChannelSetColors() -> None: ...
def getAllChannelSetCurves(): ...
def getChannelSetData(name): ...
def getChannelSetsData(sets, processed): ...
def exportChannelSets(filename, sets): ...
def importChannelSets(filename): ...
