# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import Utils.EventModuleCommon as EventModuleCommon
import PyQt5.QtCore
import QtCore
from Utils.Exceptions import GetExceptionMessage as GetExceptionMessage
from typing import Hashable

INVOKE_COLLAPSED_HANDLERS_PERIOD: int
_eventQueuedWhileProcessingEvents: bool
_invokingCollapsedHandlers: bool
_katanaEventReceiver: KatanaEventReceiver
_processingEvents: bool

class KatanaEventReceiver(PyQt5.QtCore.QObject):
    def __init__(self): ...
    def _KatanaEventReceiver__invokeCollapsedDict(self, handlersDict, args): ...
    def _KatanaEventReceiver__invokeHandlerDict(self, handlersDict, eventType, eventID, kwargs): ...
    def _KatanaEventReceiver__on_collapsedEventsTimer_timeout(self): ...
    def customEvent(self, event: QtCore.QEvent): ...
    def initialize(self): ...
    def invokeCollapsedHandlers(self): ...

def Initialize(): ...
def ProcessAllEvents(): ...
def ProcessEvents() -> bool: ...
def PumpIdleQueue(): ...
def QueueEvent(eventType: str, eventID: Hashable, priority: int = ..., **kwargs): ...
def QueuePriorityEvent(eventType: str, eventID: Hashable, **kwargs): ...