# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import Utils.EventModule as EventModule
from _typeshed import Incomplete

_AsyncGroupCount: int
_AsyncMode: bool
_AsyncUndoDisableCount: int
_IsUndoInProgress: bool
_RedoStack: list
_UndoCallbacks: list
_UndoDisableCount: int
_UndoGroupStack: list
_UndoStack: list

class UndoEntry:
    def __init__(self, name): ...
    def getName(self): ...
    def isValid(self) -> bool: ...
    def redo(self): ...
    def setName(self, name): ...
    def undo(self): ...

class _UndoGroupEntry(UndoEntry):
    def __init__(self, name: str = ...): ...
    def _UndoGroupEntry__nonzero(self): ...
    def addEntry(self, entry: UndoEntry): ...
    def clear(self): ...
    def getName(self) -> str: ...
    def isValid(self): ...
    def redo(self): ...
    def undo(self): ...
    def __len__(self): ...

def AddEntry(entry: UndoEntry): ...
def AddEntrySync(entry): ...
def Clear(): ...
def CloseGroup(discard: bool = ...): ...
def CloseGroupSync(discard: bool = ...): ...
def DisableCapture(): ...
def DisableCaptureSync(): ...
def EnableCapture(): ...
def EnableCaptureSync(): ...
def GetLastUndoName() -> str: ...
def GetNextRedoName() -> str: ...
def GetRedoNames() -> list[str]: ...
def GetRedoSize() -> int: ...
def GetUndoNames() -> list[str]: ...
def GetUndoSize() -> int: ...
def IsInsideGroup() -> bool: ...
def IsInsideGroupSync(): ...
def IsUndoEnabled() -> bool: ...
def IsUndoEnabledSync(): ...
def IsUndoInProgress(): ...
def NoCaptureContext(): ...
def OpenGroup(groupName: str = ...): ...
def OpenGroupSync(groupName): ...
def Redo(): ...
def RegisterCallback(callback): ...
def RenameTopGroupSync(name): ...
def Undo(): ...
def UndoInitAsync(): ...
def _AddEntryAsync(entry): ...
def _CloseGroupAsync(discard: bool = ...): ...
def _DisableCaptureAsync(): ...
def _EnableCaptureAsync(): ...
def _IsInsideGroupAsync(): ...
def _IsUndoEnabledAsync(): ...
def _OpenGroupAsync(groupName): ...
def _TriggerUndoCallbacks(): ...
def _Undo(undoEntry: Incomplete | None = ...): ...
def _undo_addEntry_handler(eventType, eventID, newEntry, **kwargs): ...
def _undo_closeGroup_handler(eventType, eventID, **kwargs): ...
def _undo_disable_handler(eventType, eventID, **kwargs): ...
def _undo_enable_handler(eventType, eventID, **kwargs): ...
def _undo_openGroup_handler(eventType, eventID, groupName, **kwargs): ...