[tool.mypy]
check_untyped_defs = true
files = [
    "noxfile.py",
    "*/stubgen_*.py",
    "common/src/stubgenlib"
]

[tool.ruff]
include = ["*.py"]
line-length = 88
lint.select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["stubgenlib", "hou_cleanup_config"]

[dependency-groups]
dev = [
    "nox>=2025.10.16",
]
