from PySide2 import QtWidgets
from _typeshed import Incomplete

class ChannelDialog(QtWidgets.QDialog):
    settings: Incomplete
    paths: Incomplete
    def __init__(self, parent: Incomplete | None = ...) -> None: ...
    def importChannels(self) -> None: ...
    def onEntityImportFinished(self, mariEntity) -> None: ...
    def selectImportFile(self): ...
