from PySide6.QtCore import QObject
from PySide6.QtWidgets import QWidget
from _typeshed import Incomplete
from moverlay import drawStyles as drawStyles
from moverlay.enums import Direction as Direction

tailSize: Incomplete
bgColor: Incomplete
margin: Incomplete
buttonMargin: Incomplete
closeSize: Incomplete
overlayObjectName: str
g_recoveryOverlayInstance: Incomplete

def drawBubbleTail(painter) -> None: ...

class CustomStyleWidget(QWidget):
    def paintEvent(self, e) -> None: ...

def createCloseButton(closeCallback): ...
def createLabel(text): ...
def createContentWidget(text, closeCallback): ...
def destroyOverlay(overlay) -> None: ...
def createOverlay(label, closeCallback): ...

class CrashRecoveryMsg(QObject):
    isDestroyed: bool
    destructionTimer: Incomplete
    overlay: Incomplete
    def __init__(self, text) -> None: ...
    def __del__(self) -> None: ...
    def show(self) -> None: ...
    def destroyOverlay(self) -> None: ...

def getCrashRecoveryMsg(crashFile, iconVisible): ...
def destroyOverlayMessage() -> None: ...
def initCrashRecoveryMessage() -> None: ...
def hideCrashRecoveryMessage() -> None: ...
