from _typeshed import Incomplete

windowName: str

class NodeEditorBookmarksWindow:
    def __init__(self, ned) -> None: ...
    def reset(self): ...
    def selectLastLoadedInfo(self) -> None: ...

def addCallback(ned) -> None: ...
def removeCallback(ned: Incomplete | None = None) -> None: ...
def buildMenu(ned) -> None: ...
def buildToolbar(ned) -> None: ...
def renameBookmark(ned, oldname, info, *args) -> None: ...
def loadBookmark(ned, info, *args) -> None: ...
def createBookmark(ned, *args) -> None: ...
def loadNextBookmark(ned) -> None: ...
def loadPreviousBookmark(ned) -> None: ...
def showWindow(ned, *args) -> None: ...
