def pyError(errorString) -> None: ...
def collectTripleAttrs(obj, attrs): ...
def addAndConnectObjAttrsToContainer(obj, inAttrs) -> None: ...
def removePublishedAttrsFromContainer(obj, inAttrs) -> None: ...
def publishAttrToContainer() -> None: ...
def unpublishAttrFromContainer() -> None: ...
