from _typeshed import Incomplete

def getInstance(): ...
def registerServer(serverName, addrFamily): ...

class ServerRegistryMMap:
    instance: Incomplete
    recordStruct: Incomplete
    bitmapStruct: Incomplete
    def __init__(self) -> None: ...
    def offsetToRecord(self, i): ...
    def getBitmap(self): ...
    def setBitmap(self, bitmap) -> None: ...
    def getServer(self, i): ...
    def setServer(self, i, serverName, port) -> None: ...
    def findServer(self, serverName): ...
    def firstFreeSlot(self): ...
    def addServer(self, serverName, port) -> None: ...
    def removeServer(self, serverName): ...
    def servers(self): ...
