def addPath(path, niceName) -> None: ...
def attachStore(lister, fpath): ...
def detachStore(lister) -> None: ...
def readFavorites(fname): ...
def swapDisplayNameAndKeyTupple(tpl): ...
def swapDisplayNameAndKey(srcFavorites): ...

class TLFavoriteStore:
    def __init__(self, fname) -> None: ...
    def attachClient(self, lister) -> None: ...
    def removeClient(self, lister) -> None: ...
    def get(self): ...
    def update(self, lister, path, isAdded) -> None: ...
