from .layer import Layer as Layer
from _typeshed import Incomplete
from collections.abc import Generator

class AdjustableLayer(Layer):
    hasAdjustmentStack: Incomplete
    isAdjustmentStackEnabled: Incomplete
    def __init__(self, name, parent) -> None: ...
    @property
    def adjustmentStack(self): ...
    @adjustmentStack.setter
    def adjustmentStack(self, adjustmentStack) -> None: ...
    def asDict(self, includeDict: Incomplete | None = ...): ...
    @classmethod
    def fromDict(cls, dataDict, parent, sourceFilePath): ...
    @classmethod
    def fromMariObject(cls, mariObject, parent): ...
    def makeChildren(self, finishedCallback=...) -> None: ...
    def walk(self, depth: int = ...) -> Generator[Incomplete, None, None]: ...
