# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import PyUtilModule.IRFs as IRFs
import NodegraphAPI as NodegraphAPI

_delegates: dict
_renderFiltersDelegate: None

class Delegate:
    def accepts(self, node, renderItem): ...
    def begin(self, node, renderItem): ...
    def end(self, node, renderItem, blindData): ...

class IrfException(Exception): ...

class RenderFiltersDelegate(Delegate):
    def accepts(self, node, renderItem): ...
    def begin(self, node, renderItem): ...
    def end(self, node, renderItem, blindData): ...
    def getActiveRenderFilterNodes(self) -> list[NodegraphAPI.RenderFilter.RenderFilterNode]: ...
    def setActiveRenderFilterNodes(self, nodes: list[NodegraphAPI.RenderFilter.RenderFilterNode]): ...

def GetRenderFiltersDelegate(): ...
def RegisterDelegate(nodeType, delegate): ...
def RenderPreprocessBegin(renderItem): ...
def RenderPreprocessEnd(renderItem, blindData): ...
def _GetDelegateForNode(node): ...
def _GetTypeList(node): ...