# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import NodegraphAPI as NodegraphAPI
import Utils as Utils
from _typeshed import Incomplete

_BYPASS_PARAM_NAME: str
_BypassableNodesCache: set
__bypassParameterFromBypassStateNodes: set
__bypassStateFromBypassParameterNodes: set

def EditBypassedStateExpression(node: NodegraphAPI.Node, parent: Incomplete | None = ...): ...
def IsBypassedStateAnimated(node: NodegraphAPI.Node) -> bool: ...
def IsBypassedStateControlledByExpression(node: NodegraphAPI.Node) -> bool: ...
def _CollectNodesAndChildParamsInCollapsedHandler(args) -> None: ...
def _CollectNodesAndParamsInCollapsedHandler(args) -> None: ...
def _CollectNodesInCollapsedHandler(args) -> set[NodegraphAPI.Node]: ...
def _GetBypassParameter(node: NodegraphAPI.Node) -> NodegraphAPI.Parameter: ...
def _UpdateBypassParameterFromBypassState(bypassParam: NodegraphAPI.Parameter): ...
def _UpdateBypassStateFromBypassParameter(bypassParam: NodegraphAPI.Parameter): ...
def _on_node_create(eventType, eventID, node, nodeType, nodeName): ...
def _on_node_delete(eventType, eventID, node, oldName): ...
def _on_node_setBypassed(args): ...
def _on_parameter_createChild(args): ...
def _on_parameter_deleteChild(args): ...
def _on_parameter_finalizeValue(args): ...