from typing import Iterable, Iterator, TypeVar

T = TypeVar('T')

class VersionError(Exception): ...
class ParseException(Exception): ...

class _Common:
    def __str__(self) -> str: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

def dedup(iterable: Iterable[T]) -> Iterator[T]:
    """Removes duplicates from a sorted sequence."""
