# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import PyQt5.QtWidgets

class CustomQLineEdit(PyQt5.QtWidgets.QLineEdit):
    def __init__(self, *args): ...
    def focusInEvent(self, event): ...
    def focusOutEvent(self, event): ...