# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import QtWidgets

def BackspaceSpacesToTabStop(textEdit: QtWidgets.QTextEdit, spacing: int = ...) -> bool: ...
def CountWhitespaceToTabStop(textEdit: QtWidgets.QTextEdit, previousTab: bool = ..., spacing: int = ...) -> int: ...
def DeleteSpacesToTabStop(textEdit: QtWidgets.QTextEdit, spacing: int = ...) -> bool: ...
def InsertNewLineAndAutoIndent(textEdit: QtWidgets.QTextEdit, rule: str, spacing: int = ...): ...
def MoveToLineStart(textEdit: QtWidgets.QTextEdit, keepAnchor: bool): ...
def Reindent(textEdit: QtWidgets.QTextEdit, unindent: bool, spacing: int = ...): ...
def ToggleComment(textEdit: QtWidgets.QTextEdit, commentSymbol: str): ...