# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import PyFnAttribute as FnAttribute
import PyFnGeolib as FnGeolib
import PyFnGeolibProducers as FnGeolibProducers
from LookFileBakeAPI.Exceptions import LookFileBakeException as LookFileBakeException
from _typeshed import Incomplete

def CheckRootLocations(rootLocations: Iterable[str], op: FnGeolib.GeolibRuntimeOp, rootLocationProducers: Incomplete | None = ...): ...
def FindSharedLodGroupLocations(rootLocations, origProducer) -> dict: ...
def GetLookFileProducerRootId(producer) -> str: ...
def GetProducerFromOp(op: FnGeolib.GeolibRuntimeOp) -> FnGeolibProducers.GeometryProducer: ...