# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import PyFnAttribute as FnAttribute
import Utils as Utils

__KeepAsListWhiteList: frozenset
__OrderHintWhiteList: frozenset
g_hints: dict

def AttrToHints(attr: FnAttribute.Attribute) -> Tuple[int, float, str, list, dict | None]: ...
def AttrToObject(attr: FnAttribute.Attribute) -> Tuple[int, float, str, list, dict | None]: ...
def _AttrToObject(attr, attrName: str = ...): ...
def _ShouldExtractAttributeFromList(attrName: str) -> bool: ...
def _flushHandler(args): ...