__path__: list
kVirtualCameraSceneGraphLocation: str

def AppendTerminalOp(opKey, opType, opArgs): ...
def ClearAllTerminalOps(): ...
def GetTerminalOps(): ...
def InsertTerminalOp(opKey, opType, opArgs, insertIndex): ...
def RemoveTerminalOp(opKey, deferred: bool = ...): ...
def RestoreDefaultTerminalOps(): ...
def SendCommand(command): ...
def SendData(dataType, locationPath, attributes): ...
def SetLiveAttribute(locationPath, attrPath, attrValue, attrEditor: None = ...): ...
def SetVirtualCameraAttributes(attributes): ...