# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import PyUtilModule.EnvUtils as EnvUtils
import Utils.EventModule as EventModule
import PyFnGeolib as FnGeolib
import GeoAPI as GeoAPI
import NodegraphAPI as NodegraphAPI
import Nodes3DAPI as Nodes3DAPI
import PyUtilModule.RenderManager as RenderManager
import RenderingAPI as RenderingAPI
import Utils as Utils
from _typeshed import Incomplete
from typing import Set, Tuple

gCompleted: None
gCustomEditor: None
gLog: None
gOpenInEditor: None
gOutputFilename: None
gPrintToConsole: None
gSeqID: None

def CanPrintDebugOutput() -> bool: ...
def MatchSequenceID(renderSeqID, eventFrameBuffers): ...
def OnRenderCancelled(eventType, eventID): ...
def OnRenderCompleted(eventType, eventID): ...
def OnRenderStopped(eventType, eventID): ...
def UnregisterHandlers(): ...
def WriteRenderDebug(node, renderer, filename: Incomplete | None = ..., expandProcedural: bool = ..., openInEditor: bool = ..., customEditor: Incomplete | None = ..., log: Incomplete | None = ...): ...
def WriteRenderOutput(node, renderer, filename: Incomplete | None = ..., expandProcedural: bool = ..., openInEditor: bool = ..., customEditor: Incomplete | None = ..., log: Incomplete | None = ...): ...
def WriteRenderOutputForRenderMethod(renderMethodName, node, renderer, filename: Incomplete | None = ..., expandProcedural: bool = ..., log: Incomplete | None = ..., openInEditor: bool = ..., customEditor: Incomplete | None = ..., sceneGraphPath: Incomplete | None = ..., printToConsole: bool = ...): ...
def WriteSerializedOpTreeToDisk(node, applyRenderResolvers, log: Incomplete | None = ...): ...
def _CreateTempRenderNode(node): ...
