"""Generate Python stubs for 3DEqualizer4's `tde4` and `vl_sdv` modules.

`tde4` is a built-in C module that can't be imported and introspected
standalone, so its stubs are parsed from the vendor's "Python Doc (LLM)" -- a
JSON API doc published at 3dequalizer.com.  `vl_sdv` is pure python, so it is
generated by runtime inspection of the shipped module.

See the README for the download and setup; run with
`nox -s 'generate(3dequalizer)'`.
"""

from __future__ import annotations

import argparse
import contextlib
import importlib
import inspect
import json
import logging
import os
import re
import sys
from collections.abc import Iterator, Sequence
from pathlib import Path
from types import ModuleType
from typing import Any, Final, NamedTuple, TypedDict, cast

from mypy.stubdoc import FunctionSig
from mypy.stubgenc import InspectionStubGenerator
from mypy.stubutil import FunctionContext

_LOGGER = logging.getLogger(__name__)

# Type used when a semantic type's base cannot be resolved (should not happen).
_UNKNOWN_TYPE: Final = "Incomplete"

# Structured types whose base cannot be auto-derived from their `doc_lines`.
# Keyed by the bare type name; the value is the Python type to alias it to.
_TYPE_ALIAS_OVERRIDES: Final[dict[str, str]] = {
    # Return type of calcCameraLSF / calcObjectLSF. 3DE returns a fixed-shape
    # *list* (verified live), not the tuple the doc claims; the per-element
    # meaning is lost in the widened type, so it is restated in the emitted
    # comment below (see _TYPE_ALIAS_COMMENTS).
    "LSFResult_t": "list[Vector3D_t | float]",
}

# Trailing `# ...` comments emitted next to an alias, for fixed-shape lists
# whose per-element meaning the widened type can't convey. Keyed by type name.
_TYPE_ALIAS_COMMENTS: Final[dict[str, str]] = {
    "LSFResult_t": "[position, rotation (euler), focal length (cm), deviation (px)]",
}

# Return-type corrections for functions whose spec return type is wrong, keyed by
# function name and verified against a live `tde4`. Three kinds:
#
# * the spec types these as `tuple[...]`, but 3DE returns a `list` at runtime,
#   so they are widened to `list` of the de-duplicated union of the members
#   (heterogeneous ones additionally carry a `_RETURN_SHAPE_COMMENTS` entry to
#   restate the per-position meaning the union loses);
# * some return lists whose elements are `None` for unset entries, which the
#   spec's element type omits;
# * `getTextAreaWidgetString` is spec'd `str` but returns `None` for an empty
#   text area (like its sibling `getTextAreaWidget*` accessors), so the return
#   is widened to `str | None`.
_RETURN_TYPE_OVERRIDES: Final[dict[str, str]] = {
    "convertObjectPGroupTransformation3DEToWorld": "list[Matrix3D_t | Vector3D_t]",
    "convertObjectPGroupTransformationWorldTo3DE": "list[Matrix3D_t | Vector3D_t]",
    "align3DModelto3DModel": "list[float | Vector3D_t | Matrix3D_t] | None",
    "getDisplayAreaTransformation": "list[float]",
    "getDisplayAreaDimensions": "list[int]",
    "getPGroupInvertPointCloudPoints": "list[str | None]",
    "getPGroupRootFrameA": "list[CameraID_t | int | None]",
    "getPGroupRootFrameB": "list[CameraID_t | int | None]",
    "getPGroupExtractOverallMotionPoints": "list[str | None]",
    "getTextAreaWidgetString": "str | None",
}

# Trailing `# ...` comments emitted next to a function whose return is a
# fixed-shape, heterogeneous list -- the spec types it as a tuple, but 3DE
# returns a list (corrected in _RETURN_TYPE_OVERRIDES), so the widened element
# union loses the per-position meaning restated here. Keyed by function name.
_RETURN_SHAPE_COMMENTS: Final[dict[str, str]] = {
    "convertObjectPGroupTransformation3DEToWorld": "[transform matrix, position]",
    "convertObjectPGroupTransformationWorldTo3DE": "[transform matrix, position]",
    "align3DModelto3DModel": "[deviation (cm), translation, scale-rotation matrix]",
}

# Functions present on the live `tde4` module but absent from the vendor spec
# (thin wrappers around the standard `math` module).  Keyed by name; the
# value is the `(params) -> ret` signature.
_SUPPLEMENTAL_FUNCTIONS: Final[dict[str, str]] = {
    "acos": "(x: float, /) -> float",
    "asin": "(x: float, /) -> float",
    "atan2": "(y: float, x: float, /) -> float",
    "cos": "(x: float, /) -> float",
    "sin": "(x: float, /) -> float",
    "sqrt": "(x: float, /) -> float",
}

# The module prefix on every qualified name in the spec, e.g. `tde4.createCamera`.
_TDE4_PREFIX: Final = "tde4."

# Message attached to the `@deprecated` decorator emitted for deprecated functions.
_DEPRECATED_MESSAGE: Final = "deprecated in 3DEqualizer"

# Placeholder default emitted for every omittable argument. The spec marks them as
# `<type> | None = None`, but the C functions reject an explicit `None` -- the
# argument must be omitted instead (verified against a live tde4), so we emit a bare
# `= ...` and drop the `| None` from the annotation.
_DEFAULT_VALUE: Final = "..."

# Prefixes for the variadic parameter `kind`s, used when rendering a signature.
_VAR_ARG_PREFIXES: Final[dict[str, str]] = {
    "VAR_POSITIONAL": "*",
    "VAR_KEYWORD": "**",
}

# Name imported from `typing` to annotate the emitted semantic type aliases.
_TYPE_ALIAS_IMPORT: Final = "TypeAlias"

# The spec describes container bases with capital-T `typing` names; map them to
# the lowercase builtins the emitted stubs use.
_CONTAINER_SPELLINGS: Final[dict[str, str]] = {
    "List": "list",
    "Tuple": "tuple",
    "Dict": "dict",
}
_CONTAINER_SPELLING_RE: Final = re.compile(rf"\b({'|'.join(_CONTAINER_SPELLINGS)})\b")

# `vl_sdv` rebinds these public class names to factory functions (see
# `VLSdvStubGenerator`).
_VL_SDV_SHADOWED_BASE_NAMES: Final[tuple[str, ...]] = ("vec", "mat", "igl")

# A type's `doc_lines` describe its base as a |type|`<base>` line and any enum
# members as |value|`"VALUE"` lines. Each regex below has its matched example inline.
#   '* |value|`"SEQUENCE"`'           -> captures '"SEQUENCE"'
_VALUE_DOC_RE: Final = re.compile(r'\|value\|`("[^"]*")`')

#   '|type|`List[float]`'             -> captures 'List[float]'
_TYPE_DOC_RE: Final = re.compile(r"\s*\|type\|`([^`]+)`")

#   'list[Vector2D_t]'                -> finds 'list', 'Vector2D_t'
_IDENTIFIER_RE: Final = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


class ParameterSpec(TypedDict, total=False):
    """One entry of a callable's `signature.parameters`.

    Examples:
        A required argument has no default:

            {"name": "camera_id", "kind": "POSITIONAL_OR_KEYWORD",
             "annotation": "CameraID_t", "default": None}

        An omittable argument carries `"default": "None"` and a `| None` annotation:

            {"name": "pgroup_scale", "kind": "POSITIONAL_OR_KEYWORD",
             "annotation": "float | None", "default": "None"}
    """

    name: str
    kind: str
    annotation: str | None
    default: str | None


class SignatureSpec(TypedDict, total=False):
    """A callable's `signature` block.

    We render from the structured `parameters` and `returns` (the sibling
    `text` is the same signature pre-rendered, which we don't consume).

    Example:
        `createCamera(mode: 'CameraType_t') -> 'CameraID_t'` is carried as:

            {"parameters": [{"name": "mode", "kind": "POSITIONAL_OR_KEYWORD",
                             "annotation": "CameraType_t", "default": None}],
             "returns": "CameraID_t"}
    """

    parameters: list[ParameterSpec]
    returns: str


class PreambleSpec(TypedDict, total=False):
    """A callable's `doc.Preamble`, e.g. `{"status": "deprecated"}`."""

    status: str


class DocSpec(TypedDict, total=False):
    """A callable's `doc` block, e.g. `{"Preamble": {"status": "deprecated"}}`."""

    Preamble: PreambleSpec


class SpecObject(TypedDict, total=False):
    """The per-name detail in `__WTRL_OBJECTS__` (a callable or a semantic type).

    Examples:
        A callable carries a `signature` (and optionally a `doc`):

            {"signature": {"parameters": [...], "returns": "CameraID_t"}}

        A semantic type carries `doc_lines` instead:

            {"doc_lines": ["|type|`str`"]}
    """

    doc: DocSpec
    doc_lines: list[str]
    signature: SignatureSpec


class SpecDocument(TypedDict, total=False):
    """The parsed top-level WTRL JSON spec.

    The `__WTRL_TOC_*` tables of contents map a qualified name to a JSON
    pointer; we only need the names (the keys). `__WTRL_OBJECTS__` holds the
    detail per name.

    Examples:
        A TOC maps each name to a pointer, and `__WTRL_OBJECTS__` holds the
        detail it points at:

            {
                "__WTRL_TOC_CALLABLES__": {
                    "tde4.createCamera": "/__WTRL_OBJECTS__/tde4.createCamera"
                },
                "__WTRL_OBJECTS__": {
                    "tde4.createCamera": {"signature": {"parameters": [], "returns": "..."}},
                    "tde4.CameraID_t": {"doc_lines": ["|type|`str`"]},
                },
            }
    """

    __WTRL_OBJECTS__: dict[str, SpecObject]
    __WTRL_TOC_CALLABLES__: dict[str, str]
    __WTRL_TOC_TYPES__: dict[str, str]
    __WTRL_TOC_CLASSES__: dict[str, str]
    __WTRL_TOC_CONSTANTS__: dict[str, str]


def _strip_module_prefix(qualified_name: str) -> str:
    """Strip the leading `tde4.` module prefix from a qualified name.

    Args:
        qualified_name: A qualified name such as `"tde4.getCameraFocalLength"`.

    Returns:
        The bare name (`"getCameraFocalLength"`), or `qualified_name`
        unchanged if it does not start with `tde4.`.

    Examples:
        `"tde4.createCamera"` -> `"createCamera"`
        `"vl_sdv"` -> `"vl_sdv"` (no `tde4.` prefix, unchanged)
    """
    return (
        qualified_name.split(".", 1)[1]
        if qualified_name.startswith(_TDE4_PREFIX)
        else qualified_name
    )


class Spec:
    """A loaded WTRL JSON spec, with typed accessors for the parts we need.

    We read `__WTRL_TOC_CALLABLES__` (the `tde4.<func>` names),
    `__WTRL_TOC_TYPES__` (semantic types like `CameraID_t`),
    `__WTRL_TOC_CLASSES__` / `__WTRL_TOC_CONSTANTS__` (the constant-holder
    enum classes and their members), and `__WTRL_OBJECTS__` (the detail for
    each: a callable's `signature` and `doc`, or a type's `doc_lines`).
    """

    def __init__(self, data: SpecDocument) -> None:
        """Wrap the parsed JSON document.

        Args:
            data: The parsed top-level JSON object.
        """
        self._objects: dict[str, SpecObject] = dict(data.get("__WTRL_OBJECTS__") or {})
        self._callable_names = list(data.get("__WTRL_TOC_CALLABLES__") or {})
        self._type_names = {
            _strip_module_prefix(name) for name in data.get("__WTRL_TOC_TYPES__") or {}
        }
        self._class_names = list(data.get("__WTRL_TOC_CLASSES__") or {})
        self._constant_names = list(data.get("__WTRL_TOC_CONSTANTS__") or {})

    @classmethod
    def load(cls, spec_path: Path) -> Spec:
        """Load and wrap a spec JSON file.

        Args:
            spec_path: Path to the downloaded `*.wtrl*.json` spec.

        Returns:
            The wrapped `Spec`.
        """
        data = cast(SpecDocument, json.loads(spec_path.read_text(encoding="utf-8")))
        return cls(data)

    @property
    def type_names(self) -> set[str]:
        """The set of bare semantic type names, e.g. `{"CameraID_t", ...}`."""
        return self._type_names

    def callables(self) -> list[tuple[str, SpecObject]]:
        """Return `(bare_name, object)` for every top-level `tde4` callable.

        Returns:
            The module-level functions only; class methods (names containing a
            dot after `tde4.`) are skipped. The functions preserve the vendor
            TOC order to avoid needless churn in the generated stub.

        Examples:
            `tde4.createCamera` is kept as `("createCamera", {...})`;
            `tde4.WidgetCallbackActionEnum.__init__` is skipped (dotted).
        """
        result: list[tuple[str, SpecObject]] = []
        for qualified_name in self._callable_names:
            bare_name = _strip_module_prefix(qualified_name)
            if "." in bare_name:
                continue  # a method on a class, not a module-level function

            obj = self._objects.get(qualified_name)
            if obj is not None:
                result.append((bare_name, obj))

        return result

    def type_doc_lines(self, type_name: str) -> list[str]:
        """Return the `doc_lines` describing a semantic type.

        Args:
            type_name: The bare type name, e.g. `"CameraID_t"`.

        Returns:
            The doc lines, or an empty list if the type is unknown.
        """
        obj = self._objects.get(f"{_TDE4_PREFIX}{type_name}")
        return list((obj or {}).get("doc_lines") or [])

    def enum_classes(self) -> dict[str, list[str]]:
        """Return the constant-holder classes and their integer members.

        Returns:
            A map of class name to its sorted member names, e.g.
            `{"WidgetCallbackActionEnum": ["CLICK", "DCLICK", ...]}`.
        """
        members: dict[str, list[str]] = {
            _strip_module_prefix(class_name): [] for class_name in self._class_names
        }
        for qualified_name in self._constant_names:
            bare_name = _strip_module_prefix(qualified_name)
            class_name, _, member = bare_name.partition(".")
            if member and class_name in members:
                members[class_name].append(member)

        return {name: sorted(members[name]) for name in sorted(members)}


def _normalize_typing_builtins(type_expr: str) -> str:
    """Rewrite the spec's capital-T container names to lowercase builtins.

    The semantic types' `doc_lines` describe bases using `List`/`Tuple`/
    `Dict`; the emitted stubs use the lowercase builtins instead.

    Args:
        type_expr: A type expression such as `"List[Vector3D_t]"`.

    Returns:
        The expression with `List`/`Tuple`/`Dict` lowercased.

    Examples:
        `"List[Vector3D_t]"` -> `"list[Vector3D_t]"`
        `"int | None"` -> `"int | None"` (no container names, unchanged)
    """
    return _CONTAINER_SPELLING_RE.sub(
        lambda match: _CONTAINER_SPELLINGS[match.group()], type_expr
    )


def _resolve_type_alias(type_name: str, doc_lines: Sequence[str]) -> str:
    """Resolve a semantic type to the Python type it aliases.

    Args:
        type_name: The bare type name, e.g. `"CameraType_t"`.
        doc_lines: The type's `doc_lines` from the spec.

    Returns:
        The aliased Python type expression, e.g. `"str"`, `"list[float]"` or
        `'Literal["SEQUENCE", "REF_FRAME"]'`. Falls back to `"Incomplete"`
        (and logs a warning) for a type whose base cannot be derived.

    Examples:
        Scalar:  `("CameraID_t", ["|type|`str`"])` -> `"str"`
        Container: `("Vector3D_t", ["|type|`List[float]`"])` -> `"list[float]"`
        Enum: `("CameraType_t", ['|value|`"SEQUENCE"`', '|value|`"REF_FRAME"`'])`
            -> `'Literal["SEQUENCE", "REF_FRAME"]'`
    """
    if type_name in _TYPE_ALIAS_OVERRIDES:
        return _TYPE_ALIAS_OVERRIDES[type_name]

    # Enum types list their members as `* |value|`"VALUE"` lines.
    literal_values: list[str] = []
    for line in doc_lines:
        for value in _VALUE_DOC_RE.findall(line):
            if value not in literal_values:
                literal_values.append(value)

    if literal_values:
        return f"Literal[{', '.join(literal_values)}]"

    # Scalar / container types start a line with `|type|`<base>`.
    for line in doc_lines:
        match = _TYPE_DOC_RE.match(line)
        if match:
            return _normalize_typing_builtins(match.group(1).strip())

    _LOGGER.warning("could not resolve type %r; using %s", type_name, _UNKNOWN_TYPE)
    return _UNKNOWN_TYPE


def _collect_referenced_types(annotation: str, known_types: set[str]) -> set[str]:
    """Find the semantic type names referenced in a type expression.

    Args:
        annotation: A type expression, e.g. `"list[Vector2D_t]"`.
        known_types: All known semantic type names.

    Returns:
        The subset of `known_types` mentioned in `annotation`.

    Examples:
        `("list[Vector2D_t]", {"Vector2D_t", "CameraID_t"})` -> `{"Vector2D_t"}`
    """
    tokens = set(_IDENTIFIER_RE.findall(annotation))
    return tokens & known_types


def _signature_annotations(obj: SpecObject) -> Iterator[str]:
    """Yield every type expression a callable's signature references.

    Args:
        obj: A callable's spec object.

    Yields:
        Each parameter `annotation` (skipping the `None` of `*args`) and the
        `returns` type, as raw type expressions -- used to discover which
        semantic types a signature depends on.
    """
    signature = obj.get("signature") or {}
    for parameter in signature.get("parameters", []):
        annotation = parameter.get("annotation")
        if annotation is not None:
            yield annotation

    returns = signature.get("returns")
    if returns is not None:
        yield returns


def _render_parameter(parameter: ParameterSpec) -> str:
    """Render one `signature.parameters` entry as stub source.

    Args:
        parameter: A single parameter spec.

    Returns:
        The rendered parameter, e.g. `"camera_id: CameraID_t"`,
        `"pgroup_scale: float = ..."` or `"*args: str"`.

    Examples:
        `{"name": "frame", "annotation": "int", "default": None}` -> `"frame: int"`
        `{"name": "x", "annotation": "int | None", "default": "None"}` -> `"x: int = ..."`
        `{"name": "args", "kind": "VAR_POSITIONAL", "annotation": "str"}` -> `"*args: str"`
    """
    name = f"{_VAR_ARG_PREFIXES.get(parameter.get('kind', ''), '')}{parameter['name']}"
    annotation = parameter.get("annotation")
    has_default = parameter.get("default") is not None

    if annotation is None:  # an un-annotated `*args` / `**kwargs`
        return f"{name} = {_DEFAULT_VALUE}" if has_default else name

    # An omittable arg is spec'd `<type> | None = None`; the runtime rejects an
    # explicit `None`, so narrow it to `<type> = ...` (verified live).
    if has_default and annotation.endswith(" | None"):
        annotation = annotation[: -len(" | None")]

    rendered = f"{name}: {annotation}"
    return f"{rendered} = {_DEFAULT_VALUE}" if has_default else rendered


def _render_parameters(parameters: list[ParameterSpec]) -> str:
    """Render a parameter list, marking the regular params positional-only.

    Every `tde4` function is a C builtin that rejects keyword arguments (it
    raises `TypeError: ... takes no keyword arguments`), so a `/` marker is
    inserted after the last regular parameter -- before any `*args` -- to make
    the stub reject keyword calls too.

    Examples:
        `[{"name": "mode", "annotation": "CameraType_t"}]` -> `"mode: CameraType_t, /"`
        `[{"name": "id_cam", "annotation": "CameraID_t"},
        {"name": "ldpar", "kind": "VAR_POSITIONAL", "annotation": "str"}]`
        -> `"id_cam: CameraID_t, /, *ldpar: str"`
    """
    rendered = [_render_parameter(p) for p in parameters]
    last_regular = -1
    for index, parameter in enumerate(parameters):
        if parameter.get("kind") not in _VAR_ARG_PREFIXES:
            last_regular = index
    if last_regular >= 0:
        rendered.insert(last_regular + 1, "/")
    return ", ".join(rendered)


def _build_signature(name: str, obj: SpecObject) -> str:
    """Render one callable as a `def name(...) -> ret: ...` stub line.

    Built from the structured `signature.parameters` and `signature.returns`
    (not the pre-rendered `text`): each parameter is rendered, the return type is
    replaced by any `_RETURN_TYPE_OVERRIDES` entry, and the pieces assembled.

    Args:
        name: The function's bare name, e.g. `"createCamera"`.
        obj: The function's spec object (with a `signature`).

    Returns:
        A single `.pyi` function-definition line.

    Raises:
        ValueError: If the object's `signature` has no `returns`.

    Examples:
        `("createCamera", {"signature": {"parameters": [{"name": "mode",
        "annotation": "CameraType_t"}], "returns": "CameraID_t"}})`
        -> `def createCamera(mode: CameraType_t, /) -> CameraID_t: ...`
    """
    signature = obj.get("signature")
    if signature is None or "returns" not in signature:
        raise ValueError("signature.returns is missing")

    parameters = _render_parameters(signature.get("parameters", []))
    return_type = _RETURN_TYPE_OVERRIDES.get(name, signature["returns"])

    line = f"def {name}({parameters}) -> {return_type}: ..."
    comment = _RETURN_SHAPE_COMMENTS.get(name)
    if comment:
        line += f"  # {comment}"
    return line


def _is_deprecated(obj: SpecObject) -> bool:
    """Return whether the spec flags this callable as deprecated.

    Args:
        obj: A callable's spec object.

    Returns:
        `True` if `doc.Preamble.status` is `"deprecated"`.

    Examples:
        `{"doc": {"Preamble": {"status": "deprecated"}}}` -> `True`
        `{"signature": {"returns": "..."}}` -> `False` (no status)
    """
    return obj.get("doc", {}).get("Preamble", {}).get("status") == "deprecated"


def _render_header(body_text: str) -> list[str]:
    """Render the file docstring and only the imports the body uses.

    Args:
        body_text: The already-rendered module body, scanned to decide which
            imports are needed.

    Returns:
        The header lines, ending with a blank line before the body.

    Examples:
        A body containing `Literal[` and a `: TypeAlias =` line yields a
        header whose imports include `from typing import Literal, TypeAlias`;
        a body using neither omits that import entirely.
    """
    lines = [
        '"""Type stubs for the 3DEqualizer4 `tde4` module.',
        "",
        'Auto-generated from the 3DEqualizer "Python Doc (LLM)" JSON spec',
        "(Tech Docs > Python Scripting Interface). Do not edit by hand; regenerate",
        "with `nox -s 'generate(3dequalizer)'`.",
        '"""',
        "",
    ]
    typing_imports: list[str] = []
    if "Literal[" in body_text:
        typing_imports.append("Literal")

    if f": {_TYPE_ALIAS_IMPORT} =" in body_text:
        typing_imports.append(_TYPE_ALIAS_IMPORT)

    if typing_imports:
        lines.append(f"from typing import {', '.join(typing_imports)}")

    if "@deprecated(" in body_text:
        lines.append("from typing_extensions import deprecated")

    if _UNKNOWN_TYPE in body_text:
        lines.append("from _typeshed import Incomplete")

    lines.append("")
    return lines


class Tde4SpecRenderer:
    """Renders a loaded `Spec` into the `tde4/__init__.pyi` stub text.

    Owns every `tde4`-specific rendering step (the `vl_sdv` side lives in
    `VLSdvStubGenerator`). Construct it with a `Spec` -- or with
    `from_spec_file` to load one off disk -- then call `render` for the module
    text, or `write` to create the package on disk. The stateless rendering
    leaves it calls (`_render_parameter`, `_resolve_type_alias`,
    `_build_signature`, `_render_header`, ...) stay module-level functions.
    """

    def __init__(self, spec: Spec) -> None:
        """Wrap the spec to render.

        Args:
            spec: The loaded spec to render the `tde4` stubs from.
        """
        self._spec = spec

    @classmethod
    def from_spec_file(cls, spec_path: Path) -> Tde4SpecRenderer:
        """Build a renderer from a spec JSON file on disk.

        Args:
            spec_path: Path to the downloaded `*.wtrl*.json` spec.

        Returns:
            A renderer wrapping the loaded spec.
        """
        return cls(Spec.load(spec_path))

    def render(self) -> str:
        """Render the full `tde4/__init__.pyi` text from the spec.

        Returns:
            The complete `.pyi` file contents: header, imports, constant classes,
            type aliases and function definitions.
        """
        body_lines = (
            self._render_enum_classes()
            + self._render_type_aliases()
            + self._render_functions()
        )
        body_text = "\n".join(body_lines)
        return "\n".join(_render_header(body_text)) + "\n" + body_text + "\n"

    def write(self, out_dir: Path) -> Path:
        """Render the `tde4` stub package and write it under `out_dir`.

        Args:
            out_dir: Directory in which to create the `tde4/` package.

        Returns:
            The path of the written `tde4/__init__.pyi` file.
        """
        module_text = self.render()

        package_dir = out_dir / "tde4"
        package_dir.mkdir(parents=True, exist_ok=True)
        out_file = package_dir / "__init__.pyi"
        out_file.write_text(module_text, encoding="utf-8")
        _LOGGER.info("wrote %d functions -> %s", module_text.count("def "), out_file)
        return out_file

    def _render_enum_classes(self) -> list[str]:
        """Render the constant-holder enum classes and their integer members.

        Returns:
            The `.pyi` lines for every enum class, each block followed by a blank
            line. A class with no members renders a `...` body.

        Examples:
            For one class `WidgetCallbackActionEnum` with members `CLICK`,
            `DCLICK`:

                ["class WidgetCallbackActionEnum:", "    CLICK: int",
                 "    DCLICK: int", ""]
        """
        lines: list[str] = []
        for class_name, members in self._spec.enum_classes().items():
            lines.append(f"class {class_name}:")
            if members:
                lines.extend(f"    {member}: int" for member in members)
            else:
                lines.append("    ...")
            lines.append("")

        return lines

    def _render_type_aliases(self) -> list[str]:
        """Render the semantic type aliases reachable from the signatures.

        Returns:
            One `Name: TypeAlias = <type>` line per alias (sorted), each with an
            optional trailing `# ...` comment, followed by a blank line if any
            were emitted.
        """
        aliases = self._resolve_all_type_aliases()
        lines = []
        for name in sorted(aliases):
            line = f"{name}: {_TYPE_ALIAS_IMPORT} = {aliases[name]}"
            comment = _TYPE_ALIAS_COMMENTS.get(name)
            if comment:
                line += f"  # {comment}"
            lines.append(line)

        if lines:
            lines.append("")

        return lines

    def _resolve_all_type_aliases(self) -> dict[str, str]:
        """Resolve every semantic type reachable from the callable signatures.

        Returns:
            A map of type name to its resolved alias body, including the transitive
            closure (e.g. `Matrix3D_t` pulls in `Vector3D_t`).

        Examples:
            For a spec whose only signature returns `Matrix3D_t`:

                {"Matrix3D_t": "list[Vector3D_t]", "Vector3D_t": "list[float]"}
        """
        pending: set[str] = set()
        for _, obj in self._spec.callables():
            # Scan only the structured annotations/return, never the parameter names,
            # so a parameter named like a type isn't mistaken for a type reference.
            for annotation in _signature_annotations(obj):
                pending |= _collect_referenced_types(annotation, self._spec.type_names)

        resolved: dict[str, str] = {}
        while pending:
            type_name = min(pending)
            pending.remove(type_name)
            if type_name in resolved:
                continue

            alias_body = _resolve_type_alias(
                type_name, self._spec.type_doc_lines(type_name)
            )
            resolved[type_name] = alias_body
            pending |= (
                _collect_referenced_types(alias_body, self._spec.type_names)
                - resolved.keys()
            )

        return resolved

    def _render_functions(self) -> list[str]:
        """Render every callable plus the supplemental math functions.

        Returns:
            The `.pyi` lines for all functions, each deprecated one preceded by a
            `@deprecated` decorator.
        """
        lines: list[str] = []
        spec_names: set[str] = set()
        for name, obj in self._spec.callables():
            spec_names.add(name)
            if _is_deprecated(obj):
                lines.append(f'@deprecated("{_DEPRECATED_MESSAGE}")')
            lines.append(_build_signature(name, obj))

        # The math wrappers live on the module but are absent from the spec; skip any a
        # future spec starts documenting, so we never emit a duplicate definition.
        for name, signature in sorted(_SUPPLEMENTAL_FUNCTIONS.items()):
            if name not in spec_names:
                lines.append(f"def {name}{signature}: ...")

        return lines


# Header prepended to the generated `vl_sdv` stub (it comes from the
# `vl_sdv.py` module via runtime inspection, not from the JSON spec).
_VL_SDV_HEADER = (
    '"""Type stubs for the 3DEqualizer4 `vl_sdv` module.\n'
    "\n"
    "Auto-generated with mypy inspection from the vl_sdv.py shipped with 3DEqualizer.\n"
    "Do not edit by hand; regenerate with `nox -s 'generate(3dequalizer)'`.\n"
    '"""\n\n'
)


class ClassAliasValue(NamedTuple):
    """Marks a class-valued attribute so it renders as `type[...]`, not a nested class.

    Example:
        `vec_type = vec1d` is wrapped as `ClassAliasValue(vec1d)` and
        rendered as `vec_type: ClassVar[type[_vec1d]]`.
    """

    target: type[Any]


class VLSdvStubGenerator(InspectionStubGenerator):
    """Inspection-based generator with 3DEqualizer-specific `vl_sdv` fixes.

    `vl_sdv` defines `vec`/`mat`/`igl` as base classes early in the
    module, then rebinds those public names to factory functions at the end.
    Plain inspection sees only the final functions at module scope, so derived
    classes inherit from undefined names and class-valued attributes like
    `vec_type = vec1d` get mis-rendered as nested classes.  This subclass:

    * emits the hidden bases as private classes (`_vec` / `_mat` / `_igl`),
    * rewrites derived-class bases to those private names, and
    * keeps class-valued attributes as `ClassVar[type[...]]` instead of nested
      class definitions.
    """

    def __init__(
        self,
        module_name: str,
        known_modules: list[str],
        doc_dir: str = "",
        _all_: list[str] | None = None,
        include_private: bool = False,
        export_less: bool = False,
        include_docstrings: bool = False,
        module: ModuleType | None = None,
    ) -> None:
        """Initialise the base generator, then recover the shadowed bases.

        The arguments are passed straight through to
        `mypy.stubgenc.InspectionStubGenerator` (see it for their
        meaning); the only thing this override adds is recovering the shadowed
        `vec`/`mat`/`igl` bases up front so the other overrides can use them.
        """
        super().__init__(
            module_name,
            known_modules,
            doc_dir=doc_dir,
            _all_=_all_,
            include_private=include_private,
            export_less=export_less,
            include_docstrings=include_docstrings,
            module=module,
        )
        self._shadowed_bases = self._collect_shadowed_bases()
        self._shadowed_base_aliases = {
            base_class: self._to_private_base_name(base_name)
            for base_name, base_class in self._shadowed_bases.items()
        }

    @staticmethod
    def _to_private_base_name(base_name: str) -> str:
        """Return the private stub name for a shadowed `vl_sdv` base.

        Args:
            base_name: A shadowed public base name (`"vec"`/`"mat"`/`"igl"`).

        Returns:
            The private name used in the stub, e.g. `"_vec"`.

        Examples:
            `"vec"` -> `"_vec"`; `"mat"` -> `"_mat"`
        """
        return f"_{base_name}"

    def _collect_shadowed_bases(self) -> dict[str, type[Any]]:
        """Recover the base classes hidden by the module's name rebinding.

        `vl_sdv` rebinds `vec`/`mat`/`igl` to factory functions, so the
        original classes survive only inside their subclasses' MROs.

        Returns:
            A map of shadowed base name to the recovered class, ordered like
            `_VL_SDV_SHADOWED_BASE_NAMES`.
        """
        discovered: dict[str, type[Any]] = {}
        for value in self.module.__dict__.values():
            if (
                not inspect.isclass(value)
                or self.get_obj_module(value) != self.module_name
            ):
                continue

            for base in value.__mro__[1:]:
                if self.get_obj_module(base) != self.module_name:
                    continue
                base_name = base.__name__
                if (
                    base_name in _VL_SDV_SHADOWED_BASE_NAMES
                    and base_name not in discovered
                ):
                    discovered[base_name] = base

        return {
            base_name: discovered[base_name]
            for base_name in _VL_SDV_SHADOWED_BASE_NAMES
            if base_name in discovered
        }

    def _build_hidden_base_members(self) -> list[tuple[str, type[Any]]]:
        """Return the recovered bases as `(private_name, class)` members.

        Returns:
            One `(_vec/_mat/_igl, class)` pair per recovered base, ready to be
            injected at module scope ahead of the factory functions.
        """
        return [
            (self._to_private_base_name(base_name), self._shadowed_bases[base_name])
            for base_name in _VL_SDV_SHADOWED_BASE_NAMES
            if base_name in self._shadowed_bases
        ]

    def _wrap_class_aliases(
        self, members: Sequence[tuple[str, Any]]
    ) -> list[tuple[str, Any]]:
        """Tag class-valued attributes so they render as `ClassVar[type[...]]`.

        An attribute like `vec_type = vec1d` would otherwise be mis-rendered as
        a nested class; wrapping it in `ClassAliasValue` lets
        `get_type_annotation` emit it as a typed class reference instead.

        Args:
            members: The `(name, value)` members of a class.

        Returns:
            The members with class-valued aliases wrapped, the rest unchanged.
        """
        wrapped_members: list[tuple[str, Any]] = []
        for name, value in members:
            if (
                inspect.isclass(value)
                and self.is_defined_in_module(value)
                and name != getattr(value, "__name__", None)
            ):
                wrapped_members.append((name, ClassAliasValue(value)))
            else:
                wrapped_members.append((name, value))

        return wrapped_members

    def get_members(self, obj: object) -> list[tuple[str, Any]]:
        """Inject the recovered bases and wrap class-valued aliases.

        Args:
            obj: The module or class whose members are being collected.

        Returns:
            For the module: its members with the recovered private bases inserted
            just before the shadowing factory functions. For a class: its members
            with class-valued aliases wrapped. Otherwise the members unchanged.
        """
        members = super().get_members(obj)
        if obj is self.module and self._shadowed_bases:
            hidden_members = self._build_hidden_base_members()
            output: list[tuple[str, Any]] = []
            inserted = False
            for name, value in members:
                if not inserted and name in _VL_SDV_SHADOWED_BASE_NAMES:
                    output.extend(hidden_members)
                    inserted = True
                output.append((name, value))

            if not inserted:
                output.extend(hidden_members)

            return output

        if inspect.isclass(obj):
            return self._wrap_class_aliases(members)

        return members

    def get_type_fullname(self, typ: type[Any]) -> str:
        """Map a shadowed base class to its private stub name.

        Args:
            typ: The type being referenced.

        Returns:
            `<module>._vec` (etc.) for a shadowed base, else the default name.
        """
        alias = self._shadowed_base_aliases.get(typ)
        if alias is not None:
            return f"{self.module_name}.{alias}"

        return super().get_type_fullname(typ)

    def get_default_function_sig(
        self, func: object, ctx: FunctionContext
    ) -> FunctionSig:
        """Give the `vec`/`mat`/`igl` factory functions a useful return type.

        Args:
            func: The function being rendered.
            ctx: The surrounding inspection context.

        Returns:
            The default signature, with the return type set to the matching
            private base (`_vec`/`_mat`/`_igl`) for a factory function.
        """
        signature = super().get_default_function_sig(func, ctx)
        if ctx.class_info is None and ctx.name in self._shadowed_bases:
            return FunctionSig(
                signature.name,
                signature.args,
                self._to_private_base_name(ctx.name),
            )

        return signature

    def get_type_annotation(self, obj: object) -> str:
        """Render a wrapped class alias as a `type[Target]` annotation.

        Args:
            obj: The value being annotated.

        Returns:
            `type[Target]` for a wrapped class alias, else the default
            annotation.
        """
        if isinstance(obj, ClassAliasValue):
            return f"type[{self.get_type_fullname(obj.target)}]"

        return super().get_type_annotation(obj)


def _render_vl_sdv_module(module: ModuleType) -> str:
    """Render the `vl_sdv` stub by inspecting the imported module.

    Args:
        module: The already-imported `vl_sdv` module.

    Returns:
        The generated `.pyi` text (without the file header).
    """
    generator = VLSdvStubGenerator(
        module.__name__,
        known_modules=[module.__name__],
        module=module,
    )
    generator.generate_module()
    return generator.output()


@contextlib.contextmanager
def _import_module_from_path(module_name: str, path: Path) -> Iterator[ModuleType]:
    """Import a module from `path` without leaking `sys.path` / `sys.modules`.

    `path` is prepended to `sys.path` only for the import itself, and any
    previously-imported module of the same name is restored on exit.

    Args:
        module_name: The name to import (e.g. `"vl_sdv"`).
        path: The directory containing the module.

    Yields:
        The freshly-imported module.
    """
    path_str = str(path)
    previous_module = sys.modules.pop(module_name, None)
    try:
        sys.path.insert(0, path_str)
        try:
            importlib.invalidate_caches()
            module = importlib.import_module(module_name)
        finally:
            with contextlib.suppress(ValueError):
                sys.path.remove(path_str)
        yield module
    finally:
        if previous_module is None:
            sys.modules.pop(module_name, None)
        else:
            sys.modules[module_name] = previous_module


def _generate_vl_sdv(tde4_root: Path, out_dir: Path) -> None:
    """Generate stubs for the pure-python `vl_sdv` module.

    Args:
        tde4_root: The 3DEqualizer install directory.
        out_dir: Directory in which to write `vl_sdv.pyi`.
    """
    vl_sdv_dir = tde4_root / "sys_data" / "py_vl_sdv"
    if not vl_sdv_dir.exists():
        _LOGGER.warning("skipping vl_sdv: %s not found", vl_sdv_dir)
        return

    out_file = out_dir / "vl_sdv.pyi"
    with _import_module_from_path("vl_sdv", vl_sdv_dir) as module:
        text = _render_vl_sdv_module(module)

    if not text.endswith("\n"):
        text += "\n"

    out_file.write_text(_VL_SDV_HEADER + text, encoding="utf-8")
    _LOGGER.info("wrote vl_sdv stubs -> %s", out_file)


def main() -> None:
    """Parse command-line arguments and generate the stubs."""
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "outdir",
        nargs="?",
        default="stubs",
        help="output directory for the stubs (default: stubs)",
    )
    parser.add_argument(
        "--llm-doc",
        default=os.getenv("TDE4_LLM_DOC"),
        help="path to the 3DE Python Doc (LLM) JSON (or set $TDE4_LLM_DOC)",
    )
    parser.add_argument(
        "--tde4-root",
        default=os.getenv("TDE4_ROOT"),
        help="3DEqualizer install dir, for vl_sdv (or set $TDE4_ROOT)",
    )
    parser.add_argument(
        "--no-vl-sdv",
        action="store_true",
        help="skip generating vl_sdv (needs mypy + the module)",
    )
    args = parser.parse_args()

    if not args.llm_doc:
        parser.error(
            "provide --llm-doc or set $TDE4_LLM_DOC (see README for the download)"
        )

    out_dir = Path(args.outdir)
    _LOGGER.info("Generating tde4 stubs from %s", args.llm_doc)
    Tde4SpecRenderer.from_spec_file(Path(args.llm_doc)).write(out_dir)

    if not args.no_vl_sdv and args.tde4_root:
        _LOGGER.info("Generating vl_sdv stubs")
        _generate_vl_sdv(Path(args.tde4_root), out_dir)


if __name__ == "__main__":
    main()
