from maya.app.renderSetup.views.propertyEditor.collectionPropertyEditorStrings import *
import maya.app.renderSetup.views.propertyEditor.basicCollection as basicCollection
from _typeshed import Incomplete

vSpc: int
hSpc: int

class Collection(basicCollection.BasicCollection):
    treeView: Incomplete
    children: Incomplete
    def __init__(self, item, parent) -> None: ...
    def postSelector(self) -> None: ...
    def __del__(self) -> None: ...
    def dataModelChanged(self, *posArgs, **kwArgs) -> None: ...
    def preSelector(self) -> None: ...
    def getModelSelector(self): ...
    def setupSelector(self, layout) -> None: ...
    def isAbsoluteMode(self): ...
    def populateFields(self) -> None: ...
    def highlight(self, names) -> None: ...
