from PySide6.QtWidgets import QFormLayout
from _typeshed import Incomplete

class Layout(QFormLayout):
    LABEL_COLUMN_WIDTH: Incomplete
    def __init__(self) -> None: ...
    def insertRow(self, row, v1, v2: Incomplete | None = None) -> None: ...
    def addRow(self, v1, v2: Incomplete | None = None) -> None: ...
