from _typeshed import Incomplete

def setup_parser(parser, completions: bool = False) -> None: ...
def list_repos() -> None: ...
def list_repos_containing_pkg(pkg_name, pkg_version) -> None: ...
def command(opts, parser, extra_arg_groups: Incomplete | None = None) -> None: ...
