from maya.app.edl.translator import *
from _typeshed import Incomplete

def indent(elem, level: int = 0) -> None: ...

class FCP(Translator):
    root: Incomplete
    sequence: Incomplete
    master_clips: Incomplete
    file_ids: Incomplete
    clip_ids: Incomplete
    links: Incomplete
    parent_pointers: Incomplete
    cur_elem: Incomplete
    def __init__(self, fileName) -> None: ...
    def formatErrorElement(self, cur_elem): ...
    def readFromFile(self) -> None: ...
    def getMasterClips(self) -> None: ...
    def getSequence(self): ...
    def getTrack(self, track_elem): ...
    def getClip(self, clip_elem): ...
    def getFile(self, file_elem): ...
    def getLinks(self): ...
    def writeToFile(self) -> None: ...
    def writeSequence(self, seq_info): ...
    def writeFormat(self, seq_elem, width, height): ...
    def writeTrack(self, seq_elem, track_info): ...
    def writeClip(self, track_elem, clip_info): ...
    def writeFile(self, clip_elem, file_info): ...
