from _typeshed import Incomplete

animCallback: Incomplete

def register() -> None: ...
def deregister() -> None: ...
def getAnimCallbackOption(): ...
def setAnimCallbackOption(enabled) -> None: ...
def registerAnimCallback() -> None: ...
def removeAnimCallback() -> None: ...
def animCurveEdited(objs, clientData) -> None: ...
