from maya.app.flux.imports import *
from _typeshed import Incomplete

IN_BATCH_MODE: Incomplete

def createTypeTool(font: Incomplete | None = None, style: Incomplete | None = None, text: Incomplete | None = None, legacy: bool = False) -> None: ...
def createTypeToolWithNode(typeTool, font: Incomplete | None = None, style: Incomplete | None = None, text: Incomplete | None = None, legacy: bool = False): ...
def addPolyRemeshNodeType(typeTransform, typeExtruder, typeTool, typeMesh) -> None: ...
def addUVNodeToType(typeMesh, typeExtruder) -> None: ...
def connectTypeAdjustDeformer(typeMesh, typeTransform, typeExtruder, typeTool): ...
def connectShellDeformer(typeMesh, typeTransform, typeExtruder, typeTool) -> None: ...
