from typing import ClassVar

class ExportStatus:
    __members__: ClassVar[dict] = ...  # read-only
    Cancelled: ClassVar[ExportStatus] = ...
    Error: ClassVar[ExportStatus] = ...
    Success: ClassVar[ExportStatus] = ...
    Warning: ClassVar[ExportStatus] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class MeshExportOption:
    __members__: ClassVar[dict] = ...  # read-only
    BaseMesh: ClassVar[MeshExportOption] = ...
    TessellationNormalsBaseMesh: ClassVar[MeshExportOption] = ...
    TessellationRecomputeNormals: ClassVar[MeshExportOption] = ...
    TriangulatedMesh: ClassVar[MeshExportOption] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

def export_mesh(*args, **kwargs): ...
def export_project_textures(*args, **kwargs): ...
def get_default_export_path() -> str: ...
def list_predefined_export_presets() -> list[tuple[str, str]]: ...
def list_predefined_preset_output_maps(arg0: str, arg1: int) -> str: ...
def list_preset_output_maps(arg0: str) -> str: ...
def list_project_textures(json_config: str) -> dict[tuple[str, str], list[str]]: ...
def list_resource_export_presets() -> list[str]: ...
def scene_has_tessellation() -> bool: ...
def scene_is_triangulated() -> bool: ...
