from typing import Any, ClassVar, Dict, List, Tuple

class ExportStatus:
    __members__: ClassVar[dict] = ...  # read-only
    Cancelled: ClassVar[ExportStatus] = ...
    Error: ClassVar[ExportStatus] = ...
    Success: ClassVar[ExportStatus] = ...
    Warning: ClassVar[ExportStatus] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str: ...

def export_project_textures(*args, **kwargs) -> Any: ...
def list_project_textures(json_config: str) -> Dict[Tuple[str,str],List[str]]: ...
