import _substance_painter.colormanagement
from _typeshed import Incomplete
from typing import ClassVar, overload

class BlendingMode:
    __members__: ClassVar[dict] = ...  # read-only
    Color: ClassVar[BlendingMode] = ...
    ColorBurn: ClassVar[BlendingMode] = ...
    ColorDodge: ClassVar[BlendingMode] = ...
    Darken: ClassVar[BlendingMode] = ...
    Difference: ClassVar[BlendingMode] = ...
    Disable: ClassVar[BlendingMode] = ...
    Divide: ClassVar[BlendingMode] = ...
    Exclusion: ClassVar[BlendingMode] = ...
    HardLight: ClassVar[BlendingMode] = ...
    InverseDivide: ClassVar[BlendingMode] = ...
    InverseSubtract: ClassVar[BlendingMode] = ...
    Lighten: ClassVar[BlendingMode] = ...
    LinearBurn: ClassVar[BlendingMode] = ...
    LinearDodge: ClassVar[BlendingMode] = ...
    LinearLight: ClassVar[BlendingMode] = ...
    Multiply: ClassVar[BlendingMode] = ...
    Normal: ClassVar[BlendingMode] = ...
    NormalMapCombine: ClassVar[BlendingMode] = ...
    NormalMapDetail: ClassVar[BlendingMode] = ...
    NormalMapInverseDetail: ClassVar[BlendingMode] = ...
    Overlay: ClassVar[BlendingMode] = ...
    Passthrough: ClassVar[BlendingMode] = ...
    PinLight: ClassVar[BlendingMode] = ...
    Replace: ClassVar[BlendingMode] = ...
    Saturation: ClassVar[BlendingMode] = ...
    Screen: ClassVar[BlendingMode] = ...
    SignedAddition: ClassVar[BlendingMode] = ...
    SoftLight: ClassVar[BlendingMode] = ...
    Subtract: ClassVar[BlendingMode] = ...
    Tint: ClassVar[BlendingMode] = ...
    Value: ClassVar[BlendingMode] = ...
    VividLight: ClassVar[BlendingMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class ColorSelectionBackgroundColor:
    __members__: ClassVar[dict] = ...  # read-only
    Black: ClassVar[ColorSelectionBackgroundColor] = ...
    Gray: ClassVar[ColorSelectionBackgroundColor] = ...
    Transparent: ClassVar[ColorSelectionBackgroundColor] = ...
    White: ClassVar[ColorSelectionBackgroundColor] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class ColorSelectionEffectParams:
    background_color: ColorSelectionBackgroundColor
    colors: list[_substance_painter.colormanagement.Color]
    hardness: float
    id_mask: str
    output_value: float
    tolerance: float
    def __init__(self) -> None: ...

class CompareMaskEffectOperand:
    __members__: ClassVar[dict] = ...  # read-only
    Constant: ClassVar[CompareMaskEffectOperand] = ...
    LayersBelow: ClassVar[CompareMaskEffectOperand] = ...
    ThisLayer: ClassVar[CompareMaskEffectOperand] = ...
    ThisMask: ClassVar[CompareMaskEffectOperand] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class CompareMaskEffectOperation:
    __members__: ClassVar[dict] = ...  # read-only
    GreaterThan: ClassVar[CompareMaskEffectOperation] = ...
    LesserThan: ClassVar[CompareMaskEffectOperation] = ...
    WithinTolerance: ClassVar[CompareMaskEffectOperation] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class CompareMaskEffectParams:
    channel: Incomplete
    constant: float
    hardness: float
    left_operand: CompareMaskEffectOperand
    operation: CompareMaskEffectOperation
    right_operand: CompareMaskEffectOperand
    tolerance: float
    def __init__(self) -> None: ...

class FillProjectionParams:
    angle: float | None
    backface_culling_angle: float | None
    backface_culling_enabled: bool | None
    backface_culling_hardness: float | None
    cylinder_hide_caps: bool | None
    depth_culling_enabled: bool | None
    depth_culling_hardness: float | None
    filtering_mode: FilteringMode | None
    hardness: float | None
    projection_3d_offset: float3 | None  # type: ignore[name-defined]
    projection_3d_rotation: float3 | None  # type: ignore[name-defined]
    projection_3d_scale: float3 | None  # type: ignore[name-defined]
    projection_depth: float | None
    shape_crop_mode: ShapeCropMode | None
    source_uv_set: int | None
    uv_transformation_offset: float2 | None  # type: ignore[name-defined]
    uv_transformation_rotation: float | None
    uv_transformation_scale: float2 | None  # type: ignore[name-defined]
    uv_transformation_scale_mode: ScaleMode | None
    uv_wrapping_mode: UVWrapMode | None
    def __init__(self) -> None: ...

class FilteringMode:
    __members__: ClassVar[dict] = ...  # read-only
    BilinearHQ: ClassVar[FilteringMode] = ...
    BilinearSharp: ClassVar[FilteringMode] = ...
    Nearest: ClassVar[FilteringMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class GeometryMaskType:
    __members__: ClassVar[dict] = ...  # read-only
    Mesh: ClassVar[GeometryMaskType] = ...
    UVTile: ClassVar[GeometryMaskType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class InsertPositionLocation:
    __members__: ClassVar[dict] = ...  # read-only
    Above: ClassVar[InsertPositionLocation] = ...
    Below: ClassVar[InsertPositionLocation] = ...
    Content: ClassVar[InsertPositionLocation] = ...
    Mask: ClassVar[InsertPositionLocation] = ...
    Substack: ClassVar[InsertPositionLocation] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class MaskBackground:
    __members__: ClassVar[dict] = ...  # read-only
    Black: ClassVar[MaskBackground] = ...
    White: ClassVar[MaskBackground] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class NodeType:
    __members__: ClassVar[dict] = ...  # read-only
    AnchorPointEffect: ClassVar[NodeType] = ...
    ColorSelectionEffect: ClassVar[NodeType] = ...
    CompareMaskEffect: ClassVar[NodeType] = ...
    FillEffect: ClassVar[NodeType] = ...
    FillLayer: ClassVar[NodeType] = ...
    FilterEffect: ClassVar[NodeType] = ...
    GeneratorEffect: ClassVar[NodeType] = ...
    GroupLayer: ClassVar[NodeType] = ...
    InstanceLayer: ClassVar[NodeType] = ...
    LevelsEffect: ClassVar[NodeType] = ...
    PaintEffect: ClassVar[NodeType] = ...
    PaintLayer: ClassVar[NodeType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class ProjectionMode:
    __members__: ClassVar[dict] = ...  # read-only
    Cylindrical: ClassVar[ProjectionMode] = ...
    Fill: ClassVar[ProjectionMode] = ...
    Planar: ClassVar[ProjectionMode] = ...
    Spherical: ClassVar[ProjectionMode] = ...
    Triplanar: ClassVar[ProjectionMode] = ...
    UV: ClassVar[ProjectionMode] = ...
    UVSetToUVSet: ClassVar[ProjectionMode] = ...
    Warp: ClassVar[ProjectionMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class ScaleMode:
    __members__: ClassVar[dict] = ...  # read-only
    CustomPhysicalSize: ClassVar[ScaleMode] = ...
    Factors: ClassVar[ScaleMode] = ...
    MaterialPhysicalSize: ClassVar[ScaleMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class SelectionType:
    __members__: ClassVar[dict] = ...  # read-only
    Content: ClassVar[SelectionType] = ...
    GeometryMask: ClassVar[SelectionType] = ...
    Mask: ClassVar[SelectionType] = ...
    Properties: ClassVar[SelectionType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class ShapeCropMode:
    __members__: ClassVar[dict] = ...  # read-only
    CroppedToShape: ClassVar[ShapeCropMode] = ...
    ExtendsOutsideShape: ClassVar[ShapeCropMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class UVWrapMode:
    __members__: ClassVar[dict] = ...  # read-only
    Repeat: ClassVar[UVWrapMode] = ...
    RepeatHorizontally: ClassVar[UVWrapMode] = ...
    RepeatNone: ClassVar[UVWrapMode] = ...
    RepeatVertically: ClassVar[UVWrapMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

def add_mask(arg0: int, arg1: MaskBackground) -> None: ...
def content_effects(arg0: int) -> list[int]: ...
def delete_node(arg0: int) -> None: ...
def enable_mask(arg0: int, arg1: bool) -> None: ...
def end_macro() -> None: ...
def get_blending_mode(arg0: int, arg1) -> BlendingMode: ...
def get_color_selection_params(arg0: int) -> ColorSelectionEffectParams: ...
def get_compare_mask_params(arg0: int) -> CompareMaskEffectParams: ...
def get_geometry_mask_enabled_meshes(arg0: int) -> list[str]: ...
def get_geometry_mask_enabled_uv_tiles(arg0: int) -> list[tuple[int, int]]: ...
def get_geometry_mask_type(arg0: int) -> GeometryMaskType: ...
def get_levels_effect_affected_channel(*args, **kwargs): ...
def get_levels_params(*args, **kwargs): ...
def get_mask_background(arg0: int) -> MaskBackground: ...
def get_name(arg0: int) -> str: ...
def get_next_sibling_node(arg0: int) -> int | None: ...
def get_node_type(arg0: int) -> NodeType: ...
def get_opacity(arg0: int, arg1) -> float: ...
def get_parent_node(arg0: int) -> int | None: ...
def get_previous_sibling_node(arg0: int) -> int | None: ...
def get_projection_mode(arg0: int) -> ProjectionMode: ...
def get_projection_params(arg0: int) -> tuple[ProjectionMode, FillProjectionParams]: ...
def get_root_layers_from_stack(arg0: int) -> list[int]: ...
def get_selected_nodes_from_stack(arg0: int) -> list[int]: ...
def get_selection_type(arg0: int) -> SelectionType: ...
def get_stack(arg0: int) -> int: ...
def get_stack_node_id(arg0: int) -> int | None: ...
def get_texture_set(arg0: int) -> int: ...
@overload
def has_blending(arg0: int) -> bool: ...
@overload
def has_blending(arg0: int) -> bool: ...  # type: ignore[overload-cannot-match]
def has_mask(arg0: int) -> bool: ...
def insert_anchor_point_effect(arg0: tuple[int, InsertPositionLocation | None], arg1: str) -> int: ...
def insert_color_selection_effect(arg0: tuple[int, InsertPositionLocation | None]) -> int: ...
def insert_compare_mask_effect(arg0: tuple[int, InsertPositionLocation | None]) -> int: ...
def insert_fill(arg0: tuple[int, InsertPositionLocation | None]) -> int: ...
def insert_filter_effect(arg0: tuple[int, InsertPositionLocation | None], arg1: str) -> int: ...
def insert_generator_effect(arg0: tuple[int, InsertPositionLocation | None], arg1: str) -> int: ...
def insert_group(arg0: tuple[int, InsertPositionLocation | None]) -> int: ...
def insert_levels_effect(arg0: tuple[int, InsertPositionLocation | None]) -> int: ...
def insert_paint(arg0: tuple[int, InsertPositionLocation | None]) -> int: ...
def insert_smart_mask(arg0: tuple[int, InsertPositionLocation | None], arg1: str) -> list[int]: ...
def insert_smart_material(arg0: tuple[int, InsertPositionLocation | None], arg1: str) -> int: ...
def instances(arg0: int) -> list[int]: ...
def instantiate(arg0: tuple[int, InsertPositionLocation | None], arg1: int) -> int: ...
def is_collapsed(arg0: int) -> bool: ...
def is_in_mask_stack(arg0: int) -> bool: ...
def is_mask_enabled(arg0: int) -> bool: ...
def is_visible(arg0: int) -> bool: ...
def mask_effects(arg0: int) -> list[int]: ...
def model(arg0: int) -> int | None: ...
def remove_mask(arg0: int) -> None: ...
def select_nodes(arg0: list[int]) -> None: ...
def set_blending_mode(arg0: int, arg1: BlendingMode, arg2) -> None: ...
def set_collapsed(arg0: int, arg1: bool) -> None: ...
def set_color_selection_params(arg0: int, arg1: ColorSelectionEffectParams) -> None: ...
def set_compare_mask_params(arg0: int, arg1: CompareMaskEffectParams) -> None: ...
def set_geometry_mask_enabled_meshes(arg0: int, arg1: list[str]) -> None: ...
def set_geometry_mask_enabled_uv_tiles(arg0: int, arg1: list[tuple[int, int]]) -> None: ...
def set_geometry_mask_type(arg0: int, arg1: GeometryMaskType) -> None: ...
def set_levels_effect_affected_channel(arg0: int, arg1) -> None: ...
def set_levels_params(arg0: int, arg1) -> None: ...
def set_mask_background(arg0: int, arg1: MaskBackground) -> None: ...
def set_name(arg0: int, arg1: str) -> None: ...
def set_opacity(arg0: int, arg1: float, arg2) -> None: ...
def set_projection_mode(arg0: int, arg1: ProjectionMode) -> None: ...
def set_projection_params(arg0: int, arg1: ProjectionMode, arg2: FillProjectionParams) -> None: ...
def set_selection_type(arg0: int, arg1: SelectionType) -> None: ...
def set_visible(arg0: int, arg1: bool) -> None: ...
def start_macro(arg0: str) -> None: ...
def sub_layers(arg0: int) -> list[int]: ...
def undostack() -> int: ...
