from PySide6.QtCore import QObject
from _typeshed import Incomplete
from maya.app.flux.ae.Custom import Custom as Custom
from maya.app.flux.ae.Template import Template as Template
from maya.app.flux.core import pix as pix

class MyEventFilterer(QObject):
    def eventFilter(self, widget, event): ...

class AEsvgToPolyTemplate(Template):
    def buildUI(self, nodeName) -> None: ...

class MyCustom(Custom):
    eventFilterer: Incomplete
    modernExtrude: bool
    supportedDefaultShaders: Incomplete
    lockUpdates: bool
    preventSecondaryUpdate: bool
    bevelIgnore: Incomplete
    svgLabel: Incomplete
    warningLabel: Incomplete
    pasteLabel: Incomplete
    pathField: Incomplete
    refreshBtn: Incomplete
    useArtBoard: Incomplete
    pathListLabel: Incomplete
    pathList: Incomplete
    svgOffsetWindowZSlider: Incomplete
    offsetFieldChangedStatus: bool
    svgOffsetWindowExtrudeSlider: Incomplete
    clearManipulationsBtn: Incomplete
    enableBevel: Incomplete
    bevelChoiceGrp: Incomplete
    frontBevelRadioBtn: Incomplete
    backBevelRadioBtn: Incomplete
    animPosControl: Incomplete
    animRotControl: Incomplete
    animScaleControl: Incomplete
    def buildUI(self, nodeName) -> None: ...
    def isAnimConnLegacy(self): ...
    def fixAnimLegacyConnections(self) -> None: ...
    def animationTabChanged(self, visible) -> None: ...
    def offsetFieldChanged(self, *args) -> None: ...
    def offsetFieldEditingFinished(self, *args) -> None: ...
    def nodeChanged(self) -> None: ...
    def updateAnimateEnabled(self) -> None: ...
    def manipVisibilityChanged(self, visible) -> None: ...
    def pathSelectionChanged(self) -> None: ...
    def populatePaths(self) -> None: ...
    def updatePreviewPanel(self) -> None: ...
    def updateErrorIndicator(self) -> None: ...
    def svgModeChanged(self) -> None: ...
    def updateInfoLabel(self) -> None: ...
    def pathNamesChanged(self, *args) -> None: ...
    def clearManipClicked(self) -> None: ...
    def setVectorOffset(self, *args) -> None: ...
    def setVectorOffsetAttributes(self) -> None: ...
    def getVectorOffsetAttributes(self) -> None: ...
    def clearVectorOffsetAttributes(self) -> None: ...
    def svg_catchPaste(self): ...
    def pasteRadioClicked(self) -> None: ...
    def pathRadioClicked(self) -> None: ...
    def pasteClicked(self) -> None: ...
    def pathClicked(self) -> None: ...
    def pathEdited(self) -> None: ...
    def refreshClicked(self) -> None: ...
    def backBevelEnabledChanged(self) -> None: ...
    def enableBevelClicked(self) -> None: ...
    def disableAllBevels(self) -> None: ...
    def enableBevelStyle(self) -> None: ...
    def extrudeEnableChanged(self) -> None: ...
    def switchFrontBevel(self) -> None: ...
    def switchBackBevel(self) -> None: ...
    def isBevelEnabled(self): ...
    def bevelStyleChanged(self) -> None: ...
    def updateBevelVisibility(self) -> None: ...
    def enableDisableBevels(self) -> None: ...
    navigations: Incomplete
    def setupNavigationControls(self, navigations) -> None: ...
    def getShader(self, index): ...
    def deformableTypeChanged(self) -> None: ...
    svgInputModeGrp: Incomplete
    pasteRadioBtn: Incomplete
    pathRadioBtn: Incomplete
    pasteBtn: Incomplete
    pathBtn: Incomplete
    shellAnimationBtn: Incomplete
    shellAnimOption: Incomplete
    shaderComboBox: Incomplete
    materialSplitBtn: Incomplete
    materialJoinBtn: Incomplete
    createCurveBtn: Incomplete
    def createCustomWidgets(self) -> None: ...
    def updateShellAnimOption(self) -> None: ...
    def shellAnimOptionChanged(self, index) -> None: ...
    def shellAnimationClicked(self) -> None: ...
    def alignClicked(self, index) -> None: ...
    def alignChanged(self, *args) -> None: ...
    def createLocalPivotBtn(self, axis): ...
    def showLocalPivotMenu(self, axis, rpChecked, spChecked): ...
    def createFalloffCurve(self, attr) -> None: ...
    def editFalloffCurve(self, attr) -> None: ...
    def materialSplitClicked(self) -> None: ...
    def materialJoinClicked(self) -> None: ...
    def updateMaterialSplitBtn(self) -> None: ...
    def createCurveClicked(self) -> None: ...
    def pivotLocationClicked(self, axis) -> None: ...
    def pivotLocationMenuClicked(self, cmd) -> None: ...
    def getExtrudeNode(self): ...
    def getRemeshNode(self): ...
    def getAnimationNode(self): ...
    def getAdjustNode(self): ...
    def strRes(self, name): ...
    def stringResourceFunction(self, name): ...

def joinTypeMaterials(meshShape, typeNode, shaderType) -> None: ...
def splitTypeMaterials(extrudeNode, meshShape, typeNode, shaderType) -> None: ...
def getShadingGroupsFromObject(mesh): ...
def getVectorShadingGroups(mesh, extrudeNode): ...
def getShaderFromArray(GrpMessageConections): ...
def getShaderFromObject(mesh): ...
