from maya.app.flux.imports import *
from _typeshed import Incomplete
from maya.internal.common.qt.doubleValidator import MayaQclocaleDoubleValidator as MayaQclocaleDoubleValidator

kFrame: Incomplete
kText: Incomplete

class TypeAnimTextWidget(qt.QWidget):
    node: Incomplete
    listWidget: Incomplete
    layout: Incomplete
    def __init__(self, node, parent: Incomplete | None = None) -> None: ...
    def set_node(self, node) -> None: ...

def build_qt_widget(lay, node) -> None: ...
def update_qt_widget(layout, node) -> None: ...

class AnimTextQTreeWidgetExtend(qt.QTreeWidget):
    node: Incomplete
    popup_menu: Incomplete
    def __init__(self, node, parent: Incomplete | None = None) -> None: ...
    def openMenu(self, point) -> None: ...
    def deleteItems(self) -> None: ...
    def updateContent(self) -> None: ...
    def mousePressEvent(self, event) -> None: ...
    def eventFilter(self, source, event): ...
    def onChanged(self) -> None: ...
    def addItemAction(self) -> None: ...
    def addItem(self, frame, name): ...

def HexToUni(hexStr): ...

class MyDelegate(qt.QStyledItemDelegate):
    def sizeHint(self, option, index): ...
    def createEditor(self, parent, option, index): ...
    def setEditorData(self, editor, index) -> None: ...
    def setModelData(self, editor, model, index) -> None: ...

def ByteToHex(byteStr): ...
