from rez.shells import UnixShell

class SH(UnixShell):
    norc_arg: str
    histfile: str
    histvar: str
    @classmethod
    def name(cls) -> str: ...
    @classmethod
    def file_extension(cls) -> str: ...
    @classmethod
    def get_syspaths(cls): ...
    @classmethod
    def startup_capabilities(cls, rcfile: bool = False, norc: bool = False, stdin: bool = False, command: bool = False): ...
    @classmethod
    def get_startup_sequence(cls, rcfile, norc, stdin, command): ...
    def _bind_interactive_rez(self) -> None: ...
    def setenv(self, key, value) -> None: ...
    def unsetenv(self, key) -> None: ...
    def alias(self, key, value) -> None: ...
    def source(self, value) -> None: ...
    def escape_string(self, value, is_path: bool = False): ...
    def _saferefenv(self, key) -> None: ...

def register_plugin(): ...
