from maya.app.renderSetup.views.renderSetupPreferencesViewsStrings import *
from _typeshed import Incomplete

def addRenderSetupPreferences() -> None: ...
def savePreset(captionName, fp: Incomplete | None = None) -> None: ...
def exportAOVs(captionName, fp: Incomplete | None = None) -> None: ...
def setDefaultPreset() -> None: ...
def loadUserPreset(preset) -> None: ...
def loadGlobalPreset(preset) -> None: ...
def deleteUserPreset(preset, warn: bool = True) -> None: ...
def getUserPresets(renderer): ...
def getGlobalPresets(renderer): ...
