import maya.api.OpenMaya as OpenMaya
from _typeshed import Incomplete

kParsingError: Incomplete
kAddAndDeselectEditOnly: Incomplete
kNotEditableFlags: Incomplete
kAddAndDeselectNoTogether: Incomplete
kSelectionEditFailed: Incomplete

def getRenderSetupWindow(): ...
def getPropertyEditor(): ...
def getRenderSetupView(): ...
def getSelectionModel(): ...
def getSelection(renderLayers: bool = False, collections: bool = False, renderSettingsChildCollections: bool = False, overrides: bool = False): ...
def getSelectedCollections(): ...
def notInSelectedRenderLayers(*args, **kwargs): ...
def inSelectedRenderLayers(*args, **kwargs): ...
def highlight(names) -> None: ...

class RenderSetupSelectCmd(OpenMaya.MPxCommand):
    kCmdName: str
    kAddFlag: str
    kAddFlagLong: str
    kDeselectFlag: str
    kDeselectFlagLong: str
    kRenderLayersFlag: str
    kRenderLayersFlagLong: str
    kCollectionsFlag: str
    kCollectionsFlagLong: str
    kRenderSettingsChildCollectionsFlag: str
    kRenderSettingsChildCollectionsFlagLong: str
    kOverridesFlag: str
    kOverridesFlagLong: str
    @staticmethod
    def creator(): ...
    @staticmethod
    def createSyntax(): ...
    def isUndoable(self): ...
    def doIt(self, args) -> None: ...

class RenderSetupHighlightCmd(OpenMaya.MPxCommand):
    kCmdName: str
    @staticmethod
    def creator(): ...
    @staticmethod
    def createSyntax(): ...
    def isUndoable(self): ...
    def doIt(self, args) -> None: ...
