from _typeshed import Incomplete

widgets: Incomplete

class SendDialog(widgets.QDialog):
    instance: Incomplete
    def __init__(self) -> None: ...
    def sendCommand(self): ...

def showDialog() -> None: ...
def criticalError(msg) -> None: ...
