from _typeshed import Incomplete

widgets: Incomplete

def getPaintableImageSetLayerNamePairs(obj): ...
def export(ops, format) -> None: ...
def onOKClicked(dlg, ops, format) -> None: ...
def setBold(widget) -> None: ...

class DirBrowser(widgets.QListWidget):
    def __init__(self, title: str = ...) -> None: ...
    def addToLayout(self, layout) -> None: ...
    def updateContents(self) -> None: ...
    def onItemDoubleClicked(self, item) -> None: ...
    def getSelectedPaths(self): ...

class OpList(widgets.QListWidget):
    def __init__(self, title: str = ...) -> None: ...
    def addToLayout(self, layout) -> None: ...
    def addOps(self, img_sets, dirs) -> None: ...
    def removeOps(self) -> None: ...
    def ops(self): ...

class FormatsBox(widgets.QComboBox):
    def __init__(self, img_sets_widget, default_format: str = ...) -> None: ...
    def updateFormats(self, default_format: Incomplete | None = ...) -> None: ...

def show(): ...
