from _typeshed import Incomplete

class UpdateChannelLayers:
    shader_parent: Incomplete
    shaders: Incomplete
    shaders_mask: Incomplete
    input_channels: Incomplete
    def __init__(self, shader_parent) -> None: ...
    def collectShaders(self) -> None: ...
    def collectInputs(self) -> None: ...
    def assignInputs(self) -> None: ...
    def createLayerGroups_SetMaskStack(self, layer, mask): ...
    def createLayerGroups_SetMask(self, layer, mask): ...
    def createLayerGroups(self) -> None: ...
    def update(self) -> None: ...

def update() -> None: ...
