from . import mGo as mGo

def reload_mGo() -> None: ...
def starts_mGo() -> None: ...
def checkInputs(curShader, curChannel): ...
def checkShader(curShader): ...
def syncChannels() -> None: ...
def isolateCurrentShader() -> None: ...
def isolateReset() -> None: ...
def mGoHelp() -> None: ...
