from _typeshed import Incomplete

gui: Incomplete
core: Incomplete
widgets: Incomplete

def bitDepthAsString(depth): ...
def drawSomePaint() -> None: ...
def resizeBuffer(size_combo, size_label) -> None: ...
def getPaint(Label) -> None: ...
def updatePaint() -> None: ...
def updateBuffer(depth_combo, depth_label) -> None: ...
def updateRotation(rot) -> None: ...
def updateScale(x, y) -> None: ...
def updateTranslate(x, y) -> None: ...
def setBold(widget) -> None: ...
def paintBufferTest(): ...
