from _typeshed import Incomplete

def setup_parser(parser, completions: bool = False) -> None: ...
def add_variant(pkgcache, uri, opts) -> None: ...
def remove_variant(pkgcache, uri, opts) -> None: ...
def view_logs(pkgcache, opts) -> None: ...
def command(opts, parser, extra_arg_groups: Incomplete | None = None) -> None: ...
