from _typeshed import Incomplete
from rez.build_system import BuildSystem

class MakeBuildSystem(BuildSystem):
    @classmethod
    def name(cls) -> str: ...
    @classmethod
    def is_valid_root(cls, path, package: Incomplete | None = None): ...
    def __init__(self, working_dir, opts: Incomplete | None = None, package: Incomplete | None = None, write_build_scripts: bool = False, verbose: bool = False, build_args=[], child_build_args=[]) -> None: ...

def register_plugin(): ...
