from maya.app.flux.imports import *
from _typeshed import Incomplete

string_type: Incomplete

def getAllRunTimeCommands(): ...
def getAllTTFItems(): ...
def checkInvalidNamingRTC(): ...

class MenuCrawler:
    def formatIcon(self, icon, parentIcon: str = ''): ...
    def getItemScript(self, item): ...
    def getSubmenus(self, menu, menuPath, lastDivider: str = '') -> None: ...
    tagsList: Incomplete
    commandsList: Incomplete
    commandDividers: Incomplete
    commandKeys: Incomplete
    tagKeys: Incomplete
    tags: Incomplete
    commands: Incomplete
    paths: Incomplete
    commandMenuLabels: Incomplete
    tagsMenuLabels: Incomplete
    def getMenus(self): ...

def getTopLevelMenus(asCSV: bool = False): ...
def writeCSV(inputList) -> None: ...
def getMenuInfo(): ...
def exportRTC() -> None: ...
def exportTTF() -> None: ...
def exportMenus() -> None: ...
