from PySide6.QtWidgets import QMenu
from _typeshed import Incomplete

class Menu(QMenu):
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    def __init__(self, title, parent: Incomplete | None = None) -> None: ...
    def handleMenuHovered(self, action) -> None: ...
