import _typeshed
import builtins
import collections
import shiboken2
import typing
import typing_extensions

T = typing.TypeVar('T')
P = typing.ParamSpec('P')
class QQuickStyle(shiboken2.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def addStylePath(path: str) -> None: ...
    @staticmethod
    def availableStyles() -> list[str]: ...
    @staticmethod
    def name() -> str: ...
    @staticmethod
    def path() -> str: ...
    @staticmethod
    def setFallbackStyle(style: str) -> None: ...
    @staticmethod
    def setStyle(style: str) -> None: ...
    @staticmethod
    def stylePathList() -> list[str]: ...
