from _typeshed import Incomplete

class TempDir:
    def __init__(self, tempDir: Incomplete | None = ..., cleanup: bool = ...) -> None: ...
    def __del__(self) -> None: ...
    @property
    def path(self): ...
