import threading
from _typeshed import Incomplete

class TimerObj(threading.Thread):
    runTime: Incomplete
    command: Incomplete
    def __init__(self, runTime, command) -> None: ...
    def run(self) -> None: ...

def prepMelCommand(commandString): ...
def startTimer(runTime, command) -> None: ...
