from typing import Any, Callable, ClassVar

AddCmdlineArgs: Callable

class RefinementComplexities:
    class _RefinementComplexity:
        __init__: ClassVar[Callable] = ...
        @property
        def id(self) -> Any: ...
        @property
        def name(self) -> Any: ...
        @property
        def value(self) -> Any: ...
    HIGH: ClassVar[RefinementComplexities._RefinementComplexity] = ...
    LOW: ClassVar[RefinementComplexities._RefinementComplexity] = ...
    MEDIUM: ClassVar[RefinementComplexities._RefinementComplexity] = ...
    VERY_HIGH: ClassVar[RefinementComplexities._RefinementComplexity] = ...
    _ordered: ClassVar[tuple] = ...
    fromId: ClassVar[method] = ...
    fromName: ClassVar[method] = ...
    next: ClassVar[method] = ...
    ordered: ClassVar[method] = ...
    prev: ClassVar[method] = ...