# mypy: disable-error-code="misc, override, no-redef"

import Boost.Python
from typing import ClassVar, overload

__MFB_FULL_PACKAGE_NAME: str

class ResolverContext(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    @overload
    def __init__(self, mappingFile: object) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def GetMappingFile(self) -> str: ...
    def __hash__(self) -> int: ...
