from _typeshed import Incomplete

MERGE_MAP: Incomplete
t_none: int
t_start: int
t_end: int
t_middle: int
MERGE_TYPE: Incomplete

def ByteToHex(byteStr): ...
def HexToUni(hexStr): ...
def filterAndCorrectArabic(input_string): ...
def isArabic(ch): ...
def convertText(text): ...
def isAlefChar(a): ...
def isLamChar(a): ...
def isSpaceChar(a): ...
def inMergeRange(ch): ...
def convertCharacters(chars): ...
def convertChar(ch, offset): ...
def canMegerBefore(ch): ...
def canMergeAfter(ch): ...
def getConvertType(ch): ...
def convertLamAlef(ch, offset): ...
