import PySide2
from _typeshed import Incomplete

core: Incomplete
rootWorkspace: Incomplete
modocl: Incomplete
lx: Incomplete

def isModoclAlive(): ...

class ModoLaunchError(Exception):
    message: Incomplete
    def __init__(self, message) -> None: ...

class CancelNotification(Exception):
    message: Incomplete
    def __init__(self, message) -> None: ...

class ModoSockLogger:
    modoSock: Incomplete
    tempdir: Incomplete
    logFile: Incomplete
    dryrun: bool
    dryrunCount: int
    progressObject: Incomplete
    def __init__(self, modoSock, tempdir) -> None: ...
    def startDryrun(self) -> None: ...
    def finishDryrun(self) -> None: ...
    def setProgressObject(self, progressObject) -> None: ...
    def eval(self, expression): ...
    def eval1(self, expression): ...
    def close(self): ...

class RenderSetup:
    path: Incomplete
    renderWidth: int
    renderHeight: int
    previewWidth: int
    previewHeight: int
    lxoSavePath: str
    renderSavePath: str
    channelAssignments: Incomplete
    def __init__(self, tempdir) -> None: ...

class BakeSetup:
    bakeWidth: str
    bakeHeight: str
    previewWidth: int
    previewHeight: int
    bakeProperties: Incomplete
    bakeToChannel: bool
    bakeToGeoChannel: bool
    def __init__(self, tempdir) -> None: ...

class ModoSession(PySide2.QtCore.QObject):
    modoOpened: Incomplete
    tempdir: Incomplete
    modoBinLoc: Incomplete
    savedir: Incomplete
    pausePreview: bool
    renderSetup: Incomplete
    bakeSetup: Incomplete
    def __init__(self) -> None: ...
    def setPausePreview(self, pausePreview) -> None: ...
    def defaultModoLoc(self): ...
    def renderByModo(self, path, flatten, render, progressObject: Incomplete | None = ...) -> None: ...
    def sendBakeParameters(self) -> None: ...
    def bakeByModo(self, path) -> None: ...
    def analyze(self, path): ...
    def openForBake(self, path, analyze): ...
    def setModoBinLoc(self, newLoc) -> None: ...
    def closeScenes(self) -> None: ...
    def closeModo(self) -> None: ...
