from .adjustDefaultMaterialUI import Ui_AdjustDefaultMaterial as Ui_AdjustDefaultMaterial
from .qt import QtCore as QtCore, QtWidgets as QtWidgets
from _typeshed import Incomplete

class AdjustDefaultMaterial(QtWidgets.QDialog):
    """Popup widget to adjust the default material used for rendering.
    `datamodel` should be a ViewSettingsDataModel.
    """
    _ui: Incomplete
    _dataModel: Incomplete
    _ambientCache: Incomplete
    _specularCache: Incomplete
    def __init__(self, parent, dataModel) -> None: ...
    def _updateFromData(self) -> None: ...
    def _ambientChanged(self, val) -> None: ...
    def _specularChanged(self, val) -> None: ...
    def _reset(self, unused) -> None: ...
    def _done(self, unused) -> None: ...
    def closeEvent(self, event) -> None: ...
