from .qt import QtCore as QtCore, QtGui as QtGui, QtWidgets as QtWidgets
from _typeshed import Incomplete
from pxr import Tf as Tf

def _GetDebugFlagsWithPrefix(debugFlagPrefix): ...

class DebugFlagsWidget(QtWidgets.QWidget):
    _listView: Incomplete
    _tableWidget: Incomplete
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    _allDebugFlagPrefixes: Incomplete
    def _populateDebugFlagsListView(self, listView) -> None: ...
    def _populateDebugFlagsTableView(self, debugFlagPrefix) -> None: ...
    def _onFlagSelectionChanged(self, selected, deselected) -> None: ...
    def _onDebugFlagChecked(self, item) -> None: ...
