from .qt import QtCore as QtCore, QtGui as QtGui, QtWidgets as QtWidgets
from _typeshed import Incomplete

class FrameSlider(QtWidgets.QSlider):
    """Custom QSlider class to allow scrubbing on left-click."""
    PAUSE_TIMER_INTERVAL: int
    _mousePauseTimer: Incomplete
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    def mousePaused(self) -> None:
        """Slot called when the slider scrubbing is paused."""
    def mousePressEvent(self, event) -> None: ...
    def mouseMoveEvent(self, event) -> None: ...
    def mouseReleaseEvent(self, event) -> None: ...
