from .qt import QtCore as QtCore, QtWidgets as QtWidgets
from .usdviewContextMenuItem import UsdviewContextMenuItem as UsdviewContextMenuItem
from _typeshed import Incomplete

class HeaderContextMenu(QtWidgets.QMenu):
    _menuItems: Incomplete
    def __init__(self, parent) -> None: ...
    def _prepForShow(self) -> None: ...

def _GetContextMenuItems(parent): ...

class HeaderContextMenuItem(UsdviewContextMenuItem):
    _parent: Incomplete
    _column: Incomplete
    _action: Incomplete
    _text: Incomplete
    def __init__(self, parent, column) -> None: ...
    def GetText(self): ...
    def IsEnabled(self): ...
    def IsChecked(self): ...
    def RunCommand(self) -> None: ...
    @property
    def action(self): ...
    @action.setter
    def action(self, action) -> None: ...
