from .qt import QtCore as QtCore, QtGui as QtGui, QtWidgets as QtWidgets
from .usdviewContextMenuItem import UsdviewContextMenuItem as UsdviewContextMenuItem
from _typeshed import Incomplete
from pxr import Ar as Ar
from pxr.UsdUtils.toolPaths import FindUsdBinary as FindUsdBinary

class LayerStackContextMenu(QtWidgets.QMenu):
    _menuItems: Incomplete
    def __init__(self, parent, item) -> None: ...

def _GetContextMenuItems(item): ...

class LayerStackContextMenuItem(UsdviewContextMenuItem):
    _item: Incomplete
    def __init__(self, item) -> None: ...
    def IsEnabled(self): ...
    def GetText(self): ...
    def RunCommand(self) -> None: ...

class OpenLayerMenuItem(LayerStackContextMenuItem):
    def GetText(self): ...
    def IsEnabled(self): ...
    def RunCommand(self) -> None: ...

class UsdviewLayerMenuItem(LayerStackContextMenuItem):
    def GetText(self): ...
    def IsEnabled(self): ...
    def RunCommand(self) -> None: ...

class CopyLayerPathMenuItem(LayerStackContextMenuItem):
    def GetText(self): ...
    def RunCommand(self) -> None: ...

class CopyLayerIdentifierMenuItem(LayerStackContextMenuItem):
    def GetText(self): ...
    def RunCommand(self) -> None: ...

class CopyPathMenuItem(LayerStackContextMenuItem):
    def GetText(self): ...
    def RunCommand(self) -> None: ...
    def IsEnabled(self): ...

class MuteOrUnmuteLayerMenuItem(LayerStackContextMenuItem):
    def GetText(self): ...
    def RunCommand(self) -> None: ...
    def IsEnabled(self): ...
