from .qt import QtCore as QtCore, QtWidgets as QtWidgets
from _typeshed import Incomplete

class OverridableLineEdit(QtWidgets.QLineEdit):
    _clearButton: Incomplete
    _defaultText: str
    def __init__(self, parent) -> None: ...
    def resizeEvent(self, event) -> None: ...
    def _overrideSet(self, text) -> None: ...
    def setText(self, text) -> None: ...
    def _resetDefault(self) -> None: ...
