from .common import ItalicizeLabelText as ItalicizeLabelText, PropertyViewIcons as PropertyViewIcons, UIBaseColors as UIBaseColors, UIPropertyValueSourceColors as UIPropertyValueSourceColors
from .propertyLegendUI import Ui_PropertyLegend as Ui_PropertyLegend
from .qt import QtWidgets as QtWidgets
from _typeshed import Incomplete

class PropertyLegend(QtWidgets.QWidget):
    _ui: Incomplete
    _isMinimized: bool
    _iconDisplaySize: Incomplete
    def __init__(self, parent) -> None: ...
    def IsMinimized(self): ...
    def ToggleMinimized(self) -> None: ...
    def GetHeight(self): ...
    def GetResetHeight(self): ...
