from PySide6.QtWidgets import QGroupBox, QListWidget
from _typeshed import Incomplete
from maya.app.general.mayaMixin import MayaQWidgetBaseMixin as MayaQWidgetBaseMixin
from maya.app.renderSetup.views.propertyEditor.layout import Layout as Layout

kEnable: Incomplete
kIsolate: Incomplete
kCouldNotSelectMissingObject: Incomplete

class LightProperties(MayaQWidgetBaseMixin, QGroupBox):
    item: Incomplete
    propertyEditor: Incomplete
    def __init__(self, item, parent) -> None: ...

class GroupStaticSelectionWidget(QListWidget):
    ROW_HEIGHT: Incomplete
    MIN_VISIBLE_ENTRIES: int
    MAX_VISIBLE_ENTRIES: int
    PLACEHOLDER_TEXT_PEN_ENABLED: Incomplete
    kEntryActionRemoveEntry: int
    kEntryActionRemoveMissingObjects: int
    kEntryActionRemoveAllEntry: int
    item: Incomplete
    count: int
    hasMissingItems: bool
    contextMenu: Incomplete
    selectAction: Incomplete
    selectAllAction: Incomplete
    removeAction: Incomplete
    removeAllAction: Incomplete
    deleteAction: Incomplete
    deleteAllAction: Incomplete
    removeMissingAction: Incomplete
    INITIAL_HEIGHT: Incomplete
    MAX_HEIGHT: Incomplete
    def __init__(self, item, parent: Incomplete | None = None) -> None: ...
    def rightClicked(self, point) -> None: ...
    def dragEnterEvent(self, event) -> None: ...
    def dragMoveEvent(self, event) -> None: ...
    def dropEvent(self, event) -> None: ...
    def addAction(self) -> None: ...
    def deleteEntry(self) -> None: ...
    def deleteAllEntry(self) -> None: ...
    def selectEntry(self) -> None: ...
    def selectAllEntry(self) -> None: ...
    def removeEntry(self) -> None: ...
    def removeMissingObjects(self) -> None: ...
    def removeAllEntry(self) -> None: ...
    def populate(self, lightGroup: Incomplete | None = None) -> None: ...
    def repopulate(self) -> None: ...
    def paintEvent(self, e) -> None: ...
    def sizeHintForRow(self, row): ...

class GroupProperties(MayaQWidgetBaseMixin, QGroupBox):
    LIST_BOX_HEIGHT: Incomplete
    EXPRESSION_BUTTON_WIDTH: Incomplete
    MAYA_HIGHLIGHTED_COLOR: Incomplete
    item: Incomplete
    propertyEditor: Incomplete
    staticSelector: Incomplete
    def __init__(self, item, parent) -> None: ...
