from maya.app.flux.imports import *
from _typeshed import Incomplete
from maya.app.flux.core import pix as pix

dm: Incomplete

def openPrefsWindow() -> None: ...

class ListHeader(qt.QWidget):
    clicked: Incomplete
    def __init__(self, name) -> None: ...
    def pressed(self) -> None: ...
    def paintEvent(self, e) -> None: ...

class TTFPrefsWindow(qt.QDialog):
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    tabBar: Incomplete
    tagList: Incomplete
    def setupUI(self) -> None: ...
    def convertContextToTabBarIndex(self, context): ...
    def convertTabBarIndexToContext(self, i): ...
    def contextChanged(self, i) -> None: ...
    def updateContext(self) -> None: ...
    def fixUI(self) -> None: ...
    tags: Incomplete
    def updateTagList(self) -> None: ...
    def makeGroup(self, name, expanded): ...
    def closeEvent(self, event: Incomplete | None = None) -> None: ...
    def openTagTreeMenu(self, position: Incomplete | None = None): ...
    def createTag(self, text: Incomplete | None = None): ...
    def addNewTag(self) -> None: ...
    def getSelectedTags(self): ...
    def setTagColor(self, color) -> None: ...
    def renameLayer(self) -> None: ...
    def deleteLayer(self) -> None: ...
    def tagChanged(self, item) -> None: ...
