from PySide2.QtCore import QObject as QObject

def connect(signal, response): ...
def disconnect(signal, response): ...

class SignalsBlocker:
    def __init__(self, widgets) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...

class SignalBlocker(SignalsBlocker):
    def __init__(self, widget) -> None: ...
