from _typeshed import Incomplete
from maya.app.evaluationToolkit.evaluation_toolkit_utilities import EvaluationToolkitSection, EvaluationToolkitSubsection
from maya.debug.em_debug_utilities import require_evaluation_graph

__all__ = ['EvaluationToolkitSectionDebugging']

class OutputHelper:
    output_file: Incomplete
    output_file_name: str
    def __init__(self, tool) -> None: ...
    def write(self, msg) -> None: ...
    def close(self) -> None: ...

class SubsectionTools(EvaluationToolkitSubsection):
    def update_ui(self) -> None: ...
    @staticmethod
    def callback_trace_enable(tool, trace) -> None: ...
    @staticmethod
    def callback_trace_output(tool, trace) -> None: ...
    @staticmethod
    def callback_show_trace_help(tool, trace) -> None: ...
    @staticmethod
    def callback_launch_profiler(tool) -> None: ...
    @staticmethod
    def callback_launch_analytics_window(tool) -> None: ...
    @staticmethod
    def callback_launch_scene_lint_window(tool) -> None: ...
    checkbox_traces: Incomplete
    textfield_traces: Incomplete
    def __init__(self) -> None: ...

class SubsectionDynamicAttributes(EvaluationToolkitSubsection):
    @staticmethod
    def process_connections(disconnect) -> None: ...
    @staticmethod
    @require_evaluation_graph
    def callback_print_extra_connections(tool) -> None: ...
    @staticmethod
    @require_evaluation_graph
    def callback_remove_extra_connections(tool) -> None: ...
    def __init__(self) -> None: ...

class SubsectionSceneSimplification(EvaluationToolkitSubsection):
    @staticmethod
    @require_evaluation_graph
    def callback_select_minimal_scene(tool): ...
    @staticmethod
    def callback_remove_all_but_minimal_scene(tool) -> None: ...
    def __init__(self) -> None: ...

class SubsectionGraphInspection(EvaluationToolkitSubsection):
    def get_output_file_info(self): ...
    def get_selection_info(self): ...
    @staticmethod
    def callback_update_scope(tool) -> None: ...
    def main_frame_layout(self) -> None: ...
    @staticmethod
    def callback_update_graphical_output_format(tool) -> None: ...
    @staticmethod
    def callback_choose_graphical_output_location(tool) -> None: ...
    @staticmethod
    @require_evaluation_graph
    def callback_visualize_evaluation_graph(tool) -> None: ...
    @staticmethod
    @require_evaluation_graph
    def callback_visualize_scheduling_graph(tool) -> None: ...
    def graphical_frame_layout(self) -> None: ...
    @staticmethod
    def callback_update_text_output_format(tool) -> None: ...
    @staticmethod
    def callback_update_text_output_location(tool) -> None: ...
    @staticmethod
    def callback_choose_text_output(tool) -> None: ...
    @staticmethod
    @require_evaluation_graph
    def callback_print_nodes(tool) -> None: ...
    @staticmethod
    @require_evaluation_graph
    def callback_print_graph(tool) -> None: ...
    @staticmethod
    @require_evaluation_graph
    def callback_print_scheduling_types(tool) -> None: ...
    @staticmethod
    @require_evaluation_graph
    def callback_print_scheduling_graph(tool) -> None: ...
    def text_frame_layout(self) -> None: ...
    widgets: Incomplete
    get_graphviz_manager: Incomplete
    format_text: Incomplete
    output_location_text: Incomplete
    include_cluster_annotation: Incomplete
    include_cluster_label: Incomplete
    include_plug_annotation: Incomplete
    include_plug_label: Incomplete
    three_column_layout: Incomplete
    def __init__(self, get_graphviz_manager) -> None: ...

class EvaluationToolkitSectionDebugging(EvaluationToolkitSection):
    subsections: Incomplete
    def __init__(self, title, start_closed, get_graphviz_manager) -> None: ...
    def update_ui(self) -> None: ...
