from _typeshed import Incomplete
from maya.app.evaluationToolkit.EvaluationToolkitSectionDebugging import EvaluationToolkitSectionDebugging as EvaluationToolkitSectionDebugging
from maya.app.evaluationToolkit.EvaluationToolkitSectionGPUOverride import EvaluationToolkitSectionGPUOverride as EvaluationToolkitSectionGPUOverride
from maya.app.evaluationToolkit.EvaluationToolkitSectionHUD import EvaluationToolkitSectionHUD as EvaluationToolkitSectionHUD
from maya.app.evaluationToolkit.evaluation_toolkit_utilities import BUTTON_WIDTH as BUTTON_WIDTH, COLUMN_SPACING as COLUMN_SPACING, FILE_TEXT_FIELD_WIDTH as FILE_TEXT_FIELD_WIDTH, ROW_SPACING as ROW_SPACING, section_layout as section_layout, set_gpu_override_active as set_gpu_override_active
from maya.common.ui import LayoutManager as LayoutManager, callback_tool as callback_tool, scrollableMessageBox as scrollableMessageBox, showMessageBox as showMessageBox
from maya.debug.EvaluatorManager import EvaluatorManager as EvaluatorManager
from maya.debug.GraphVizManager import GraphVizManager as GraphVizManager
from maya.debug.emCorrectnessTest import emCorrectnessTest as emCorrectnessTest
from maya.debug.emModeManager import emModeManager as emModeManager
from maya.debug.emPerformanceTest import emPerformanceOptions as emPerformanceOptions, emPerformanceTest as emPerformanceTest
from maya.debug.em_debug_utilities import convert_exception_to_unicode as convert_exception_to_unicode, dotFormatting as dotFormatting, get_all_custom_evaluators_clusters as get_all_custom_evaluators_clusters
from maya.debug.frozenUtilities import list_frozen as list_frozen, unfreeze_nodes as unfreeze_nodes
from maya.plugin.evaluator.CacheUiToolkit import CacheUiToolkit as CacheUiToolkit
from maya.plugin.evaluator.EvaluationToolkitSectionCaching import EvaluationToolkitSectionCaching as EvaluationToolkitSectionCaching

kWindowName: str
kSectionHUD: str
kSectionDebugging: str
kSectionGPUOverride: str
kSectionCaching: str
kTextNumberWidth: int
kPathTextFieldWidth: int
kGroupLabelWidth: int
kEvaluationManagerModes: Incomplete
kCorrectnessModeNames: Incomplete
kPerformanceModeNames: Incomplete
kTestNotRun: Incomplete
kProcessTypes: Incomplete
kNodeOptions: Incomplete
kActionOptions: Incomplete
kDynamicsOptions: Incomplete
kDynamicsModes: Incomplete
kFreezeDownstreamModes: Incomplete
kFreezeUpstreamModes: Incomplete
kSchedulingTypes: Incomplete
kPrintLabel: Incomplete
kSelectLabel: Incomplete
kRunLabel: Incomplete
kGenerateLabel: Incomplete
kOpenLabel: Incomplete
kRemoveLabel: Incomplete
kShowLabel: Incomplete
kSetLabel: Incomplete
kUIRateFmt: Incomplete
kNodeNotInCluster: Incomplete
kIdleActions: Incomplete
kInvisibilityModes: Incomplete
kInvisibilityNotificationModes: Incomplete

class EvaluationToolkit:
    windowTitle: Incomplete
    windowName: Incomplete
    sections: Incomplete
    def __init__(self, windowName=...) -> None: ...
    checkboxUseSystemGraphviz: Incomplete
    evaluationModeList: Incomplete
    checkboxGPUOverride: Incomplete
    checkboxControllerPrepopulate: Incomplete
    layoutModesAdvanced: Incomplete
    checkboxManipulation: Incomplete
    checkboxManipulationPrevalidation: Incomplete
    checkboxReduceGraphRebuild: Incomplete
    idleActionList: Incomplete
    layoutEvaluators: Incomplete
    dynamicsModeList: Incomplete
    layoutDynamicsAdvanced: Incomplete
    listDynamics: Incomplete
    checkboxTransitiveReductionFullGraph: Incomplete
    checkboxMarkClusters: Incomplete
    cyclesList: Incomplete
    fieldCycleSizeThreshold: Incomplete
    textfieldSourceNode: Incomplete
    textfieldDestinationNode: Incomplete
    checkboxOnlyShortestPath: Incomplete
    checkboxTransitiveReductionCycleGraph: Incomplete
    upstreamNodesList: Incomplete
    downstreamNodesList: Incomplete
    checkboxTransitiveReductionDependenciesGraph: Incomplete
    performance_result_fields: Incomplete
    correctness_result_fields: Incomplete
    checkboxReports: Incomplete
    checkboxFreezePropagation: Incomplete
    freezeDownstreamModeList: Incomplete
    freezeUpstreamModeList: Incomplete
    checkboxFreezeInvisible: Incomplete
    schedulingTypeList: Incomplete
    nodeTypesList: Incomplete
    invisibilityModeList: Incomplete
    invisibilityInvalidateButton: Incomplete
    layoutInvisibilityAdvanced: Incomplete
    invisibilityNotificationModeList: Incomplete
    motionTrailsManipCheckbox: Incomplete
    motionTrailsInvalidateButton: Incomplete
    scriptJobDeleteAll: Incomplete
    scriptJobDbTraceChanged: Incomplete
    scriptJobCustomEvaluatorChanged: Incomplete
    scriptJobFreezeOptionsChanged: Incomplete
    def create(self) -> None: ...
    def updateUI(self) -> None: ...

def require_evaluation_graph(func): ...
def updateUI_00_Viewport(self) -> None: ...
def get_graphviz_manager(tool): ...
def callback_CFG_PrintGraphvizVersion(tool) -> None: ...
def updateUI_01_Mode(self) -> None: ...
def callback_01_UpdateEvaluationMode(tool) -> None: ...
def callback_01_UpdateGPUOverride(tool) -> None: ...
def callback_01_UpdateControllerPrepopulate(tool) -> None: ...
def callback_01_UpdateReduceGraphRebuild(tool) -> None: ...
def callback_01_UpdateManipulation(tool) -> None: ...
def callback_01_UpdateManipulationPrevalidation(tool) -> None: ...
def callback_01_UpdateIdleAction(tool) -> None: ...
def updateUI_04_CustomEvaluators(self) -> None: ...
def callback_04_setEvaluatorActive(tool, evaluator, state) -> None: ...
def callback_04_ShowHelpEvaluator(tool, evaluator) -> None: ...
def callback_04_GetEvaluatorInfo(tool, evaluator): ...
def callback_04_PrintEvaluatorInfo(tool, evaluator) -> None: ...
def callback_04_GetClaimedNodes(tool, evaluator): ...
def callback_04_ShowEvaluatorNodes(tool, evaluator) -> None: ...
def updateUI_05_Dynamics(self) -> None: ...
def callback_05_UpdateDynamicsMode(tool) -> None: ...
def callback_05_UpdateDynamicsOptions(tool, option) -> None: ...
def updateUI_07_Selection(self) -> None: ...
@require_evaluation_graph
def callback_07_SelectNodesUnderEvaluationManagerControl(tool) -> None: ...
@require_evaluation_graph
def callback_07_SelectUpStreamNodes(tool) -> None: ...
@require_evaluation_graph
def callback_07_SelectDownStreamNodes(tool) -> None: ...
def updateUI_08_Cycles(self) -> None: ...
@require_evaluation_graph
def callback_08_GenerateFullGraph(tool) -> None: ...
@require_evaluation_graph
def callback_08_RefreshCycleClusters(tool): ...
@require_evaluation_graph
def callback_08_SelectCycleBasedOnSelection(tool) -> None: ...
def callback_08_ListNodesInCycleCluster(tool) -> None: ...
def callback_08_SelectNode(tool, textfield) -> None: ...
@require_evaluation_graph
def callback_08_GenerateCycleGraph(tool) -> None: ...
def callback_08_SelectNodes(tool, textScrollList) -> None: ...
@require_evaluation_graph
def callback_08_GenerateDependenciesGraph(tool) -> None: ...
def updateUI_09_Validation(self) -> None: ...
def clear_09_Validation(tool) -> None: ...
def callback_09_RunPerformanceTest(tool) -> None: ...
def callback_09_RunCorrectnessTest(tool) -> None: ...
def updateUI_10_Reports(self) -> None: ...
def callback_10_RunReports(tool) -> None: ...
def updateUI_11_FreezeOptions(self) -> None: ...
def callback_11_UpdateDownstreamFreezeMode(tool) -> None: ...
def callback_11_UpdateUpstreamFreezeMode(tool) -> None: ...
def callback_11_UpdateFreezeInvisibleNodes(tool) -> None: ...
def callback_11_UpdateFreezeInvisibleDisplayLayers(tool) -> None: ...
def callback_11_UpdateFreezeRuntimePropagation(tool) -> None: ...
def callback_11_UpdateFreezeExplicitPropagation(tool) -> None: ...
def callback_11_SelectFrozenNodes(tool) -> None: ...
def callback_11_PrintFrozenNodes(tool) -> None: ...
def callback_11_UnfreezeAllFrozenNodes(tool) -> None: ...
def updateUI_12_Scheduling(self) -> None: ...
def callback_12_RefreshNodeTypes(tool) -> None: ...
def callback_12_PrintSchedulingForTypes(tool) -> None: ...
def callback_12_SetSchedulingForTypes(tool) -> None: ...
def callback_12_PrintSchedulingForTypesOfNodes(tool) -> None: ...
def callback_12_SetSchedulingForTypesOfNodes(tool) -> None: ...
@require_evaluation_graph
def callback_12_PrintSchedulingUsedForNodes(tool) -> None: ...
def updateUI_14_Invisibility(self) -> None: ...
def callback_14_UpdateInvisibilityMode(tool) -> None: ...
def callback_14_Invalidate(tool) -> None: ...
def callback_14_UpdateInvisibilityNotificationMode(tool) -> None: ...
def updateUI_15_MotionTrail(self) -> None: ...
def callback_15_Invalidate(tool) -> None: ...
def callback_15_Manipulation(tool) -> None: ...
def callback_scriptJob_deleteAll(tool) -> None: ...
def callback_scriptJob_dbTraceChanged(tool) -> None: ...
def callback_scriptJob_customEvaluatorChanged(tool) -> None: ...
def callback_scriptJob_freezeOptionsChanged(tool) -> None: ...
def callback_scriptJob_uiDeleted(tool) -> None: ...
def getEvaluationManagerMode(): ...
def setEvaluationManagerMode(mode): ...
def isEvaluatorActive(evaluatorName): ...
def setEvaluatorActive(evaluator, state) -> None: ...
def isGPUOverrideActive(): ...
def isControllerPrepopulateActive(): ...
def setControllerPrepopulateActive(state) -> None: ...
def setReduceGraphRebuild(state): ...
def isReduceGraphRebuild(): ...
def isManipulationActive(): ...
def setManipulationActive(state) -> None: ...
def isManipulationPrevalidationActive(): ...
def setManipulationPrevalidationActive(state) -> None: ...
def getIdleAction(): ...
def setIdleAction(idleAction) -> None: ...
def getEvaluationGraph(attributes, allObjects: bool = False): ...
def getEvaluationManagerNodes(): ...
def selectNodesUnderEvaluationManagerControl() -> None: ...
def selectNextNodes(upstream: bool = True) -> None: ...
def getCycleCluster(name): ...
def getCycleClusters(nodes): ...
def getShortestPaths(nodes, startNode, endNode: Incomplete | None = None): ...
def getShortestPath(nodes, startNode, endNode): ...
def dumpClusterToDot(fileName, nodesInCycle, nodesToMark, shortestPathInfo) -> None: ...
def dumpEvaluationGraphToDot(fileName) -> None: ...
def dumpDependenciesBetweenToDot(fileName, upstreamNodes, downstreamNodes) -> None: ...
def open_file(file_name) -> None: ...
def runEMPerformanceTest(): ...
def runEMCorrectnessTest(): ...
def printReportExpressions() -> None: ...
def printReportPerformance() -> None: ...
def getReports(): ...
def setSchedulingTypeOverride(nodeType, schedulingInfo) -> None: ...
def getSchedulingTypeOverride(nodeType): ...
def OpenEvaluationToolkitUI(): ...
