from _typeshed import Incomplete
from maya.app.ghosting.GhostingManager import GhostingManager as GhostingManager, string_to_frames as string_to_frames
from maya.app.ghosting.ghosting_optionvar_states import GhostingPreferenceGhostsStep as GhostingPreferenceGhostsStep, GhostingPreferencePostFrames as GhostingPreferencePostFrames, GhostingPreferencePreFrames as GhostingPreferencePreFrames

PREFERENCES_MONITORED: Incomplete
CLIENT_GHOSTING: str
RTC_UNGHOST_ALL: str
ANN_UNGHOST_ALL: Incomplete
LBL_UNGHOST_ALL: Incomplete
RTC_GHOST_SELECTED: str
ANN_GHOST_SELECTED: Incomplete
LBL_GHOST_SELECTED: Incomplete
RTC_UNGHOST_SELECTED: str
ANN_UNGHOST_SELECTED: Incomplete
LBL_UNGHOST_SELECTED: Incomplete
RTC_OPEN_GHOST_EDITOR: str
LBL_OPEN_GHOST_EDITOR_WINDOW_MENU: Incomplete
ANN_OPEN_GHOST_EDITOR: Incomplete
LBL_OPEN_GHOST_EDITOR: Incomplete
GHOSTING_RUNTIME_INITIALIZED: bool
TAGS_GHOSTING: Incomplete
KEYWORDS_GHOSTING: Incomplete
AE_TEMPLATE: str
AE_CUSTOM_FRAMES_WIDGET: str
NODE_TYPES_HIDING_GHOSTING_ATTRIBUTES: Incomplete

def tag_runtime_ghosting_commands() -> None: ...
def mel_as_python(mel_script): ...
def initialize_ghosting_runtime_commands() -> None: ...
def update_toggle_menu(menu_item) -> None: ...
def create_window_ghosting_menu_item() -> None: ...
def create_visualize_ghosting_menu_items() -> None: ...
def create_animation_shelf_ghosting_buttons() -> None: ...
def layout_ghosting_attributes(node_name) -> None: ...
def ae_check_ghosting_mode(node_name) -> None: ...
def ae_ghost_frames_new(plug_added) -> None: ...
def ae_ghost_frames_replace(plug_replaced) -> None: ...
def ae_update_ghost_frames(plug_to_update) -> None: ...
