# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import PyFnAttribute as FnAttribute
import NodegraphAPI as NodegraphAPI
import PackageSuperToolAPI.Packages as Packages
import QtCore
import QtGui
import QtWidgets
import UI4.Widgets.SceneGraphView
from UI4.Widgets.SceneGraphView.ItemDelegates.NameItemDelegate import NameItemDelegate
from _typeshed import Incomplete
from typing import ClassVar

class PackageNameItemDelegate(NameItemDelegate):
    DefaultColumnWidth: ClassVar[int] = ...
    MaximumColumnWidth: ClassVar[None] = ...
    def __init__(self, bridge: UI4.Widgets.SceneGraphView.Bridge, treeWidget: QtWidgets.QTreeWidget, parent: Incomplete | None = ...): ...
    def _PackageNameItemDelegate__getEditPackageClass(self, locationPath: str) -> type | None: ...
    def _PackageNameItemDelegate__getErrorOrWarning(self, locationPath: str) -> tuple[bool, bool, str, str]: ...
    def _PackageNameItemDelegate__getIcon(self, iconNameOrFilename: str, desiredResolution: int = ...) -> QtGui.QIcon | None: ...
    def _PackageNameItemDelegate__getPackageFromSceneGraphLocation(self, locationPath: str) -> Package | None: ...
    def _PackageNameItemDelegate__isErrorOrWarning(self, locationPath) -> bool: ...
    def createEditor(self, parent: QtWidgets.QWidget, option: QtWidgets.QStyleOptionViewItem, index: QtCore.QModelIndex) -> QtWidgets.QWidget | None: ...
    def initStyleOption(self, option: QtWidgets.QStyleOptionViewItem, index: QtCore.QModelIndex): ...
    def setModelData(self, editor: QtWidgets.QWidget, model: QtCore.QAbstractItemModel, index: QtCore.QModelIndex): ...
    def setSuperToolName(self, superToolName: str | None): ...
    def toolTipEvent(self, index: QtCore.QModelIndex): ...