# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import NodegraphAPI.Version.Registry as Registry
import NodegraphAPI.Xio as Xio
from NodegraphAPI.Version.Updater import Updater as Updater
from typing import ClassVar, Set, Tuple

class Updater2_7_27(Updater):
    DELETE_BlockerCreate: ClassVar[bool] = ...
    DELETE_DiskCache: ClassVar[bool] = ...
    DELETE_PrmanRerenderEnable: ClassVar[bool] = ...
    DELETE_Roto: ClassVar[bool] = ...
    RENAME_Colorspace_TO: ClassVar[str] = ...
    RENAME_Display_TO: ClassVar[str] = ...
    RENAME_FileTransform_TO: ClassVar[str] = ...
    VERSION: ClassVar[tuple] = ...
    def upgrade_PrmanRerenderCache(self, node): ...
