# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import NodegraphAPI
import NodegraphAPI.Xio as Xio
from NodegraphAPI.Version.Updater import Updater as Updater
from typing import ClassVar, Set, Tuple

class Updater2_0_1_6(Updater):
    VERSION: ClassVar[tuple] = ...
    def _Updater2_0_1_6__getAllNodeChildren(self, node: NodegraphAPI.Node): ...
    def _Updater2_0_1_6__updateMuteAndSoloStorage(self, node: NodegraphAPI.Node): ...
    def _Updater2_0_1_6__updateNodeInternals(self, node: NodegraphAPI.Node, document): ...
    def upgrade_GafferThree(self, node, document): ...
