# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import NodegraphAPI.Version.Registry as Registry
import NodegraphAPI.Xio as Xio

_actionMappings: dict
localVersion: tuple

def IsDynamicParameterEnabled(param): ...
def UpgradeMaterial(node): ...
def UpgradeShadingNetworkMaterial(node): ...
def update(document): ...