# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import NodegraphAPI.Version.Registry as Registry
import NodegraphAPI.Xio as Xio
from typing import Set, Tuple

localVersion: tuple

def UpgradeCoordinateSystemDefine(node, nodeType): ...
def UpgradePrimitiveCreate(node, nodeType): ...
def UpgradeTeapotCreate(node, nodeType): ...
def update(document): ...
