# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import NodegraphAPI.Xio as Xio
from NodegraphAPI.Version.Updater import Updater as Updater
from typing import ClassVar

class Updater2_0_1_12(Updater):
    VERSION: ClassVar[tuple] = ...
    def _Updater2_0_1_12__appendSoloListEditNodes(self, document, rootNode, newSourcePorts, soloListEditOutputPorts): ...
    def _Updater2_0_1_12__createSoloListEditNode(self, document, parent, position, inputPortName): ...
    def upgrade_GafferThree(self, node, document): ...