# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import NodegraphAPI.Xio as Xio
from NodegraphAPI.Version.Updater import Updater as Updater
from typing import ClassVar, Set, Tuple

_Version: tuple

class Updater3711(Updater):
    VERSION: ClassVar[tuple] = ...
    def _Updater3711__extractInternalNMCNodes(self, node): ...
    def _Updater3711__extractInternalNMENodes(self, node): ...
    def _Updater3711__upgradeNMCNode(self, node, document): ...
    def _Updater3711__upgradeNMENode(self, node, document): ...
    def update(self, document): ...
