# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import NodegraphAPI.Xio as Xio
from NodegraphAPI.Version.Updater import Updater as Updater
from typing import ClassVar, Set, Tuple

_Version: tuple

class Updater3711(Updater):
    VERSION: ClassVar[tuple] = ...
    @staticmethod
    def _Updater3711__extractInternalNMCNodes(node): ...
    @staticmethod
    def _Updater3711__extractInternalNMENodes(node): ...
    @staticmethod
    def _Updater3711__upgradeNMCNode(node, document): ...
    @staticmethod
    def _Updater3711__upgradeNMENode(node, document): ...
    def update(self, document): ...
