# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"


_Files: dict

class ResourceManager:
    def __init__(self, paths, exceptionForMissing: bool = ...): ...
    def clearCache(self): ...
    def getResourceFile(self, resourceName): ...
    def isExceptionForMissing(self): ...
    def setExceptionForMissing(self, doExc): ...

def _ExpandPath(path): ...