from .TsTest_Grapher import TsTest_Grapher as TsTest_Grapher
from _typeshed import Incomplete

class TsTest_Comparator:
    @classmethod
    def Init(cls): ...
    _sampleSets: Incomplete
    _grapher: Incomplete
    _haveCompared: bool
    def __init__(self, title, widthPx: int = 1000, heightPx: int = 1500) -> None: ...
    def AddSpline(self, name, splineData, samples, baked: Incomplete | None = None) -> None: ...
    def Display(self) -> None: ...
    def Write(self, filePath) -> None: ...
    def GetMaxDiff(self): ...
    def _Compare(self) -> None: ...
    _diffs: Incomplete
    _maxDiff: int
    def _FindDiffs(self) -> None: ...
