import mari
from _typeshed import Incomplete

ocio: Incomplete
filter_factory: Incomplete

class OCIOFilterFactory(mari.GLSLFilterFactory):
    def __init__(self) -> None: ...
    def resolve_config_path(self, config_path): ...
    def setupFilter(self, filter) -> None: ...

def registerCustomOcioFilter() -> None: ...
def resetAdjustmentLevelClampToDefault() -> None: ...
