from PySide2 import QtGui as QtGui, QtWidgets as QtWidgets
from _typeshed import Incomplete

gui: Incomplete
widgets: Incomplete

def printMessage(Str) -> None: ...
def run_mGo(): ...
def getProjects(mayaHost, mGoPath) -> None: ...
def importGEO(sendMode, projectName, nameSpace, groups, FilePath, setR, sd, isAnim, startAnim, endAnim, myObjList, myFileName, meshData, sendShader, shadersOnly, shader_file) -> None: ...
def importCAM(projectName, startTime, endTime, camFileName) -> None: ...
