def createShaderStacks_ChannelShaderStack_AddShader(obj, channel_shaderstack, channel_diffuse): ...
def createShaderStacks_ChannelShaderStack(obj): ...
def createShaderStacks_ChannelDiffuse(obj, channel_name, color): ...
def createShaderStacks_ChannelMask(obj): ...
def createShaderStacks() -> None: ...
