import maya.app.renderSetup.model.observable as observable

class ProgressObservable(observable.SingletonObservable):
    class StartProgressNotification:
        def __init__(self) -> None: ...
    class EndProgressNotification:
        def __init__(self) -> None: ...
    progress: int
    callerCount: int
    def __init__(self) -> None: ...
    def startProgress(self) -> None: ...
    def notifyItemObserver(self, progress, info) -> None: ...
    def endProgress(self) -> None: ...
    def inProgress(self): ...
    def topLevelCaller(self): ...

class ProgressCtxMgr:
    def __init__(self) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...

def progress(f): ...
