from ._utils.powershell_base import PowerShellBase as PowerShellBase

class PowerShellCore(PowerShellBase):
    @classmethod
    def name(cls): ...
    @classmethod
    def file_extension(cls): ...
    @classmethod
    def get_syspaths(cls): ...

def register_plugin(): ...
