# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"

import PyQt5.QtWidgets
import QtCore as QtCore
import QtGui as QtGui
import PyQt5.QtWidgets as QtWidgets
from _typeshed import Incomplete
from typing import Set, Tuple

class FormWidgetLabel(PyQt5.QtWidgets.QLabel):
    def __init__(self, text: str, parent: Incomplete | None = ...): ...
    def FormatByteSize(self, size: int) -> str: ...
    def _FormWidgetLabel__updateToolTip(self): ...
    def enterEvent(self, event: QtCore.QEvent): ...
    def event(self, event: QtCore.QEvent) -> bool: ...
    def getBuddy(self): ...
    def leaveEvent(self, event: QtCore.QEvent): ...
    def mousePressEvent(self, event: QtGui.QMouseEvent): ...
    def mouseReleaseEvent(self, event: QtGui.QMouseEvent): ...
    def setColor(self, color: QtGui.QColor): ...
    def setText(self, text: str): ...
