# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"


_HintTrueValues: list

def GetCapsuleArgsFromHints(hints): ...
def GetColor(colorHint): ...
def GetColorList(listHint): ...
def GetMapping(mappingHint, numberValues: bool = ..., order: list = ...): ...
def GetSliderArgsFromHints(hints): ...
def GetStringList(listHint): ...
def HintTrue(hintName: str, hints: dict, default: bool = ...) -> bool: ...