from PySide2 import QtWidgets
from _typeshed import Incomplete

class MariEntityTreeWidgetItem(QtWidgets.QTreeWidgetItem):
    def __init__(self, parent, mariEntity, dragEnabled: bool = ..., dropEnabled: bool = ..., selectable: bool = ..., userCheckable: bool = ..., tristate: bool = ..., iconName: Incomplete | None = ...) -> None: ...
    @property
    def mariEntity(self): ...
    def updateIcons(self) -> None: ...
