from .mari_entity import MariEntityTreeWidget as MariEntityTreeWidget
from _typeshed import Incomplete

class MariEntitySourceShaderTreeWidget(MariEntityTreeWidget):
    def __init__(self, parent: Incomplete | None = ...) -> None: ...
    def populateView(self) -> None: ...
