from .mari_entity import MariEntityTreeWidget as MariEntityTreeWidget
from _typeshed import Incomplete

class MariEntityTargetShaderTreeWidget(MariEntityTreeWidget):
    def __init__(self, parent: Incomplete | None = ...) -> None: ...
    def dragMoveEvent(self, event) -> None: ...
    def dropEvent(self, event) -> None: ...
    def onMakeShaderFinished(self, shader) -> None: ...
    def populateView(self) -> None: ...
