from . import METATYPES_JSON_SUFFIX as METATYPES_JSON_SUFFIX, MOD_CMD as MOD_CMD, PYPROJECT_FILE_PATTERNS as PYPROJECT_FILE_PATTERNS, PYPROJECT_JSON_PATTERN as PYPROJECT_JSON_PATTERN, PYPROJECT_TOML_PATTERN as PYPROJECT_TOML_PATTERN, QML_IMPORT_MAJOR_VERSION as QML_IMPORT_MAJOR_VERSION, QML_IMPORT_MINOR_VERSION as QML_IMPORT_MINOR_VERSION, QML_IMPORT_NAME as QML_IMPORT_NAME, QT_MODULES as QT_MODULES, TRANSLATION_SUFFIX as TRANSLATION_SUFFIX, qt_metatype_json_dir as qt_metatype_json_dir
from .pyproject_json import parse_pyproject_json as parse_pyproject_json
from .pyproject_toml import parse_pyproject_toml as parse_pyproject_toml
from _typeshed import Incomplete
from pathlib import Path

def is_python_file(file: Path) -> bool: ...

class ProjectData:
    _project_file: Incomplete
    _sub_projects_files: list[Path]
    _files: list[Path]
    _qml_files: list[Path]
    _python_files: list[Path]
    _ui_files: list[Path]
    _qrc_files: list[Path]
    _ts_files: list[Path]
    def __init__(self, project_file: Path) -> None: ...
    @property
    def project_file(self): ...
    @property
    def files(self): ...
    @property
    def main_file(self): ...
    _main_file: Incomplete
    @main_file.setter  # type: ignore[no-redef]
    def main_file(self, main_file) -> None: ...
    @property
    def python_files(self): ...
    @property
    def ui_files(self): ...
    @property
    def qrc_files(self): ...
    @property
    def qml_files(self): ...
    @property
    def ts_files(self): ...
    @property
    def sub_projects_files(self): ...
    def _find_main_file(self) -> str: ...

class QmlProjectData:
    _import_name: str
    _import_major_version: int
    _import_minor_version: int
    _qt_modules: list[str]
    def __init__(self) -> None: ...
    def registrar_options(self): ...
    @property
    def import_name(self): ...
    @import_name.setter
    def import_name(self, n) -> None: ...
    @property
    def import_major_version(self): ...
    @import_major_version.setter
    def import_major_version(self, v) -> None: ...
    @property
    def import_minor_version(self): ...
    @import_minor_version.setter
    def import_minor_version(self, v) -> None: ...
    @property
    def qt_modules(self): ...
    @qt_modules.setter
    def qt_modules(self, v) -> None: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...

def _has_qml_decorated_class(class_list: list) -> bool: ...
def check_qml_decorators(py_file: Path) -> tuple[bool, QmlProjectData]: ...
