from . import ClOptions as ClOptions, PYPROJECT_FILE_PATTERNS as PYPROJECT_FILE_PATTERNS, PYPROJECT_JSON_PATTERN as PYPROJECT_JSON_PATTERN, PYPROJECT_TOML_PATTERN as PYPROJECT_TOML_PATTERN, QTPATHS_CMD as QTPATHS_CMD
from .pyproject_json import parse_pyproject_json as parse_pyproject_json
from .pyproject_toml import parse_pyproject_toml as parse_pyproject_toml
from pathlib import Path

def run_command(command: list[str], cwd: str = None, ignore_fail: bool = False) -> int: ...  # type: ignore[assignment]
def qrc_file_requires_rebuild(resources_file_path: Path, compiled_resources_path: Path) -> bool: ...
def requires_rebuild(sources: list[Path], artifact: Path) -> bool: ...
def _remove_path_recursion(path: Path): ...
def remove_path(path: Path): ...
def package_dir() -> Path: ...

_qtpaths_info: dict[str, str]

def qtpaths() -> dict[str, str]: ...

_qt_metatype_json_dir: Path | None

def qt_metatype_json_dir() -> Path: ...
def resolve_valid_project_file(project_path_input: str = None, project_file_patterns: list[str] = ...) -> Path: ...  # type: ignore[assignment]
