import PySide6.QtCore
import _typeshed
import collections
import enum
import shiboken6
import typing
import typing_extensions

from typing import Any, Dict, List, Optional, OrderedDict, Set, Tuple, Union
T = typing.TypeVar('T')
P = typing.ParamSpec('P')
class QFutureQString(shiboken6.Object):
    @typing.overload
    def __init__(self, QFutureQString: QFutureQString, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def cancel(self, /) -> None: ...
    def cancelChain(self, /) -> None: ...
    def isCanceled(self, /) -> bool: ...
    def isFinished(self, /) -> bool: ...
    def isPaused(self, /) -> bool: ...
    def isRunning(self, /) -> bool: ...
    def isStarted(self, /) -> bool: ...
    def isSuspended(self, /) -> bool: ...
    def isSuspending(self, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    def pause(self, /) -> None: ...
    def progressMaximum(self, /) -> int: ...
    def progressMinimum(self, /) -> int: ...
    def progressText(self, /) -> str: ...
    def progressValue(self, /) -> int: ...
    def resultCount(self, /) -> int: ...
    def resume(self, /) -> None: ...
    def setPaused(self, paused: bool, /) -> None: ...
    def setSuspended(self, suspend: bool, /) -> None: ...
    def suspend(self, /) -> None: ...
    def togglePaused(self, /) -> None: ...
    def toggleSuspended(self, /) -> None: ...
    def waitForFinished(self, /) -> None: ...
    def __copy__(self, /) -> typing_extensions.Self: ...

class QFutureVoid(shiboken6.Object):
    @typing.overload
    def __init__(self, QFutureVoid: QFutureVoid, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def cancel(self, /) -> None: ...
    def cancelChain(self, /) -> None: ...
    def isCanceled(self, /) -> bool: ...
    def isFinished(self, /) -> bool: ...
    def isPaused(self, /) -> bool: ...
    def isRunning(self, /) -> bool: ...
    def isStarted(self, /) -> bool: ...
    def isSuspended(self, /) -> bool: ...
    def isSuspending(self, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    def pause(self, /) -> None: ...
    def progressMaximum(self, /) -> int: ...
    def progressMinimum(self, /) -> int: ...
    def progressText(self, /) -> str: ...
    def progressValue(self, /) -> int: ...
    def resultCount(self, /) -> int: ...
    def resume(self, /) -> None: ...
    def setPaused(self, paused: bool, /) -> None: ...
    def setSuspended(self, suspend: bool, /) -> None: ...
    def suspend(self, /) -> None: ...
    def togglePaused(self, /) -> None: ...
    def toggleSuspended(self, /) -> None: ...
    def waitForFinished(self, /) -> None: ...
    def __copy__(self, /) -> typing_extensions.Self: ...

class QFutureWatcherQString(PySide6.QtCore.QObject):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, _parent: PySide6.QtCore.QObject | None = ..., canceled: typing.Callable = ..., destroyed: typing.Callable = ..., finished: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., paused: typing.Callable = ..., progressRangeChanged: typing.Callable = ..., progressTextChanged: typing.Callable = ..., progressValueChanged: typing.Callable = ..., resultReadyAt: typing.Callable = ..., resultsReadyAt: typing.Callable = ..., resumed: typing.Callable = ..., started: typing.Callable = ..., suspended: typing.Callable = ..., suspending: typing.Callable = ...) -> None: ...
    def future(self, /) -> QFutureQString: ...
    def setFuture(self, future: QFutureQString, /) -> None: ...

class QFutureWatcherVoid(PySide6.QtCore.QObject):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, _parent: PySide6.QtCore.QObject | None = ..., canceled: typing.Callable = ..., destroyed: typing.Callable = ..., finished: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., paused: typing.Callable = ..., progressRangeChanged: typing.Callable = ..., progressTextChanged: typing.Callable = ..., progressValueChanged: typing.Callable = ..., resultReadyAt: typing.Callable = ..., resultsReadyAt: typing.Callable = ..., resumed: typing.Callable = ..., started: typing.Callable = ..., suspended: typing.Callable = ..., suspending: typing.Callable = ...) -> None: ...

class QIntList:
    __opaque_container__: typing.ClassVar[bool] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs): ...
    def capacity(self, *args, **kwargs): ...
    def clear(self, *args, **kwargs): ...
    def constData(self, *args, **kwargs): ...
    def data(self, *args, **kwargs): ...
    def pop_back(self, *args, **kwargs): ...
    def pop_front(self, *args, **kwargs): ...
    def prepend(self, *args, **kwargs): ...
    def push_back(self, *args, **kwargs): ...
    def push_front(self, *args, **kwargs): ...
    def removeFirst(self, *args, **kwargs): ...
    def removeLast(self, *args, **kwargs): ...
    def reserve(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, object) -> None: ...

class QtConcurrent(shiboken6.Object):
    class FutureResult(enum.Enum):
        Ignore = 0

    class ReduceOption(enum.Flag):
        OrderedReduce = 2
        SequentialReduce = 4
        UnorderedReduce = 1

    class ThreadFunctionResult(enum.Enum):
        ThreadFinished = 1
        ThrottleThread = 0
    def __init__(self, *args, **kwargs) -> None: ...
