import PySide6.QtCore
import PySide6.QtGui
import _typeshed
import collections
import enum
import shiboken6
import typing
import typing_extensions

from typing import Any, Dict, List, Optional, OrderedDict, Set, Tuple, Union
T = typing.TypeVar('T')
P = typing.ParamSpec('P')
class QAbstractVideoBuffer(shiboken6.Object):
    class MapData(shiboken6.Object):
        planeCount: _typeshed.Incomplete
        @typing.overload
        def __init__(self, MapData: QAbstractVideoBuffer.MapData, /) -> None: ...
        @typing.overload
        def __init__(self, /) -> None: ...
        def __copy__(self, /) -> typing_extensions.Self: ...
    def __init__(self, /) -> None: ...
    def format(self, /) -> QVideoFrameFormat: ...
    def map(self, mode: QVideoFrame.MapMode, /) -> QAbstractVideoBuffer.MapData: ...
    def unmap(self, /) -> None: ...

class QAudio(shiboken6.Object):
    class Error(enum.Enum):
        FatalError = 4
        IOError = 2
        NoError = 0
        OpenError = 1
        UnderrunError = 3

    class State(enum.Enum):
        ActiveState = 0
        IdleState = 3
        StoppedState = 2
        SuspendedState = 1

    class VolumeScale(enum.Enum):
        CubicVolumeScale = 1
        DecibelVolumeScale = 3
        LinearVolumeScale = 0
        LogarithmicVolumeScale = 2
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def convertVolume(volume: float, from_: QAudio.VolumeScale, to: QAudio.VolumeScale, /) -> float: ...

class QAudioBuffer(shiboken6.Object):
    @typing.overload
    def __init__(self, numFrames: int, format: QAudioFormat, /, startTime: int = ...) -> None: ...
    @typing.overload
    def __init__(self, data: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, format: QAudioFormat, /, startTime: int = ...) -> None: ...
    @typing.overload
    def __init__(self, other: QAudioBuffer, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def byteCount(self, /) -> int: ...
    def constData(self, /) -> bytes | bytearray | memoryview: ...
    def data(self, /) -> bytes | bytearray | memoryview: ...
    def duration(self, /) -> int: ...
    def format(self, /) -> QAudioFormat: ...
    def frameCount(self, /) -> int: ...
    def isValid(self, /) -> bool: ...
    def sampleCount(self, /) -> int: ...
    def startTime(self, /) -> int: ...
    def swap(self, other: QAudioBuffer, /) -> None: ...
    def __copy__(self, /) -> typing_extensions.Self: ...

class QAudioBufferInput(PySide6.QtCore.QObject):
    readyToSendAudioBuffer: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    @typing.overload
    def __init__(self, format: QAudioFormat, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., readyToSendAudioBuffer: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., readyToSendAudioBuffer: typing.Callable = ...) -> None: ...
    def captureSession(self, /) -> QMediaCaptureSession: ...
    def format(self, /) -> QAudioFormat: ...
    def sendAudioBuffer(self, audioBuffer: QAudioBuffer, /) -> bool: ...

class QAudioBufferOutput(PySide6.QtCore.QObject):
    audioBufferReceived: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    @typing.overload
    def __init__(self, format: QAudioFormat, /, parent: PySide6.QtCore.QObject | None = ..., audioBufferReceived: typing.Callable = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., audioBufferReceived: typing.Callable = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def format(self, /) -> QAudioFormat: ...

class QAudioDecoder(PySide6.QtCore.QObject):
    class Error(enum.Enum):
        AccessDeniedError = 3
        FormatError = 2
        NoError = 0
        NotSupportedError = 4
        ResourceError = 1
    bufferAvailableChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    bufferReady: typing.ClassVar[PySide6.QtCore.Signal] = ...
    durationChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    error: typing.ClassVar[PySide6.QtCore.Signal] = ...
    finished: typing.ClassVar[PySide6.QtCore.Signal] = ...
    formatChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    isDecodingChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    positionChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sourceChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, source: PySide6.QtCore.QUrl | None = ..., isDecoding: bool | None = ..., error: str | None = ..., bufferAvailable: bool | None = ..., bufferAvailableChanged: typing.Callable = ..., bufferReady: typing.Callable = ..., destroyed: typing.Callable = ..., durationChanged: typing.Callable = ..., finished: typing.Callable = ..., formatChanged: typing.Callable = ..., isDecodingChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., positionChanged: typing.Callable = ..., sourceChanged: typing.Callable = ...) -> None: ...
    def audioFormat(self, /) -> QAudioFormat: ...
    def bufferAvailable(self, /) -> bool: ...
    def duration(self, /) -> int: ...
    def errorString(self, /) -> str: ...
    def isDecoding(self, /) -> bool: ...
    def isSupported(self, /) -> bool: ...
    def position(self, /) -> int: ...
    def read(self, /) -> QAudioBuffer: ...
    def setAudioFormat(self, format: QAudioFormat, /) -> None: ...
    def setSource(self, fileName: PySide6.QtCore.QUrl | str, /) -> None: ...
    def setSourceDevice(self, device: PySide6.QtCore.QIODevice, /) -> None: ...
    def source(self, /) -> PySide6.QtCore.QUrl: ...
    def sourceDevice(self, /) -> PySide6.QtCore.QIODevice: ...
    def start(self, /) -> None: ...
    def stop(self, /) -> None: ...

class QAudioDevice(shiboken6.Object):
    class Mode(enum.Enum):
        Input = 1
        Null = 0
        Output = 2
    @typing.overload
    def __init__(self, other: QAudioDevice, /, *, id: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview | None = ..., description: str | None = ..., isDefault: bool | None = ..., mode: QAudioDevice.Mode | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, id: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview | None = ..., description: str | None = ..., isDefault: bool | None = ..., mode: QAudioDevice.Mode | None = ...) -> None: ...
    def channelConfiguration(self, /) -> QAudioFormat.ChannelConfig: ...
    def description(self, /) -> str: ...
    def id(self, /) -> PySide6.QtCore.QByteArray: ...
    def isDefault(self, /) -> bool: ...
    def isFormatSupported(self, format: QAudioFormat, /) -> bool: ...
    def isNull(self, /) -> bool: ...
    def maximumChannelCount(self, /) -> int: ...
    def maximumSampleRate(self, /) -> int: ...
    def minimumChannelCount(self, /) -> int: ...
    def minimumSampleRate(self, /) -> int: ...
    def mode(self, /) -> QAudioDevice.Mode: ...
    def preferredFormat(self, /) -> QAudioFormat: ...
    def supportedSampleFormats(self, /) -> List[QAudioFormat.SampleFormat]: ...
    def swap(self, other: QAudioDevice, /) -> None: ...
    def __bool__(self) -> bool: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QAudioFormat(shiboken6.Object):
    class AudioChannelPosition(enum.Enum):
        BackCenter = 9
        BackLeft = 5
        BackRight = 6
        BottomFrontCenter = 22
        BottomFrontLeft = 23
        BottomFrontRight = 24
        FrontCenter = 3
        FrontLeft = 1
        FrontLeftOfCenter = 7
        FrontRight = 2
        FrontRightOfCenter = 8
        LFE = 4
        LFE2 = 19
        SideLeft = 10
        SideRight = 11
        TopBackCenter = 17
        TopBackLeft = 16
        TopBackRight = 18
        TopCenter = 12
        TopFrontCenter = 14
        TopFrontLeft = 13
        TopFrontRight = 15
        TopSideLeft = 20
        TopSideRight = 21
        UnknownPosition = 0

    class ChannelConfig(enum.Enum):
        ChannelConfig2Dot1 = 22
        ChannelConfig3Dot0 = 14
        ChannelConfig3Dot1 = 30
        ChannelConfigMono = 8
        ChannelConfigStereo = 6
        ChannelConfigSurround5Dot0 = 110
        ChannelConfigSurround5Dot1 = 126
        ChannelConfigSurround7Dot0 = 3182
        ChannelConfigSurround7Dot1 = 3198
        ChannelConfigUnknown = 0

    class SampleFormat(enum.Enum):
        Float = 4
        Int16 = 2
        Int32 = 3
        NSampleFormats = 5
        UInt8 = 1
        Unknown = 0
    NChannelPositions: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, QAudioFormat: QAudioFormat, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def bytesForDuration(self, microseconds: int, /) -> int: ...
    def bytesForFrames(self, frameCount: int, /) -> int: ...
    def bytesPerFrame(self, /) -> int: ...
    def bytesPerSample(self, /) -> int: ...
    def channelConfig(self, /) -> QAudioFormat.ChannelConfig: ...
    def channelCount(self, /) -> int: ...
    def channelOffset(self, channel: QAudioFormat.AudioChannelPosition, /) -> int: ...
    @staticmethod
    def defaultChannelConfigForChannelCount(channelCount: int, /) -> QAudioFormat.ChannelConfig: ...
    def durationForBytes(self, byteCount: int, /) -> int: ...
    def durationForFrames(self, frameCount: int, /) -> int: ...
    def framesForBytes(self, byteCount: int, /) -> int: ...
    def framesForDuration(self, microseconds: int, /) -> int: ...
    def isValid(self, /) -> bool: ...
    def normalizedSampleValue(self, sample: bytes | bytearray | memoryview, /) -> float: ...
    def sampleFormat(self, /) -> QAudioFormat.SampleFormat: ...
    def sampleRate(self, /) -> int: ...
    def setChannelConfig(self, config: QAudioFormat.ChannelConfig, /) -> None: ...
    def setChannelCount(self, channelCount: int, /) -> None: ...
    def setSampleFormat(self, f: QAudioFormat.SampleFormat, /) -> None: ...
    def setSampleRate(self, sampleRate: int, /) -> None: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QAudioInput(PySide6.QtCore.QObject):
    deviceChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    mutedChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    volumeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    @typing.overload
    def __init__(self, deviceInfo: QAudioDevice, /, parent: PySide6.QtCore.QObject | None = ..., *, device: QAudioDevice | None = ..., volume: float | None = ..., muted: bool | None = ..., destroyed: typing.Callable = ..., deviceChanged: typing.Callable = ..., mutedChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., volumeChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, device: QAudioDevice | None = ..., volume: float | None = ..., muted: bool | None = ..., destroyed: typing.Callable = ..., deviceChanged: typing.Callable = ..., mutedChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., volumeChanged: typing.Callable = ...) -> None: ...
    def device(self, /) -> QAudioDevice: ...
    def isMuted(self, /) -> bool: ...
    def setDevice(self, device: QAudioDevice, /) -> None: ...
    def setMuted(self, muted: bool, /) -> None: ...
    def setVolume(self, volume: float, /) -> None: ...
    def volume(self, /) -> float: ...

class QAudioOutput(PySide6.QtCore.QObject):
    deviceChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    mutedChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    volumeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    @typing.overload
    def __init__(self, device: QAudioDevice, /, parent: PySide6.QtCore.QObject | None = ..., *, volume: float | None = ..., muted: bool | None = ..., destroyed: typing.Callable = ..., deviceChanged: typing.Callable = ..., mutedChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., volumeChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, device: QAudioDevice | None = ..., volume: float | None = ..., muted: bool | None = ..., destroyed: typing.Callable = ..., deviceChanged: typing.Callable = ..., mutedChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., volumeChanged: typing.Callable = ...) -> None: ...
    def device(self, /) -> QAudioDevice: ...
    def isMuted(self, /) -> bool: ...
    def setDevice(self, device: QAudioDevice, /) -> None: ...
    def setMuted(self, muted: bool, /) -> None: ...
    def setVolume(self, volume: float, /) -> None: ...
    def volume(self, /) -> float: ...

class QAudioSink(PySide6.QtCore.QObject):
    stateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    @typing.overload
    def __init__(self, audioDeviceInfo: QAudioDevice, /, format: QAudioFormat = ..., parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., stateChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, format: QAudioFormat = ..., parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., stateChanged: typing.Callable = ...) -> None: ...
    def bufferFrameCount(self, /) -> int: ...
    def bufferSize(self, /) -> int: ...
    def bytesFree(self, /) -> int: ...
    def elapsedUSecs(self, /) -> int: ...
    def error(self, /) -> QtAudio.Error: ...
    def format(self, /) -> QAudioFormat: ...
    def framesFree(self, /) -> int: ...
    def isNull(self, /) -> bool: ...
    def processedUSecs(self, /) -> int: ...
    def reset(self, /) -> None: ...
    def resume(self, /) -> None: ...
    def setBufferFrameCount(self, framesCount: int, /) -> None: ...
    def setBufferSize(self, bytes: int, /) -> None: ...
    def setVolume(self, arg__1: float, /) -> None: ...
    @typing.overload
    def start(self, device: PySide6.QtCore.QIODevice, /) -> None: ...
    @typing.overload
    def start(self, /) -> PySide6.QtCore.QIODevice: ...
    def state(self, /) -> QtAudio.State: ...
    def stop(self, /) -> None: ...
    def suspend(self, /) -> None: ...
    def volume(self, /) -> float: ...
    def __bool__(self) -> bool: ...

class QAudioSource(PySide6.QtCore.QObject):
    stateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    @typing.overload
    def __init__(self, audioDeviceInfo: QAudioDevice, /, format: QAudioFormat = ..., parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., stateChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, format: QAudioFormat = ..., parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., stateChanged: typing.Callable = ...) -> None: ...
    def bufferFrameCount(self, /) -> int: ...
    def bufferSize(self, /) -> int: ...
    def bytesAvailable(self, /) -> int: ...
    def elapsedUSecs(self, /) -> int: ...
    def error(self, /) -> QtAudio.Error: ...
    def format(self, /) -> QAudioFormat: ...
    def framesAvailable(self, /) -> int: ...
    def isNull(self, /) -> bool: ...
    def processedUSecs(self, /) -> int: ...
    def reset(self, /) -> None: ...
    def resume(self, /) -> None: ...
    def setBufferFrameCount(self, frames: int, /) -> None: ...
    def setBufferSize(self, bytes: int, /) -> None: ...
    def setVolume(self, volume: float, /) -> None: ...
    @typing.overload
    def start(self, device: PySide6.QtCore.QIODevice, /) -> None: ...
    @typing.overload
    def start(self, /) -> PySide6.QtCore.QIODevice: ...
    def state(self, /) -> QtAudio.State: ...
    def stop(self, /) -> None: ...
    def suspend(self, /) -> None: ...
    def volume(self, /) -> float: ...
    def __bool__(self) -> bool: ...

class QCamera(PySide6.QtCore.QObject):
    class Error(enum.Enum):
        CameraError = 1
        NoError = 0

    class ExposureMode(enum.Enum):
        ExposureAction = 7
        ExposureAuto = 0
        ExposureBarcode = 16
        ExposureBeach = 6
        ExposureCandlelight = 15
        ExposureFireworks = 13
        ExposureLandscape = 8
        ExposureManual = 1
        ExposureNight = 3
        ExposureNightPortrait = 9
        ExposureParty = 14
        ExposurePortrait = 2
        ExposureSnow = 5
        ExposureSports = 4
        ExposureSteadyPhoto = 12
        ExposureSunset = 11
        ExposureTheatre = 10

    class Feature(enum.Flag):
        ColorTemperature = 1
        CustomFocusPoint = 16
        ExposureCompensation = 2
        FocusDistance = 32
        IsoSensitivity = 4
        ManualExposureTime = 8

    class FlashMode(enum.Enum):
        FlashAuto = 2
        FlashOff = 0
        FlashOn = 1

    class FocusMode(enum.Enum):
        FocusModeAuto = 0
        FocusModeAutoFar = 2
        FocusModeAutoNear = 1
        FocusModeHyperfocal = 3
        FocusModeInfinity = 4
        FocusModeManual = 5

    class TorchMode(enum.Enum):
        TorchAuto = 2
        TorchOff = 0
        TorchOn = 1

    class WhiteBalanceMode(enum.Enum):
        WhiteBalanceAuto = 0
        WhiteBalanceCloudy = 3
        WhiteBalanceFlash = 7
        WhiteBalanceFluorescent = 6
        WhiteBalanceManual = 1
        WhiteBalanceShade = 4
        WhiteBalanceSunlight = 2
        WhiteBalanceSunset = 8
        WhiteBalanceTungsten = 5
    activeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    brightnessChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    cameraDeviceChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    cameraFormatChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    colorTemperatureChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    contrastChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    customFocusPointChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorOccurred: typing.ClassVar[PySide6.QtCore.Signal] = ...
    exposureCompensationChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    exposureModeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    exposureTimeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    flashModeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    flashReady: typing.ClassVar[PySide6.QtCore.Signal] = ...
    focusDistanceChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    focusModeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    focusPointChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    hueChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    isoSensitivityChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    manualExposureTimeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    manualIsoSensitivityChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    maximumZoomFactorChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    minimumZoomFactorChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    saturationChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    supportedFeaturesChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    torchModeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    whiteBalanceModeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    zoomFactorChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    @typing.overload
    def __init__(self, position: QCameraDevice.Position, /, parent: PySide6.QtCore.QObject | None = ..., *, active: bool | None = ..., cameraDevice: QCameraDevice | None = ..., error: QCamera.Error | None = ..., errorString: str | None = ..., cameraFormat: QCameraFormat | None = ..., focusMode: QCamera.FocusMode | None = ..., focusPoint: PySide6.QtCore.QPointF | None = ..., customFocusPoint: PySide6.QtCore.QPointF | None = ..., focusDistance: float | None = ..., minimumZoomFactor: float | None = ..., maximumZoomFactor: float | None = ..., zoomFactor: float | None = ..., exposureTime: float | None = ..., manualExposureTime: float | None = ..., isoSensitivity: int | None = ..., manualIsoSensitivity: int | None = ..., exposureCompensation: float | None = ..., exposureMode: QCamera.ExposureMode | None = ..., flashReady: bool | None = ..., flashMode: QCamera.FlashMode | None = ..., torchMode: QCamera.TorchMode | None = ..., whiteBalanceMode: QCamera.WhiteBalanceMode | None = ..., colorTemperature: int | None = ..., supportedFeatures: QCamera.Feature | None = ..., activeChanged: typing.Callable = ..., brightnessChanged: typing.Callable = ..., cameraDeviceChanged: typing.Callable = ..., cameraFormatChanged: typing.Callable = ..., colorTemperatureChanged: typing.Callable = ..., contrastChanged: typing.Callable = ..., customFocusPointChanged: typing.Callable = ..., destroyed: typing.Callable = ..., errorChanged: typing.Callable = ..., errorOccurred: typing.Callable = ..., exposureCompensationChanged: typing.Callable = ..., exposureModeChanged: typing.Callable = ..., exposureTimeChanged: typing.Callable = ..., flashModeChanged: typing.Callable = ..., focusDistanceChanged: typing.Callable = ..., focusModeChanged: typing.Callable = ..., focusPointChanged: typing.Callable = ..., hueChanged: typing.Callable = ..., isoSensitivityChanged: typing.Callable = ..., manualExposureTimeChanged: typing.Callable = ..., manualIsoSensitivityChanged: typing.Callable = ..., maximumZoomFactorChanged: typing.Callable = ..., minimumZoomFactorChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., saturationChanged: typing.Callable = ..., supportedFeaturesChanged: typing.Callable = ..., torchModeChanged: typing.Callable = ..., whiteBalanceModeChanged: typing.Callable = ..., zoomFactorChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, cameraDevice: QCameraDevice, /, parent: PySide6.QtCore.QObject | None = ..., *, active: bool | None = ..., error: QCamera.Error | None = ..., errorString: str | None = ..., cameraFormat: QCameraFormat | None = ..., focusMode: QCamera.FocusMode | None = ..., focusPoint: PySide6.QtCore.QPointF | None = ..., customFocusPoint: PySide6.QtCore.QPointF | None = ..., focusDistance: float | None = ..., minimumZoomFactor: float | None = ..., maximumZoomFactor: float | None = ..., zoomFactor: float | None = ..., exposureTime: float | None = ..., manualExposureTime: float | None = ..., isoSensitivity: int | None = ..., manualIsoSensitivity: int | None = ..., exposureCompensation: float | None = ..., exposureMode: QCamera.ExposureMode | None = ..., flashReady: bool | None = ..., flashMode: QCamera.FlashMode | None = ..., torchMode: QCamera.TorchMode | None = ..., whiteBalanceMode: QCamera.WhiteBalanceMode | None = ..., colorTemperature: int | None = ..., supportedFeatures: QCamera.Feature | None = ..., activeChanged: typing.Callable = ..., brightnessChanged: typing.Callable = ..., cameraDeviceChanged: typing.Callable = ..., cameraFormatChanged: typing.Callable = ..., colorTemperatureChanged: typing.Callable = ..., contrastChanged: typing.Callable = ..., customFocusPointChanged: typing.Callable = ..., destroyed: typing.Callable = ..., errorChanged: typing.Callable = ..., errorOccurred: typing.Callable = ..., exposureCompensationChanged: typing.Callable = ..., exposureModeChanged: typing.Callable = ..., exposureTimeChanged: typing.Callable = ..., flashModeChanged: typing.Callable = ..., focusDistanceChanged: typing.Callable = ..., focusModeChanged: typing.Callable = ..., focusPointChanged: typing.Callable = ..., hueChanged: typing.Callable = ..., isoSensitivityChanged: typing.Callable = ..., manualExposureTimeChanged: typing.Callable = ..., manualIsoSensitivityChanged: typing.Callable = ..., maximumZoomFactorChanged: typing.Callable = ..., minimumZoomFactorChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., saturationChanged: typing.Callable = ..., supportedFeaturesChanged: typing.Callable = ..., torchModeChanged: typing.Callable = ..., whiteBalanceModeChanged: typing.Callable = ..., zoomFactorChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, active: bool | None = ..., cameraDevice: QCameraDevice | None = ..., error: QCamera.Error | None = ..., errorString: str | None = ..., cameraFormat: QCameraFormat | None = ..., focusMode: QCamera.FocusMode | None = ..., focusPoint: PySide6.QtCore.QPointF | None = ..., customFocusPoint: PySide6.QtCore.QPointF | None = ..., focusDistance: float | None = ..., minimumZoomFactor: float | None = ..., maximumZoomFactor: float | None = ..., zoomFactor: float | None = ..., exposureTime: float | None = ..., manualExposureTime: float | None = ..., isoSensitivity: int | None = ..., manualIsoSensitivity: int | None = ..., exposureCompensation: float | None = ..., exposureMode: QCamera.ExposureMode | None = ..., flashReady: bool | None = ..., flashMode: QCamera.FlashMode | None = ..., torchMode: QCamera.TorchMode | None = ..., whiteBalanceMode: QCamera.WhiteBalanceMode | None = ..., colorTemperature: int | None = ..., supportedFeatures: QCamera.Feature | None = ..., activeChanged: typing.Callable = ..., brightnessChanged: typing.Callable = ..., cameraDeviceChanged: typing.Callable = ..., cameraFormatChanged: typing.Callable = ..., colorTemperatureChanged: typing.Callable = ..., contrastChanged: typing.Callable = ..., customFocusPointChanged: typing.Callable = ..., destroyed: typing.Callable = ..., errorChanged: typing.Callable = ..., errorOccurred: typing.Callable = ..., exposureCompensationChanged: typing.Callable = ..., exposureModeChanged: typing.Callable = ..., exposureTimeChanged: typing.Callable = ..., flashModeChanged: typing.Callable = ..., focusDistanceChanged: typing.Callable = ..., focusModeChanged: typing.Callable = ..., focusPointChanged: typing.Callable = ..., hueChanged: typing.Callable = ..., isoSensitivityChanged: typing.Callable = ..., manualExposureTimeChanged: typing.Callable = ..., manualIsoSensitivityChanged: typing.Callable = ..., maximumZoomFactorChanged: typing.Callable = ..., minimumZoomFactorChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., saturationChanged: typing.Callable = ..., supportedFeaturesChanged: typing.Callable = ..., torchModeChanged: typing.Callable = ..., whiteBalanceModeChanged: typing.Callable = ..., zoomFactorChanged: typing.Callable = ...) -> None: ...
    def cameraDevice(self, /) -> QCameraDevice: ...
    def cameraFormat(self, /) -> QCameraFormat: ...
    def captureSession(self, /) -> QMediaCaptureSession: ...
    def colorTemperature(self, /) -> int: ...
    def customFocusPoint(self, /) -> PySide6.QtCore.QPointF: ...
    def error(self, /) -> QCamera.Error: ...
    def errorString(self, /) -> str: ...
    def exposureCompensation(self, /) -> float: ...
    def exposureMode(self, /) -> QCamera.ExposureMode: ...
    def exposureTime(self, /) -> float: ...
    def flashMode(self, /) -> QCamera.FlashMode: ...
    def focusDistance(self, /) -> float: ...
    def focusMode(self, /) -> QCamera.FocusMode: ...
    def focusPoint(self, /) -> PySide6.QtCore.QPointF: ...
    def isActive(self, /) -> bool: ...
    def isAvailable(self, /) -> bool: ...
    def isExposureModeSupported(self, mode: QCamera.ExposureMode, /) -> bool: ...
    def isFlashModeSupported(self, mode: QCamera.FlashMode, /) -> bool: ...
    def isFlashReady(self, /) -> bool: ...
    def isFocusModeSupported(self, mode: QCamera.FocusMode, /) -> bool: ...
    def isTorchModeSupported(self, mode: QCamera.TorchMode, /) -> bool: ...
    def isWhiteBalanceModeSupported(self, mode: QCamera.WhiteBalanceMode, /) -> bool: ...
    def isoSensitivity(self, /) -> int: ...
    def manualExposureTime(self, /) -> float: ...
    def manualIsoSensitivity(self, /) -> int: ...
    def maximumExposureTime(self, /) -> float: ...
    def maximumIsoSensitivity(self, /) -> int: ...
    def maximumZoomFactor(self, /) -> float: ...
    def minimumExposureTime(self, /) -> float: ...
    def minimumIsoSensitivity(self, /) -> int: ...
    def minimumZoomFactor(self, /) -> float: ...
    def setActive(self, active: bool, /) -> None: ...
    def setAutoExposureTime(self, /) -> None: ...
    def setAutoIsoSensitivity(self, /) -> None: ...
    def setCameraDevice(self, cameraDevice: QCameraDevice, /) -> None: ...
    def setCameraFormat(self, format: QCameraFormat, /) -> None: ...
    def setColorTemperature(self, colorTemperature: int, /) -> None: ...
    def setCustomFocusPoint(self, point: PySide6.QtCore.QPointF | PySide6.QtCore.QPoint | PySide6.QtGui.QPainterPath.Element, /) -> None: ...
    def setExposureCompensation(self, ev: float, /) -> None: ...
    def setExposureMode(self, mode: QCamera.ExposureMode, /) -> None: ...
    def setFlashMode(self, mode: QCamera.FlashMode, /) -> None: ...
    def setFocusDistance(self, d: float, /) -> None: ...
    def setFocusMode(self, mode: QCamera.FocusMode, /) -> None: ...
    def setManualExposureTime(self, seconds: float, /) -> None: ...
    def setManualIsoSensitivity(self, iso: int, /) -> None: ...
    def setTorchMode(self, mode: QCamera.TorchMode, /) -> None: ...
    def setWhiteBalanceMode(self, mode: QCamera.WhiteBalanceMode, /) -> None: ...
    def setZoomFactor(self, factor: float, /) -> None: ...
    def start(self, /) -> None: ...
    def stop(self, /) -> None: ...
    def supportedFeatures(self, /) -> QCamera.Feature: ...
    def torchMode(self, /) -> QCamera.TorchMode: ...
    def whiteBalanceMode(self, /) -> QCamera.WhiteBalanceMode: ...
    def zoomFactor(self, /) -> float: ...
    def zoomTo(self, zoom: float, rate: float, /) -> None: ...

class QCameraDevice(shiboken6.Object):
    class Position(enum.Enum):
        BackFace = 1
        FrontFace = 2
        UnspecifiedPosition = 0
    @typing.overload
    def __init__(self, other: QCameraDevice, /, *, id: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview | None = ..., description: str | None = ..., isDefault: bool | None = ..., position: QCameraDevice.Position | None = ..., videoFormats: typing.Iterable[QCameraFormat] | None = ..., correctionAngle: QtVideo.Rotation | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, id: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview | None = ..., description: str | None = ..., isDefault: bool | None = ..., position: QCameraDevice.Position | None = ..., videoFormats: typing.Iterable[QCameraFormat] | None = ..., correctionAngle: QtVideo.Rotation | None = ...) -> None: ...
    def correctionAngle(self, /) -> QtVideo.Rotation: ...
    def description(self, /) -> str: ...
    def id(self, /) -> PySide6.QtCore.QByteArray: ...
    def isDefault(self, /) -> bool: ...
    def isNull(self, /) -> bool: ...
    def photoResolutions(self, /) -> List[PySide6.QtCore.QSize]: ...
    def position(self, /) -> QCameraDevice.Position: ...
    def videoFormats(self, /) -> List[QCameraFormat]: ...
    def __bool__(self) -> bool: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QCameraFormat(shiboken6.Object):
    @typing.overload
    def __init__(self, other: QCameraFormat, /, *, resolution: PySide6.QtCore.QSize | None = ..., pixelFormat: QVideoFrameFormat.PixelFormat | None = ..., minFrameRate: float | None = ..., maxFrameRate: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, resolution: PySide6.QtCore.QSize | None = ..., pixelFormat: QVideoFrameFormat.PixelFormat | None = ..., minFrameRate: float | None = ..., maxFrameRate: float | None = ...) -> None: ...
    def isNull(self, /) -> bool: ...
    def maxFrameRate(self, /) -> float: ...
    def minFrameRate(self, /) -> float: ...
    def pixelFormat(self, /) -> QVideoFrameFormat.PixelFormat: ...
    def resolution(self, /) -> PySide6.QtCore.QSize: ...
    def __bool__(self) -> bool: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QCapturableWindow(shiboken6.Object):
    @typing.overload
    def __init__(self, window: PySide6.QtGui.QWindow, /, *, description: str | None = ..., isValid: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, other: QCapturableWindow, /, *, description: str | None = ..., isValid: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, description: str | None = ..., isValid: bool | None = ...) -> None: ...
    def description(self, /) -> str: ...
    def isValid(self, /) -> bool: ...
    def swap(self, other: QCapturableWindow, /) -> None: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QImageCapture(PySide6.QtCore.QObject):
    class Error(enum.Enum):
        FormatError = 5
        NoError = 0
        NotReadyError = 1
        NotSupportedFeatureError = 4
        OutOfSpaceError = 3
        ResourceError = 2

    class FileFormat(enum.Enum):
        JPEG = 1
        LastFileFormat = 4
        PNG = 2
        Tiff = 4
        UnspecifiedFormat = 0
        WebP = 3

    class Quality(enum.Enum):
        HighQuality = 3
        LowQuality = 1
        NormalQuality = 2
        VeryHighQuality = 4
        VeryLowQuality = 0
    errorChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorOccurred: typing.ClassVar[PySide6.QtCore.Signal] = ...
    fileFormatChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    imageAvailable: typing.ClassVar[PySide6.QtCore.Signal] = ...
    imageCaptured: typing.ClassVar[PySide6.QtCore.Signal] = ...
    imageExposed: typing.ClassVar[PySide6.QtCore.Signal] = ...
    imageMetadataAvailable: typing.ClassVar[PySide6.QtCore.Signal] = ...
    imageSaved: typing.ClassVar[PySide6.QtCore.Signal] = ...
    metaDataChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    qualityChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    readyForCaptureChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    resolutionChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, readyForCapture: bool | None = ..., metaData: QMediaMetaData | None = ..., error: QImageCapture.Error | None = ..., errorString: str | None = ..., fileFormat: QImageCapture.FileFormat | None = ..., quality: QImageCapture.Quality | None = ..., supportedFormats: typing.Iterable[QImageCapture.FileFormat] | None = ..., destroyed: typing.Callable = ..., errorChanged: typing.Callable = ..., errorOccurred: typing.Callable = ..., fileFormatChanged: typing.Callable = ..., imageAvailable: typing.Callable = ..., imageCaptured: typing.Callable = ..., imageExposed: typing.Callable = ..., imageMetadataAvailable: typing.Callable = ..., imageSaved: typing.Callable = ..., metaDataChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., qualityChanged: typing.Callable = ..., readyForCaptureChanged: typing.Callable = ..., resolutionChanged: typing.Callable = ...) -> None: ...
    def addMetaData(self, metaData: QMediaMetaData, /) -> None: ...
    def capture(self, /) -> int: ...
    def captureSession(self, /) -> QMediaCaptureSession: ...
    def captureToFile(self, /, location: str = ...) -> int: ...
    def error(self, /) -> QImageCapture.Error: ...
    def errorString(self, /) -> str: ...
    def fileFormat(self, /) -> QImageCapture.FileFormat: ...
    @staticmethod
    def fileFormatDescription(c: QImageCapture.FileFormat, /) -> str: ...
    @staticmethod
    def fileFormatName(c: QImageCapture.FileFormat, /) -> str: ...
    def isAvailable(self, /) -> bool: ...
    def isReadyForCapture(self, /) -> bool: ...
    def metaData(self, /) -> QMediaMetaData: ...
    def quality(self, /) -> QImageCapture.Quality: ...
    def resolution(self, /) -> PySide6.QtCore.QSize: ...
    def setFileFormat(self, format: QImageCapture.FileFormat, /) -> None: ...
    def setMetaData(self, metaData: QMediaMetaData, /) -> None: ...
    def setQuality(self, quality: QImageCapture.Quality, /) -> None: ...
    @typing.overload
    def setResolution(self, width: int, height: int, /) -> None: ...
    @typing.overload
    def setResolution(self, arg__1: PySide6.QtCore.QSize, /) -> None: ...
    @staticmethod
    def supportedFormats() -> List[QImageCapture.FileFormat]: ...

class QIntList:
    __opaque_container__: typing.ClassVar[bool] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs): ...
    def capacity(self, *args, **kwargs): ...
    def clear(self, *args, **kwargs): ...
    def constData(self, *args, **kwargs): ...
    def data(self, *args, **kwargs): ...
    def pop_back(self, *args, **kwargs): ...
    def pop_front(self, *args, **kwargs): ...
    def prepend(self, *args, **kwargs): ...
    def push_back(self, *args, **kwargs): ...
    def push_front(self, *args, **kwargs): ...
    def removeFirst(self, *args, **kwargs): ...
    def removeLast(self, *args, **kwargs): ...
    def reserve(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, object) -> None: ...

class QMediaCaptureSession(PySide6.QtCore.QObject):
    audioBufferInputChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    audioInputChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    audioOutputChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    cameraChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    imageCaptureChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    recorderChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    screenCaptureChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    videoFrameInputChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    videoOutputChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    windowCaptureChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, audioInput: QAudioInput | None = ..., audioBufferInput: QAudioBufferInput | None = ..., audioOutput: QAudioOutput | None = ..., camera: QCamera | None = ..., screenCapture: QScreenCapture | None = ..., windowCapture: QWindowCapture | None = ..., videoFrameInput: QVideoFrameInput | None = ..., imageCapture: QImageCapture | None = ..., recorder: QMediaRecorder | None = ..., videoOutput: PySide6.QtCore.QObject | None = ..., audioBufferInputChanged: typing.Callable = ..., audioInputChanged: typing.Callable = ..., audioOutputChanged: typing.Callable = ..., cameraChanged: typing.Callable = ..., destroyed: typing.Callable = ..., imageCaptureChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., recorderChanged: typing.Callable = ..., screenCaptureChanged: typing.Callable = ..., videoFrameInputChanged: typing.Callable = ..., videoOutputChanged: typing.Callable = ..., windowCaptureChanged: typing.Callable = ...) -> None: ...
    def audioBufferInput(self, /) -> QAudioBufferInput: ...
    def audioInput(self, /) -> QAudioInput: ...
    def audioOutput(self, /) -> QAudioOutput: ...
    def camera(self, /) -> QCamera: ...
    def imageCapture(self, /) -> QImageCapture: ...
    def recorder(self, /) -> QMediaRecorder: ...
    def screenCapture(self, /) -> QScreenCapture: ...
    def setAudioBufferInput(self, input: QAudioBufferInput, /) -> None: ...
    def setAudioInput(self, input: QAudioInput, /) -> None: ...
    def setAudioOutput(self, output: QAudioOutput, /) -> None: ...
    def setCamera(self, camera: QCamera, /) -> None: ...
    def setImageCapture(self, imageCapture: QImageCapture, /) -> None: ...
    def setRecorder(self, recorder: QMediaRecorder, /) -> None: ...
    def setScreenCapture(self, screenCapture: QScreenCapture, /) -> None: ...
    def setVideoFrameInput(self, input: QVideoFrameInput, /) -> None: ...
    def setVideoOutput(self, output: PySide6.QtCore.QObject, /) -> None: ...
    def setVideoSink(self, sink: QVideoSink, /) -> None: ...
    def setWindowCapture(self, windowCapture: QWindowCapture, /) -> None: ...
    def videoFrameInput(self, /) -> QVideoFrameInput: ...
    def videoOutput(self, /) -> PySide6.QtCore.QObject: ...
    def videoSink(self, /) -> QVideoSink: ...
    def windowCapture(self, /) -> QWindowCapture: ...

class QMediaDevices(PySide6.QtCore.QObject):
    audioInputsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    audioOutputsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    videoInputsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, audioInputs: typing.Iterable[QAudioDevice] | None = ..., audioOutputs: typing.Iterable[QAudioDevice] | None = ..., videoInputs: typing.Iterable[QCameraDevice] | None = ..., defaultAudioInput: QAudioDevice | None = ..., defaultAudioOutput: QAudioDevice | None = ..., defaultVideoInput: QCameraDevice | None = ..., audioInputsChanged: typing.Callable = ..., audioOutputsChanged: typing.Callable = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., videoInputsChanged: typing.Callable = ...) -> None: ...
    @staticmethod
    def audioInputs() -> List[QAudioDevice]: ...
    @staticmethod
    def audioOutputs() -> List[QAudioDevice]: ...
    def connectNotify(self, signal: PySide6.QtCore.QMetaMethod, /) -> None: ...
    @staticmethod
    def defaultAudioInput() -> QAudioDevice: ...
    @staticmethod
    def defaultAudioOutput() -> QAudioDevice: ...
    @staticmethod
    def defaultVideoInput() -> QCameraDevice: ...
    @staticmethod
    def videoInputs() -> List[QCameraDevice]: ...

class QMediaFormat(shiboken6.Object):
    class AudioCodec(enum.Enum):
        AAC = 1
        AC3 = 2
        ALAC = 10
        DolbyTrueHD = 5
        EAC3 = 3
        FLAC = 4
        LastAudioCodec = 10
        MP3 = 0
        Opus = 6
        Unspecified = -1
        Vorbis = 7
        WMA = 9
        Wave = 8

    class ConversionMode(enum.Enum):
        Decode = 1
        Encode = 0

    class FileFormat(enum.Enum):
        AAC = 8
        AVI = 1
        FLAC = 11
        LastFileFormat = 12
        MP3 = 10
        MPEG4 = 3
        Matroska = 2
        Mpeg4Audio = 7
        Ogg = 4
        QuickTime = 5
        UnspecifiedFormat = -1
        WMA = 9
        WMV = 0
        Wave = 12
        WebM = 6

    class ResolveFlags(enum.Enum):
        NoFlags = 0
        RequiresVideo = 1

    class VideoCodec(enum.Enum):
        AV1 = 7
        H264 = 3
        H265 = 4
        LastVideoCodec = 10
        MPEG1 = 0
        MPEG2 = 1
        MPEG4 = 2
        MotionJPEG = 10
        Theora = 8
        Unspecified = -1
        VP8 = 5
        VP9 = 6
        WMV = 9
    audio: _typeshed.Incomplete
    fmt: _typeshed.Incomplete
    video: _typeshed.Incomplete
    @typing.overload
    def __init__(self, other: QMediaFormat, /, *, fileFormat: QMediaFormat.FileFormat | None = ..., audioCodec: QMediaFormat.AudioCodec | None = ..., videoCodec: QMediaFormat.VideoCodec | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, format: QMediaFormat.FileFormat = ..., *, fileFormat: QMediaFormat.FileFormat | None = ..., audioCodec: QMediaFormat.AudioCodec | None = ..., videoCodec: QMediaFormat.VideoCodec | None = ...) -> None: ...
    def audioCodec(self, /) -> QMediaFormat.AudioCodec: ...
    @staticmethod
    def audioCodecDescription(codec: QMediaFormat.AudioCodec, /) -> str: ...
    @staticmethod
    def audioCodecName(codec: QMediaFormat.AudioCodec, /) -> str: ...
    def fileFormat(self, /) -> QMediaFormat.FileFormat: ...
    @staticmethod
    def fileFormatDescription(fileFormat: QMediaFormat.FileFormat, /) -> str: ...
    @staticmethod
    def fileFormatName(fileFormat: QMediaFormat.FileFormat, /) -> str: ...
    def isSupported(self, mode: QMediaFormat.ConversionMode, /) -> bool: ...
    def mimeType(self, /) -> PySide6.QtCore.QMimeType: ...
    def resolveForEncoding(self, flags: QMediaFormat.ResolveFlags, /) -> None: ...
    def setAudioCodec(self, codec: QMediaFormat.AudioCodec, /) -> None: ...
    def setFileFormat(self, f: QMediaFormat.FileFormat, /) -> None: ...
    def setVideoCodec(self, codec: QMediaFormat.VideoCodec, /) -> None: ...
    def supportedAudioCodecs(self, m: QMediaFormat.ConversionMode, /) -> List[QMediaFormat.AudioCodec]: ...
    def supportedFileFormats(self, m: QMediaFormat.ConversionMode, /) -> List[QMediaFormat.FileFormat]: ...
    def supportedVideoCodecs(self, m: QMediaFormat.ConversionMode, /) -> List[QMediaFormat.VideoCodec]: ...
    def swap(self, other: QMediaFormat | QMediaFormat.FileFormat, /) -> None: ...
    def videoCodec(self, /) -> QMediaFormat.VideoCodec: ...
    @staticmethod
    def videoCodecDescription(codec: QMediaFormat.VideoCodec, /) -> str: ...
    @staticmethod
    def videoCodecName(codec: QMediaFormat.VideoCodec, /) -> str: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QMediaMetaData(shiboken6.Object):
    class Key(enum.Enum):
        AlbumArtist = 19
        AlbumTitle = 18
        AudioBitRate = 13
        AudioCodec = 14
        Author = 1
        Comment = 2
        Composer = 22
        ContributingArtist = 20
        Copyright = 8
        CoverArtImage = 25
        Date = 5
        Description = 3
        Duration = 10
        FileFormat = 12
        Genre = 4
        HasHdrContent = 28
        Language = 6
        LeadPerformer = 23
        MediaType = 11
        Orientation = 26
        Publisher = 7
        Resolution = 27
        ThumbnailImage = 24
        Title = 0
        TrackNumber = 21
        Url = 9
        VideoBitRate = 15
        VideoCodec = 16
        VideoFrameRate = 17
    NumMetaData: typing.ClassVar[int] = ...
    data: _typeshed.Incomplete
    @typing.overload
    def __init__(self, QMediaMetaData: QMediaMetaData, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def clear(self, /) -> None: ...
    def insert(self, k: QMediaMetaData.Key, value: Any, /) -> None: ...
    def isEmpty(self, /) -> bool: ...
    @staticmethod
    def keyType(key: QMediaMetaData.Key, /) -> PySide6.QtCore.QMetaType: ...
    def keys(self, /) -> List[QMediaMetaData.Key]: ...
    @staticmethod
    def metaDataKeyToString(k: QMediaMetaData.Key, /) -> str: ...
    def remove(self, k: QMediaMetaData.Key, /) -> None: ...
    def stringValue(self, k: QMediaMetaData.Key, /) -> str: ...
    def value(self, k: QMediaMetaData.Key, /) -> Any: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QMediaPlayer(PySide6.QtCore.QObject):
    class Error(enum.Enum):
        AccessDeniedError = 4
        FormatError = 2
        NetworkError = 3
        NoError = 0
        ResourceError = 1

    class Loops(enum.IntEnum):
        Infinite = -1
        Once = 1

    class MediaStatus(enum.Enum):
        BufferedMedia = 5
        BufferingMedia = 4
        EndOfMedia = 6
        InvalidMedia = 7
        LoadedMedia = 2
        LoadingMedia = 1
        NoMedia = 0
        StalledMedia = 3

    class PitchCompensationAvailability(enum.Enum):
        AlwaysOn = 0
        Available = 1
        Unavailable = 2

    class PlaybackState(enum.Enum):
        PausedState = 2
        PlayingState = 1
        StoppedState = 0
    activeTracksChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    audioBufferOutputChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    audioOutputChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    bufferProgressChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    durationChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorOccurred: typing.ClassVar[PySide6.QtCore.Signal] = ...
    hasAudioChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    hasVideoChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    loopsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    mediaStatusChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    metaDataChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    pitchCompensationChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    playbackOptionsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    playbackRateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    playbackStateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    playingChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    positionChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    seekableChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sourceChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    tracksChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    videoOutputChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, source: PySide6.QtCore.QUrl | None = ..., duration: int | None = ..., position: int | None = ..., bufferProgress: float | None = ..., hasAudio: bool | None = ..., hasVideo: bool | None = ..., seekable: bool | None = ..., playing: bool | None = ..., playbackRate: float | None = ..., loops: int | None = ..., playbackState: QMediaPlayer.PlaybackState | None = ..., mediaStatus: QMediaPlayer.MediaStatus | None = ..., metaData: QMediaMetaData | None = ..., error: QMediaPlayer.Error | None = ..., errorString: str | None = ..., videoOutput: PySide6.QtCore.QObject | None = ..., audioOutput: QAudioOutput | None = ..., audioBufferOutput: QAudioBufferOutput | None = ..., audioTracks: typing.Iterable[QMediaMetaData] | None = ..., videoTracks: typing.Iterable[QMediaMetaData] | None = ..., subtitleTracks: typing.Iterable[QMediaMetaData] | None = ..., activeAudioTrack: int | None = ..., activeVideoTrack: int | None = ..., activeSubtitleTrack: int | None = ..., pitchCompensationAvailability: QMediaPlayer.PitchCompensationAvailability | None = ..., pitchCompensation: bool | None = ..., playbackOptions: QPlaybackOptions | None = ..., activeTracksChanged: typing.Callable = ..., audioBufferOutputChanged: typing.Callable = ..., audioOutputChanged: typing.Callable = ..., bufferProgressChanged: typing.Callable = ..., destroyed: typing.Callable = ..., durationChanged: typing.Callable = ..., errorChanged: typing.Callable = ..., errorOccurred: typing.Callable = ..., hasAudioChanged: typing.Callable = ..., hasVideoChanged: typing.Callable = ..., loopsChanged: typing.Callable = ..., mediaStatusChanged: typing.Callable = ..., metaDataChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., pitchCompensationChanged: typing.Callable = ..., playbackOptionsChanged: typing.Callable = ..., playbackRateChanged: typing.Callable = ..., playbackStateChanged: typing.Callable = ..., playingChanged: typing.Callable = ..., positionChanged: typing.Callable = ..., seekableChanged: typing.Callable = ..., sourceChanged: typing.Callable = ..., tracksChanged: typing.Callable = ..., videoOutputChanged: typing.Callable = ...) -> None: ...
    def activeAudioTrack(self, /) -> int: ...
    def activeSubtitleTrack(self, /) -> int: ...
    def activeVideoTrack(self, /) -> int: ...
    def audioBufferOutput(self, /) -> QAudioBufferOutput: ...
    def audioOutput(self, /) -> QAudioOutput: ...
    def audioTracks(self, /) -> List[QMediaMetaData]: ...
    def bufferProgress(self, /) -> float: ...
    def bufferedTimeRange(self, /) -> QMediaTimeRange: ...
    def duration(self, /) -> int: ...
    def error(self, /) -> QMediaPlayer.Error: ...
    def errorString(self, /) -> str: ...
    def hasAudio(self, /) -> bool: ...
    def hasVideo(self, /) -> bool: ...
    def isAvailable(self, /) -> bool: ...
    def isPlaying(self, /) -> bool: ...
    def isSeekable(self, /) -> bool: ...
    def loops(self, /) -> int: ...
    def mediaStatus(self, /) -> QMediaPlayer.MediaStatus: ...
    def metaData(self, /) -> QMediaMetaData: ...
    def pause(self, /) -> None: ...
    def pitchCompensation(self, /) -> bool: ...
    def pitchCompensationAvailability(self, /) -> QMediaPlayer.PitchCompensationAvailability: ...
    def play(self, /) -> None: ...
    def playbackOptions(self, /) -> QPlaybackOptions: ...
    def playbackRate(self, /) -> float: ...
    def playbackState(self, /) -> QMediaPlayer.PlaybackState: ...
    def position(self, /) -> int: ...
    def resetPlaybackOptions(self, /) -> None: ...
    def setActiveAudioTrack(self, index: int, /) -> None: ...
    def setActiveSubtitleTrack(self, index: int, /) -> None: ...
    def setActiveVideoTrack(self, index: int, /) -> None: ...
    def setAudioBufferOutput(self, output: QAudioBufferOutput, /) -> None: ...
    def setAudioOutput(self, output: QAudioOutput, /) -> None: ...
    def setLoops(self, loops: int, /) -> None: ...
    def setPitchCompensation(self, arg__1: bool, /) -> None: ...
    def setPlaybackOptions(self, options: QPlaybackOptions, /) -> None: ...
    def setPlaybackRate(self, rate: float, /) -> None: ...
    def setPosition(self, position: int, /) -> None: ...
    def setSource(self, source: PySide6.QtCore.QUrl | str, /) -> None: ...
    def setSourceDevice(self, device: PySide6.QtCore.QIODevice, /, sourceUrl: PySide6.QtCore.QUrl | str = ...) -> None: ...
    def setVideoOutput(self, arg__1: PySide6.QtCore.QObject, /) -> None: ...
    def setVideoSink(self, sink: QVideoSink, /) -> None: ...
    def source(self, /) -> PySide6.QtCore.QUrl: ...
    def sourceDevice(self, /) -> PySide6.QtCore.QIODevice: ...
    def stop(self, /) -> None: ...
    def subtitleTracks(self, /) -> List[QMediaMetaData]: ...
    def videoOutput(self, /) -> PySide6.QtCore.QObject: ...
    def videoSink(self, /) -> QVideoSink: ...
    def videoTracks(self, /) -> List[QMediaMetaData]: ...

class QMediaRecorder(PySide6.QtCore.QObject):
    class EncodingMode(enum.Enum):
        AverageBitRateEncoding = 2
        ConstantBitRateEncoding = 1
        ConstantQualityEncoding = 0
        TwoPassEncoding = 3

    class Error(enum.Enum):
        FormatError = 2
        LocationNotWritable = 4
        NoError = 0
        OutOfSpaceError = 3
        ResourceError = 1

    class Quality(enum.Enum):
        HighQuality = 3
        LowQuality = 1
        NormalQuality = 2
        VeryHighQuality = 4
        VeryLowQuality = 0

    class RecorderState(enum.Enum):
        PausedState = 2
        RecordingState = 1
        StoppedState = 0
    actualLocationChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    audioBitRateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    audioChannelCountChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    audioSampleRateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    autoStopChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    durationChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    encoderSettingsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    encodingModeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorOccurred: typing.ClassVar[PySide6.QtCore.Signal] = ...
    mediaFormatChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    metaDataChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    qualityChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    recorderStateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    videoBitRateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    videoFrameRateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    videoResolutionChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, recorderState: QMediaRecorder.RecorderState | None = ..., duration: int | None = ..., outputLocation: PySide6.QtCore.QUrl | None = ..., actualLocation: PySide6.QtCore.QUrl | None = ..., metaData: QMediaMetaData | None = ..., error: QMediaRecorder.Error | None = ..., errorString: str | None = ..., mediaFormat: QMediaFormat | None = ..., quality: QMediaRecorder.Quality | None = ..., encodingMode: QMediaRecorder.EncodingMode | None = ..., videoResolution: PySide6.QtCore.QSize | None = ..., videoFrameRate: float | None = ..., videoBitRate: int | None = ..., audioBitRate: int | None = ..., audioChannelCount: int | None = ..., audioSampleRate: int | None = ..., autoStop: bool | None = ..., actualLocationChanged: typing.Callable = ..., audioBitRateChanged: typing.Callable = ..., audioChannelCountChanged: typing.Callable = ..., audioSampleRateChanged: typing.Callable = ..., autoStopChanged: typing.Callable = ..., destroyed: typing.Callable = ..., durationChanged: typing.Callable = ..., encoderSettingsChanged: typing.Callable = ..., encodingModeChanged: typing.Callable = ..., errorChanged: typing.Callable = ..., errorOccurred: typing.Callable = ..., mediaFormatChanged: typing.Callable = ..., metaDataChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., qualityChanged: typing.Callable = ..., recorderStateChanged: typing.Callable = ..., videoBitRateChanged: typing.Callable = ..., videoFrameRateChanged: typing.Callable = ..., videoResolutionChanged: typing.Callable = ...) -> None: ...
    def actualLocation(self, /) -> PySide6.QtCore.QUrl: ...
    def addMetaData(self, metaData: QMediaMetaData, /) -> None: ...
    def audioBitRate(self, /) -> int: ...
    def audioChannelCount(self, /) -> int: ...
    def audioSampleRate(self, /) -> int: ...
    def autoStop(self, /) -> bool: ...
    def captureSession(self, /) -> QMediaCaptureSession: ...
    def duration(self, /) -> int: ...
    def encodingMode(self, /) -> QMediaRecorder.EncodingMode: ...
    def error(self, /) -> QMediaRecorder.Error: ...
    def errorString(self, /) -> str: ...
    def isAvailable(self, /) -> bool: ...
    def mediaFormat(self, /) -> QMediaFormat: ...
    def metaData(self, /) -> QMediaMetaData: ...
    def outputDevice(self, /) -> PySide6.QtCore.QIODevice: ...
    def outputLocation(self, /) -> PySide6.QtCore.QUrl: ...
    def pause(self, /) -> None: ...
    def quality(self, /) -> QMediaRecorder.Quality: ...
    def record(self, /) -> None: ...
    def recorderState(self, /) -> QMediaRecorder.RecorderState: ...
    def setAudioBitRate(self, bitRate: int, /) -> None: ...
    def setAudioChannelCount(self, channels: int, /) -> None: ...
    def setAudioSampleRate(self, sampleRate: int, /) -> None: ...
    def setAutoStop(self, autoStop: bool, /) -> None: ...
    def setEncodingMode(self, arg__1: QMediaRecorder.EncodingMode, /) -> None: ...
    def setMediaFormat(self, format: QMediaFormat | QMediaFormat.FileFormat, /) -> None: ...
    def setMetaData(self, metaData: QMediaMetaData, /) -> None: ...
    def setOutputDevice(self, device: PySide6.QtCore.QIODevice, /) -> None: ...
    def setOutputLocation(self, location: PySide6.QtCore.QUrl | str, /) -> None: ...
    def setQuality(self, quality: QMediaRecorder.Quality, /) -> None: ...
    def setVideoBitRate(self, bitRate: int, /) -> None: ...
    def setVideoFrameRate(self, frameRate: float, /) -> None: ...
    @typing.overload
    def setVideoResolution(self, width: int, height: int, /) -> None: ...
    @typing.overload
    def setVideoResolution(self, arg__1: PySide6.QtCore.QSize, /) -> None: ...
    def stop(self, /) -> None: ...
    def videoBitRate(self, /) -> int: ...
    def videoFrameRate(self, /) -> float: ...
    def videoResolution(self, /) -> PySide6.QtCore.QSize: ...

class QMediaTimeRange(shiboken6.Object):
    class Interval(shiboken6.Object):
        @typing.overload
        def __init__(self, start: int, end: int, /) -> None: ...
        @typing.overload
        def __init__(self, Interval: QMediaTimeRange.Interval, /) -> None: ...
        @typing.overload
        def __init__(self, /) -> None: ...
        def contains(self, time: int, /) -> bool: ...
        def end(self, /) -> int: ...
        def isNormal(self, /) -> bool: ...
        def normalized(self, /) -> QMediaTimeRange.Interval: ...
        def start(self, /) -> int: ...
        def translated(self, offset: int, /) -> QMediaTimeRange.Interval: ...
        def __copy__(self, /) -> typing_extensions.Self: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
    @typing.overload
    def __init__(self, start: int, end: int, /) -> None: ...
    @typing.overload
    def __init__(self, range: QMediaTimeRange, /) -> None: ...
    @typing.overload
    def __init__(self, arg__1: QMediaTimeRange.Interval, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def addInterval(self, start: int, end: int, /) -> None: ...
    @typing.overload
    def addInterval(self, interval: QMediaTimeRange.Interval, /) -> None: ...
    def addTimeRange(self, arg__1: QMediaTimeRange | QMediaTimeRange.Interval, /) -> None: ...
    def clear(self, /) -> None: ...
    def contains(self, time: int, /) -> bool: ...
    def earliestTime(self, /) -> int: ...
    def intervals(self, /) -> List[QMediaTimeRange.Interval]: ...
    def isContinuous(self, /) -> bool: ...
    def isEmpty(self, /) -> bool: ...
    def latestTime(self, /) -> int: ...
    @typing.overload
    def removeInterval(self, start: int, end: int, /) -> None: ...
    @typing.overload
    def removeInterval(self, interval: QMediaTimeRange.Interval, /) -> None: ...
    def removeTimeRange(self, arg__1: QMediaTimeRange | QMediaTimeRange.Interval, /) -> None: ...
    def swap(self, other: QMediaTimeRange | QMediaTimeRange.Interval, /) -> None: ...
    def __add__(self, r2: QMediaTimeRange | QMediaTimeRange.Interval, /) -> QMediaTimeRange: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    @typing.overload  # type: ignore[misc]
    def __iadd__(self, arg__1: QMediaTimeRange.Interval, /) -> QMediaTimeRange: ...
    @typing.overload
    def __iadd__(self, arg__1: QMediaTimeRange | QMediaTimeRange.Interval, /) -> QMediaTimeRange: ...
    @typing.overload  # type: ignore[misc]
    def __isub__(self, arg__1: QMediaTimeRange.Interval, /) -> QMediaTimeRange: ...
    @typing.overload
    def __isub__(self, arg__1: QMediaTimeRange | QMediaTimeRange.Interval, /) -> QMediaTimeRange: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __radd__(self, other): ...
    def __rsub__(self, other): ...
    def __sub__(self, r2: QMediaTimeRange | QMediaTimeRange.Interval, /) -> QMediaTimeRange: ...

class QPlaybackOptions(shiboken6.Object):
    class PlaybackIntent(enum.Enum):
        LowLatencyStreaming = 1
        Playback = 0
    @typing.overload
    def __init__(self, arg__1: QPlaybackOptions, /, *, networkTimeout: int | None = ..., playbackIntent: QPlaybackOptions.PlaybackIntent | None = ..., probeSize: int | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, networkTimeout: int | None = ..., playbackIntent: QPlaybackOptions.PlaybackIntent | None = ..., probeSize: int | None = ...) -> None: ...
    def networkTimeout(self, /) -> int: ...
    def playbackIntent(self, /) -> QPlaybackOptions.PlaybackIntent: ...
    def probeSize(self, /) -> int: ...
    def resetNetworkTimeout(self, /) -> None: ...
    def resetPlaybackIntent(self, /) -> None: ...
    def resetProbeSize(self, /) -> None: ...
    def setNetworkTimeout(self, timeout: int, /) -> None: ...
    def setPlaybackIntent(self, intent: QPlaybackOptions.PlaybackIntent, /) -> None: ...
    def setProbeSize(self, probeSizeBytes: int, /) -> None: ...
    def swap(self, other: QPlaybackOptions, /) -> None: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QScreenCapture(PySide6.QtCore.QObject):
    class Error(enum.Enum):
        CaptureFailed = 4
        CapturingNotSupported = 2
        InternalError = 1
        NoError = 0
        NotFound = 5
    activeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorOccurred: typing.ClassVar[PySide6.QtCore.Signal] = ...
    screenChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, active: bool | None = ..., screen: PySide6.QtGui.QScreen | None = ..., error: QScreenCapture.Error | None = ..., errorString: str | None = ..., activeChanged: typing.Callable = ..., destroyed: typing.Callable = ..., errorChanged: typing.Callable = ..., errorOccurred: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., screenChanged: typing.Callable = ...) -> None: ...
    def captureSession(self, /) -> QMediaCaptureSession: ...
    def error(self, /) -> QScreenCapture.Error: ...
    def errorString(self, /) -> str: ...
    def isActive(self, /) -> bool: ...
    def screen(self, /) -> PySide6.QtGui.QScreen: ...
    def setActive(self, active: bool, /) -> None: ...
    def setScreen(self, screen: PySide6.QtGui.QScreen, /) -> None: ...
    def start(self, /) -> None: ...
    def stop(self, /) -> None: ...

class QSoundEffect(PySide6.QtCore.QObject):
    class Loop(enum.Enum):
        Infinite = -2

    class Status(enum.Enum):
        Error = 3
        Loading = 1
        Null = 0
        Ready = 2
    audioDeviceChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    loadedChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    loopCountChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    loopsRemainingChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    mutedChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    playingChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sourceChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    statusChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    volumeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    @typing.overload
    def __init__(self, audioDevice: QAudioDevice, /, parent: PySide6.QtCore.QObject | None = ..., *, source: PySide6.QtCore.QUrl | None = ..., loops: int | None = ..., loopsRemaining: int | None = ..., volume: float | None = ..., muted: bool | None = ..., playing: bool | None = ..., status: QSoundEffect.Status | None = ..., audioDeviceChanged: typing.Callable = ..., destroyed: typing.Callable = ..., loadedChanged: typing.Callable = ..., loopCountChanged: typing.Callable = ..., loopsRemainingChanged: typing.Callable = ..., mutedChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., playingChanged: typing.Callable = ..., sourceChanged: typing.Callable = ..., statusChanged: typing.Callable = ..., volumeChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, source: PySide6.QtCore.QUrl | None = ..., loops: int | None = ..., loopsRemaining: int | None = ..., volume: float | None = ..., muted: bool | None = ..., playing: bool | None = ..., status: QSoundEffect.Status | None = ..., audioDevice: QAudioDevice | None = ..., audioDeviceChanged: typing.Callable = ..., destroyed: typing.Callable = ..., loadedChanged: typing.Callable = ..., loopCountChanged: typing.Callable = ..., loopsRemainingChanged: typing.Callable = ..., mutedChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., playingChanged: typing.Callable = ..., sourceChanged: typing.Callable = ..., statusChanged: typing.Callable = ..., volumeChanged: typing.Callable = ...) -> None: ...
    def audioDevice(self, /) -> QAudioDevice: ...
    def isLoaded(self, /) -> bool: ...
    def isMuted(self, /) -> bool: ...
    def isPlaying(self, /) -> bool: ...
    def loopCount(self, /) -> int: ...
    def loopsRemaining(self, /) -> int: ...
    def play(self, /) -> None: ...
    def setAudioDevice(self, device: QAudioDevice, /) -> None: ...
    def setLoopCount(self, loopCount: int, /) -> None: ...
    def setMuted(self, muted: bool, /) -> None: ...
    def setSource(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def setVolume(self, volume: float, /) -> None: ...
    def source(self, /) -> PySide6.QtCore.QUrl: ...
    def status(self, /) -> QSoundEffect.Status: ...
    def stop(self, /) -> None: ...
    @staticmethod
    def supportedMimeTypes() -> List[str]: ...
    def volume(self, /) -> float: ...

class QVideoFrame(shiboken6.Object):
    class HandleType(enum.Enum):
        NoHandle = 0
        RhiTextureHandle = 1

    class MapMode(enum.Enum):
        NotMapped = 0
        ReadOnly = 1
        ReadWrite = 3
        WriteOnly = 2

    class PaintOptions(shiboken6.Object):
        class PaintFlag(enum.Flag):
            DontDrawSubtitles = 1
        aspectRatioMode: _typeshed.Incomplete
        backgroundColor: _typeshed.Incomplete
        paintFlags: _typeshed.Incomplete
        @typing.overload
        def __init__(self, PaintOptions: QVideoFrame.PaintOptions, /) -> None: ...
        @typing.overload
        def __init__(self, /) -> None: ...
        def __copy__(self, /) -> typing_extensions.Self: ...

    class RotationAngle(enum.Enum):
        Rotation0 = 0
        Rotation180 = 180
        Rotation270 = 270
        Rotation90 = 90
    @typing.overload
    def __init__(self, buffer: QAbstractVideoBuffer, format: QVideoFrameFormat, /) -> None: ...
    @typing.overload
    def __init__(self, other: QVideoFrame, /) -> None: ...
    @typing.overload
    def __init__(self, image: PySide6.QtGui.QImage, /) -> None: ...
    @typing.overload
    def __init__(self, format: QVideoFrameFormat, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def bits(self, plane: int, /) -> bytes | bytearray | memoryview: ...
    def bytesPerLine(self, plane: int, /) -> int: ...
    def endTime(self, /) -> int: ...
    def handleType(self, /) -> QVideoFrame.HandleType: ...
    def height(self, /) -> int: ...
    def isMapped(self, /) -> bool: ...
    def isReadable(self, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    def isWritable(self, /) -> bool: ...
    def map(self, mode: QVideoFrame.MapMode, /) -> bool: ...
    def mapMode(self, /) -> QVideoFrame.MapMode: ...
    def mappedBytes(self, plane: int, /) -> int: ...
    def mirrored(self, /) -> bool: ...
    def paint(self, painter: PySide6.QtGui.QPainter, rect: PySide6.QtCore.QRectF | PySide6.QtCore.QRect, options: QVideoFrame.PaintOptions, /) -> None: ...
    def pixelFormat(self, /) -> QVideoFrameFormat.PixelFormat: ...
    def planeCount(self, /) -> int: ...
    def rotation(self, /) -> QtVideo.Rotation: ...
    def rotationAngle(self, /) -> QVideoFrame.RotationAngle: ...
    def setEndTime(self, time: int, /) -> None: ...
    def setMirrored(self, arg__1: bool, /) -> None: ...
    def setRotation(self, angle: QtVideo.Rotation, /) -> None: ...
    def setRotationAngle(self, angle: QVideoFrame.RotationAngle, /) -> None: ...
    def setStartTime(self, time: int, /) -> None: ...
    def setStreamFrameRate(self, rate: float, /) -> None: ...
    def setSubtitleText(self, text: str, /) -> None: ...
    def size(self, /) -> PySide6.QtCore.QSize: ...
    def startTime(self, /) -> int: ...
    def streamFrameRate(self, /) -> float: ...
    def subtitleText(self, /) -> str: ...
    def surfaceFormat(self, /) -> QVideoFrameFormat: ...
    def swap(self, other: QVideoFrame | QVideoFrameFormat, /) -> None: ...
    def toImage(self, /) -> PySide6.QtGui.QImage: ...
    def unmap(self, /) -> None: ...
    def videoBuffer(self, /) -> QAbstractVideoBuffer: ...
    def width(self, /) -> int: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QVideoFrameFormat(shiboken6.Object):
    class ColorRange(enum.Enum):
        ColorRange_Full = 2
        ColorRange_Unknown = 0
        ColorRange_Video = 1

    class ColorSpace(enum.Enum):
        ColorSpace_AdobeRgb = 5
        ColorSpace_BT2020 = 6
        ColorSpace_BT601 = 1
        ColorSpace_BT709 = 2
        ColorSpace_Undefined = 0

    class ColorTransfer(enum.Enum):
        ColorTransfer_BT601 = 2
        ColorTransfer_BT709 = 1
        ColorTransfer_Gamma22 = 4
        ColorTransfer_Gamma28 = 5
        ColorTransfer_Linear = 3
        ColorTransfer_ST2084 = 6
        ColorTransfer_STD_B67 = 7
        ColorTransfer_Unknown = 0

    class Direction(enum.Enum):
        BottomToTop = 1
        TopToBottom = 0

    class PixelFormat(enum.Enum):
        Format_ABGR8888 = 7
        Format_ARGB8888 = 1
        Format_ARGB8888_Premultiplied = 2
        Format_AYUV = 11
        Format_AYUV_Premultiplied = 12
        Format_BGRA8888 = 4
        Format_BGRA8888_Premultiplied = 5
        Format_BGRX8888 = 6
        Format_IMC1 = 20
        Format_IMC2 = 21
        Format_IMC3 = 22
        Format_IMC4 = 23
        Format_Invalid = 0
        Format_Jpeg = 29
        Format_NV12 = 18
        Format_NV21 = 19
        Format_P010 = 26
        Format_P016 = 27
        Format_RGBA8888 = 9
        Format_RGBX8888 = 10
        Format_SamplerExternalOES = 28
        Format_SamplerRect = 30
        Format_UYVY = 16
        Format_XBGR8888 = 8
        Format_XRGB8888 = 3
        Format_Y16 = 25
        Format_Y8 = 24
        Format_YUV420P = 13
        Format_YUV420P10 = 31
        Format_YUV422P = 14
        Format_YUYV = 17
        Format_YV12 = 15

    class YCbCrColorSpace(enum.Enum):
        YCbCr_BT2020 = 6
        YCbCr_BT601 = 1
        YCbCr_BT709 = 2
        YCbCr_JPEG = 5
        YCbCr_Undefined = 0
        YCbCr_xvYCC601 = 3
        YCbCr_xvYCC709 = 4
    NPixelFormats: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, size: PySide6.QtCore.QSize, pixelFormat: QVideoFrameFormat.PixelFormat, /) -> None: ...
    @typing.overload
    def __init__(self, format: QVideoFrameFormat, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def colorRange(self, /) -> QVideoFrameFormat.ColorRange: ...
    def colorSpace(self, /) -> QVideoFrameFormat.ColorSpace: ...
    def colorTransfer(self, /) -> QVideoFrameFormat.ColorTransfer: ...
    def fragmentShaderFileName(self, /) -> str: ...
    def frameHeight(self, /) -> int: ...
    def frameRate(self, /) -> float: ...
    def frameSize(self, /) -> PySide6.QtCore.QSize: ...
    def frameWidth(self, /) -> int: ...
    @staticmethod
    def imageFormatFromPixelFormat(format: QVideoFrameFormat.PixelFormat, /) -> PySide6.QtGui.QImage.Format: ...
    def isMirrored(self, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    def maxLuminance(self, /) -> float: ...
    def pixelFormat(self, /) -> QVideoFrameFormat.PixelFormat: ...
    @staticmethod
    def pixelFormatFromImageFormat(format: PySide6.QtGui.QImage.Format, /) -> QVideoFrameFormat.PixelFormat: ...
    @staticmethod
    def pixelFormatToString(pixelFormat: QVideoFrameFormat.PixelFormat, /) -> str: ...
    def planeCount(self, /) -> int: ...
    def rotation(self, /) -> QtVideo.Rotation: ...
    def scanLineDirection(self, /) -> QVideoFrameFormat.Direction: ...
    def setColorRange(self, range: QVideoFrameFormat.ColorRange, /) -> None: ...
    def setColorSpace(self, colorSpace: QVideoFrameFormat.ColorSpace, /) -> None: ...
    def setColorTransfer(self, colorTransfer: QVideoFrameFormat.ColorTransfer, /) -> None: ...
    def setFrameRate(self, rate: float, /) -> None: ...
    @typing.overload
    def setFrameSize(self, width: int, height: int, /) -> None: ...
    @typing.overload
    def setFrameSize(self, size: PySide6.QtCore.QSize, /) -> None: ...
    def setMaxLuminance(self, lum: float, /) -> None: ...
    def setMirrored(self, mirrored: bool, /) -> None: ...
    def setRotation(self, rotation: QtVideo.Rotation, /) -> None: ...
    def setScanLineDirection(self, direction: QVideoFrameFormat.Direction, /) -> None: ...
    def setStreamFrameRate(self, rate: float, /) -> None: ...
    def setViewport(self, viewport: PySide6.QtCore.QRect, /) -> None: ...
    def setYCbCrColorSpace(self, colorSpace: QVideoFrameFormat.YCbCrColorSpace, /) -> None: ...
    def streamFrameRate(self, /) -> float: ...
    def swap(self, other: QVideoFrameFormat, /) -> None: ...
    def updateUniformData(self, dst: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, frame: QVideoFrame | QVideoFrameFormat, transform: PySide6.QtGui.QMatrix4x4 | PySide6.QtGui.QTransform, opacity: float, /) -> None: ...
    def vertexShaderFileName(self, /) -> str: ...
    def viewport(self, /) -> PySide6.QtCore.QRect: ...
    def yCbCrColorSpace(self, /) -> QVideoFrameFormat.YCbCrColorSpace: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QVideoFrameInput(PySide6.QtCore.QObject):
    readyToSendVideoFrame: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    @typing.overload
    def __init__(self, format: QVideoFrameFormat, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., readyToSendVideoFrame: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., readyToSendVideoFrame: typing.Callable = ...) -> None: ...
    def captureSession(self, /) -> QMediaCaptureSession: ...
    def format(self, /) -> QVideoFrameFormat: ...
    def sendVideoFrame(self, frame: QVideoFrame | QVideoFrameFormat, /) -> bool: ...

class QVideoSink(PySide6.QtCore.QObject):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    subtitleTextChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    videoFrameChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    videoSizeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, subtitleText: str | None = ..., videoSize: PySide6.QtCore.QSize | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., subtitleTextChanged: typing.Callable = ..., videoFrameChanged: typing.Callable = ..., videoSizeChanged: typing.Callable = ...) -> None: ...
    def rhi(self, /) -> PySide6.QtGui.QRhi: ...
    def setRhi(self, rhi: PySide6.QtGui.QRhi, /) -> None: ...
    def setSubtitleText(self, subtitle: str, /) -> None: ...
    def setVideoFrame(self, frame: QVideoFrame | QVideoFrameFormat, /) -> None: ...
    def subtitleText(self, /) -> str: ...
    def videoFrame(self, /) -> QVideoFrame: ...
    def videoSize(self, /) -> PySide6.QtCore.QSize: ...

class QWaveDecoder(PySide6.QtCore.QIODevice):
    formatKnown: typing.ClassVar[PySide6.QtCore.Signal] = ...
    parsingError: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    @typing.overload
    def __init__(self, device: PySide6.QtCore.QIODevice, format: QAudioFormat, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, device: PySide6.QtCore.QIODevice, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def audioFormat(self, /) -> QAudioFormat: ...
    def bytesAvailable(self, /) -> int: ...
    def close(self, /) -> None: ...
    def duration(self, /) -> int: ...
    def getDevice(self, /) -> PySide6.QtCore.QIODevice: ...
    @staticmethod
    def headerLength() -> int: ...
    def isSequential(self, /) -> bool: ...
    def open(self, mode: PySide6.QtCore.QIODeviceBase.OpenModeFlag, /) -> bool: ...
    def pos(self, /) -> int: ...
    def readData(self, maxlen: int, /) -> typing.Any: ...
    def seek(self, pos: int, /) -> bool: ...
    def size(self, /) -> int: ...
    def writeData(self, data: bytes | bytearray | memoryview, len: int, /) -> int: ...

class QWindowCapture(PySide6.QtCore.QObject):
    class Error(enum.Enum):
        CaptureFailed = 4
        CapturingNotSupported = 2
        InternalError = 1
        NoError = 0
        NotFound = 5
    activeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorOccurred: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    windowChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, active: bool | None = ..., window: QCapturableWindow | None = ..., error: QWindowCapture.Error | None = ..., errorString: str | None = ..., activeChanged: typing.Callable = ..., destroyed: typing.Callable = ..., errorChanged: typing.Callable = ..., errorOccurred: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., windowChanged: typing.Callable = ...) -> None: ...
    @staticmethod
    def capturableWindows() -> List[QCapturableWindow]: ...
    def captureSession(self, /) -> QMediaCaptureSession: ...
    def error(self, /) -> QWindowCapture.Error: ...
    def errorString(self, /) -> str: ...
    def isActive(self, /) -> bool: ...
    def setActive(self, active: bool, /) -> None: ...
    def setWindow(self, window: QCapturableWindow, /) -> None: ...
    def start(self, /) -> None: ...
    def stop(self, /) -> None: ...
    def window(self, /) -> QCapturableWindow: ...

class QtAudio(shiboken6.Object):
    class Error(enum.Enum):
        FatalError = 4
        IOError = 2
        NoError = 0
        OpenError = 1
        UnderrunError = 3

    class State(enum.Enum):
        ActiveState = 0
        IdleState = 3
        StoppedState = 2
        SuspendedState = 1

    class VolumeScale(enum.Enum):
        CubicVolumeScale = 1
        DecibelVolumeScale = 3
        LinearVolumeScale = 0
        LogarithmicVolumeScale = 2
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def convertVolume(volume: float, from_: QtAudio.VolumeScale, to: QtAudio.VolumeScale, /) -> float: ...

class QtVideo(shiboken6.Object):
    class Rotation(enum.Enum):
        Clockwise180 = 180
        Clockwise270 = 270
        Clockwise90 = 90
        None_ = 0
    def __init__(self, *args, **kwargs) -> None: ...
