import PySide6.QtCore
import _typeshed
import collections
import datetime
import enum
import shiboken6
import typing
import typing_extensions

from typing import Any, Dict, List, Optional, OrderedDict, Set, Tuple, Union
T = typing.TypeVar('T')
P = typing.ParamSpec('P')
class QGeoAddress(shiboken6.Object):
    @typing.overload
    def __init__(self, other: QGeoAddress, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def city(self, /) -> str: ...
    def clear(self, /) -> None: ...
    def country(self, /) -> str: ...
    def countryCode(self, /) -> str: ...
    def county(self, /) -> str: ...
    def district(self, /) -> str: ...
    def isEmpty(self, /) -> bool: ...
    def isTextGenerated(self, /) -> bool: ...
    def postalCode(self, /) -> str: ...
    def setCity(self, city: str, /) -> None: ...
    def setCountry(self, country: str, /) -> None: ...
    def setCountryCode(self, countryCode: str, /) -> None: ...
    def setCounty(self, county: str, /) -> None: ...
    def setDistrict(self, district: str, /) -> None: ...
    def setPostalCode(self, postalCode: str, /) -> None: ...
    def setState(self, state: str, /) -> None: ...
    def setStreet(self, street: str, /) -> None: ...
    def setStreetNumber(self, streetNumber: str, /) -> None: ...
    def setText(self, text: str, /) -> None: ...
    def state(self, /) -> str: ...
    def street(self, /) -> str: ...
    def streetNumber(self, /) -> str: ...
    def swap(self, other: QGeoAddress, /) -> None: ...
    def text(self, /) -> str: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QGeoAreaMonitorInfo(shiboken6.Object):
    @typing.overload
    def __init__(self, other: QGeoAreaMonitorInfo, /) -> None: ...
    @typing.overload
    def __init__(self, /, name: str = ...) -> None: ...
    def area(self, /) -> QGeoShape: ...
    def expiration(self, /) -> PySide6.QtCore.QDateTime: ...
    def identifier(self, /) -> str: ...
    def isPersistent(self, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    def name(self, /) -> str: ...
    def notificationParameters(self, /) -> Dict[str, Any]: ...
    def setArea(self, newShape: QGeoShape, /) -> None: ...
    def setExpiration(self, expiry: PySide6.QtCore.QDateTime | datetime.datetime, /) -> None: ...
    def setName(self, name: str, /) -> None: ...
    def setNotificationParameters(self, parameters: Dict[str, Any], /) -> None: ...
    def setPersistent(self, isPersistent: bool, /) -> None: ...
    def swap(self, other: QGeoAreaMonitorInfo | str, /) -> None: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lshift__(self, ds: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __rlshift__(self, other): ...
    def __rrshift__(self, other): ...
    def __rshift__(self, ds: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...

class QGeoAreaMonitorSource(PySide6.QtCore.QObject):
    class AreaMonitorFeature(enum.Flag):
        AnyAreaMonitorFeature = 4294967295
        PersistentAreaMonitorFeature = 1

    class Error(enum.Enum):
        AccessError = 0
        InsufficientPositionInfo = 1
        NoError = 3
        UnknownSourceError = 2
    areaEntered: typing.ClassVar[PySide6.QtCore.Signal] = ...
    areaExited: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorOccurred: typing.ClassVar[PySide6.QtCore.Signal] = ...
    monitorExpired: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def activeMonitors(self, lookupArea: QGeoShape, /) -> List[QGeoAreaMonitorInfo]: ...
    @typing.overload
    def activeMonitors(self, /) -> List[QGeoAreaMonitorInfo]: ...
    @staticmethod
    def availableSources() -> List[str]: ...
    def backendProperty(self, name: str, /) -> Any: ...
    @staticmethod
    def createDefaultSource(parent: PySide6.QtCore.QObject | None, /) -> QGeoAreaMonitorSource: ...
    @staticmethod
    def createSource(sourceName: str, parent: PySide6.QtCore.QObject | None, /) -> QGeoAreaMonitorSource: ...
    def error(self, /) -> QGeoAreaMonitorSource.Error: ...
    def positionInfoSource(self, /) -> QGeoPositionInfoSource: ...
    def requestUpdate(self, monitor: QGeoAreaMonitorInfo | str, signal: bytes | bytearray | memoryview, /) -> bool: ...
    def setBackendProperty(self, name: str, value: Any, /) -> bool: ...
    def setPositionInfoSource(self, source: QGeoPositionInfoSource, /) -> None: ...
    def sourceName(self, /) -> str: ...
    def startMonitoring(self, monitor: QGeoAreaMonitorInfo | str, /) -> bool: ...
    def stopMonitoring(self, monitor: QGeoAreaMonitorInfo | str, /) -> bool: ...
    def supportedAreaMonitorFeatures(self, /) -> QGeoAreaMonitorSource.AreaMonitorFeature: ...

class QGeoCircle(QGeoShape):
    @typing.overload
    def __init__(self, other: QGeoCircle, /, *, center: QGeoCoordinate | None = ..., radius: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, other: QGeoShape, /, *, center: QGeoCoordinate | None = ..., radius: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, center: QGeoCoordinate | None = ..., radius: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, center: QGeoCoordinate, /, radius: float = ...) -> None: ...
    def center(self, /) -> QGeoCoordinate: ...
    def extendCircle(self, coordinate: QGeoCoordinate, /) -> None: ...
    def radius(self, /) -> float: ...
    def setCenter(self, center: QGeoCoordinate, /) -> None: ...
    def setRadius(self, radius: float, /) -> None: ...
    def toString(self, /) -> str: ...
    def translate(self, degreesLatitude: float, degreesLongitude: float, /) -> None: ...
    def translated(self, degreesLatitude: float, degreesLongitude: float, /) -> QGeoCircle: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __lshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
    def __rlshift__(self, other): ...
    def __rrshift__(self, other): ...
    def __rshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...

class QGeoCoordinate(shiboken6.Object):
    class CoordinateFormat(enum.Enum):
        Degrees = 0
        DegreesMinutes = 2
        DegreesMinutesSeconds = 4
        DegreesMinutesSecondsWithHemisphere = 5
        DegreesMinutesWithHemisphere = 3
        DegreesWithHemisphere = 1

    class CoordinateType(enum.Enum):
        Coordinate2D = 1
        Coordinate3D = 2
        InvalidCoordinate = 0
    @typing.overload
    def __init__(self, other: QGeoCoordinate, /, *, latitude: float | None = ..., longitude: float | None = ..., altitude: float | None = ..., isValid: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, latitude: float, longitude: float, altitude: float, /, *, isValid: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, latitude: float, longitude: float, /, *, altitude: float | None = ..., isValid: bool | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, latitude: float | None = ..., longitude: float | None = ..., altitude: float | None = ..., isValid: bool | None = ...) -> None: ...
    def altitude(self, /) -> float: ...
    def atDistanceAndAzimuth(self, distance: float, azimuth: float, /, distanceUp: float = ...) -> QGeoCoordinate: ...
    def azimuthTo(self, other: QGeoCoordinate, /) -> float: ...
    def distanceTo(self, other: QGeoCoordinate, /) -> float: ...
    def isValid(self, /) -> bool: ...
    def latitude(self, /) -> float: ...
    def longitude(self, /) -> float: ...
    def setAltitude(self, altitude: float, /) -> None: ...
    def setLatitude(self, latitude: float, /) -> None: ...
    def setLongitude(self, longitude: float, /) -> None: ...
    def swap(self, other: QGeoCoordinate, /) -> None: ...
    def toString(self, /, format: QGeoCoordinate.CoordinateFormat = ...) -> str: ...
    def type(self, /) -> QGeoCoordinate.CoordinateType: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __rlshift__(self, other): ...
    def __rrshift__(self, other): ...
    def __rshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...

class QGeoLocation(shiboken6.Object):
    @typing.overload
    def __init__(self, other: QGeoLocation, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def address(self, /) -> QGeoAddress: ...
    def boundingShape(self, /) -> QGeoShape: ...
    def coordinate(self, /) -> QGeoCoordinate: ...
    def extendedAttributes(self, /) -> Dict[str, Any]: ...
    def isEmpty(self, /) -> bool: ...
    def setAddress(self, address: QGeoAddress, /) -> None: ...
    def setBoundingShape(self, shape: QGeoShape, /) -> None: ...
    def setCoordinate(self, position: QGeoCoordinate, /) -> None: ...
    def setExtendedAttributes(self, data: Dict[str, Any], /) -> None: ...
    def swap(self, other: QGeoLocation, /) -> None: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QGeoPath(QGeoShape):
    @typing.overload
    def __init__(self, other: QGeoPath, /, *, path: typing.Iterable[typing.Any] | None = ..., width: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, other: QGeoShape, /, *, path: typing.Iterable[typing.Any] | None = ..., width: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, path: typing.Iterable[typing.Any] | None = ..., width: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, path: typing.Iterable[QGeoCoordinate], /, width: float = ...) -> None: ...
    def addCoordinate(self, coordinate: QGeoCoordinate, /) -> None: ...
    def clearPath(self, /) -> None: ...
    def containsCoordinate(self, coordinate: QGeoCoordinate, /) -> bool: ...
    def coordinateAt(self, index: int, /) -> QGeoCoordinate: ...
    def insertCoordinate(self, index: int, coordinate: QGeoCoordinate, /) -> None: ...
    def length(self, /, indexFrom: int | None = ..., indexTo: int = ...) -> float: ...
    def path(self, /) -> List[QGeoCoordinate]: ...
    @typing.overload
    def removeCoordinate(self, index: int, /) -> None: ...
    @typing.overload
    def removeCoordinate(self, coordinate: QGeoCoordinate, /) -> None: ...
    def replaceCoordinate(self, index: int, coordinate: QGeoCoordinate, /) -> None: ...
    def setPath(self, path: typing.Iterable[QGeoCoordinate], /) -> None: ...
    def setVariantPath(self, path: typing.Iterable[typing.Any], /) -> None: ...
    def setWidth(self, width: float, /) -> None: ...
    def size(self, /) -> int: ...
    def toString(self, /) -> str: ...
    def translate(self, degreesLatitude: float, degreesLongitude: float, /) -> None: ...
    def translated(self, degreesLatitude: float, degreesLongitude: float, /) -> QGeoPath: ...
    def variantPath(self, /) -> List[Any]: ...
    def width(self, /) -> float: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __lshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
    def __rlshift__(self, other): ...
    def __rrshift__(self, other): ...
    def __rshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...

class QGeoPolygon(QGeoShape):
    @typing.overload
    def __init__(self, path: typing.Iterable[QGeoCoordinate], /, *, perimeter: typing.Iterable[QGeoCoordinate] | None = ...) -> None: ...
    @typing.overload
    def __init__(self, other: QGeoPolygon, /, *, perimeter: typing.Iterable[QGeoCoordinate] | None = ...) -> None: ...
    @typing.overload
    def __init__(self, other: QGeoShape, /, *, perimeter: typing.Iterable[QGeoCoordinate] | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, perimeter: typing.Iterable[QGeoCoordinate] | None = ...) -> None: ...
    def addCoordinate(self, coordinate: QGeoCoordinate, /) -> None: ...
    @typing.overload
    def addHole(self, holePath: typing.Iterable[QGeoCoordinate], /) -> None: ...
    @typing.overload
    def addHole(self, holePath: Any, /) -> None: ...
    def containsCoordinate(self, coordinate: QGeoCoordinate, /) -> bool: ...
    def coordinateAt(self, index: int, /) -> QGeoCoordinate: ...
    def hole(self, index: int, /) -> List[Any]: ...
    def holePath(self, index: int, /) -> List[QGeoCoordinate]: ...
    def holesCount(self, /) -> int: ...
    def insertCoordinate(self, index: int, coordinate: QGeoCoordinate, /) -> None: ...
    def length(self, /, indexFrom: int | None = ..., indexTo: int = ...) -> float: ...
    def perimeter(self, /) -> List[QGeoCoordinate]: ...
    @typing.overload
    def removeCoordinate(self, index: int, /) -> None: ...
    @typing.overload
    def removeCoordinate(self, coordinate: QGeoCoordinate, /) -> None: ...
    def removeHole(self, index: int, /) -> None: ...
    def replaceCoordinate(self, index: int, coordinate: QGeoCoordinate, /) -> None: ...
    def setPerimeter(self, path: typing.Iterable[QGeoCoordinate], /) -> None: ...
    def size(self, /) -> int: ...
    def toString(self, /) -> str: ...
    def translate(self, degreesLatitude: float, degreesLongitude: float, /) -> None: ...
    def translated(self, degreesLatitude: float, degreesLongitude: float, /) -> QGeoPolygon: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __lshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
    def __rlshift__(self, other): ...
    def __rrshift__(self, other): ...
    def __rshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...

class QGeoPositionInfo(shiboken6.Object):
    class Attribute(enum.Enum):
        Direction = 0
        DirectionAccuracy = 6
        GroundSpeed = 1
        HorizontalAccuracy = 4
        MagneticVariation = 3
        VerticalAccuracy = 5
        VerticalSpeed = 2
    @typing.overload
    def __init__(self, coordinate: QGeoCoordinate, updateTime: PySide6.QtCore.QDateTime | datetime.datetime, /) -> None: ...
    @typing.overload
    def __init__(self, other: QGeoPositionInfo, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def attribute(self, attribute: QGeoPositionInfo.Attribute, /) -> float: ...
    def coordinate(self, /) -> QGeoCoordinate: ...
    def hasAttribute(self, attribute: QGeoPositionInfo.Attribute, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    def removeAttribute(self, attribute: QGeoPositionInfo.Attribute, /) -> None: ...
    def setAttribute(self, attribute: QGeoPositionInfo.Attribute, value: float, /) -> None: ...
    def setCoordinate(self, coordinate: QGeoCoordinate, /) -> None: ...
    def setTimestamp(self, timestamp: PySide6.QtCore.QDateTime | datetime.datetime, /) -> None: ...
    def swap(self, other: QGeoPositionInfo, /) -> None: ...
    def timestamp(self, /) -> PySide6.QtCore.QDateTime: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __rlshift__(self, other): ...
    def __rrshift__(self, other): ...
    def __rshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...

class QGeoPositionInfoSource(PySide6.QtCore.QObject):
    class Error(enum.Enum):
        AccessError = 0
        ClosedError = 1
        NoError = 3
        UnknownSourceError = 2
        UpdateTimeoutError = 4

    class PositioningMethod(enum.Flag):
        AllPositioningMethods = 4294967295
        NoPositioningMethods = 0
        NonSatellitePositioningMethods = 4294967040
        SatellitePositioningMethods = 255
    errorOccurred: typing.ClassVar[PySide6.QtCore.Signal] = ...
    positionUpdated: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    supportedPositioningMethodsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, updateInterval: int | None = ..., minimumUpdateInterval: int | None = ..., sourceName: str | None = ..., preferredPositioningMethods: QGeoPositionInfoSource.PositioningMethod | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    @staticmethod
    def availableSources() -> List[str]: ...
    def backendProperty(self, name: str, /) -> Any: ...
    @typing.overload
    @staticmethod
    def createDefaultSource(parameters: Dict[str, Any], parent: PySide6.QtCore.QObject | None, /) -> QGeoPositionInfoSource: ...
    @typing.overload
    @staticmethod
    def createDefaultSource(parent: PySide6.QtCore.QObject | None, /) -> QGeoPositionInfoSource: ...
    @typing.overload
    @staticmethod
    def createSource(sourceName: str, parameters: Dict[str, Any], parent: PySide6.QtCore.QObject | None, /) -> QGeoPositionInfoSource: ...
    @typing.overload
    @staticmethod
    def createSource(sourceName: str, parent: PySide6.QtCore.QObject | None, /) -> QGeoPositionInfoSource: ...
    def error(self, /) -> QGeoPositionInfoSource.Error: ...
    def lastKnownPosition(self, /, fromSatellitePositioningMethodsOnly: bool = ...) -> QGeoPositionInfo: ...
    def minimumUpdateInterval(self, /) -> int: ...
    def preferredPositioningMethods(self, /) -> QGeoPositionInfoSource.PositioningMethod: ...
    def requestUpdate(self, /, timeout: int | None = ...) -> None: ...
    def setBackendProperty(self, name: str, value: Any, /) -> bool: ...
    def setPreferredPositioningMethods(self, methods: QGeoPositionInfoSource.PositioningMethod, /) -> None: ...
    def setUpdateInterval(self, msec: int, /) -> None: ...
    def sourceName(self, /) -> str: ...
    def startUpdates(self, /) -> None: ...
    def stopUpdates(self, /) -> None: ...
    def supportedPositioningMethods(self, /) -> QGeoPositionInfoSource.PositioningMethod: ...
    def updateInterval(self, /) -> int: ...

class QGeoPositionInfoSourceFactory(shiboken6.Object):
    def __init__(self, /) -> None: ...
    def areaMonitor(self, parent: PySide6.QtCore.QObject | None, parameters: Dict[str, Any], /) -> QGeoAreaMonitorSource: ...
    def positionInfoSource(self, parent: PySide6.QtCore.QObject | None, parameters: Dict[str, Any], /) -> QGeoPositionInfoSource: ...
    def satelliteInfoSource(self, parent: PySide6.QtCore.QObject | None, parameters: Dict[str, Any], /) -> QGeoSatelliteInfoSource: ...

class QGeoRectangle(QGeoShape):
    @typing.overload
    def __init__(self, center: QGeoCoordinate, degreesWidth: float, degreesHeight: float, /, *, bottomLeft: QGeoCoordinate | None = ..., bottomRight: QGeoCoordinate | None = ..., topLeft: QGeoCoordinate | None = ..., topRight: QGeoCoordinate | None = ..., height: float | None = ..., width: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, other: QGeoRectangle, /, *, bottomLeft: QGeoCoordinate | None = ..., bottomRight: QGeoCoordinate | None = ..., topLeft: QGeoCoordinate | None = ..., topRight: QGeoCoordinate | None = ..., center: QGeoCoordinate | None = ..., height: float | None = ..., width: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, other: QGeoShape, /, *, bottomLeft: QGeoCoordinate | None = ..., bottomRight: QGeoCoordinate | None = ..., topLeft: QGeoCoordinate | None = ..., topRight: QGeoCoordinate | None = ..., center: QGeoCoordinate | None = ..., height: float | None = ..., width: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, coordinates: typing.Iterable[QGeoCoordinate], /, *, bottomLeft: QGeoCoordinate | None = ..., bottomRight: QGeoCoordinate | None = ..., topLeft: QGeoCoordinate | None = ..., topRight: QGeoCoordinate | None = ..., center: QGeoCoordinate | None = ..., height: float | None = ..., width: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, topLeft: QGeoCoordinate, bottomRight: QGeoCoordinate, /, *, bottomLeft: QGeoCoordinate | None = ..., topRight: QGeoCoordinate | None = ..., center: QGeoCoordinate | None = ..., height: float | None = ..., width: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, bottomLeft: QGeoCoordinate | None = ..., bottomRight: QGeoCoordinate | None = ..., topLeft: QGeoCoordinate | None = ..., topRight: QGeoCoordinate | None = ..., center: QGeoCoordinate | None = ..., height: float | None = ..., width: float | None = ...) -> None: ...
    def bottomLeft(self, /) -> QGeoCoordinate: ...
    def bottomRight(self, /) -> QGeoCoordinate: ...
    def center(self, /) -> QGeoCoordinate: ...
    @typing.overload
    def contains(self, rectangle: QGeoRectangle | QGeoShape | typing.Iterable[QGeoCoordinate], /) -> bool: ...
    @typing.overload
    def contains(self, coordinate: QGeoCoordinate, /) -> bool: ...
    def extendRectangle(self, coordinate: QGeoCoordinate, /) -> None: ...
    def height(self, /) -> float: ...
    def intersects(self, rectangle: QGeoRectangle | QGeoShape | typing.Iterable[QGeoCoordinate], /) -> bool: ...
    def setBottomLeft(self, bottomLeft: QGeoCoordinate, /) -> None: ...
    def setBottomRight(self, bottomRight: QGeoCoordinate, /) -> None: ...
    def setCenter(self, center: QGeoCoordinate, /) -> None: ...
    def setHeight(self, degreesHeight: float, /) -> None: ...
    def setTopLeft(self, topLeft: QGeoCoordinate, /) -> None: ...
    def setTopRight(self, topRight: QGeoCoordinate, /) -> None: ...
    def setWidth(self, degreesWidth: float, /) -> None: ...
    def toString(self, /) -> str: ...
    def topLeft(self, /) -> QGeoCoordinate: ...
    def topRight(self, /) -> QGeoCoordinate: ...
    def translate(self, degreesLatitude: float, degreesLongitude: float, /) -> None: ...
    def translated(self, degreesLatitude: float, degreesLongitude: float, /) -> QGeoRectangle: ...
    def united(self, rectangle: QGeoRectangle | QGeoShape | typing.Iterable[QGeoCoordinate], /) -> QGeoRectangle: ...
    def width(self, /) -> float: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __ior__(self, rectangle: QGeoRectangle | QGeoShape | typing.Iterable[QGeoCoordinate], /) -> QGeoRectangle: ...
    def __lshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
    def __or__(self, rectangle: QGeoRectangle | QGeoShape | typing.Iterable[QGeoCoordinate], /) -> QGeoRectangle: ...
    def __rlshift__(self, other): ...
    def __ror__(self, other): ...
    def __rrshift__(self, other): ...
    def __rshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...

class QGeoSatelliteInfo(shiboken6.Object):
    class Attribute(enum.Enum):
        Azimuth = 1
        Elevation = 0

    class SatelliteSystem(enum.Enum):
        BEIDOU = 4
        CustomType = 256
        GALILEO = 3
        GLONASS = 2
        GPS = 1
        Multiple = 255
        QZSS = 5
        Undefined = 0
    @typing.overload
    def __init__(self, other: QGeoSatelliteInfo, /, *, satelliteSystem: QGeoSatelliteInfo.SatelliteSystem | None = ..., satelliteIdentifier: int | None = ..., signalStrength: float | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, satelliteSystem: QGeoSatelliteInfo.SatelliteSystem | None = ..., satelliteIdentifier: int | None = ..., signalStrength: float | None = ...) -> None: ...
    def attribute(self, attribute: QGeoSatelliteInfo.Attribute, /) -> float: ...
    def hasAttribute(self, attribute: QGeoSatelliteInfo.Attribute, /) -> bool: ...
    def removeAttribute(self, attribute: QGeoSatelliteInfo.Attribute, /) -> None: ...
    def satelliteIdentifier(self, /) -> int: ...
    def satelliteSystem(self, /) -> QGeoSatelliteInfo.SatelliteSystem: ...
    def setAttribute(self, attribute: QGeoSatelliteInfo.Attribute, value: float, /) -> None: ...
    def setSatelliteIdentifier(self, satId: int, /) -> None: ...
    def setSatelliteSystem(self, system: QGeoSatelliteInfo.SatelliteSystem, /) -> None: ...
    def setSignalStrength(self, signalStrength: int, /) -> None: ...
    def signalStrength(self, /) -> int: ...
    def swap(self, other: QGeoSatelliteInfo, /) -> None: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __rlshift__(self, other): ...
    def __rrshift__(self, other): ...
    def __rshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...

class QGeoSatelliteInfoSource(PySide6.QtCore.QObject):
    class Error(enum.Enum):
        AccessError = 0
        ClosedError = 1
        NoError = 2
        UnknownSourceError = -1
        UpdateTimeoutError = 3
    errorOccurred: typing.ClassVar[PySide6.QtCore.Signal] = ...
    satellitesInUseUpdated: typing.ClassVar[PySide6.QtCore.Signal] = ...
    satellitesInViewUpdated: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, updateInterval: int | None = ..., minimumUpdateInterval: int | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    @staticmethod
    def availableSources() -> List[str]: ...
    def backendProperty(self, name: str, /) -> Any: ...
    @typing.overload
    @staticmethod
    def createDefaultSource(parameters: Dict[str, Any], parent: PySide6.QtCore.QObject | None, /) -> QGeoSatelliteInfoSource: ...
    @typing.overload
    @staticmethod
    def createDefaultSource(parent: PySide6.QtCore.QObject | None, /) -> QGeoSatelliteInfoSource: ...
    @typing.overload
    @staticmethod
    def createSource(sourceName: str, parameters: Dict[str, Any], parent: PySide6.QtCore.QObject | None, /) -> QGeoSatelliteInfoSource: ...
    @typing.overload
    @staticmethod
    def createSource(sourceName: str, parent: PySide6.QtCore.QObject | None, /) -> QGeoSatelliteInfoSource: ...
    def error(self, /) -> QGeoSatelliteInfoSource.Error: ...
    def minimumUpdateInterval(self, /) -> int: ...
    def requestUpdate(self, /, timeout: int | None = ...) -> None: ...
    def setBackendProperty(self, name: str, value: Any, /) -> bool: ...
    def setUpdateInterval(self, msec: int, /) -> None: ...
    def sourceName(self, /) -> str: ...
    def startUpdates(self, /) -> None: ...
    def stopUpdates(self, /) -> None: ...
    def updateInterval(self, /) -> int: ...

class QGeoShape(shiboken6.Object):
    class ShapeType(enum.Enum):
        CircleType = 2
        PathType = 3
        PolygonType = 4
        RectangleType = 1
        UnknownType = 0
    @typing.overload
    def __init__(self, other: QGeoShape, /, *, type: QGeoShape.ShapeType | None = ..., isValid: bool | None = ..., isEmpty: bool | None = ..., center: QGeoCoordinate | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, type: QGeoShape.ShapeType | None = ..., isValid: bool | None = ..., isEmpty: bool | None = ..., center: QGeoCoordinate | None = ...) -> None: ...
    def boundingGeoRectangle(self, /) -> QGeoRectangle: ...
    def center(self, /) -> QGeoCoordinate: ...
    def contains(self, coordinate: QGeoCoordinate, /) -> bool: ...
    def isEmpty(self, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    def toString(self, /) -> str: ...
    def type(self, /) -> QGeoShape.ShapeType: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __rlshift__(self, other): ...
    def __rrshift__(self, other): ...
    def __rshift__(self, stream: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...

class QIntList:
    __opaque_container__: typing.ClassVar[bool] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs): ...
    def capacity(self, *args, **kwargs): ...
    def clear(self, *args, **kwargs): ...
    def constData(self, *args, **kwargs): ...
    def data(self, *args, **kwargs): ...
    def pop_back(self, *args, **kwargs): ...
    def pop_front(self, *args, **kwargs): ...
    def prepend(self, *args, **kwargs): ...
    def push_back(self, *args, **kwargs): ...
    def push_front(self, *args, **kwargs): ...
    def removeFirst(self, *args, **kwargs): ...
    def removeLast(self, *args, **kwargs): ...
    def reserve(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, object) -> None: ...

class QNmeaPositionInfoSource(QGeoPositionInfoSource):
    class UpdateMode(enum.Enum):
        RealTimeMode = 1
        SimulationMode = 2
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, updateMode: QNmeaPositionInfoSource.UpdateMode, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def device(self, /) -> PySide6.QtCore.QIODevice: ...
    def error(self, /) -> QGeoPositionInfoSource.Error: ...
    def lastKnownPosition(self, /, fromSatellitePositioningMethodsOnly: bool = ...) -> QGeoPositionInfo: ...
    def minimumUpdateInterval(self, /) -> int: ...
    @typing.overload
    def parsePosInfoFromNmeaData(self, data: bytes | bytearray | memoryview, size: int, posInfo: QGeoPositionInfo, /) -> Tuple[bool, bool]: ...
    @typing.overload
    def parsePosInfoFromNmeaData(self, data: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, posInfo: QGeoPositionInfo, /) -> Tuple[bool, bool]: ...
    def requestUpdate(self, /, timeout: int | None = ...) -> None: ...
    def setDevice(self, source: PySide6.QtCore.QIODevice, /) -> None: ...
    def setError(self, positionError: QGeoPositionInfoSource.Error, /) -> None: ...
    def setUpdateInterval(self, msec: int, /) -> None: ...
    def setUserEquivalentRangeError(self, uere: float, /) -> None: ...
    def startUpdates(self, /) -> None: ...
    def stopUpdates(self, /) -> None: ...
    def supportedPositioningMethods(self, /) -> QGeoPositionInfoSource.PositioningMethod: ...
    def updateMode(self, /) -> QNmeaPositionInfoSource.UpdateMode: ...
    def userEquivalentRangeError(self, /) -> float: ...

class QNmeaSatelliteInfoSource(QGeoSatelliteInfoSource):
    class SatelliteInfoParseStatus(enum.Enum):
        FullyParsed = 2
        NotParsed = 0
        PartiallyParsed = 1

    class UpdateMode(enum.Enum):
        RealTimeMode = 1
        SimulationMode = 2
    SimulationUpdateInterval: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, mode: QNmeaSatelliteInfoSource.UpdateMode, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def backendProperty(self, name: str, /) -> Any: ...
    def device(self, /) -> PySide6.QtCore.QIODevice: ...
    def error(self, /) -> QGeoSatelliteInfoSource.Error: ...
    def minimumUpdateInterval(self, /) -> int: ...
    @typing.overload
    def parseSatelliteInfoFromNmea(self, data: bytes | bytearray | memoryview, size: int, infos: typing.Iterable[QGeoSatelliteInfo], system: QGeoSatelliteInfo.SatelliteSystem, /) -> QNmeaSatelliteInfoSource.SatelliteInfoParseStatus: ...
    @typing.overload
    def parseSatelliteInfoFromNmea(self, data: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, infos: typing.Iterable[QGeoSatelliteInfo], system: QGeoSatelliteInfo.SatelliteSystem, /) -> QNmeaSatelliteInfoSource.SatelliteInfoParseStatus: ...
    @typing.overload
    def parseSatellitesInUseFromNmea(self, data: bytes | bytearray | memoryview, size: int, pnrsInUse: typing.Iterable[int], /) -> QGeoSatelliteInfo.SatelliteSystem: ...
    @typing.overload
    def parseSatellitesInUseFromNmea(self, data: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, pnrsInUse: typing.Iterable[int], /) -> QGeoSatelliteInfo.SatelliteSystem: ...
    def requestUpdate(self, /, timeout: int | None = ...) -> None: ...
    def setBackendProperty(self, name: str, value: Any, /) -> bool: ...
    def setDevice(self, source: PySide6.QtCore.QIODevice, /) -> None: ...
    def setError(self, satelliteError: QGeoSatelliteInfoSource.Error, /) -> None: ...
    def setUpdateInterval(self, msec: int, /) -> None: ...
    def startUpdates(self, /) -> None: ...
    def stopUpdates(self, /) -> None: ...
    def updateMode(self, /) -> QNmeaSatelliteInfoSource.UpdateMode: ...
