import PySide6.QtCore
import PySide6.QtNetwork
import _typeshed
import collections
import collections.abc
import enum
import os
import shiboken6
import typing
import typing_extensions

from typing import Any, Dict, List, Optional, OrderedDict, Set, Tuple, Union
T = typing.TypeVar('T')
P = typing.ParamSpec('P')
class _add_QQmlProperty_read_overloads:
    """
    Overloads for QQmlProperty.read.

    This descriptor-based workflow allows us to describe overloads that mix static and instance
    methods. 
    """
    class StaticOverloads:
        class read:
            @staticmethod
            @typing.overload
            def __call__(arg__1: PySide6.QtCore.QObject, arg__2: str, /) -> Any: ...
            @staticmethod
            @typing.overload
            def __call__(arg__1: PySide6.QtCore.QObject, arg__2: str, arg__3: QQmlEngine, /) -> Any: ...
            @staticmethod
            @typing.overload
            def __call__(arg__1: PySide6.QtCore.QObject, arg__2: str, arg__3: QQmlContext, /) -> Any: ...

    class InstanceOverloads:
        class read:
            @typing.overload
            def __call__(self, /) -> Any: ...
            @typing.overload
            def __call__(self, arg__1: PySide6.QtCore.QObject, arg__2: str, /) -> Any: ...
            @typing.overload
            def __call__(self, arg__1: PySide6.QtCore.QObject, arg__2: str, arg__3: QQmlEngine, /) -> Any: ...
            @typing.overload
            def __call__(self, arg__1: PySide6.QtCore.QObject, arg__2: str, arg__3: QQmlContext, /) -> Any: ...

    def __init__(self, cb: typing.Callable) -> None: ...

    @typing.overload
    def __get__(self, object: None, owner: typing.Any) -> StaticOverloads.read: ...

    @typing.overload
    def __get__(self, object: QQmlProperty, owner: typing.Any) -> InstanceOverloads.read: ...

class _add_QQmlProperty_write_overloads:
    """
    Overloads for QQmlProperty.write.

    This descriptor-based workflow allows us to describe overloads that mix static and instance
    methods. 
    """
    class StaticOverloads:
        class write:
            @staticmethod
            @typing.overload
            def __call__(arg__1: PySide6.QtCore.QObject, arg__2: str, arg__3: Any, /) -> bool: ...
            @staticmethod
            @typing.overload
            def __call__(arg__1: PySide6.QtCore.QObject, arg__2: str, arg__3: Any, arg__4: QQmlEngine, /) -> bool: ...
            @staticmethod
            @typing.overload
            def __call__(arg__1: PySide6.QtCore.QObject, arg__2: str, arg__3: Any, arg__4: QQmlContext, /) -> bool: ...

    class InstanceOverloads:
        class write:
            @typing.overload
            def __call__(self, arg__1: Any, /) -> bool: ...
            @typing.overload
            def __call__(self, arg__1: PySide6.QtCore.QObject, arg__2: str, arg__3: Any, /) -> bool: ...
            @typing.overload
            def __call__(self, arg__1: PySide6.QtCore.QObject, arg__2: str, arg__3: Any, arg__4: QQmlEngine, /) -> bool: ...
            @typing.overload
            def __call__(self, arg__1: PySide6.QtCore.QObject, arg__2: str, arg__3: Any, arg__4: QQmlContext, /) -> bool: ...

    def __init__(self, cb: typing.Callable) -> None: ...

    @typing.overload
    def __get__(self, object: None, owner: typing.Any) -> StaticOverloads.write: ...

    @typing.overload
    def __get__(self, object: QQmlProperty, owner: typing.Any) -> InstanceOverloads.write: ...

QML_HAS_ATTACHED_PROPERTIES: int

class ListProperty(PySide6.QtCore.Property):
    def __init__(self, type: type, /, append: collections.abc.Callable[..., typing.Any] | None = ..., at: collections.abc.Callable[..., typing.Any] | None = ..., clear: collections.abc.Callable[..., typing.Any] | None = ..., count: collections.abc.Callable[..., typing.Any] | None = ...) -> None: ...

class QIntList:
    __opaque_container__: typing.ClassVar[bool] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs): ...
    def capacity(self, *args, **kwargs): ...
    def clear(self, *args, **kwargs): ...
    def constData(self, *args, **kwargs): ...
    def data(self, *args, **kwargs): ...
    def pop_back(self, *args, **kwargs): ...
    def pop_front(self, *args, **kwargs): ...
    def prepend(self, *args, **kwargs): ...
    def push_back(self, *args, **kwargs): ...
    def push_front(self, *args, **kwargs): ...
    def removeFirst(self, *args, **kwargs): ...
    def removeLast(self, *args, **kwargs): ...
    def reserve(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, object) -> None: ...

class QJSEngine(PySide6.QtCore.QObject):
    class Extension(enum.Flag):
        AllExtensions = 4294967295
        ConsoleExtension = 2
        GarbageCollectionExtension = 4
        TranslationExtension = 1

    class ObjectOwnership(enum.Enum):
        CppOwnership = 0
        JavaScriptOwnership = 1
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    uiLanguageChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    @typing.overload
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, uiLanguage: str | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., uiLanguageChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, uiLanguage: str | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., uiLanguageChanged: typing.Callable = ...) -> None: ...
    def catchError(self, /) -> QJSValue: ...
    def collectGarbage(self, /) -> None: ...
    def evaluate(self, program: str, /, fileName: str = ..., lineNumber: int = ...) -> Tuple[QJSValue, List[str]]: ...
    def globalObject(self, /) -> QJSValue: ...
    def hasError(self, /) -> bool: ...
    def importModule(self, fileName: str, /) -> QJSValue: ...
    def installExtensions(self, extensions: QJSEngine.Extension, /, object: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int = ...) -> None: ...
    def isInterrupted(self, /) -> bool: ...
    def newArray(self, /, length: int | None = ...) -> QJSValue: ...
    def newErrorObject(self, errorType: QJSValue.ErrorType, /, message: str = ...) -> QJSValue: ...
    def newObject(self, /) -> QJSValue: ...
    def newQMetaObject(self, metaObject: PySide6.QtCore.QMetaObject, /) -> QJSValue: ...
    def newQObject(self, object: PySide6.QtCore.QObject, /) -> QJSValue: ...
    def newSymbol(self, name: str, /) -> QJSValue: ...
    @staticmethod
    def objectOwnership(arg__1: PySide6.QtCore.QObject, /) -> QJSEngine.ObjectOwnership: ...
    def registerModule(self, moduleName: str, value: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int, /) -> bool: ...
    def setInterrupted(self, interrupted: bool, /) -> None: ...
    @staticmethod
    def setObjectOwnership(arg__1: PySide6.QtCore.QObject, arg__2: QJSEngine.ObjectOwnership, /) -> None: ...
    def setUiLanguage(self, language: str, /) -> None: ...
    @typing.overload
    def throwError(self, errorType: QJSValue.ErrorType, /, message: str = ...) -> None: ...
    @typing.overload
    def throwError(self, message: str, /) -> None: ...
    @typing.overload
    def throwError(self, error: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int, /) -> None: ...
    def toScriptValue(self, value: Any, /) -> QJSValue: ...
    def uiLanguage(self, /) -> str: ...

class QJSManagedValue(shiboken6.Object):
    class Type(enum.Enum):
        Boolean = 1
        Function = 6
        Number = 2
        Object = 4
        String = 3
        Symbol = 5
        Undefined = 0
    @typing.overload
    def __init__(self, variant: Any, engine: QJSEngine, /) -> None: ...
    @typing.overload
    def __init__(self, value: QJSPrimitiveValue | str | bool | float | int, engine: QJSEngine, /) -> None: ...  # type: ignore[overload-cannot-match]
    @typing.overload
    def __init__(self, value: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int, engine: QJSEngine, /) -> None: ...  # type: ignore[overload-cannot-match]
    @typing.overload
    def __init__(self, string: str, engine: QJSEngine, /) -> None: ...  # type: ignore[overload-cannot-match]
    @typing.overload
    def __init__(self, /) -> None: ...
    def call(self, /, arguments: typing.Iterable[QJSValue] = ...) -> QJSValue: ...
    def callAsConstructor(self, /, arguments: typing.Iterable[QJSValue] = ...) -> QJSValue: ...
    def callWithInstance(self, instance: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int, /, arguments: typing.Iterable[QJSValue] = ...) -> QJSValue: ...
    @typing.overload
    def deleteProperty(self, name: str, /) -> bool: ...
    @typing.overload
    def deleteProperty(self, arrayIndex: int, /) -> bool: ...
    def engine(self, /) -> QJSEngine: ...
    def equals(self, other: QJSManagedValue, /) -> bool: ...
    @typing.overload
    def hasOwnProperty(self, name: str, /) -> bool: ...
    @typing.overload
    def hasOwnProperty(self, arrayIndex: int, /) -> bool: ...
    @typing.overload
    def hasProperty(self, name: str, /) -> bool: ...
    @typing.overload
    def hasProperty(self, arrayIndex: int, /) -> bool: ...
    def isArray(self, /) -> bool: ...
    def isBoolean(self, /) -> bool: ...
    def isDate(self, /) -> bool: ...
    def isError(self, /) -> bool: ...
    def isFunction(self, /) -> bool: ...
    def isInteger(self, /) -> bool: ...
    def isJsMetaType(self, /) -> bool: ...
    def isNull(self, /) -> bool: ...
    def isNumber(self, /) -> bool: ...
    def isObject(self, /) -> bool: ...
    def isQMetaObject(self, /) -> bool: ...
    def isQObject(self, /) -> bool: ...
    def isRegularExpression(self, /) -> bool: ...
    def isString(self, /) -> bool: ...
    def isSymbol(self, /) -> bool: ...
    def isUndefined(self, /) -> bool: ...
    def isUrl(self, /) -> bool: ...
    def isVariant(self, /) -> bool: ...
    def jsMetaInstantiate(self, /, values: typing.Iterable[QJSValue] = ...) -> QJSManagedValue: ...
    def jsMetaMembers(self, /) -> List[str]: ...
    def jsMetaType(self, /) -> QJSManagedValue: ...
    @typing.overload
    def property(self, name: str, /) -> QJSValue: ...
    @typing.overload
    def property(self, arrayIndex: int, /) -> QJSValue: ...
    def prototype(self, /) -> QJSManagedValue: ...
    @typing.overload
    def setProperty(self, name: str, value: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int, /) -> None: ...
    @typing.overload
    def setProperty(self, arrayIndex: int, value: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int, /) -> None: ...
    def setPrototype(self, prototype: QJSManagedValue, /) -> None: ...
    def strictlyEquals(self, other: QJSManagedValue, /) -> bool: ...
    def toBoolean(self, /) -> bool: ...
    def toDateTime(self, /) -> PySide6.QtCore.QDateTime: ...
    def toInteger(self, /) -> int: ...
    def toJSValue(self, /) -> QJSValue: ...
    def toNumber(self, /) -> float: ...
    def toPrimitive(self, /) -> QJSPrimitiveValue: ...
    def toQMetaObject(self, /) -> PySide6.QtCore.QMetaObject: ...
    def toQObject(self, /) -> PySide6.QtCore.QObject: ...
    def toRegularExpression(self, /) -> PySide6.QtCore.QRegularExpression: ...
    def toString(self, /) -> str: ...
    def toUrl(self, /) -> PySide6.QtCore.QUrl: ...
    def toVariant(self, /) -> Any: ...
    def type(self, /) -> QJSManagedValue.Type: ...
    def __bool__(self) -> bool: ...

class QJSPrimitiveValue(shiboken6.Object):
    class Type(enum.Enum):
        Boolean = 2
        Double = 4
        Integer = 3
        Null = 1
        String = 5
        Undefined = 0
    @typing.overload
    def __init__(self, type: PySide6.QtCore.QMetaType | PySide6.QtCore.QMetaType.Type, value: int, /) -> None: ...
    @typing.overload
    def __init__(self, variant: Any, /) -> None: ...
    @typing.overload
    def __init__(self, value: bool, /) -> None: ...  # type: ignore[overload-cannot-match]
    @typing.overload
    def __init__(self, value: int, /) -> None: ...  # type: ignore[overload-cannot-match]
    @typing.overload
    def __init__(self, value: float, /) -> None: ...  # type: ignore[overload-cannot-match]
    @typing.overload
    def __init__(self, type: PySide6.QtCore.QMetaType | PySide6.QtCore.QMetaType.Type, /) -> None: ...  # type: ignore[overload-cannot-match]
    @typing.overload
    def __init__(self, string: str, /) -> None: ...  # type: ignore[overload-cannot-match]
    @typing.overload
    def __init__(self, QJSPrimitiveValue: QJSPrimitiveValue, /) -> None: ...  # type: ignore[overload-cannot-match]
    @typing.overload
    def __init__(self, /) -> None: ...
    def constData(self, /) -> int: ...
    def data(self, /) -> int: ...
    def equals(self, other: QJSPrimitiveValue | str | bool | float | int, /) -> bool: ...
    def metaType(self, /) -> PySide6.QtCore.QMetaType: ...
    def strictlyEquals(self, other: QJSPrimitiveValue | str | bool | float | int, /) -> bool: ...
    def toBoolean(self, /) -> bool: ...
    def toDouble(self, /) -> float: ...
    def toInteger(self, /) -> int: ...
    def toString(self, /) -> str: ...
    def toVariant(self, /) -> Any: ...
    def type(self, /) -> QJSPrimitiveValue.Type: ...
    def __add__(self, rhs: QJSPrimitiveValue | str | bool | float | int, /) -> QJSPrimitiveValue: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __iadd__(self, arg__1: int, /) -> QJSPrimitiveValue: ...  # type: ignore[misc]
    def __isub__(self, arg__1: int, /) -> QJSPrimitiveValue: ...  # type: ignore[misc]
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __mod__(self, rhs: QJSPrimitiveValue | str | bool | float | int, /) -> QJSPrimitiveValue: ...
    def __mul__(self, rhs: QJSPrimitiveValue | str | bool | float | int, /) -> QJSPrimitiveValue: ...
    def __ne__(self, other: object) -> bool: ...
    def __neg__(self, /) -> QJSPrimitiveValue: ...
    def __pos__(self, /) -> QJSPrimitiveValue: ...
    def __radd__(self, other): ...
    def __rmod__(self, other): ...
    def __rmul__(self, other): ...
    def __rsub__(self, other): ...
    def __rtruediv__(self, other): ...
    def __sub__(self, rhs: QJSPrimitiveValue | str | bool | float | int, /) -> QJSPrimitiveValue: ...
    def __truediv__(self, other): ...

class QJSValue(shiboken6.Object):
    class ErrorType(enum.Enum):
        EvalError = 2
        GenericError = 1
        NoError = 0
        RangeError = 3
        ReferenceError = 4
        SyntaxError = 5
        TypeError = 6
        URIError = 7

    class ObjectConversionBehavior(enum.Enum):
        ConvertJSObjects = 0
        RetainJSObjects = 1

    class SpecialValue(enum.Enum):
        NullValue = 0
        UndefinedValue = 1
    @typing.overload
    def __init__(self, value: str, /) -> None: ...
    @typing.overload
    def __init__(self, value: bool, /) -> None: ...
    @typing.overload
    def __init__(self, value: int, /) -> None: ...
    @typing.overload
    def __init__(self, value: float, /) -> None: ...
    @typing.overload
    def __init__(self, str: bytes | bytearray | memoryview, /) -> None: ...
    @typing.overload
    def __init__(self, other: QJSValue, /) -> None: ...
    @typing.overload
    def __init__(self, /, value: QJSValue.SpecialValue = ...) -> None: ...
    def call(self, /, args: typing.Iterable[QJSValue] = ...) -> QJSValue: ...
    def callAsConstructor(self, /, args: typing.Iterable[QJSValue] = ...) -> QJSValue: ...
    def callWithInstance(self, instance: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int, /, args: typing.Iterable[QJSValue] = ...) -> QJSValue: ...
    def deleteProperty(self, name: str, /) -> bool: ...
    def equals(self, other: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int, /) -> bool: ...
    def errorType(self, /) -> QJSValue.ErrorType: ...
    def hasOwnProperty(self, name: str, /) -> bool: ...
    def hasProperty(self, name: str, /) -> bool: ...
    def isArray(self, /) -> bool: ...
    def isBool(self, /) -> bool: ...
    def isCallable(self, /) -> bool: ...
    def isDate(self, /) -> bool: ...
    def isError(self, /) -> bool: ...
    def isNull(self, /) -> bool: ...
    def isNumber(self, /) -> bool: ...
    def isObject(self, /) -> bool: ...
    def isQMetaObject(self, /) -> bool: ...
    def isQObject(self, /) -> bool: ...
    def isRegExp(self, /) -> bool: ...
    def isString(self, /) -> bool: ...
    def isUndefined(self, /) -> bool: ...
    def isUrl(self, /) -> bool: ...
    def isVariant(self, /) -> bool: ...
    @typing.overload
    def property(self, name: str, /) -> QJSValue: ...
    @typing.overload
    def property(self, arrayIndex: int, /) -> QJSValue: ...
    def prototype(self, /) -> QJSValue: ...
    @typing.overload
    def setProperty(self, name: str, value: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int, /) -> None: ...
    @typing.overload
    def setProperty(self, arrayIndex: int, value: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int, /) -> None: ...
    def setPrototype(self, prototype: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int, /) -> None: ...
    def strictlyEquals(self, other: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int, /) -> bool: ...
    def toBool(self, /) -> bool: ...
    def toDateTime(self, /) -> PySide6.QtCore.QDateTime: ...
    def toInt(self, /) -> int: ...
    def toNumber(self, /) -> float: ...
    def toPrimitive(self, /) -> QJSPrimitiveValue: ...
    def toQMetaObject(self, /) -> PySide6.QtCore.QMetaObject: ...
    def toQObject(self, /) -> PySide6.QtCore.QObject: ...
    def toString(self, /) -> str: ...
    def toUInt(self, /) -> int: ...
    @typing.overload
    def toVariant(self, behavior: QJSValue.ObjectConversionBehavior, /) -> Any: ...
    @typing.overload
    def toVariant(self, /) -> Any: ...
    def __bool__(self) -> bool: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __lshift__(self, arg__1: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
    def __rlshift__(self, other): ...
    def __rrshift__(self, other): ...
    def __rshift__(self, arg__1: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...

class QJSValueIterator(shiboken6.Object):
    def __init__(self, value: QJSValue | QJSValue.SpecialValue | bool | str | bytes | bytearray | memoryview | float | int, /) -> None: ...
    def hasNext(self, /) -> bool: ...
    def name(self, /) -> str: ...
    def next(self, /) -> bool: ...
    def value(self, /) -> QJSValue: ...

class QPyQmlParserStatus(PySide6.QtCore.QObject, QQmlParserStatus):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...

class QPyQmlPropertyValueSource(PySide6.QtCore.QObject, QQmlPropertyValueSource):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...

class QQmlAbstractUrlInterceptor(shiboken6.Object):
    class DataType(enum.Enum):
        JavaScriptFile = 1
        QmlFile = 0
        QmldirFile = 2
        UrlString = 4096
    def __init__(self, /) -> None: ...
    def intercept(self, path: PySide6.QtCore.QUrl | str, type: QQmlAbstractUrlInterceptor.DataType, /) -> PySide6.QtCore.QUrl: ...

class QQmlApplicationEngine(QQmlEngine):
    objectCreated: typing.ClassVar[PySide6.QtCore.Signal] = ...
    objectCreationFailed: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    @typing.overload
    def __init__(self, uri: str, typeName: str, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., exit: typing.Callable = ..., objectCreated: typing.Callable = ..., objectCreationFailed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., offlineStoragePath: str = ..., offlineStoragePathChanged: typing.Callable = ..., quit: typing.Callable = ..., uiLanguage: str = ..., uiLanguageChanged: typing.Callable = ..., warnings: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, url: PySide6.QtCore.QUrl | str, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., exit: typing.Callable = ..., objectCreated: typing.Callable = ..., objectCreationFailed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., offlineStoragePath: str = ..., offlineStoragePathChanged: typing.Callable = ..., quit: typing.Callable = ..., uiLanguage: str = ..., uiLanguageChanged: typing.Callable = ..., warnings: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, filePath: str, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., exit: typing.Callable = ..., objectCreated: typing.Callable = ..., objectCreationFailed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., offlineStoragePath: str = ..., offlineStoragePathChanged: typing.Callable = ..., quit: typing.Callable = ..., uiLanguage: str = ..., uiLanguageChanged: typing.Callable = ..., warnings: typing.Callable = ...) -> None: ...  # type: ignore[overload-cannot-match]
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., exit: typing.Callable = ..., objectCreated: typing.Callable = ..., objectCreationFailed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., offlineStoragePath: str = ..., offlineStoragePathChanged: typing.Callable = ..., quit: typing.Callable = ..., uiLanguage: str = ..., uiLanguageChanged: typing.Callable = ..., warnings: typing.Callable = ...) -> None: ...
    @typing.overload
    def load(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    @typing.overload
    def load(self, filePath: str | bytes | os.PathLike[str], /) -> None: ...
    def loadData(self, data: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /, url: PySide6.QtCore.QUrl | str = ...) -> None: ...
    def loadFromModule(self, uri: str, typeName: str, /) -> None: ...
    def rootObjects(self, /) -> List[PySide6.QtCore.QObject]: ...
    def setExtraFileSelectors(self, extraFileSelectors: typing.Iterable[str], /) -> None: ...
    def setInitialProperties(self, initialProperties: Dict[str, Any], /) -> None: ...

class QQmlComponent(PySide6.QtCore.QObject):
    class CompilationMode(enum.Enum):
        Asynchronous = 1
        PreferSynchronous = 0

    class Status(enum.Enum):
        Error = 3
        Loading = 2
        Null = 0
        Ready = 1
    progressChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    statusChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    @typing.overload
    def __init__(self, engine: QQmlEngine, uri: str, typeName: str, mode: QQmlComponent.CompilationMode, /, parent: PySide6.QtCore.QObject | None = ..., *, progress: float | None = ..., status: QQmlComponent.Status | None = ..., url: PySide6.QtCore.QUrl | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., progressChanged: typing.Callable = ..., statusChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, engine: QQmlEngine, uri: str, typeName: str, /, parent: PySide6.QtCore.QObject | None = ..., *, progress: float | None = ..., status: QQmlComponent.Status | None = ..., url: PySide6.QtCore.QUrl | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., progressChanged: typing.Callable = ..., statusChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, arg__1: QQmlEngine, fileName: str, mode: QQmlComponent.CompilationMode, /, parent: PySide6.QtCore.QObject | None = ..., *, progress: float | None = ..., status: QQmlComponent.Status | None = ..., url: PySide6.QtCore.QUrl | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., progressChanged: typing.Callable = ..., statusChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, arg__1: QQmlEngine, url: PySide6.QtCore.QUrl | str, mode: QQmlComponent.CompilationMode, /, parent: PySide6.QtCore.QObject | None = ..., *, progress: float | None = ..., status: QQmlComponent.Status | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., progressChanged: typing.Callable = ..., statusChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, arg__1: QQmlEngine, fileName: str, /, parent: PySide6.QtCore.QObject | None = ..., *, progress: float | None = ..., status: QQmlComponent.Status | None = ..., url: PySide6.QtCore.QUrl | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., progressChanged: typing.Callable = ..., statusChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, arg__1: QQmlEngine, url: PySide6.QtCore.QUrl | str, /, parent: PySide6.QtCore.QObject | None = ..., *, progress: float | None = ..., status: QQmlComponent.Status | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., progressChanged: typing.Callable = ..., statusChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, arg__1: QQmlEngine, /, parent: PySide6.QtCore.QObject | None = ..., *, progress: float | None = ..., status: QQmlComponent.Status | None = ..., url: PySide6.QtCore.QUrl | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., progressChanged: typing.Callable = ..., statusChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, progress: float | None = ..., status: QQmlComponent.Status | None = ..., url: PySide6.QtCore.QUrl | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., progressChanged: typing.Callable = ..., statusChanged: typing.Callable = ...) -> None: ...
    def beginCreate(self, arg__1: QQmlContext, /) -> PySide6.QtCore.QObject: ...
    def completeCreate(self, /) -> None: ...
    @typing.overload
    def create(self, arg__1: QQmlIncubator, /, context: QQmlContext | None = ..., forContext: QQmlContext | None = ...) -> None: ...
    @typing.overload
    def create(self, /, context: QQmlContext | None = ...) -> PySide6.QtCore.QObject: ...
    def createObject(self, /, parent: PySide6.QtCore.QObject | None = ..., properties: Dict[str, Any] = ...) -> PySide6.QtCore.QObject: ...
    def createWithInitialProperties(self, initialProperties: Dict[str, Any], /, context: QQmlContext | None = ...) -> PySide6.QtCore.QObject: ...
    def creationContext(self, /) -> QQmlContext: ...
    def engine(self, /) -> QQmlEngine: ...
    def errorString(self, /) -> str: ...
    def errors(self, /) -> List[QQmlError]: ...
    def isBound(self, /) -> bool: ...
    def isError(self, /) -> bool: ...
    def isLoading(self, /) -> bool: ...
    def isNull(self, /) -> bool: ...
    def isReady(self, /) -> bool: ...
    def loadFromModule(self, uri: str, typeName: str, /, mode: QQmlComponent.CompilationMode = ...) -> None: ...
    @typing.overload
    def loadUrl(self, url: PySide6.QtCore.QUrl | str, mode: QQmlComponent.CompilationMode, /) -> None: ...
    @typing.overload
    def loadUrl(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def progress(self, /) -> float: ...
    def setData(self, arg__1: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, baseUrl: PySide6.QtCore.QUrl | str, /) -> None: ...
    def setInitialProperties(self, component: PySide6.QtCore.QObject, properties: Dict[str, Any], /) -> None: ...
    def status(self, /) -> QQmlComponent.Status: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...
    def __bool__(self) -> bool: ...

class QQmlContext(PySide6.QtCore.QObject):
    class PropertyPair(shiboken6.Object):
        name: _typeshed.Incomplete
        value: _typeshed.Incomplete
        @typing.overload
        def __init__(self, PropertyPair: QQmlContext.PropertyPair, /) -> None: ...
        @typing.overload
        def __init__(self, /) -> None: ...
        def __copy__(self, /) -> typing_extensions.Self: ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    @typing.overload
    def __init__(self, parent: QQmlEngine, /, objParent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, parent: QQmlContext, /, objParent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def baseUrl(self, /) -> PySide6.QtCore.QUrl: ...
    def contextObject(self, /) -> PySide6.QtCore.QObject: ...
    def contextProperty(self, arg__1: str, /) -> Any: ...
    def engine(self, /) -> QQmlEngine: ...
    def importedScript(self, name: str, /) -> QJSValue: ...
    def isValid(self, /) -> bool: ...
    def nameForObject(self, arg__1: PySide6.QtCore.QObject, /) -> str: ...
    def objectForName(self, arg__1: str, /) -> PySide6.QtCore.QObject: ...
    def parentContext(self, /) -> QQmlContext: ...
    def resolvedUrl(self, arg__1: PySide6.QtCore.QUrl | str, /) -> PySide6.QtCore.QUrl: ...
    def setBaseUrl(self, arg__1: PySide6.QtCore.QUrl | str, /) -> None: ...
    def setContextObject(self, arg__1: PySide6.QtCore.QObject, /) -> None: ...
    def setContextProperties(self, properties: typing.Iterable[QQmlContext.PropertyPair], /) -> None: ...
    @typing.overload
    def setContextProperty(self, arg__1: str, arg__2: PySide6.QtCore.QObject, /) -> None: ...
    @typing.overload
    def setContextProperty(self, arg__1: str, arg__2: Any, /) -> None: ...

class QQmlDebuggingEnabler(shiboken6.Object):
    class StartMode(enum.Enum):
        DoNotWaitForClient = 0
        WaitForClient = 1
    def __init__(self, /, printWarning: bool = ...) -> None: ...
    @staticmethod
    def connectToLocalDebugger(socketFileName: str, /, mode: QQmlDebuggingEnabler.StartMode = ...) -> bool: ...
    @staticmethod
    def debuggerServices() -> List[str]: ...
    @staticmethod
    def enableDebugging(printWarning: bool, /) -> None: ...
    @staticmethod
    def inspectorServices() -> List[str]: ...
    @staticmethod
    def nativeDebuggerServices() -> List[str]: ...
    @staticmethod
    def profilerServices() -> List[str]: ...
    @staticmethod
    def setServices(services: typing.Iterable[str], /) -> None: ...
    @staticmethod
    def startDebugConnector(pluginName: str, /, configuration: Dict[str, Any] = ...) -> bool: ...
    @staticmethod
    def startTcpDebugServer(port: int, /, mode: QQmlDebuggingEnabler.StartMode = ..., hostName: str = ...) -> bool: ...

class QQmlEngine(QJSEngine):
    exit: typing.ClassVar[PySide6.QtCore.Signal] = ...
    offlineStoragePathChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    quit: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    warnings: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, /, p: PySide6.QtCore.QObject | None = ..., *, offlineStoragePath: str | None = ..., destroyed: typing.Callable = ..., exit: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., offlineStoragePathChanged: typing.Callable = ..., quit: typing.Callable = ..., uiLanguage: str = ..., uiLanguageChanged: typing.Callable = ..., warnings: typing.Callable = ...) -> None: ...
    def addImageProvider(self, id: str, arg__2: QQmlImageProviderBase, /) -> None: ...
    def addImportPath(self, dir: str | bytes | os.PathLike[str], /) -> None: ...
    def addNamedBundle(self, arg__1: str, arg__2: str, /) -> bool: ...
    def addPluginPath(self, dir: str | bytes | os.PathLike[str], /) -> None: ...
    def addUrlInterceptor(self, urlInterceptor: QQmlAbstractUrlInterceptor, /) -> None: ...
    def baseUrl(self, /) -> PySide6.QtCore.QUrl: ...
    def captureProperty(self, object: PySide6.QtCore.QObject, property: PySide6.QtCore.QMetaProperty, /) -> None: ...
    def clearComponentCache(self, /) -> None: ...
    def clearSingletons(self, /) -> None: ...
    @staticmethod
    def contextForObject(arg__1: PySide6.QtCore.QObject, /) -> QQmlContext: ...
    def event(self, arg__1: PySide6.QtCore.QEvent, /) -> bool: ...
    def imageProvider(self, id: str, /) -> QQmlImageProviderBase: ...
    def importPathList(self, /) -> List[str]: ...
    def importPlugin(self, filePath: str, uri: str, errors: typing.Iterable[QQmlError], /) -> bool: ...
    def incubationController(self, /) -> QQmlIncubationController: ...
    def interceptUrl(self, url: PySide6.QtCore.QUrl | str, type: QQmlAbstractUrlInterceptor.DataType, /) -> PySide6.QtCore.QUrl: ...
    def markCurrentFunctionAsTranslationBinding(self, /) -> None: ...
    def networkAccessManager(self, /) -> PySide6.QtNetwork.QNetworkAccessManager: ...
    def networkAccessManagerFactory(self, /) -> QQmlNetworkAccessManagerFactory: ...
    def offlineStorageDatabaseFilePath(self, databaseName: str, /) -> str: ...
    def offlineStoragePath(self, /) -> str: ...
    def outputWarningsToStandardError(self, /) -> bool: ...
    def pluginPathList(self, /) -> List[str]: ...
    def removeImageProvider(self, id: str, /) -> None: ...
    def removeUrlInterceptor(self, urlInterceptor: QQmlAbstractUrlInterceptor, /) -> None: ...
    def retranslate(self, /) -> None: ...
    def rootContext(self, /) -> QQmlContext: ...
    def setBaseUrl(self, arg__1: PySide6.QtCore.QUrl | str, /) -> None: ...
    @staticmethod
    def setContextForObject(arg__1: PySide6.QtCore.QObject, arg__2: QQmlContext, /) -> None: ...
    def setImportPathList(self, paths: typing.Iterable[str], /) -> None: ...
    def setIncubationController(self, arg__1: QQmlIncubationController, /) -> None: ...
    def setNetworkAccessManagerFactory(self, arg__1: QQmlNetworkAccessManagerFactory, /) -> None: ...
    def setOfflineStoragePath(self, dir: str, /) -> None: ...
    def setOutputWarningsToStandardError(self, arg__1: bool, /) -> None: ...
    def setPluginPathList(self, paths: typing.Iterable[str], /) -> None: ...
    def setUrlInterceptor(self, urlInterceptor: QQmlAbstractUrlInterceptor, /) -> None: ...
    @typing.overload
    def singletonInstance(self, uri: str, typeName: str, /) -> PySide6.QtCore.QObject | QJSValue | None: ...
    @typing.overload
    def singletonInstance(self, qmlTypeId: int, /) -> PySide6.QtCore.QObject | QJSValue | None: ...
    def trimComponentCache(self, /) -> None: ...
    def urlInterceptor(self, /) -> QQmlAbstractUrlInterceptor: ...
    def urlInterceptors(self, /) -> List[QQmlAbstractUrlInterceptor]: ...

class QQmlError(shiboken6.Object):
    @typing.overload
    def __init__(self, arg__1: QQmlError, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def column(self, /) -> int: ...
    def description(self, /) -> str: ...
    def isValid(self, /) -> bool: ...
    def line(self, /) -> int: ...
    def messageType(self, /) -> PySide6.QtCore.QtMsgType: ...
    def object(self, /) -> PySide6.QtCore.QObject: ...
    def setColumn(self, arg__1: int, /) -> None: ...
    def setDescription(self, arg__1: str, /) -> None: ...
    def setLine(self, arg__1: int, /) -> None: ...
    def setMessageType(self, messageType: PySide6.QtCore.QtMsgType, /) -> None: ...
    def setObject(self, arg__1: PySide6.QtCore.QObject, /) -> None: ...
    def setUrl(self, arg__1: PySide6.QtCore.QUrl | str, /) -> None: ...
    def swap(self, other: QQmlError, /) -> None: ...
    def toString(self, /) -> str: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...
    def __copy__(self, /) -> typing_extensions.Self: ...

class QQmlExpression(PySide6.QtCore.QObject):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    valueChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    @typing.overload
    def __init__(self, arg__1: QQmlContext, arg__2: PySide6.QtCore.QObject, arg__3: str, /, arg__4: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., valueChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, arg__1: QQmlScriptString, /, arg__2: QQmlContext | None = ..., arg__3: PySide6.QtCore.QObject | None = ..., arg__4: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., valueChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., valueChanged: typing.Callable = ...) -> None: ...
    def clearError(self, /) -> None: ...
    def columnNumber(self, /) -> int: ...
    def context(self, /) -> QQmlContext: ...
    def engine(self, /) -> QQmlEngine: ...
    def error(self, /) -> QQmlError: ...
    def evaluate(self, /) -> Tuple[Any, bool]: ...
    def expression(self, /) -> str: ...
    def hasError(self, /) -> bool: ...
    def lineNumber(self, /) -> int: ...
    def notifyOnValueChanged(self, /) -> bool: ...
    def scopeObject(self, /) -> PySide6.QtCore.QObject: ...
    def setExpression(self, arg__1: str, /) -> None: ...
    def setNotifyOnValueChanged(self, arg__1: bool, /) -> None: ...
    def setSourceLocation(self, fileName: str, line: int, /, column: int | None = ...) -> None: ...
    def sourceFile(self, /) -> str: ...

class QQmlExtensionInterface(QQmlTypesExtensionInterface):
    def __init__(self, /) -> None: ...
    def initializeEngine(self, engine: QQmlEngine, uri: bytes | bytearray | memoryview, /) -> None: ...

class QQmlExtensionPlugin(PySide6.QtCore.QObject, QQmlExtensionInterface):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def baseUrl(self, /) -> PySide6.QtCore.QUrl: ...
    def initializeEngine(self, engine: QQmlEngine, uri: bytes | bytearray | memoryview, /) -> None: ...
    def registerTypes(self, uri: bytes | bytearray | memoryview, /) -> None: ...
    def unregisterTypes(self, /) -> None: ...

class QQmlFile(shiboken6.Object):
    class Status(enum.Enum):
        Error = 2
        Loading = 3
        Null = 0
        Ready = 1
    @typing.overload
    def __init__(self, engine: QQmlEngine, url: str, /) -> None: ...
    @typing.overload
    def __init__(self, engine: QQmlEngine, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def clear(self, object: PySide6.QtCore.QObject, /) -> None: ...
    @typing.overload
    def clear(self, /) -> None: ...
    @typing.overload
    def connectDownloadProgress(self, arg__1: PySide6.QtCore.QObject, arg__2: bytes | bytearray | memoryview, /) -> bool: ...
    @typing.overload
    def connectDownloadProgress(self, arg__1: PySide6.QtCore.QObject, arg__2: int, /) -> bool: ...
    @typing.overload
    def connectFinished(self, arg__1: PySide6.QtCore.QObject, arg__2: bytes | bytearray | memoryview, /) -> bool: ...
    @typing.overload
    def connectFinished(self, arg__1: PySide6.QtCore.QObject, arg__2: int, /) -> bool: ...
    def data(self, /) -> bytes | bytearray | memoryview: ...
    def dataByteArray(self, /) -> PySide6.QtCore.QByteArray: ...
    def error(self, /) -> str: ...
    def isError(self, /) -> bool: ...
    def isLoading(self, /) -> bool: ...
    @typing.overload
    @staticmethod
    def isLocalFile(url: str, /) -> bool: ...
    @typing.overload
    @staticmethod
    def isLocalFile(url: PySide6.QtCore.QUrl | str, /) -> bool: ...
    def isNull(self, /) -> bool: ...
    def isReady(self, /) -> bool: ...
    @typing.overload
    @staticmethod
    def isSynchronous(url: str, /) -> bool: ...
    @typing.overload
    @staticmethod
    def isSynchronous(url: PySide6.QtCore.QUrl | str, /) -> bool: ...
    @typing.overload
    def load(self, arg__1: QQmlEngine, arg__2: str, /) -> None: ...
    @typing.overload
    def load(self, arg__1: QQmlEngine, arg__2: PySide6.QtCore.QUrl | str, /) -> None: ...
    def size(self, /) -> int: ...
    def status(self, /) -> QQmlFile.Status: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...
    @typing.overload
    @staticmethod
    def urlToLocalFileOrQrc(arg__1: str, /) -> str: ...
    @typing.overload
    @staticmethod
    def urlToLocalFileOrQrc(arg__1: PySide6.QtCore.QUrl | str, /) -> str: ...
    def __bool__(self) -> bool: ...

class QQmlFileSelector(PySide6.QtCore.QObject):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, engine: QQmlEngine, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    @staticmethod
    def get(arg__1: QQmlEngine, /) -> QQmlFileSelector: ...
    def selector(self, /) -> PySide6.QtCore.QFileSelector: ...
    def setExtraSelectors(self, strings: typing.Iterable[str], /) -> None: ...
    def setSelector(self, selector: PySide6.QtCore.QFileSelector, /) -> None: ...

class QQmlImageProviderBase(PySide6.QtCore.QObject):
    class Flag(enum.Flag):
        ForceAsynchronousImageLoading = 1

    class ImageType(enum.Enum):
        Image = 1
        ImageResponse = 4
        Invalid = 0
        Pixmap = 2
        Texture = 3
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, *args, destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., **kwargs) -> None: ...
    def flags(self, /) -> QQmlImageProviderBase.Flag: ...
    def imageType(self, /) -> QQmlImageProviderBase.ImageType: ...

class QQmlIncubationController(shiboken6.Object):
    def __init__(self, /) -> None: ...
    def engine(self, /) -> QQmlEngine: ...
    def incubateFor(self, msecs: int, /) -> None: ...
    def incubateWhile(self, flag: VolatileBool, /, msecs: int | None = ...) -> None: ...
    def incubatingObjectCount(self, /) -> int: ...
    def incubatingObjectCountChanged(self, arg__1: int, /) -> None: ...

class QQmlIncubator(shiboken6.Object):
    class IncubationMode(enum.Enum):
        Asynchronous = 0
        AsynchronousIfNested = 1
        Synchronous = 2

    class Status(enum.Enum):
        Error = 3
        Loading = 2
        Null = 0
        Ready = 1
    def __init__(self, /, arg__1: QQmlIncubator.IncubationMode = ...) -> None: ...
    def clear(self, /) -> None: ...
    def errors(self, /) -> List[QQmlError]: ...
    def forceCompletion(self, /) -> None: ...
    def incubationMode(self, /) -> QQmlIncubator.IncubationMode: ...
    def isError(self, /) -> bool: ...
    def isLoading(self, /) -> bool: ...
    def isNull(self, /) -> bool: ...
    def isReady(self, /) -> bool: ...
    def object(self, /) -> PySide6.QtCore.QObject: ...
    def setInitialProperties(self, initialProperties: Dict[str, Any], /) -> None: ...
    def setInitialState(self, arg__1: PySide6.QtCore.QObject, /) -> None: ...
    def status(self, /) -> QQmlIncubator.Status: ...
    def statusChanged(self, arg__1: QQmlIncubator.Status, /) -> None: ...
    def __bool__(self) -> bool: ...

class QQmlListReference(shiboken6.Object):
    @typing.overload
    def __init__(self, o: PySide6.QtCore.QObject, property: bytes | bytearray | memoryview, engine: QQmlEngine, /) -> None: ...
    @typing.overload
    def __init__(self, variant: Any, engine: QQmlEngine, /) -> None: ...
    @typing.overload
    def __init__(self, o: PySide6.QtCore.QObject, property: bytes | bytearray | memoryview, /) -> None: ...
    @typing.overload
    def __init__(self, variant: Any, /) -> None: ...
    @typing.overload
    def __init__(self, arg__1: QQmlListReference, /) -> None: ...  # type: ignore[overload-cannot-match]
    @typing.overload
    def __init__(self, /) -> None: ...
    def append(self, arg__1: PySide6.QtCore.QObject, /) -> bool: ...
    def at(self, arg__1: int, /) -> PySide6.QtCore.QObject: ...
    def canAppend(self, /) -> bool: ...
    def canAt(self, /) -> bool: ...
    def canClear(self, /) -> bool: ...
    def canCount(self, /) -> bool: ...
    def canRemoveLast(self, /) -> bool: ...
    def canReplace(self, /) -> bool: ...
    def clear(self, /) -> bool: ...
    def count(self, /) -> int: ...
    def isManipulable(self, /) -> bool: ...
    def isReadable(self, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    def listElementType(self, /) -> PySide6.QtCore.QMetaObject: ...
    def object(self, /) -> PySide6.QtCore.QObject: ...
    def removeLast(self, /) -> bool: ...
    def replace(self, arg__1: int, arg__2: PySide6.QtCore.QObject, /) -> bool: ...
    def size(self, /) -> int: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...  # type: ignore[valid-type]
    def __ge__(self, other: object) -> bool: ...  # type: ignore[valid-type]
    def __gt__(self, other: object) -> bool: ...  # type: ignore[valid-type]
    def __le__(self, other: object) -> bool: ...  # type: ignore[valid-type]
    def __lt__(self, other: object) -> bool: ...  # type: ignore[valid-type]
    def __ne__(self, other: object) -> bool: ...  # type: ignore[valid-type]

class QQmlModuleImportSpecialVersions(enum.Flag):
    QQmlModuleImportAuto = -2
    QQmlModuleImportLatest = -1
    QQmlModuleImportModuleAny = -1

class QQmlNetworkAccessManagerFactory(shiboken6.Object):
    def __init__(self, /) -> None: ...
    def create(self, parent: PySide6.QtCore.QObject | None, /) -> PySide6.QtNetwork.QNetworkAccessManager: ...

class QQmlParserStatus(shiboken6.Object):
    def __init__(self, /) -> None: ...
    def classBegin(self, /) -> None: ...
    def componentComplete(self, /) -> None: ...

class QQmlProperty(shiboken6.Object):
    class PropertyTypeCategory(enum.Enum):
        InvalidCategory = 0
        List = 1
        Normal = 3
        Object = 2

    class Type(enum.Enum):
        Invalid = 0
        Property = 1
        SignalProperty = 2
    @typing.overload
    def __init__(self, arg__1: PySide6.QtCore.QObject, arg__2: str, arg__3: QQmlEngine, /, *, object: PySide6.QtCore.QObject | None = ..., name: str | None = ...) -> None: ...
    @typing.overload
    def __init__(self, arg__1: PySide6.QtCore.QObject, arg__2: str, arg__3: QQmlContext, /, *, object: PySide6.QtCore.QObject | None = ..., name: str | None = ...) -> None: ...
    @typing.overload
    def __init__(self, arg__1: PySide6.QtCore.QObject, arg__2: QQmlEngine, /, *, object: PySide6.QtCore.QObject | None = ..., name: str | None = ...) -> None: ...
    @typing.overload
    def __init__(self, arg__1: PySide6.QtCore.QObject, arg__2: QQmlContext, /, *, object: PySide6.QtCore.QObject | None = ..., name: str | None = ...) -> None: ...
    @typing.overload
    def __init__(self, arg__1: PySide6.QtCore.QObject, arg__2: str, /, *, object: PySide6.QtCore.QObject | None = ..., name: str | None = ...) -> None: ...
    @typing.overload
    def __init__(self, arg__1: PySide6.QtCore.QObject, /, *, object: PySide6.QtCore.QObject | None = ..., name: str | None = ...) -> None: ...
    @typing.overload
    def __init__(self, arg__1: QQmlProperty, /, *, object: PySide6.QtCore.QObject | None = ..., name: str | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, object: PySide6.QtCore.QObject | None = ..., name: str | None = ...) -> None: ...
    @typing.overload
    def connectNotifySignal(self, dest: PySide6.QtCore.QObject, slot: bytes | bytearray | memoryview, /) -> bool: ...
    @typing.overload
    def connectNotifySignal(self, dest: PySide6.QtCore.QObject, method: int, /) -> bool: ...
    def hasNotifySignal(self, /) -> bool: ...
    def index(self, /) -> int: ...
    def isBindable(self, /) -> bool: ...
    def isDesignable(self, /) -> bool: ...
    def isProperty(self, /) -> bool: ...
    def isResettable(self, /) -> bool: ...
    def isSignalProperty(self, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    def isWritable(self, /) -> bool: ...
    def method(self, /) -> PySide6.QtCore.QMetaMethod: ...
    def name(self, /) -> str: ...
    def needsNotifySignal(self, /) -> bool: ...
    def object(self, /) -> PySide6.QtCore.QObject: ...
    def property(self, /) -> PySide6.QtCore.QMetaProperty: ...
    def propertyMetaType(self, /) -> PySide6.QtCore.QMetaType: ...
    def propertyType(self, /) -> int: ...
    def propertyTypeCategory(self, /) -> QQmlProperty.PropertyTypeCategory: ...
    def propertyTypeName(self, /) -> bytes | bytearray | memoryview: ...
    @_add_QQmlProperty_read_overloads
    def read(self) -> typing.Any: ...
    def reset(self, /) -> bool: ...
    def swap(self, other: QQmlProperty | PySide6.QtCore.QObject, /) -> None: ...
    def type(self, /) -> QQmlProperty.Type: ...
    @_add_QQmlProperty_write_overloads
    def write(self) -> typing.Any: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...  # type: ignore[valid-type]
    def __ge__(self, other: object) -> bool: ...  # type: ignore[valid-type]
    def __gt__(self, other: object) -> bool: ...  # type: ignore[valid-type]
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object) -> bool: ...  # type: ignore[valid-type]
    def __lt__(self, other: object) -> bool: ...  # type: ignore[valid-type]
    def __ne__(self, other: object) -> bool: ...  # type: ignore[valid-type]

class QQmlPropertyMap(PySide6.QtCore.QObject):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    valueChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., valueChanged: typing.Callable = ...) -> None: ...
    def clear(self, key: str, /) -> None: ...
    def contains(self, key: str, /) -> bool: ...
    def count(self, /) -> int: ...
    def freeze(self, /) -> None: ...
    @typing.overload
    def insert(self, key: str, value: Any, /) -> None: ...
    @typing.overload
    def insert(self, values: Dict[str, Any], /) -> None: ...
    def isEmpty(self, /) -> bool: ...
    def keys(self, /) -> List[str]: ...
    def size(self, /) -> int: ...
    def updateValue(self, key: str, input: Any, /) -> Any: ...
    def value(self, key: str, /) -> Any: ...

class QQmlPropertyValueSource(shiboken6.Object):
    def __init__(self, /) -> None: ...
    def setTarget(self, arg__1: QQmlProperty | PySide6.QtCore.QObject, /) -> None: ...

class QQmlScriptString(shiboken6.Object):
    @typing.overload
    def __init__(self, arg__1: QQmlScriptString, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def booleanLiteral(self, /) -> Tuple[bool, bool]: ...
    def isEmpty(self, /) -> bool: ...
    def isNullLiteral(self, /) -> bool: ...
    def isUndefinedLiteral(self, /) -> bool: ...
    def numberLiteral(self, /) -> Tuple[float, bool]: ...
    def stringLiteral(self, /) -> str: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QQmlTypesExtensionInterface(shiboken6.Object):
    def __init__(self, /) -> None: ...
    def registerTypes(self, uri: bytes | bytearray | memoryview, /) -> None: ...

class VolatileBool:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def get(self) -> bool: ...
    def set(self, a: object) -> None: ...

def QmlAnonymous(arg__1: object, /) -> typing.Any: ...
def QmlElement(arg__1: object, /) -> typing.Any: ...
def QmlSingleton(arg__1: object, /) -> typing.Any: ...
def qjsEngine(arg__1: PySide6.QtCore.QObject, /) -> QJSEngine | None: ...
def qmlAttachedPropertiesObject(type_obj: type, arg__2: PySide6.QtCore.QObject, /, arg__3: bool = ...) -> PySide6.QtCore.QObject: ...
def qmlClearTypeRegistrations() -> None: ...
def qmlContext(arg__1: PySide6.QtCore.QObject, /) -> QQmlContext | None: ...
def qmlEngine(arg__1: PySide6.QtCore.QObject, /) -> QQmlEngine | None: ...
def qmlProtectModule(uri: bytes | bytearray | memoryview, majVersion: int, /) -> bool: ...
def qmlRegisterModule(uri: bytes | bytearray | memoryview, versionMajor: int, versionMinor: int, /) -> None: ...
def qmlRegisterSingletonInstance(type_obj: type, uri: str, version_major: int, version_minor: int, qml_name: bytes | bytearray | memoryview, callback: object, /) -> int: ...
@typing.overload
def qmlRegisterSingletonType(type_obj: type, uri: str, version_major: int, version_minor: int, qml_name: bytes | bytearray | memoryview, callback: object, /) -> int: ...
@typing.overload
def qmlRegisterSingletonType(url: PySide6.QtCore.QUrl | str, uri: bytes | bytearray | memoryview, versionMajor: int, versionMinor: int, qmlName: bytes | bytearray | memoryview, /) -> int: ...
@typing.overload
def qmlRegisterSingletonType(uri: str, version_major: int, version_minor: int, qml_name: bytes | bytearray | memoryview, callback: object, /) -> int: ...
@typing.overload
def qmlRegisterSingletonType(type_obj: type, uri: str, version_major: int, version_minor: int, qml_name: bytes | bytearray | memoryview, /) -> int: ...
@typing.overload
def qmlRegisterType(url: PySide6.QtCore.QUrl | str, uri: bytes | bytearray | memoryview, versionMajor: int, versionMinor: int, qmlName: bytes | bytearray | memoryview, /) -> int: ...
@typing.overload
def qmlRegisterType(type_obj: type, uri: str, version_major: int, version_minor: int, qml_name: bytes | bytearray | memoryview, /) -> int: ...
def qmlRegisterUncreatableMetaObject(staticMetaObject: PySide6.QtCore.QMetaObject, uri: bytes | bytearray | memoryview, versionMajor: int, versionMinor: int, qmlName: bytes | bytearray | memoryview, reason: str, /) -> int: ...
def qmlRegisterUncreatableType(type_obj: type, uri: str, version_major: int, version_minor: int, qml_name: bytes | bytearray | memoryview, message: bytes | bytearray | memoryview, /) -> int: ...
def qmlTypeId(uri: bytes | bytearray | memoryview, versionMajor: int, versionMinor: int, qmlName: bytes | bytearray | memoryview, /) -> int: ...
