import PySide6.QtCore
import _typeshed
import builtins
import collections
import enum
import shiboken6
import typing
import typing_extensions

from typing import Any, Dict, List, Optional, OrderedDict, Set, Tuple, Union
T = typing.TypeVar('T')
P = typing.ParamSpec('P')
class QAccelerometer(QSensor):
    class AccelerationMode(enum.Enum):
        Combined = 0
        Gravity = 1
        User = 2
    accelerationModeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, accelerationMode: QAccelerometer.AccelerationMode | None = ..., accelerationModeChanged: typing.Callable = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def accelerationMode(self, /) -> QAccelerometer.AccelerationMode: ...
    def reading(self, /) -> QAccelerometerReading: ...
    def setAccelerationMode(self, accelerationMode: QAccelerometer.AccelerationMode, /) -> None: ...

class QAccelerometerFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QAccelerometerReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QAccelerometerReading(QSensorReading):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, x: float | None = ..., y: float | None = ..., z: float | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def setX(self, x: float, /) -> None: ...
    def setY(self, y: float, /) -> None: ...
    def setZ(self, z: float, /) -> None: ...
    def x(self, /) -> float: ...
    def y(self, /) -> float: ...
    def z(self, /) -> float: ...

class QAmbientLightFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QAmbientLightReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QAmbientLightReading(QSensorReading):
    class LightLevel(enum.Enum):
        Bright = 4
        Dark = 1
        Light = 3
        Sunny = 5
        Twilight = 2
        Undefined = 0
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, lightLevel: QAmbientLightReading.LightLevel | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def lightLevel(self, /) -> QAmbientLightReading.LightLevel: ...
    def setLightLevel(self, lightLevel: QAmbientLightReading.LightLevel, /) -> None: ...

class QAmbientLightSensor(QSensor):
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def reading(self, /) -> QAmbientLightReading: ...

class QAmbientTemperatureFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QAmbientTemperatureReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QAmbientTemperatureReading(QSensorReading):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, temperature: float | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def setTemperature(self, temperature: float, /) -> None: ...
    def temperature(self, /) -> float: ...

class QAmbientTemperatureSensor(QSensor):
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def reading(self, /) -> QAmbientTemperatureReading: ...

class QCompass(QSensor):
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def reading(self, /) -> QCompassReading: ...

class QCompassFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QCompassReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QCompassReading(QSensorReading):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, azimuth: float | None = ..., calibrationLevel: float | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def azimuth(self, /) -> float: ...
    def calibrationLevel(self, /) -> float: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def setAzimuth(self, azimuth: float, /) -> None: ...
    def setCalibrationLevel(self, calibrationLevel: float, /) -> None: ...

class QGyroscope(QSensor):
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def reading(self, /) -> QGyroscopeReading: ...

class QGyroscopeFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QGyroscopeReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QGyroscopeReading(QSensorReading):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, x: float | None = ..., y: float | None = ..., z: float | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def setX(self, x: float, /) -> None: ...
    def setY(self, y: float, /) -> None: ...
    def setZ(self, z: float, /) -> None: ...
    def x(self, /) -> float: ...
    def y(self, /) -> float: ...
    def z(self, /) -> float: ...

class QHumidityFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QHumidityReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QHumidityReading(QSensorReading):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, relativeHumidity: float | None = ..., absoluteHumidity: float | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def absoluteHumidity(self, /) -> float: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def relativeHumidity(self, /) -> float: ...
    def setAbsoluteHumidity(self, value: float, /) -> None: ...
    def setRelativeHumidity(self, percent: float, /) -> None: ...

class QHumiditySensor(QSensor):
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def reading(self, /) -> QHumidityReading: ...

class QIRProximityFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QIRProximityReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QIRProximityReading(QSensorReading):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, reflectance: float | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def reflectance(self, /) -> float: ...
    def setReflectance(self, reflectance: float, /) -> None: ...

class QIRProximitySensor(QSensor):
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def reading(self, /) -> QIRProximityReading: ...

class QIntList:
    __opaque_container__: typing.ClassVar[bool] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs): ...
    def capacity(self, *args, **kwargs): ...
    def clear(self, *args, **kwargs): ...
    def constData(self, *args, **kwargs): ...
    def data(self, *args, **kwargs): ...
    def pop_back(self, *args, **kwargs): ...
    def pop_front(self, *args, **kwargs): ...
    def prepend(self, *args, **kwargs): ...
    def push_back(self, *args, **kwargs): ...
    def push_front(self, *args, **kwargs): ...
    def removeFirst(self, *args, **kwargs): ...
    def removeLast(self, *args, **kwargs): ...
    def reserve(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, object) -> None: ...

class QLidFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QLidReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QLidReading(QSensorReading):
    backLidChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    frontLidChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, backLidClosed: bool | None = ..., frontLidClosed: bool | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def backLidClosed(self, /) -> bool: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def frontLidClosed(self, /) -> bool: ...
    def setBackLidClosed(self, closed: bool, /) -> None: ...
    def setFrontLidClosed(self, closed: bool, /) -> None: ...

class QLidSensor(QSensor):
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def reading(self, /) -> QLidReading: ...

class QLightFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QLightReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QLightReading(QSensorReading):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, lux: float | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def lux(self, /) -> float: ...
    def setLux(self, lux: float, /) -> None: ...

class QLightSensor(QSensor):
    fieldOfViewChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, fieldOfView: float | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., fieldOfViewChanged: typing.Callable = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def fieldOfView(self, /) -> float: ...
    def reading(self, /) -> QLightReading: ...
    def setFieldOfView(self, fieldOfView: float, /) -> None: ...

class QMagnetometer(QSensor):
    returnGeoValuesChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, returnGeoValues: bool | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., returnGeoValuesChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def reading(self, /) -> QMagnetometerReading: ...
    def returnGeoValues(self, /) -> bool: ...
    def setReturnGeoValues(self, returnGeoValues: bool, /) -> None: ...

class QMagnetometerFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QMagnetometerReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QMagnetometerReading(QSensorReading):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, x: float | None = ..., y: float | None = ..., z: float | None = ..., calibrationLevel: float | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def calibrationLevel(self, /) -> float: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def setCalibrationLevel(self, calibrationLevel: float, /) -> None: ...
    def setX(self, x: float, /) -> None: ...
    def setY(self, y: float, /) -> None: ...
    def setZ(self, z: float, /) -> None: ...
    def x(self, /) -> float: ...
    def y(self, /) -> float: ...
    def z(self, /) -> float: ...

class QOrientationFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QOrientationReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QOrientationReading(QSensorReading):
    class Orientation(enum.Enum):
        FaceDown = 6
        FaceUp = 5
        LeftUp = 3
        RightUp = 4
        TopDown = 2
        TopUp = 1
        Undefined = 0
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, orientation: QOrientationReading.Orientation | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def orientation(self, /) -> QOrientationReading.Orientation: ...
    def setOrientation(self, orientation: QOrientationReading.Orientation, /) -> None: ...

class QOrientationSensor(QSensor):
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def reading(self, /) -> QOrientationReading: ...

class QPressureFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QPressureReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QPressureReading(QSensorReading):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, pressure: float | None = ..., temperature: float | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def pressure(self, /) -> float: ...
    def setPressure(self, pressure: float, /) -> None: ...
    def setTemperature(self, temperature: float, /) -> None: ...
    def temperature(self, /) -> float: ...

class QPressureSensor(QSensor):
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def reading(self, /) -> QPressureReading: ...

class QProximityFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QProximityReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QProximityReading(QSensorReading):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, close: bool | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def close(self, /) -> bool: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def setClose(self, close: bool, /) -> None: ...

class QProximitySensor(QSensor):
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def reading(self, /) -> QProximityReading: ...

class QRotationFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QRotationReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QRotationReading(QSensorReading):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, x: float | None = ..., y: float | None = ..., z: float | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def setFromEuler(self, x: float, y: float, z: float, /) -> None: ...
    def x(self, /) -> float: ...
    def y(self, /) -> float: ...
    def z(self, /) -> float: ...

class QRotationSensor(QSensor):
    hasZChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, hasZ: bool | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., hasZChanged: typing.Callable = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def hasZ(self, /) -> bool: ...
    def reading(self, /) -> QRotationReading: ...
    def setHasZ(self, hasZ: bool, /) -> None: ...

class QSensor(PySide6.QtCore.QObject):
    class AxesOrientationMode(enum.Enum):
        AutomaticOrientation = 1
        FixedOrientation = 0
        UserOrientation = 2

    class Feature(enum.Enum):
        AccelerationMode = 4
        AlwaysOn = 1
        AxesOrientation = 6
        Buffering = 0
        FieldOfView = 3
        GeoValues = 2
        PressureSensorTemperature = 7
        Reserved = 257
        SkipDuplicates = 5
    activeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    alwaysOnChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    availableSensorsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    axesOrientationModeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    bufferSizeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    busyChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    currentOrientationChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    dataRateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    efficientBufferSizeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    identifierChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    maxBufferSizeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    readingChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sensorError: typing.ClassVar[PySide6.QtCore.Signal] = ...
    skipDuplicatesChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    userOrientationChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, type: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /, parent: PySide6.QtCore.QObject | None = ..., *, identifier: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview | None = ..., connectedToBackend: bool | None = ..., availableDataRates: typing.Iterable[tuple[int, int]] | None = ..., dataRate: int | None = ..., reading: QSensorReading | None = ..., busy: bool | None = ..., active: bool | None = ..., outputRanges: typing.Iterable[qoutputrange] | None = ..., outputRange: int | None = ..., description: str | None = ..., error: int | None = ..., alwaysOn: bool | None = ..., skipDuplicates: bool | None = ..., axesOrientationMode: QSensor.AxesOrientationMode | None = ..., currentOrientation: int | None = ..., userOrientation: int | None = ..., maxBufferSize: int | None = ..., efficientBufferSize: int | None = ..., bufferSize: int | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def addFilter(self, filter: QSensorFilter, /) -> None: ...
    def availableDataRates(self, /) -> List[Tuple[int, int]]: ...
    def axesOrientationMode(self, /) -> QSensor.AxesOrientationMode: ...
    def backend(self, /) -> QSensorBackend: ...
    def bufferSize(self, /) -> int: ...
    def connectToBackend(self, /) -> bool: ...
    def currentOrientation(self, /) -> int: ...
    def dataRate(self, /) -> int: ...
    @staticmethod
    def defaultSensorForType(type: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> PySide6.QtCore.QByteArray: ...
    def description(self, /) -> str: ...
    def efficientBufferSize(self, /) -> int: ...
    def error(self, /) -> int: ...
    def filters(self, /) -> List[QSensorFilter]: ...
    def identifier(self, /) -> PySide6.QtCore.QByteArray: ...
    def isActive(self, /) -> bool: ...
    def isAlwaysOn(self, /) -> bool: ...
    def isBusy(self, /) -> bool: ...
    def isConnectedToBackend(self, /) -> bool: ...
    def isFeatureSupported(self, feature: QSensor.Feature, /) -> bool: ...
    def maxBufferSize(self, /) -> int: ...
    def outputRange(self, /) -> int: ...
    def outputRanges(self, /) -> List[qoutputrange]: ...
    def reading(self, /) -> QSensorReading: ...
    def removeFilter(self, filter: QSensorFilter, /) -> None: ...
    @staticmethod
    def sensorTypes() -> List[PySide6.QtCore.QByteArray]: ...
    @staticmethod
    def sensorsForType(type: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> List[PySide6.QtCore.QByteArray]: ...
    def setActive(self, active: bool, /) -> None: ...
    def setAlwaysOn(self, alwaysOn: bool, /) -> None: ...
    def setAxesOrientationMode(self, axesOrientationMode: QSensor.AxesOrientationMode, /) -> None: ...
    def setBufferSize(self, bufferSize: int, /) -> None: ...
    def setCurrentOrientation(self, currentOrientation: int, /) -> None: ...
    def setDataRate(self, rate: int, /) -> None: ...
    def setEfficientBufferSize(self, efficientBufferSize: int, /) -> None: ...
    def setIdentifier(self, identifier: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> None: ...
    def setMaxBufferSize(self, maxBufferSize: int, /) -> None: ...
    def setOutputRange(self, index: int, /) -> None: ...
    def setSkipDuplicates(self, skipDuplicates: bool, /) -> None: ...
    def setUserOrientation(self, userOrientation: int, /) -> None: ...
    def skipDuplicates(self, /) -> bool: ...
    def start(self, /) -> bool: ...
    def stop(self, /) -> None: ...
    def type(self, /) -> PySide6.QtCore.QByteArray: ...
    def userOrientation(self, /) -> int: ...

class QSensorBackend(PySide6.QtCore.QObject):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, sensor: QSensor, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def addDataRate(self, min: float, max: float, /) -> None: ...
    def addOutputRange(self, min: float, max: float, accuracy: float, /) -> None: ...
    def isFeatureSupported(self, feature: QSensor.Feature, /) -> bool: ...
    def newReadingAvailable(self, /) -> None: ...
    def reading(self, /) -> QSensorReading: ...
    def sensor(self, /) -> QSensor: ...
    def sensorBusy(self, /, busy: bool = ...) -> None: ...
    def sensorError(self, error: int, /) -> None: ...
    def sensorStopped(self, /) -> None: ...
    def setDataRates(self, otherSensor: QSensor, /) -> None: ...
    def setDescription(self, description: str, /) -> None: ...
    def start(self, /) -> None: ...
    def stop(self, /) -> None: ...

class QSensorBackendFactory(shiboken6.Object):
    def __init__(self, /) -> None: ...
    def createBackend(self, sensor: QSensor, /) -> QSensorBackend: ...

class QSensorChangesInterface(shiboken6.Object):
    def __init__(self, /) -> None: ...
    def sensorsChanged(self, /) -> None: ...

class QSensorFilter(shiboken6.Object):
    m_sensor: _typeshed.Incomplete
    def __init__(self, /) -> None: ...
    def filter(self, reading: QSensorReading, /) -> bool: ...
    def setSensor(self, sensor: QSensor, /) -> None: ...

class QSensorManager(shiboken6.Object):
    def __init__(self, /) -> None: ...
    @staticmethod
    def createBackend(sensor: QSensor, /) -> QSensorBackend: ...
    @staticmethod
    def isBackendRegistered(type: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, identifier: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> bool: ...
    @staticmethod
    def registerBackend(type: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, identifier: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, factory: QSensorBackendFactory, /) -> None: ...
    @staticmethod
    def setDefaultBackend(type: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, identifier: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> None: ...
    @staticmethod
    def unregisterBackend(type: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, identifier: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> None: ...

class QSensorPluginInterface(shiboken6.Object):
    def __init__(self, /) -> None: ...
    def registerSensors(self, /) -> None: ...

class QSensorReading(PySide6.QtCore.QObject):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, *args, destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., **kwargs) -> None: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def setTimestamp(self, timestamp: int, /) -> None: ...
    def timestamp(self, /) -> int: ...
    def value(self, index: int, /) -> Any: ...
    def valueCount(self, /) -> int: ...

class QTapFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QTapReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QTapReading(QSensorReading):
    class TapDirection(enum.Enum):
        Undefined = 0
        X = 1
        X_Both = 273
        X_Neg = 257
        X_Pos = 17
        Y = 2
        Y_Both = 546
        Y_Neg = 514
        Y_Pos = 34
        Z = 4
        Z_Both = 1092
        Z_Neg = 1028
        Z_Pos = 68
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, tapDirection: QTapReading.TapDirection | None = ..., doubleTap: bool | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def isDoubleTap(self, /) -> bool: ...
    def setDoubleTap(self, doubleTap: bool, /) -> None: ...
    def setTapDirection(self, tapDirection: QTapReading.TapDirection, /) -> None: ...
    def tapDirection(self, /) -> QTapReading.TapDirection: ...

class QTapSensor(QSensor):
    returnDoubleTapEventsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, returnDoubleTapEvents: bool | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., returnDoubleTapEventsChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def reading(self, /) -> QTapReading: ...
    def returnDoubleTapEvents(self, /) -> bool: ...
    def setReturnDoubleTapEvents(self, returnDoubleTapEvents: bool, /) -> None: ...

class QTiltFilter(QSensorFilter):
    def __init__(self, *args, **kwargs) -> None: ...
    @typing.overload
    def filter(self, reading: QTiltReading, /) -> bool: ...
    @typing.overload
    def filter(self, reading: QSensorReading, /) -> bool: ...

class QTiltReading(QSensorReading):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, yRotation: float | None = ..., xRotation: float | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def copyValuesFrom(self, other: QSensorReading, /) -> None: ...
    def setXRotation(self, x: float, /) -> None: ...
    def setYRotation(self, y: float, /) -> None: ...
    def xRotation(self, /) -> float: ...
    def yRotation(self, /) -> float: ...

class QTiltSensor(QSensor):
    sensorType: typing.ClassVar[str] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., active: bool = ..., activeChanged: typing.Callable = ..., alwaysOn: bool = ..., alwaysOnChanged: typing.Callable = ..., availableDataRates: typing.Any = ..., availableSensorsChanged: typing.Callable = ..., axesOrientationMode: QSensor.AxesOrientationMode = ..., axesOrientationModeChanged: typing.Callable = ..., bufferSize: int = ..., bufferSizeChanged: typing.Callable = ..., busy: bool = ..., busyChanged: typing.Callable = ..., connectedToBackend: bool = ..., currentOrientation: int = ..., currentOrientationChanged: typing.Callable = ..., dataRate: int = ..., dataRateChanged: typing.Callable = ..., description: str = ..., destroyed: typing.Callable = ..., efficientBufferSize: int = ..., efficientBufferSizeChanged: typing.Callable = ..., error: int = ..., identifier: PySide6.QtCore.QByteArray | bytes = ..., identifierChanged: typing.Callable = ..., maxBufferSize: int = ..., maxBufferSizeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputRange: int = ..., outputRanges: typing.Any = ..., reading: QSensorReading = ..., readingChanged: typing.Callable = ..., sensorError: typing.Callable = ..., skipDuplicates: bool = ..., skipDuplicatesChanged: typing.Callable = ..., type: PySide6.QtCore.QByteArray | bytes = ..., userOrientation: int = ..., userOrientationChanged: typing.Callable = ...) -> None: ...
    def calibrate(self, /) -> None: ...
    def reading(self, /) -> QTiltReading: ...

class qoutputrange(shiboken6.Object):
    accuracy: _typeshed.Incomplete
    maximum: _typeshed.Incomplete
    minimum: _typeshed.Incomplete
    @typing.overload
    def __init__(self, qoutputrange: qoutputrange, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
