import PySide6.QtCore
import _typeshed
import collections
import enum
import shiboken6
import typing
import typing_extensions

from typing import Any, Dict, List, Optional, OrderedDict, Set, Tuple, Union
T = typing.TypeVar('T')
P = typing.ParamSpec('P')
class QIntList:
    __opaque_container__: typing.ClassVar[bool] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs): ...
    def capacity(self, *args, **kwargs): ...
    def clear(self, *args, **kwargs): ...
    def constData(self, *args, **kwargs): ...
    def data(self, *args, **kwargs): ...
    def pop_back(self, *args, **kwargs): ...
    def pop_front(self, *args, **kwargs): ...
    def prepend(self, *args, **kwargs): ...
    def push_back(self, *args, **kwargs): ...
    def push_front(self, *args, **kwargs): ...
    def removeFirst(self, *args, **kwargs): ...
    def removeLast(self, *args, **kwargs): ...
    def reserve(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, object) -> None: ...

class QSerialPort(PySide6.QtCore.QIODevice):
    class BaudRate(enum.IntEnum):
        Baud115200 = 115200
        Baud1200 = 1200
        Baud19200 = 19200
        Baud2400 = 2400
        Baud38400 = 38400
        Baud4800 = 4800
        Baud57600 = 57600
        Baud9600 = 9600

    class DataBits(enum.Enum):
        Data5 = 5
        Data6 = 6
        Data7 = 7
        Data8 = 8

    class Direction(enum.Flag):
        AllDirections = 3
        Input = 1
        Output = 2

    class FlowControl(enum.Enum):
        HardwareControl = 1
        NoFlowControl = 0
        SoftwareControl = 2

    class Parity(enum.Enum):
        EvenParity = 2
        MarkParity = 5
        NoParity = 0
        OddParity = 3
        SpaceParity = 4

    class PinoutSignal(enum.Flag):
        ClearToSendSignal = 128
        DataCarrierDetectSignal = 8
        DataSetReadySignal = 16
        DataTerminalReadySignal = 4
        NoSignal = 0
        RequestToSendSignal = 64
        RingIndicatorSignal = 32
        SecondaryReceivedDataSignal = 512
        SecondaryTransmittedDataSignal = 256

    class SerialPortError(enum.Enum):
        DeviceNotFoundError = 1
        NoError = 0
        NotOpenError = 10
        OpenError = 3
        PermissionError = 2
        ReadError = 5
        ResourceError = 6
        TimeoutError = 9
        UnknownError = 8
        UnsupportedOperationError = 7
        WriteError = 4

    class StopBits(enum.Enum):
        OneAndHalfStop = 3
        OneStop = 1
        TwoStop = 2
    baudRateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    breakEnabledChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    dataBitsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    dataTerminalReadyChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorOccurred: typing.ClassVar[PySide6.QtCore.Signal] = ...
    flowControlChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    parityChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    requestToSendChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    settingsRestoredOnCloseChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    stopBitsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    @typing.overload
    def __init__(self, name: str, /, parent: PySide6.QtCore.QObject | None = ..., *, baudRate: int | None = ..., dataBits: QSerialPort.DataBits | None = ..., parity: QSerialPort.Parity | None = ..., stopBits: QSerialPort.StopBits | None = ..., flowControl: QSerialPort.FlowControl | None = ..., dataTerminalReady: bool | None = ..., requestToSend: bool | None = ..., error: QSerialPort.SerialPortError | None = ..., breakEnabled: bool | None = ..., settingsRestoredOnClose: bool | None = ..., aboutToClose: typing.Callable = ..., baudRateChanged: typing.Callable = ..., breakEnabledChanged: typing.Callable = ..., bytesWritten: typing.Callable = ..., channelBytesWritten: typing.Callable = ..., channelReadyRead: typing.Callable = ..., dataBitsChanged: typing.Callable = ..., dataTerminalReadyChanged: typing.Callable = ..., destroyed: typing.Callable = ..., errorOccurred: typing.Callable = ..., flowControlChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., parityChanged: typing.Callable = ..., readChannelFinished: typing.Callable = ..., readyRead: typing.Callable = ..., requestToSendChanged: typing.Callable = ..., settingsRestoredOnCloseChanged: typing.Callable = ..., stopBitsChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, info: QSerialPortInfo, /, parent: PySide6.QtCore.QObject | None = ..., *, baudRate: int | None = ..., dataBits: QSerialPort.DataBits | None = ..., parity: QSerialPort.Parity | None = ..., stopBits: QSerialPort.StopBits | None = ..., flowControl: QSerialPort.FlowControl | None = ..., dataTerminalReady: bool | None = ..., requestToSend: bool | None = ..., error: QSerialPort.SerialPortError | None = ..., breakEnabled: bool | None = ..., settingsRestoredOnClose: bool | None = ..., aboutToClose: typing.Callable = ..., baudRateChanged: typing.Callable = ..., breakEnabledChanged: typing.Callable = ..., bytesWritten: typing.Callable = ..., channelBytesWritten: typing.Callable = ..., channelReadyRead: typing.Callable = ..., dataBitsChanged: typing.Callable = ..., dataTerminalReadyChanged: typing.Callable = ..., destroyed: typing.Callable = ..., errorOccurred: typing.Callable = ..., flowControlChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., parityChanged: typing.Callable = ..., readChannelFinished: typing.Callable = ..., readyRead: typing.Callable = ..., requestToSendChanged: typing.Callable = ..., settingsRestoredOnCloseChanged: typing.Callable = ..., stopBitsChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, baudRate: int | None = ..., dataBits: QSerialPort.DataBits | None = ..., parity: QSerialPort.Parity | None = ..., stopBits: QSerialPort.StopBits | None = ..., flowControl: QSerialPort.FlowControl | None = ..., dataTerminalReady: bool | None = ..., requestToSend: bool | None = ..., error: QSerialPort.SerialPortError | None = ..., breakEnabled: bool | None = ..., settingsRestoredOnClose: bool | None = ..., aboutToClose: typing.Callable = ..., baudRateChanged: typing.Callable = ..., breakEnabledChanged: typing.Callable = ..., bytesWritten: typing.Callable = ..., channelBytesWritten: typing.Callable = ..., channelReadyRead: typing.Callable = ..., dataBitsChanged: typing.Callable = ..., dataTerminalReadyChanged: typing.Callable = ..., destroyed: typing.Callable = ..., errorOccurred: typing.Callable = ..., flowControlChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., parityChanged: typing.Callable = ..., readChannelFinished: typing.Callable = ..., readyRead: typing.Callable = ..., requestToSendChanged: typing.Callable = ..., settingsRestoredOnCloseChanged: typing.Callable = ..., stopBitsChanged: typing.Callable = ...) -> None: ...
    def baudRate(self, /, directions: QSerialPort.Direction = ...) -> int: ...
    def bytesAvailable(self, /) -> int: ...
    def bytesToWrite(self, /) -> int: ...
    def canReadLine(self, /) -> bool: ...
    def clear(self, /, directions: QSerialPort.Direction = ...) -> bool: ...
    def clearError(self, /) -> None: ...
    def close(self, /) -> None: ...
    def dataBits(self, /) -> QSerialPort.DataBits: ...
    def error(self, /) -> QSerialPort.SerialPortError: ...
    def flowControl(self, /) -> QSerialPort.FlowControl: ...
    def flush(self, /) -> bool: ...
    def handle(self, /) -> int: ...
    def isBreakEnabled(self, /) -> bool: ...
    def isDataTerminalReady(self, /) -> bool: ...
    def isRequestToSend(self, /) -> bool: ...
    def isSequential(self, /) -> bool: ...
    def open(self, mode: PySide6.QtCore.QIODeviceBase.OpenModeFlag, /) -> bool: ...
    def parity(self, /) -> QSerialPort.Parity: ...
    def pinoutSignals(self, /) -> QSerialPort.PinoutSignal: ...
    def portName(self, /) -> str: ...
    def readBufferSize(self, /) -> int: ...
    def readData(self, maxSize: int, /) -> typing.Any: ...
    def readLineData(self, maxSize: int, /) -> typing.Any: ...
    def setBaudRate(self, baudRate: int, /, directions: QSerialPort.Direction = ...) -> bool: ...
    def setBreakEnabled(self, /, set: bool = ...) -> bool: ...
    def setDataBits(self, dataBits: QSerialPort.DataBits, /) -> bool: ...
    def setDataTerminalReady(self, set: bool, /) -> bool: ...
    def setFlowControl(self, flowControl: QSerialPort.FlowControl, /) -> bool: ...
    def setParity(self, parity: QSerialPort.Parity, /) -> bool: ...
    def setPort(self, info: QSerialPortInfo, /) -> None: ...
    def setPortName(self, name: str, /) -> None: ...
    def setReadBufferSize(self, size: int, /) -> None: ...
    def setRequestToSend(self, set: bool, /) -> bool: ...
    def setSettingsRestoredOnClose(self, restore: bool, /) -> None: ...
    def setStopBits(self, stopBits: QSerialPort.StopBits, /) -> bool: ...
    def setWriteBufferSize(self, size: int, /) -> None: ...
    def settingsRestoredOnClose(self, /) -> bool: ...
    def stopBits(self, /) -> QSerialPort.StopBits: ...
    def waitForBytesWritten(self, /, msecs: int = ...) -> bool: ...
    def waitForReadyRead(self, /, msecs: int = ...) -> bool: ...
    def writeBufferSize(self, /) -> int: ...
    def writeData(self, data: bytes | bytearray | memoryview, maxSize: int, /) -> int: ...

class QSerialPortInfo(shiboken6.Object):
    @typing.overload
    def __init__(self, port: QSerialPort, /) -> None: ...
    @typing.overload
    def __init__(self, other: QSerialPortInfo, /) -> None: ...
    @typing.overload
    def __init__(self, name: str, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    @staticmethod
    def availablePorts() -> List[QSerialPortInfo]: ...
    def description(self, /) -> str: ...
    def hasProductIdentifier(self, /) -> bool: ...
    def hasVendorIdentifier(self, /) -> bool: ...
    def isNull(self, /) -> bool: ...
    def manufacturer(self, /) -> str: ...
    def portName(self, /) -> str: ...
    def productIdentifier(self, /) -> int: ...
    def serialNumber(self, /) -> str: ...
    @staticmethod
    def standardBaudRates() -> List[int]: ...
    def swap(self, other: QSerialPortInfo, /) -> None: ...
    def systemLocation(self, /) -> str: ...
    def vendorIdentifier(self, /) -> int: ...
    def __bool__(self) -> bool: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
