import PySide6.QtCore
import PySide6.QtGui
import PySide6.QtMultimedia
import _typeshed
import collections
import enum
import typing
import typing_extensions

from typing import Any, Dict, List, Optional, OrderedDict, Set, Tuple, Union
T = typing.TypeVar('T')
P = typing.ParamSpec('P')
class QAmbientSound(PySide6.QtCore.QObject):
    class Loops(enum.IntEnum):
        Infinite = -1
        Once = 1
    autoPlayChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    loopsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sourceChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    volumeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, engine: QAudioEngine, /, *, source: PySide6.QtCore.QUrl | None = ..., volume: float | None = ..., loops: int | None = ..., autoPlay: bool | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def autoPlay(self, /) -> bool: ...
    def engine(self, /) -> QAudioEngine: ...
    def loops(self, /) -> int: ...
    def pause(self, /) -> None: ...
    def play(self, /) -> None: ...
    def setAutoPlay(self, autoPlay: bool, /) -> None: ...
    def setLoops(self, loops: int, /) -> None: ...
    def setSource(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def setVolume(self, volume: float, /) -> None: ...
    def source(self, /) -> PySide6.QtCore.QUrl: ...
    def stop(self, /) -> None: ...
    def volume(self, /) -> float: ...

class QAudioEngine(PySide6.QtCore.QObject):
    class OutputMode(enum.Enum):
        Headphone = 2
        Stereo = 1
        Surround = 0
    DistanceScaleCentimeter: typing.ClassVar[float] = ...
    DistanceScaleMeter: typing.ClassVar[float] = ...
    distanceScaleChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    masterVolumeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    outputDeviceChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    outputModeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    pausedChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    @typing.overload
    def __init__(self, sampleRate: int, /, parent: PySide6.QtCore.QObject | None = ..., *, outputMode: QAudioEngine.OutputMode | None = ..., outputDevice: PySide6.QtMultimedia.QAudioDevice | None = ..., masterVolume: float | None = ..., paused: bool | None = ..., distanceScale: float | None = ..., destroyed: typing.Callable = ..., distanceScaleChanged: typing.Callable = ..., masterVolumeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputDeviceChanged: typing.Callable = ..., outputModeChanged: typing.Callable = ..., pausedChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, parent: PySide6.QtCore.QObject | None, /, *, outputMode: QAudioEngine.OutputMode | None = ..., outputDevice: PySide6.QtMultimedia.QAudioDevice | None = ..., masterVolume: float | None = ..., paused: bool | None = ..., distanceScale: float | None = ..., destroyed: typing.Callable = ..., distanceScaleChanged: typing.Callable = ..., masterVolumeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputDeviceChanged: typing.Callable = ..., outputModeChanged: typing.Callable = ..., pausedChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, outputMode: QAudioEngine.OutputMode | None = ..., outputDevice: PySide6.QtMultimedia.QAudioDevice | None = ..., masterVolume: float | None = ..., paused: bool | None = ..., distanceScale: float | None = ..., destroyed: typing.Callable = ..., distanceScaleChanged: typing.Callable = ..., masterVolumeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., outputDeviceChanged: typing.Callable = ..., outputModeChanged: typing.Callable = ..., pausedChanged: typing.Callable = ...) -> None: ...
    def distanceScale(self, /) -> float: ...
    def masterVolume(self, /) -> float: ...
    def outputDevice(self, /) -> PySide6.QtMultimedia.QAudioDevice: ...
    def outputMode(self, /) -> QAudioEngine.OutputMode: ...
    def pause(self, /) -> None: ...
    def paused(self, /) -> bool: ...
    def resume(self, /) -> None: ...
    def roomEffectsEnabled(self, /) -> bool: ...
    def sampleRate(self, /) -> int: ...
    def setDistanceScale(self, scale: float, /) -> None: ...
    def setMasterVolume(self, volume: float, /) -> None: ...
    def setOutputDevice(self, device: PySide6.QtMultimedia.QAudioDevice, /) -> None: ...
    def setOutputMode(self, mode: QAudioEngine.OutputMode, /) -> None: ...
    def setPaused(self, paused: bool, /) -> None: ...
    def setRoomEffectsEnabled(self, enabled: bool, /) -> None: ...
    def start(self, /) -> None: ...
    def stop(self, /) -> None: ...

class QAudioListener(PySide6.QtCore.QObject):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, engine: QAudioEngine, /, destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def engine(self, /) -> QAudioEngine: ...
    def position(self, /) -> PySide6.QtGui.QVector3D: ...
    def rotation(self, /) -> PySide6.QtGui.QQuaternion: ...
    def setPosition(self, pos: PySide6.QtGui.QVector3D, /) -> None: ...
    def setRotation(self, q: PySide6.QtGui.QQuaternion, /) -> None: ...

class QAudioRoom(PySide6.QtCore.QObject):
    class Material(enum.Enum):
        AcousticCeilingTiles = 1
        BrickBare = 2
        BrickPainted = 3
        ConcreteBlockCoarse = 4
        ConcreteBlockPainted = 5
        CurtainHeavy = 6
        FiberGlassInsulation = 7
        GlassThick = 9
        GlassThin = 8
        Grass = 10
        LinoleumOnConcrete = 11
        Marble = 12
        Metal = 13
        ParquetOnConcrete = 14
        PlasterRough = 15
        PlasterSmooth = 16
        PlywoodPanel = 17
        PolishedConcreteOrTile = 18
        Sheetrock = 19
        Transparent = 0
        UniformMaterial = 23
        WaterOrIceSurface = 20
        WoodCeiling = 21
        WoodPanel = 22

    class Wall(enum.Enum):
        BackWall = 5
        Ceiling = 3
        Floor = 2
        FrontWall = 4
        LeftWall = 0
        RightWall = 1
    dimensionsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    positionChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    reflectionGainChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    reverbBrightnessChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    reverbGainChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    reverbTimeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    rotationChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    wallsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, engine: QAudioEngine, /, *, position: PySide6.QtGui.QVector3D | None = ..., dimensions: PySide6.QtGui.QVector3D | None = ..., rotation: PySide6.QtGui.QQuaternion | None = ..., reflectionGain: float | None = ..., reverbGain: float | None = ..., reverbTime: float | None = ..., reverbBrightness: float | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def dimensions(self, /) -> PySide6.QtGui.QVector3D: ...
    def position(self, /) -> PySide6.QtGui.QVector3D: ...
    def reflectionGain(self, /) -> float: ...
    def reverbBrightness(self, /) -> float: ...
    def reverbGain(self, /) -> float: ...
    def reverbTime(self, /) -> float: ...
    def rotation(self, /) -> PySide6.QtGui.QQuaternion: ...
    def setDimensions(self, dim: PySide6.QtGui.QVector3D, /) -> None: ...
    def setPosition(self, pos: PySide6.QtGui.QVector3D, /) -> None: ...
    def setReflectionGain(self, factor: float, /) -> None: ...
    def setReverbBrightness(self, factor: float, /) -> None: ...
    def setReverbGain(self, factor: float, /) -> None: ...
    def setReverbTime(self, factor: float, /) -> None: ...
    def setRotation(self, q: PySide6.QtGui.QQuaternion, /) -> None: ...
    def setWallMaterial(self, wall: QAudioRoom.Wall, material: QAudioRoom.Material, /) -> None: ...
    def wallMaterial(self, wall: QAudioRoom.Wall, /) -> QAudioRoom.Material: ...

class QIntList:
    __opaque_container__: typing.ClassVar[bool] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs): ...
    def capacity(self, *args, **kwargs): ...
    def clear(self, *args, **kwargs): ...
    def constData(self, *args, **kwargs): ...
    def data(self, *args, **kwargs): ...
    def pop_back(self, *args, **kwargs): ...
    def pop_front(self, *args, **kwargs): ...
    def prepend(self, *args, **kwargs): ...
    def push_back(self, *args, **kwargs): ...
    def push_front(self, *args, **kwargs): ...
    def removeFirst(self, *args, **kwargs): ...
    def removeLast(self, *args, **kwargs): ...
    def reserve(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, object) -> None: ...

class QSpatialSound(PySide6.QtCore.QObject):
    class DistanceModel(enum.Enum):
        Linear = 1
        Logarithmic = 0
        ManualAttenuation = 2

    class Loops(enum.IntEnum):
        Infinite = -1
        Once = 1
    autoPlayChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    directivityChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    directivityOrderChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    distanceCutoffChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    distanceModelChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    loopsChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    manualAttenuationChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    nearFieldGainChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    occlusionIntensityChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    positionChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    rotationChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sizeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sourceChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    volumeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, engine: QAudioEngine, /, *, source: PySide6.QtCore.QUrl | None = ..., position: PySide6.QtGui.QVector3D | None = ..., rotation: PySide6.QtGui.QQuaternion | None = ..., volume: float | None = ..., distanceModel: QSpatialSound.DistanceModel | None = ..., size: float | None = ..., distanceCutoff: float | None = ..., manualAttenuation: float | None = ..., occlusionIntensity: float | None = ..., directivity: float | None = ..., directivityOrder: float | None = ..., nearFieldGain: float | None = ..., loops: int | None = ..., autoPlay: bool | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def autoPlay(self, /) -> bool: ...
    def directivity(self, /) -> float: ...
    def directivityOrder(self, /) -> float: ...
    def distanceCutoff(self, /) -> float: ...
    def distanceModel(self, /) -> QSpatialSound.DistanceModel: ...
    def engine(self, /) -> QAudioEngine: ...
    def loops(self, /) -> int: ...
    def manualAttenuation(self, /) -> float: ...
    def nearFieldGain(self, /) -> float: ...
    def occlusionIntensity(self, /) -> float: ...
    def pause(self, /) -> None: ...
    def play(self, /) -> None: ...
    def position(self, /) -> PySide6.QtGui.QVector3D: ...
    def rotation(self, /) -> PySide6.QtGui.QQuaternion: ...
    def setAutoPlay(self, autoPlay: bool, /) -> None: ...
    def setDirectivity(self, alpha: float, /) -> None: ...
    def setDirectivityOrder(self, alpha: float, /) -> None: ...
    def setDistanceCutoff(self, cutoff: float, /) -> None: ...
    def setDistanceModel(self, model: QSpatialSound.DistanceModel, /) -> None: ...
    def setLoops(self, loops: int, /) -> None: ...
    def setManualAttenuation(self, attenuation: float, /) -> None: ...
    def setNearFieldGain(self, gain: float, /) -> None: ...
    def setOcclusionIntensity(self, occlusion: float, /) -> None: ...
    def setPosition(self, pos: PySide6.QtGui.QVector3D, /) -> None: ...
    def setRotation(self, q: PySide6.QtGui.QQuaternion, /) -> None: ...
    def setSize(self, size: float, /) -> None: ...
    def setSource(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def setVolume(self, volume: float, /) -> None: ...
    def size(self, /) -> float: ...
    def source(self, /) -> PySide6.QtCore.QUrl: ...
    def stop(self, /) -> None: ...
    def volume(self, /) -> float: ...
