import PySide6.QtCore
import PySide6.QtWidgets
import _typeshed
import collections
import enum
import shiboken6
import typing
import typing_extensions

from typing import Any, Dict, List, Optional, OrderedDict, Set, Tuple, Union
T = typing.TypeVar('T')
P = typing.ParamSpec('P')
class QIntList:
    __opaque_container__: typing.ClassVar[bool] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs): ...
    def capacity(self, *args, **kwargs): ...
    def clear(self, *args, **kwargs): ...
    def constData(self, *args, **kwargs): ...
    def data(self, *args, **kwargs): ...
    def pop_back(self, *args, **kwargs): ...
    def pop_front(self, *args, **kwargs): ...
    def prepend(self, *args, **kwargs): ...
    def push_back(self, *args, **kwargs): ...
    def push_front(self, *args, **kwargs): ...
    def removeFirst(self, *args, **kwargs): ...
    def removeLast(self, *args, **kwargs): ...
    def reserve(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, object) -> None: ...

class QSql(shiboken6.Object):
    class Location(enum.Enum):
        AfterLastRow = -2
        BeforeFirstRow = -1

    class NumericalPrecisionPolicy(enum.Enum):
        HighPrecision = 0
        LowPrecisionDouble = 4
        LowPrecisionInt32 = 1
        LowPrecisionInt64 = 2

    class ParamTypeFlag(enum.Flag):
        Binary = 4
        In = 1
        InOut = 3
        Out = 2

    class TableType(enum.Enum):
        AllTables = 255
        SystemTables = 2
        Tables = 1
        Views = 4
    def __init__(self, *args, **kwargs) -> None: ...

class QSqlDatabase(shiboken6.Object):
    @typing.overload
    def __init__(self, type: str, /, *, numericalPrecisionPolicy: QSql.NumericalPrecisionPolicy | None = ...) -> None: ...
    @typing.overload
    def __init__(self, other: QSqlDatabase, /, *, numericalPrecisionPolicy: QSql.NumericalPrecisionPolicy | None = ...) -> None: ...
    @typing.overload
    def __init__(self, driver: QSqlDriver, /, *, numericalPrecisionPolicy: QSql.NumericalPrecisionPolicy | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, numericalPrecisionPolicy: QSql.NumericalPrecisionPolicy | None = ...) -> None: ...
    @typing.overload
    @staticmethod
    def addDatabase(type: str, /, connectionName: str = ...) -> QSqlDatabase: ...
    @typing.overload
    @staticmethod
    def addDatabase(driver: QSqlDriver, /, connectionName: str = ...) -> QSqlDatabase: ...
    @typing.overload
    @staticmethod
    def cloneDatabase(other: QSqlDatabase, connectionName: str, /) -> QSqlDatabase: ...
    @typing.overload
    @staticmethod
    def cloneDatabase(other: str, connectionName: str, /) -> QSqlDatabase: ...
    def close(self, /) -> None: ...
    def commit(self, /) -> bool: ...
    def connectOptions(self, /) -> str: ...
    def connectionName(self, /) -> str: ...
    @staticmethod
    def connectionNames() -> List[str]: ...
    @staticmethod
    def contains(connectionName: str = ...) -> bool: ...
    @staticmethod
    def database(connectionName: str = ..., open: bool = ...) -> QSqlDatabase: ...
    def databaseName(self, /) -> str: ...
    def driver(self, /) -> QSqlDriver: ...
    def driverName(self, /) -> str: ...
    @staticmethod
    def drivers() -> List[str]: ...
    def exec(self, /, query: str = ...) -> QSqlQuery: ...
    def exec_(self, /, query: str = ...) -> QSqlQuery: ...
    def hostName(self, /) -> str: ...
    @staticmethod
    def isDriverAvailable(name: str, /) -> bool: ...
    def isOpen(self, /) -> bool: ...
    def isOpenError(self, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    def lastError(self, /) -> QSqlError: ...
    def moveToThread(self, targetThread: PySide6.QtCore.QThread, /) -> bool: ...
    def numericalPrecisionPolicy(self, /) -> QSql.NumericalPrecisionPolicy: ...
    @typing.overload
    def open(self, user: str, password: str, /) -> bool: ...
    @typing.overload
    def open(self, /) -> bool: ...
    def password(self, /) -> str: ...
    def port(self, /) -> int: ...
    def primaryIndex(self, tablename: str, /) -> QSqlIndex: ...
    def record(self, tablename: str, /) -> QSqlRecord: ...
    @staticmethod
    def registerSqlDriver(name: str, creator: QSqlDriverCreatorBase, /) -> None: ...
    @staticmethod
    def removeDatabase(connectionName: str, /) -> None: ...
    def rollback(self, /) -> bool: ...
    def setConnectOptions(self, /, options: str = ...) -> None: ...
    def setDatabaseName(self, name: str, /) -> None: ...
    def setHostName(self, host: str, /) -> None: ...
    def setNumericalPrecisionPolicy(self, precisionPolicy: QSql.NumericalPrecisionPolicy, /) -> None: ...
    def setPassword(self, password: str, /) -> None: ...
    def setPort(self, p: int, /) -> None: ...
    def setUserName(self, name: str, /) -> None: ...
    def tables(self, /, type: QSql.TableType = ...) -> List[str]: ...
    def thread(self, /) -> PySide6.QtCore.QThread: ...
    def transaction(self, /) -> bool: ...
    def userName(self, /) -> str: ...
    def __copy__(self, /) -> typing_extensions.Self: ...

class QSqlDriver(PySide6.QtCore.QObject):
    class DbmsType(enum.Enum):
        DB2 = 8
        Interbase = 7
        MSSqlServer = 1
        MimerSQL = 9
        MySqlServer = 2
        Oracle = 4
        PostgreSQL = 3
        SQLite = 6
        Sybase = 5
        UnknownDbms = 0

    class DriverFeature(enum.Enum):
        BLOB = 2
        BatchOperations = 8
        CancelQuery = 14
        EventNotifications = 11
        FinishQuery = 12
        LastInsertId = 7
        LowPrecisionNumbers = 10
        MultipleResultSets = 13
        NamedPlaceholders = 5
        PositionalPlaceholders = 6
        PreparedQueries = 4
        QuerySize = 1
        SimpleLocking = 9
        Transactions = 0
        Unicode = 3

    class IdentifierType(enum.Enum):
        FieldName = 0
        TableName = 1

    class NotificationSource(enum.Enum):
        OtherSource = 2
        SelfSource = 1
        UnknownSource = 0

    class StatementType(enum.Enum):
        DeleteStatement = 4
        InsertStatement = 3
        SelectStatement = 1
        UpdateStatement = 2
        WhereStatement = 0
    notification: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, numericalPrecisionPolicy: QSql.NumericalPrecisionPolicy | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def beginTransaction(self, /) -> bool: ...
    def cancelQuery(self, /) -> bool: ...
    def close(self, /) -> None: ...
    def commitTransaction(self, /) -> bool: ...
    def connectionName(self, /) -> str: ...
    def createResult(self, /) -> QSqlResult: ...
    def dbmsType(self, /) -> QSqlDriver.DbmsType: ...
    def escapeIdentifier(self, identifier: str, type: QSqlDriver.IdentifierType, /) -> str: ...
    def formatValue(self, field: QSqlField, /, trimStrings: bool = ...) -> str: ...
    def hasFeature(self, f: QSqlDriver.DriverFeature, /) -> bool: ...
    def isIdentifierEscaped(self, identifier: str, type: QSqlDriver.IdentifierType, /) -> bool: ...
    def isOpen(self, /) -> bool: ...
    def isOpenError(self, /) -> bool: ...
    def lastError(self, /) -> QSqlError: ...
    def maximumIdentifierLength(self, type: QSqlDriver.IdentifierType, /) -> int: ...
    def numericalPrecisionPolicy(self, /) -> QSql.NumericalPrecisionPolicy: ...
    def open(self, db: str, /, user: str = ..., password: str = ..., host: str = ..., port: int = ..., connOpts: str = ...) -> bool: ...
    def primaryIndex(self, tableName: str, /) -> QSqlIndex: ...
    def record(self, tableName: str, /) -> QSqlRecord: ...
    def rollbackTransaction(self, /) -> bool: ...
    def setLastError(self, e: QSqlError, /) -> None: ...
    def setNumericalPrecisionPolicy(self, precisionPolicy: QSql.NumericalPrecisionPolicy, /) -> None: ...
    def setOpen(self, o: bool, /) -> None: ...
    def setOpenError(self, e: bool, /) -> None: ...
    def sqlStatement(self, type: QSqlDriver.StatementType, tableName: str, rec: QSqlRecord, preparedStatement: bool, /) -> str: ...
    def stripDelimiters(self, identifier: str, type: QSqlDriver.IdentifierType, /) -> str: ...
    def subscribeToNotification(self, name: str, /) -> bool: ...
    def subscribedToNotifications(self, /) -> List[str]: ...
    def tables(self, tableType: QSql.TableType, /) -> List[str]: ...
    def unsubscribeFromNotification(self, name: str, /) -> bool: ...

class QSqlDriverCreatorBase(shiboken6.Object):
    def __init__(self, /) -> None: ...
    def createObject(self, /) -> QSqlDriver: ...

class QSqlError(shiboken6.Object):
    class ErrorType(enum.Enum):
        ConnectionError = 1
        NoError = 0
        StatementError = 2
        TransactionError = 3
        UnknownError = 4
    @typing.overload
    def __init__(self, /, driverText: str = ..., databaseText: str = ..., type: QSqlError.ErrorType = ..., nativeErrorCode: str = ...) -> None: ...
    @typing.overload
    def __init__(self, other: QSqlError, /) -> None: ...
    def databaseText(self, /) -> str: ...
    def driverText(self, /) -> str: ...
    def isValid(self, /) -> bool: ...
    def nativeErrorCode(self, /) -> str: ...
    def swap(self, other: QSqlError, /) -> None: ...
    def text(self, /) -> str: ...
    def type(self, /) -> QSqlError.ErrorType: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QSqlField(shiboken6.Object):
    class RequiredStatus(enum.Enum):
        Optional = 0
        Required = 1
        Unknown = -1
    @typing.overload
    def __init__(self, /, fieldName: str = ..., type: PySide6.QtCore.QMetaType | PySide6.QtCore.QMetaType.Type = ..., tableName: str = ..., *, value: Optional[Any] = ..., defaultValue: Optional[Any] = ..., name: str | None = ..., metaType: PySide6.QtCore.QMetaType | None = ..., requiredStatus: QSqlField.RequiredStatus | None = ..., readOnly: bool | None = ..., generated: bool | None = ..., autoValue: bool | None = ..., length: int | None = ..., precision: int | None = ...) -> None: ...
    @typing.overload
    def __init__(self, other: QSqlField, /, *, value: Optional[Any] = ..., defaultValue: Optional[Any] = ..., name: str | None = ..., tableName: str | None = ..., metaType: PySide6.QtCore.QMetaType | None = ..., requiredStatus: QSqlField.RequiredStatus | None = ..., readOnly: bool | None = ..., generated: bool | None = ..., autoValue: bool | None = ..., length: int | None = ..., precision: int | None = ...) -> None: ...
    def clear(self, /) -> None: ...
    def defaultValue(self, /) -> Any: ...
    def isAutoValue(self, /) -> bool: ...
    def isGenerated(self, /) -> bool: ...
    def isNull(self, /) -> bool: ...
    def isReadOnly(self, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    def length(self, /) -> int: ...
    def metaType(self, /) -> PySide6.QtCore.QMetaType: ...
    def name(self, /) -> str: ...
    def precision(self, /) -> int: ...
    def requiredStatus(self, /) -> QSqlField.RequiredStatus: ...
    def setAutoValue(self, autoVal: bool, /) -> None: ...
    def setDefaultValue(self, value: Any, /) -> None: ...
    def setGenerated(self, gen: bool, /) -> None: ...
    def setLength(self, fieldLength: int, /) -> None: ...
    def setMetaType(self, type: PySide6.QtCore.QMetaType | PySide6.QtCore.QMetaType.Type, /) -> None: ...
    def setName(self, name: str, /) -> None: ...
    def setPrecision(self, precision: int, /) -> None: ...
    def setReadOnly(self, readOnly: bool, /) -> None: ...
    def setRequired(self, required: bool, /) -> None: ...
    def setRequiredStatus(self, status: QSqlField.RequiredStatus, /) -> None: ...
    def setSqlType(self, type: int, /) -> None: ...
    def setTableName(self, tableName: str, /) -> None: ...
    def setValue(self, value: Any, /) -> None: ...
    def swap(self, other: QSqlField, /) -> None: ...
    def tableName(self, /) -> str: ...
    def typeID(self, /) -> int: ...
    def value(self, /) -> Any: ...
    def __bool__(self) -> bool: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QSqlIndex(QSqlRecord):
    @typing.overload
    def __init__(self, other: QSqlIndex, /, *, name: str | None = ..., cursorName: str | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, cursorName: str = ..., name: str = ...) -> None: ...
    @typing.overload
    def append(self, field: QSqlField, desc: bool, /) -> None: ...
    @typing.overload
    def append(self, field: QSqlField, /) -> None: ...
    def cursorName(self, /) -> str: ...
    def isDescending(self, i: int, /) -> bool: ...
    def name(self, /) -> str: ...
    def setCursorName(self, cursorName: str, /) -> None: ...
    def setDescending(self, i: int, desc: bool, /) -> None: ...
    def setName(self, name: str, /) -> None: ...
    def swap(self, other: QSqlIndex, /) -> None: ...  # type: ignore[override]
    def __copy__(self, /) -> typing_extensions.Self: ...

class QSqlQuery(shiboken6.Object):
    class BatchExecutionMode(enum.Enum):
        ValuesAsColumns = 1
        ValuesAsRows = 0
    @typing.overload
    def __init__(self, /, query: str = ..., db: QSqlDatabase = ..., *, forwardOnly: bool | None = ..., positionalBindingEnabled: bool | None = ..., numericalPrecisionPolicy: QSql.NumericalPrecisionPolicy | None = ...) -> None: ...
    @typing.overload
    def __init__(self, r: QSqlResult, /, *, forwardOnly: bool | None = ..., positionalBindingEnabled: bool | None = ..., numericalPrecisionPolicy: QSql.NumericalPrecisionPolicy | None = ...) -> None: ...
    @typing.overload
    def __init__(self, other: QSqlQuery, /, *, forwardOnly: bool | None = ..., positionalBindingEnabled: bool | None = ..., numericalPrecisionPolicy: QSql.NumericalPrecisionPolicy | None = ...) -> None: ...
    @typing.overload
    def __init__(self, db: QSqlDatabase, /, *, forwardOnly: bool | None = ..., positionalBindingEnabled: bool | None = ..., numericalPrecisionPolicy: QSql.NumericalPrecisionPolicy | None = ...) -> None: ...
    def addBindValue(self, val: Any, /, type: QSql.ParamTypeFlag = ...) -> None: ...
    def at(self, /) -> int: ...
    @typing.overload
    def bindValue(self, pos: int, val: Any, /, type: QSql.ParamTypeFlag = ...) -> None: ...
    @typing.overload
    def bindValue(self, placeholder: str, val: Any, /, type: QSql.ParamTypeFlag = ...) -> None: ...
    @typing.overload
    def boundValue(self, pos: int, /) -> Any: ...
    @typing.overload
    def boundValue(self, placeholder: str, /) -> Any: ...
    def boundValueName(self, pos: int, /) -> str: ...
    def boundValueNames(self, /) -> List[str]: ...
    def boundValues(self, /) -> List[Any]: ...
    def clear(self, /) -> None: ...
    def driver(self, /) -> QSqlDriver: ...
    @typing.overload
    def exec(self, query: str, /) -> bool: ...
    @typing.overload
    def exec(self, /) -> bool: ...
    def execBatch(self, /, mode: QSqlQuery.BatchExecutionMode = ...) -> bool: ...
    @typing.overload
    def exec_(self, arg__1: str, /) -> bool: ...
    @typing.overload
    def exec_(self, /) -> bool: ...
    def executedQuery(self, /) -> str: ...
    def finish(self, /) -> None: ...
    def first(self, /) -> bool: ...
    def isActive(self, /) -> bool: ...
    def isForwardOnly(self, /) -> bool: ...
    @typing.overload
    def isNull(self, name: str, /) -> bool: ...
    @typing.overload
    def isNull(self, field: int, /) -> bool: ...
    def isPositionalBindingEnabled(self, /) -> bool: ...
    def isSelect(self, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    def last(self, /) -> bool: ...
    def lastError(self, /) -> QSqlError: ...
    def lastInsertId(self, /) -> Any: ...
    def lastQuery(self, /) -> str: ...
    def next(self, /) -> bool: ...
    def nextResult(self, /) -> bool: ...
    def numRowsAffected(self, /) -> int: ...
    def numericalPrecisionPolicy(self, /) -> QSql.NumericalPrecisionPolicy: ...
    def prepare(self, query: str, /) -> bool: ...
    def previous(self, /) -> bool: ...
    def record(self, /) -> QSqlRecord: ...
    def result(self, /) -> QSqlResult: ...
    def seek(self, i: int, /, relative: bool = ...) -> bool: ...
    def setForwardOnly(self, forward: bool, /) -> None: ...
    def setNumericalPrecisionPolicy(self, precisionPolicy: QSql.NumericalPrecisionPolicy, /) -> None: ...
    def setPositionalBindingEnabled(self, enable: bool, /) -> None: ...
    def size(self, /) -> int: ...
    def swap(self, other: QSqlQuery, /) -> None: ...
    @typing.overload
    def value(self, name: str, /) -> Any: ...
    @typing.overload
    def value(self, i: int, /) -> Any: ...
    def __copy__(self, /) -> typing_extensions.Self: ...

class QSqlQueryModel(PySide6.QtCore.QAbstractTableModel):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., columnsAboutToBeInserted: typing.Callable = ..., columnsAboutToBeMoved: typing.Callable = ..., columnsAboutToBeRemoved: typing.Callable = ..., columnsInserted: typing.Callable = ..., columnsMoved: typing.Callable = ..., columnsRemoved: typing.Callable = ..., dataChanged: typing.Callable = ..., destroyed: typing.Callable = ..., headerDataChanged: typing.Callable = ..., layoutAboutToBeChanged: typing.Callable = ..., layoutChanged: typing.Callable = ..., modelAboutToBeReset: typing.Callable = ..., modelReset: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., rowsAboutToBeInserted: typing.Callable = ..., rowsAboutToBeMoved: typing.Callable = ..., rowsAboutToBeRemoved: typing.Callable = ..., rowsInserted: typing.Callable = ..., rowsMoved: typing.Callable = ..., rowsRemoved: typing.Callable = ...) -> None: ...
    def beginInsertColumns(self, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, first: int, last: int, /) -> None: ...
    def beginInsertRows(self, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, first: int, last: int, /) -> None: ...
    def beginRemoveColumns(self, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, first: int, last: int, /) -> None: ...
    def beginRemoveRows(self, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, first: int, last: int, /) -> None: ...
    def beginResetModel(self, /) -> None: ...
    def canFetchMore(self, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> bool: ...
    def clear(self, /) -> None: ...
    def columnCount(self, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> int: ...
    def data(self, item: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /, role: PySide6.QtCore.Qt.ItemDataRole | int = ...) -> Any: ...
    def endInsertColumns(self, /) -> None: ...
    def endInsertRows(self, /) -> None: ...
    def endRemoveColumns(self, /) -> None: ...
    def endRemoveRows(self, /) -> None: ...
    def endResetModel(self, /) -> None: ...
    def fetchMore(self, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> None: ...
    def headerData(self, section: int, orientation: PySide6.QtCore.Qt.Orientation, /, role: PySide6.QtCore.Qt.ItemDataRole | int = ...) -> Any: ...
    def indexInQuery(self, item: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /) -> PySide6.QtCore.QModelIndex: ...
    def insertColumns(self, column: int, count: int, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> bool: ...
    def lastError(self, /) -> QSqlError: ...
    def query(self, /) -> QSqlQuery: ...
    def queryChange(self, /) -> None: ...
    @typing.overload
    def record(self, row: int, /) -> QSqlRecord: ...
    @typing.overload
    def record(self, /) -> QSqlRecord: ...
    def refresh(self, /) -> None: ...
    def removeColumns(self, column: int, count: int, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> bool: ...
    def roleNames(self, /) -> Dict[int, PySide6.QtCore.QByteArray]: ...
    def rowCount(self, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> int: ...
    def setHeaderData(self, section: int, orientation: PySide6.QtCore.Qt.Orientation, value: Any, /, role: PySide6.QtCore.Qt.ItemDataRole | int = ...) -> bool: ...
    def setLastError(self, error: QSqlError, /) -> None: ...
    @typing.overload
    def setQuery(self, query: str, /, db: QSqlDatabase = ...) -> None: ...
    @typing.overload
    def setQuery(self, query: QSqlQuery, /) -> None: ...

class QSqlRecord(shiboken6.Object):
    @typing.overload
    def __init__(self, other: QSqlRecord, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def append(self, field: QSqlField, /) -> None: ...
    def clear(self, /) -> None: ...
    def clearValues(self, /) -> None: ...
    def contains(self, name: str, /) -> bool: ...
    def count(self, /) -> int: ...
    @typing.overload
    def field(self, name: str, /) -> QSqlField: ...
    @typing.overload
    def field(self, i: int, /) -> QSqlField: ...
    def fieldName(self, i: int, /) -> str: ...
    def indexOf(self, name: str, /) -> int: ...
    def insert(self, pos: int, field: QSqlField, /) -> None: ...
    def isEmpty(self, /) -> bool: ...
    @typing.overload
    def isGenerated(self, name: str, /) -> bool: ...
    @typing.overload
    def isGenerated(self, i: int, /) -> bool: ...
    @typing.overload
    def isNull(self, name: str, /) -> bool: ...
    @typing.overload
    def isNull(self, i: int, /) -> bool: ...
    def keyValues(self, keyFields: QSqlRecord, /) -> QSqlRecord: ...
    def remove(self, pos: int, /) -> None: ...
    def replace(self, pos: int, field: QSqlField, /) -> None: ...
    @typing.overload
    def setGenerated(self, name: str, generated: bool, /) -> None: ...
    @typing.overload
    def setGenerated(self, i: int, generated: bool, /) -> None: ...
    @typing.overload
    def setNull(self, name: str, /) -> None: ...
    @typing.overload
    def setNull(self, i: int, /) -> None: ...
    @typing.overload
    def setValue(self, name: str, val: Any, /) -> None: ...
    @typing.overload
    def setValue(self, i: int, val: Any, /) -> None: ...
    def swap(self, other: QSqlRecord, /) -> None: ...
    @typing.overload
    def value(self, name: str, /) -> Any: ...
    @typing.overload
    def value(self, i: int, /) -> Any: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QSqlRelation(shiboken6.Object):
    @typing.overload
    def __init__(self, aTableName: str, indexCol: str, displayCol: str, /) -> None: ...
    @typing.overload
    def __init__(self, QSqlRelation: QSqlRelation, /) -> None: ...
    @typing.overload
    def __init__(self, /) -> None: ...
    def displayColumn(self, /) -> str: ...
    def indexColumn(self, /) -> str: ...
    def isValid(self, /) -> bool: ...
    def swap(self, other: QSqlRelation, /) -> None: ...
    def tableName(self, /) -> str: ...
    def __copy__(self, /) -> typing_extensions.Self: ...

class QSqlRelationalDelegate(PySide6.QtWidgets.QStyledItemDelegate):
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, aParent: PySide6.QtCore.QObject | None = ..., closeEditor: typing.Callable = ..., commitData: typing.Callable = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., sizeHintChanged: typing.Callable = ...) -> None: ...
    def createEditor(self, aParent: PySide6.QtWidgets.QWidget, option: PySide6.QtWidgets.QStyleOptionViewItem, index: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /) -> PySide6.QtWidgets.QWidget: ...  # type: ignore[override]
    def setEditorData(self, editor: PySide6.QtWidgets.QWidget, index: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /) -> None: ...
    def setModelData(self, editor: PySide6.QtWidgets.QWidget, model: PySide6.QtCore.QAbstractItemModel, index: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /) -> None: ...

class QSqlRelationalTableModel(QSqlTableModel):
    class JoinMode(enum.Enum):
        InnerJoin = 0
        LeftJoin = 1
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., db: QSqlDatabase = ..., beforeDelete: typing.Callable = ..., beforeInsert: typing.Callable = ..., beforeUpdate: typing.Callable = ..., columnsAboutToBeInserted: typing.Callable = ..., columnsAboutToBeMoved: typing.Callable = ..., columnsAboutToBeRemoved: typing.Callable = ..., columnsInserted: typing.Callable = ..., columnsMoved: typing.Callable = ..., columnsRemoved: typing.Callable = ..., dataChanged: typing.Callable = ..., destroyed: typing.Callable = ..., headerDataChanged: typing.Callable = ..., layoutAboutToBeChanged: typing.Callable = ..., layoutChanged: typing.Callable = ..., modelAboutToBeReset: typing.Callable = ..., modelReset: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., primeInsert: typing.Callable = ..., rowsAboutToBeInserted: typing.Callable = ..., rowsAboutToBeMoved: typing.Callable = ..., rowsAboutToBeRemoved: typing.Callable = ..., rowsInserted: typing.Callable = ..., rowsMoved: typing.Callable = ..., rowsRemoved: typing.Callable = ...) -> None: ...
    def clear(self, /) -> None: ...
    def data(self, item: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /, role: PySide6.QtCore.Qt.ItemDataRole | int = ...) -> Any: ...
    def insertRowIntoTable(self, values: QSqlRecord, /) -> bool: ...
    def orderByClause(self, /) -> str: ...
    def relation(self, column: int, /) -> QSqlRelation: ...
    def relationModel(self, column: int, /) -> QSqlTableModel: ...
    def removeColumns(self, column: int, count: int, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> bool: ...
    def revertRow(self, row: int, /) -> None: ...
    def select(self, /) -> bool: ...
    def selectStatement(self, /) -> str: ...
    def setData(self, item: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, value: Any, /, role: PySide6.QtCore.Qt.ItemDataRole | int = ...) -> bool: ...
    def setJoinMode(self, joinMode: QSqlRelationalTableModel.JoinMode, /) -> None: ...
    def setRelation(self, column: int, relation: QSqlRelation, /) -> None: ...
    def setTable(self, tableName: str, /) -> None: ...
    def updateRowInTable(self, row: int, values: QSqlRecord, /) -> bool: ...

class QSqlResult(shiboken6.Object):
    class BindingSyntax(enum.Enum):
        NamedBinding = 1
        PositionalBinding = 0

    class VirtualHookOperation(enum.Enum): ...  # type: ignore[misc]
    def __init__(self, db: QSqlDriver, /) -> None: ...
    def addBindValue(self, val: Any, type: QSql.ParamTypeFlag, /) -> None: ...
    def at(self, /) -> int: ...
    @typing.overload
    def bindValue(self, pos: int, val: Any, type: QSql.ParamTypeFlag, /) -> None: ...
    @typing.overload
    def bindValue(self, placeholder: str, val: Any, type: QSql.ParamTypeFlag, /) -> None: ...
    @typing.overload
    def bindValueType(self, pos: int, /) -> QSql.ParamTypeFlag: ...
    @typing.overload
    def bindValueType(self, placeholder: str, /) -> QSql.ParamTypeFlag: ...
    def bindingSyntax(self, /) -> QSqlResult.BindingSyntax: ...
    @typing.overload
    def boundValue(self, pos: int, /) -> Any: ...
    @typing.overload
    def boundValue(self, placeholder: str, /) -> Any: ...
    def boundValueCount(self, /) -> int: ...
    def boundValueName(self, pos: int, /) -> str: ...
    def boundValueNames(self, /) -> List[str]: ...
    def boundValues(self, /) -> List[Any]: ...
    def clear(self, /) -> None: ...
    def data(self, i: int, /) -> Any: ...
    def detachFromResultSet(self, /) -> None: ...
    def driver(self, /) -> QSqlDriver: ...
    def exec(self, /) -> bool: ...
    def execBatch(self, /, arrayBind: bool = ...) -> bool: ...
    def exec_(self, /) -> bool: ...
    def executedQuery(self, /) -> str: ...
    def fetch(self, i: int, /) -> bool: ...
    def fetchFirst(self, /) -> bool: ...
    def fetchLast(self, /) -> bool: ...
    def fetchNext(self, /) -> bool: ...
    def fetchPrevious(self, /) -> bool: ...
    def handle(self, /) -> Any: ...
    def hasOutValues(self, /) -> bool: ...
    def isActive(self, /) -> bool: ...
    def isForwardOnly(self, /) -> bool: ...
    def isNull(self, i: int, /) -> bool: ...
    def isPositionalBindingEnabled(self, /) -> bool: ...
    def isSelect(self, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    def lastError(self, /) -> QSqlError: ...
    def lastInsertId(self, /) -> Any: ...
    def lastQuery(self, /) -> str: ...
    def nextResult(self, /) -> bool: ...
    def numRowsAffected(self, /) -> int: ...
    def numericalPrecisionPolicy(self, /) -> QSql.NumericalPrecisionPolicy: ...
    def prepare(self, query: str, /) -> bool: ...
    def record(self, /) -> QSqlRecord: ...
    def reset(self, sqlquery: str, /) -> bool: ...
    def resetBindCount(self, /) -> None: ...
    def savePrepare(self, sqlquery: str, /) -> bool: ...
    def setActive(self, a: bool, /) -> None: ...
    def setAt(self, at: int, /) -> None: ...
    def setForwardOnly(self, forward: bool, /) -> None: ...
    def setLastError(self, e: QSqlError, /) -> None: ...
    def setNumericalPrecisionPolicy(self, policy: QSql.NumericalPrecisionPolicy, /) -> None: ...
    def setPositionalBindingEnabled(self, enable: bool, /) -> None: ...
    def setQuery(self, query: str, /) -> None: ...
    def setSelect(self, s: bool, /) -> None: ...
    def size(self, /) -> int: ...

class QSqlTableModel(QSqlQueryModel):
    class EditStrategy(enum.Enum):
        OnFieldChange = 0
        OnManualSubmit = 2
        OnRowChange = 1
    beforeDelete: typing.ClassVar[PySide6.QtCore.Signal] = ...
    beforeInsert: typing.ClassVar[PySide6.QtCore.Signal] = ...
    beforeUpdate: typing.ClassVar[PySide6.QtCore.Signal] = ...
    primeInsert: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., db: QSqlDatabase = ..., beforeDelete: typing.Callable = ..., beforeInsert: typing.Callable = ..., beforeUpdate: typing.Callable = ..., columnsAboutToBeInserted: typing.Callable = ..., columnsAboutToBeMoved: typing.Callable = ..., columnsAboutToBeRemoved: typing.Callable = ..., columnsInserted: typing.Callable = ..., columnsMoved: typing.Callable = ..., columnsRemoved: typing.Callable = ..., dataChanged: typing.Callable = ..., destroyed: typing.Callable = ..., headerDataChanged: typing.Callable = ..., layoutAboutToBeChanged: typing.Callable = ..., layoutChanged: typing.Callable = ..., modelAboutToBeReset: typing.Callable = ..., modelReset: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., primeInsert: typing.Callable = ..., rowsAboutToBeInserted: typing.Callable = ..., rowsAboutToBeMoved: typing.Callable = ..., rowsAboutToBeRemoved: typing.Callable = ..., rowsInserted: typing.Callable = ..., rowsMoved: typing.Callable = ..., rowsRemoved: typing.Callable = ...) -> None: ...
    def clear(self, /) -> None: ...
    def clearItemData(self, index: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /) -> bool: ...
    def data(self, idx: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /, role: PySide6.QtCore.Qt.ItemDataRole | int = ...) -> Any: ...
    def database(self, /) -> QSqlDatabase: ...
    def deleteRowFromTable(self, row: int, /) -> bool: ...
    def editStrategy(self, /) -> QSqlTableModel.EditStrategy: ...
    def fieldIndex(self, fieldName: str, /) -> int: ...
    def filter(self, /) -> str: ...
    def flags(self, index: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /) -> PySide6.QtCore.Qt.ItemFlag: ...
    def headerData(self, section: int, orientation: PySide6.QtCore.Qt.Orientation, /, role: PySide6.QtCore.Qt.ItemDataRole | int = ...) -> Any: ...
    def indexInQuery(self, item: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /) -> PySide6.QtCore.QModelIndex: ...
    def insertRecord(self, row: int, record: QSqlRecord, /) -> bool: ...
    def insertRowIntoTable(self, values: QSqlRecord, /) -> bool: ...
    def insertRows(self, row: int, count: int, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> bool: ...
    @typing.overload
    def isDirty(self, index: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, /) -> bool: ...
    @typing.overload
    def isDirty(self, /) -> bool: ...
    def orderByClause(self, /) -> str: ...
    def primaryKey(self, /) -> QSqlIndex: ...
    def primaryValues(self, row: int, /) -> QSqlRecord: ...
    @typing.overload
    def record(self, row: int, /) -> QSqlRecord: ...
    @typing.overload
    def record(self, /) -> QSqlRecord: ...
    def removeColumns(self, column: int, count: int, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> bool: ...
    def removeRows(self, row: int, count: int, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> bool: ...
    def revert(self, /) -> None: ...
    def revertAll(self, /) -> None: ...
    def revertRow(self, row: int, /) -> None: ...
    def rowCount(self, /, parent: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex = ...) -> int: ...
    def select(self, /) -> bool: ...
    def selectRow(self, row: int, /) -> bool: ...
    def selectStatement(self, /) -> str: ...
    def setData(self, index: PySide6.QtCore.QModelIndex | PySide6.QtCore.QPersistentModelIndex, value: Any, /, role: PySide6.QtCore.Qt.ItemDataRole | int = ...) -> bool: ...
    def setEditStrategy(self, strategy: QSqlTableModel.EditStrategy, /) -> None: ...
    def setFilter(self, filter: str, /) -> None: ...
    def setPrimaryKey(self, key: QSqlIndex, /) -> None: ...
    def setRecord(self, row: int, record: QSqlRecord, /) -> bool: ...
    def setSort(self, column: int, order: PySide6.QtCore.Qt.SortOrder, /) -> None: ...
    def setTable(self, tableName: str, /) -> None: ...
    def sort(self, column: int, order: PySide6.QtCore.Qt.SortOrder, /) -> None: ...  # type: ignore[override]
    def submit(self, /) -> bool: ...
    def submitAll(self, /) -> bool: ...
    def tableName(self, /) -> str: ...
    def updateRowInTable(self, row: int, values: QSqlRecord, /) -> bool: ...
