import PySide6.QtCore
import PySide6.QtGui
import _typeshed
import collections
import enum
import shiboken6
import typing
import typing_extensions

from typing import Any, Dict, List, Optional, OrderedDict, Set, Tuple, Union
T = typing.TypeVar('T')
P = typing.ParamSpec('P')
class QIntList:
    __opaque_container__: typing.ClassVar[bool] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs): ...
    def capacity(self, *args, **kwargs): ...
    def clear(self, *args, **kwargs): ...
    def constData(self, *args, **kwargs): ...
    def data(self, *args, **kwargs): ...
    def pop_back(self, *args, **kwargs): ...
    def pop_front(self, *args, **kwargs): ...
    def prepend(self, *args, **kwargs): ...
    def push_back(self, *args, **kwargs): ...
    def push_front(self, *args, **kwargs): ...
    def removeFirst(self, *args, **kwargs): ...
    def removeLast(self, *args, **kwargs): ...
    def reserve(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, object) -> None: ...

class QSvgGenerator(PySide6.QtGui.QPaintDevice):
    class SvgVersion(enum.Enum):
        Svg11 = 1
        SvgTiny12 = 0
    @typing.overload
    def __init__(self, version: QSvgGenerator.SvgVersion, /, *, size: PySide6.QtCore.QSize | None = ..., viewBox: PySide6.QtCore.QRectF | None = ..., title: str | None = ..., description: str | None = ..., fileName: str | None = ..., outputDevice: PySide6.QtCore.QIODevice | None = ..., resolution: int | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, size: PySide6.QtCore.QSize | None = ..., viewBox: PySide6.QtCore.QRectF | None = ..., title: str | None = ..., description: str | None = ..., fileName: str | None = ..., outputDevice: PySide6.QtCore.QIODevice | None = ..., resolution: int | None = ...) -> None: ...
    def description(self, /) -> str: ...
    def fileName(self, /) -> str: ...
    def metric(self, metric: PySide6.QtGui.QPaintDevice.PaintDeviceMetric, /) -> int: ...
    def outputDevice(self, /) -> PySide6.QtCore.QIODevice: ...
    def paintEngine(self, /) -> PySide6.QtGui.QPaintEngine: ...
    def resolution(self, /) -> int: ...
    def setDescription(self, description: str, /) -> None: ...
    def setFileName(self, fileName: str, /) -> None: ...
    def setOutputDevice(self, outputDevice: PySide6.QtCore.QIODevice, /) -> None: ...
    def setResolution(self, dpi: int, /) -> None: ...
    def setSize(self, size: PySide6.QtCore.QSize, /) -> None: ...
    def setTitle(self, title: str, /) -> None: ...
    @typing.overload
    def setViewBox(self, viewBox: PySide6.QtCore.QRect, /) -> None: ...
    @typing.overload
    def setViewBox(self, viewBox: PySide6.QtCore.QRectF | PySide6.QtCore.QRect, /) -> None: ...
    def size(self, /) -> PySide6.QtCore.QSize: ...
    def svgVersion(self, /) -> QSvgGenerator.SvgVersion: ...
    def title(self, /) -> str: ...
    def viewBox(self, /) -> PySide6.QtCore.QRect: ...
    def viewBoxF(self, /) -> PySide6.QtCore.QRectF: ...

class QSvgRenderer(PySide6.QtCore.QObject):
    repaintNeeded: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    @typing.overload
    def __init__(self, filename: str, /, parent: PySide6.QtCore.QObject | None = ..., *, viewBox: PySide6.QtCore.QRectF | None = ..., framesPerSecond: int | None = ..., currentFrame: int | None = ..., aspectRatioMode: PySide6.QtCore.Qt.AspectRatioMode | None = ..., options: QtSvg.Option | None = ..., animationEnabled: bool | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., repaintNeeded: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, contents: PySide6.QtCore.QXmlStreamReader, /, parent: PySide6.QtCore.QObject | None = ..., *, viewBox: PySide6.QtCore.QRectF | None = ..., framesPerSecond: int | None = ..., currentFrame: int | None = ..., aspectRatioMode: PySide6.QtCore.Qt.AspectRatioMode | None = ..., options: QtSvg.Option | None = ..., animationEnabled: bool | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., repaintNeeded: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, contents: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /, parent: PySide6.QtCore.QObject | None = ..., *, viewBox: PySide6.QtCore.QRectF | None = ..., framesPerSecond: int | None = ..., currentFrame: int | None = ..., aspectRatioMode: PySide6.QtCore.Qt.AspectRatioMode | None = ..., options: QtSvg.Option | None = ..., animationEnabled: bool | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., repaintNeeded: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, viewBox: PySide6.QtCore.QRectF | None = ..., framesPerSecond: int | None = ..., currentFrame: int | None = ..., aspectRatioMode: PySide6.QtCore.Qt.AspectRatioMode | None = ..., options: QtSvg.Option | None = ..., animationEnabled: bool | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., repaintNeeded: typing.Callable = ...) -> None: ...
    def animated(self, /) -> bool: ...
    def animationDuration(self, /) -> int: ...
    def aspectRatioMode(self, /) -> PySide6.QtCore.Qt.AspectRatioMode: ...
    def boundsOnElement(self, id: str, /) -> PySide6.QtCore.QRectF: ...
    def currentFrame(self, /) -> int: ...
    def defaultSize(self, /) -> PySide6.QtCore.QSize: ...
    def elementExists(self, id: str, /) -> bool: ...
    def framesPerSecond(self, /) -> int: ...
    def isAnimationEnabled(self, /) -> bool: ...
    def isValid(self, /) -> bool: ...
    @typing.overload
    def load(self, filename: str, /) -> bool: ...
    @typing.overload
    def load(self, contents: PySide6.QtCore.QXmlStreamReader, /) -> bool: ...
    @typing.overload
    def load(self, contents: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /) -> bool: ...
    def options(self, /) -> QtSvg.Option: ...
    @typing.overload
    def render(self, p: PySide6.QtGui.QPainter, elementId: str, /, bounds: PySide6.QtCore.QRectF | PySide6.QtCore.QRect = ...) -> None: ...
    @typing.overload
    def render(self, p: PySide6.QtGui.QPainter, bounds: PySide6.QtCore.QRectF | PySide6.QtCore.QRect, /) -> None: ...
    @typing.overload
    def render(self, p: PySide6.QtGui.QPainter, /) -> None: ...
    def setAnimationEnabled(self, enable: bool, /) -> None: ...
    def setAspectRatioMode(self, mode: PySide6.QtCore.Qt.AspectRatioMode, /) -> None: ...
    def setCurrentFrame(self, arg__1: int, /) -> None: ...
    @staticmethod
    def setDefaultOptions(flags: QtSvg.Option, /) -> None: ...
    def setFramesPerSecond(self, num: int, /) -> None: ...
    def setOptions(self, flags: QtSvg.Option, /) -> None: ...
    @typing.overload
    def setViewBox(self, viewbox: PySide6.QtCore.QRect, /) -> None: ...
    @typing.overload
    def setViewBox(self, viewbox: PySide6.QtCore.QRectF | PySide6.QtCore.QRect, /) -> None: ...
    def transformForElement(self, id: str, /) -> PySide6.QtGui.QTransform: ...
    def viewBox(self, /) -> PySide6.QtCore.QRect: ...
    def viewBoxF(self, /) -> PySide6.QtCore.QRectF: ...

class QtSvg(shiboken6.Object):
    class Option(enum.Flag):
        AssumeTrustedSource = 2
        DisableAnimations = 240
        DisableCSSAnimations = 32
        DisableSMILAnimations = 16
        NoOption = 0
        Tiny12FeaturesOnly = 1
    def __init__(self, *args, **kwargs) -> None: ...
