import PySide6.QtCore
import _typeshed
import collections
import enum
import shiboken6
import typing
import typing_extensions

from typing import Any, Dict, List, Optional, OrderedDict, Set, Tuple, Union
T = typing.TypeVar('T')
P = typing.ParamSpec('P')
class QIntList:
    __opaque_container__: typing.ClassVar[bool] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs): ...
    def capacity(self, *args, **kwargs): ...
    def clear(self, *args, **kwargs): ...
    def constData(self, *args, **kwargs): ...
    def data(self, *args, **kwargs): ...
    def pop_back(self, *args, **kwargs): ...
    def pop_front(self, *args, **kwargs): ...
    def prepend(self, *args, **kwargs): ...
    def push_back(self, *args, **kwargs): ...
    def push_front(self, *args, **kwargs): ...
    def removeFirst(self, *args, **kwargs): ...
    def removeLast(self, *args, **kwargs): ...
    def reserve(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, object) -> None: ...

class QTextToSpeech(PySide6.QtCore.QObject):
    class BoundaryHint(enum.Enum):
        Default = 0
        Immediate = 1
        Sentence = 3
        Utterance = 4
        Word = 2

    class Capability(enum.Flag):
        None_ = 0
        PauseResume = 2
        Speak = 1
        Synthesize = 8
        WordByWordProgress = 4

    class ErrorReason(enum.Enum):
        Configuration = 2
        Initialization = 1
        Input = 3
        NoError = 0
        Playback = 4

    class State(enum.Enum):
        Error = 3
        Paused = 2
        Ready = 0
        Speaking = 1
        Synthesizing = 4
    aboutToSynthesize: typing.ClassVar[PySide6.QtCore.Signal] = ...
    engineChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    errorOccurred: typing.ClassVar[PySide6.QtCore.Signal] = ...
    localeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    pitchChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    rateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sayingWord: typing.ClassVar[PySide6.QtCore.Signal] = ...
    stateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    voiceChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    volumeChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    @typing.overload
    def __init__(self, engine: str, params: Dict[str, Any], /, parent: PySide6.QtCore.QObject | None = ..., *, state: QTextToSpeech.State | None = ..., volume: float | None = ..., rate: float | None = ..., pitch: float | None = ..., locale: PySide6.QtCore.QLocale | None = ..., voice: QVoice | None = ..., engineCapabilities: QTextToSpeech.Capability | None = ..., aboutToSynthesize: typing.Callable = ..., destroyed: typing.Callable = ..., engineChanged: typing.Callable = ..., errorOccurred: typing.Callable = ..., localeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., pitchChanged: typing.Callable = ..., rateChanged: typing.Callable = ..., sayingWord: typing.Callable = ..., stateChanged: typing.Callable = ..., voiceChanged: typing.Callable = ..., volumeChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, engine: str, /, parent: PySide6.QtCore.QObject | None = ..., *, state: QTextToSpeech.State | None = ..., volume: float | None = ..., rate: float | None = ..., pitch: float | None = ..., locale: PySide6.QtCore.QLocale | None = ..., voice: QVoice | None = ..., engineCapabilities: QTextToSpeech.Capability | None = ..., aboutToSynthesize: typing.Callable = ..., destroyed: typing.Callable = ..., engineChanged: typing.Callable = ..., errorOccurred: typing.Callable = ..., localeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., pitchChanged: typing.Callable = ..., rateChanged: typing.Callable = ..., sayingWord: typing.Callable = ..., stateChanged: typing.Callable = ..., voiceChanged: typing.Callable = ..., volumeChanged: typing.Callable = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, engine: str | None = ..., state: QTextToSpeech.State | None = ..., volume: float | None = ..., rate: float | None = ..., pitch: float | None = ..., locale: PySide6.QtCore.QLocale | None = ..., voice: QVoice | None = ..., engineCapabilities: QTextToSpeech.Capability | None = ..., aboutToSynthesize: typing.Callable = ..., destroyed: typing.Callable = ..., engineChanged: typing.Callable = ..., errorOccurred: typing.Callable = ..., localeChanged: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., pitchChanged: typing.Callable = ..., rateChanged: typing.Callable = ..., sayingWord: typing.Callable = ..., stateChanged: typing.Callable = ..., voiceChanged: typing.Callable = ..., volumeChanged: typing.Callable = ...) -> None: ...
    def allVoices(self, locale: PySide6.QtCore.QLocale | PySide6.QtCore.QLocale.Language, /) -> List[QVoice]: ...
    @staticmethod
    def availableEngines() -> List[str]: ...
    def availableLocales(self, /) -> List[PySide6.QtCore.QLocale]: ...
    def availableVoices(self, /) -> List[QVoice]: ...
    def engine(self, /) -> str: ...
    def engineCapabilities(self, /) -> QTextToSpeech.Capability: ...
    def enqueue(self, text: str, /) -> int: ...
    def errorReason(self, /) -> QTextToSpeech.ErrorReason: ...
    def errorString(self, /) -> str: ...
    def locale(self, /) -> PySide6.QtCore.QLocale: ...
    def pause(self, /, boundaryHint: QTextToSpeech.BoundaryHint = ...) -> None: ...
    def pitch(self, /) -> float: ...
    def rate(self, /) -> float: ...
    def resume(self, /) -> None: ...
    def say(self, text: str, /) -> None: ...
    def setEngine(self, engine: str, /, params: Dict[str, Any] = ...) -> bool: ...
    def setLocale(self, locale: PySide6.QtCore.QLocale | PySide6.QtCore.QLocale.Language, /) -> None: ...
    def setPitch(self, pitch: float, /) -> None: ...
    def setRate(self, rate: float, /) -> None: ...
    def setVoice(self, voice: QVoice, /) -> None: ...
    def setVolume(self, volume: float, /) -> None: ...
    def state(self, /) -> QTextToSpeech.State: ...
    def stop(self, /, boundaryHint: QTextToSpeech.BoundaryHint = ...) -> None: ...
    def voice(self, /) -> QVoice: ...
    def volume(self, /) -> float: ...

class QTextToSpeechEngine(PySide6.QtCore.QObject):
    errorOccurred: typing.ClassVar[PySide6.QtCore.Signal] = ...
    sayingWord: typing.ClassVar[PySide6.QtCore.Signal] = ...
    stateChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    synthesized: typing.ClassVar[PySide6.QtCore.Signal] = ...
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def availableLocales(self, /) -> List[PySide6.QtCore.QLocale]: ...
    def availableVoices(self, /) -> List[QVoice]: ...
    def capabilities(self, /) -> QTextToSpeech.Capability: ...
    @staticmethod
    def createVoice(name: str, locale: PySide6.QtCore.QLocale | PySide6.QtCore.QLocale.Language, gender: QVoice.Gender, age: QVoice.Age, data: Any, /) -> QVoice: ...
    def errorReason(self, /) -> QTextToSpeech.ErrorReason: ...
    def errorString(self, /) -> str: ...
    def locale(self, /) -> PySide6.QtCore.QLocale: ...
    def pause(self, boundaryHint: QTextToSpeech.BoundaryHint, /) -> None: ...
    def pitch(self, /) -> float: ...
    def rate(self, /) -> float: ...
    def resume(self, /) -> None: ...
    def say(self, text: str, /) -> None: ...
    def setLocale(self, locale: PySide6.QtCore.QLocale | PySide6.QtCore.QLocale.Language, /) -> bool: ...
    def setPitch(self, pitch: float, /) -> bool: ...
    def setRate(self, rate: float, /) -> bool: ...
    def setVoice(self, voice: QVoice, /) -> bool: ...
    def setVolume(self, volume: float, /) -> bool: ...
    def state(self, /) -> QTextToSpeech.State: ...
    def stop(self, boundaryHint: QTextToSpeech.BoundaryHint, /) -> None: ...
    def synthesize(self, text: str, /) -> None: ...
    def voice(self, /) -> QVoice: ...
    @staticmethod
    def voiceData(voice: QVoice, /) -> Any: ...
    def volume(self, /) -> float: ...

class QVoice(shiboken6.Object):
    class Age(enum.Enum):
        Adult = 2
        Child = 0
        Other = 4
        Senior = 3
        Teenager = 1

    class Gender(enum.Enum):
        Female = 1
        Male = 0
        Unknown = 2
    @typing.overload
    def __init__(self, other: QVoice, /, *, name: str | None = ..., gender: QVoice.Gender | None = ..., age: QVoice.Age | None = ..., locale: PySide6.QtCore.QLocale | None = ..., language: PySide6.QtCore.QLocale.Language | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, name: str | None = ..., gender: QVoice.Gender | None = ..., age: QVoice.Age | None = ..., locale: PySide6.QtCore.QLocale | None = ..., language: PySide6.QtCore.QLocale.Language | None = ...) -> None: ...
    def age(self, /) -> QVoice.Age: ...
    @staticmethod
    def ageName(age: QVoice.Age, /) -> str: ...
    def gender(self, /) -> QVoice.Gender: ...
    @staticmethod
    def genderName(gender: QVoice.Gender, /) -> str: ...
    def language(self, /) -> PySide6.QtCore.QLocale.Language: ...
    def locale(self, /) -> PySide6.QtCore.QLocale: ...
    def name(self, /) -> str: ...
    def swap(self, other: QVoice, /) -> None: ...
    def __copy__(self, /) -> typing_extensions.Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lshift__(self, str: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __rlshift__(self, other): ...
    def __rrshift__(self, other): ...
    def __rshift__(self, str: PySide6.QtCore.QDataStream, /) -> PySide6.QtCore.QDataStream: ...
