import PySide6.QtCore
import PySide6.QtGui
import PySide6.QtPrintSupport
import PySide6.QtWebEngineCore
import PySide6.QtWidgets
import _typeshed
import collections
import collections.abc
import typing
import typing_extensions

from typing import Any, Dict, List, Optional, OrderedDict, Set, Tuple, Union
T = typing.TypeVar('T')
P = typing.ParamSpec('P')
class QIntList:
    __opaque_container__: typing.ClassVar[bool] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs): ...
    def capacity(self, *args, **kwargs): ...
    def clear(self, *args, **kwargs): ...
    def constData(self, *args, **kwargs): ...
    def data(self, *args, **kwargs): ...
    def pop_back(self, *args, **kwargs): ...
    def pop_front(self, *args, **kwargs): ...
    def prepend(self, *args, **kwargs): ...
    def push_back(self, *args, **kwargs): ...
    def push_front(self, *args, **kwargs): ...
    def removeFirst(self, *args, **kwargs): ...
    def removeLast(self, *args, **kwargs): ...
    def reserve(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, object) -> None: ...

class QWebEngineView(PySide6.QtWidgets.QWidget):
    iconChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    iconUrlChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    loadFinished: typing.ClassVar[PySide6.QtCore.Signal] = ...
    loadProgress: typing.ClassVar[PySide6.QtCore.Signal] = ...
    loadStarted: typing.ClassVar[PySide6.QtCore.Signal] = ...
    pdfPrintingFinished: typing.ClassVar[PySide6.QtCore.Signal] = ...
    printFinished: typing.ClassVar[PySide6.QtCore.Signal] = ...
    printRequested: typing.ClassVar[PySide6.QtCore.Signal] = ...
    printRequestedByFrame: typing.ClassVar[PySide6.QtCore.Signal] = ...
    renderProcessTerminated: typing.ClassVar[PySide6.QtCore.Signal] = ...
    selectionChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    staticMetaObject: typing.ClassVar[PySide6.QtCore.QMetaObject] = ...
    titleChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    urlChanged: typing.ClassVar[PySide6.QtCore.Signal] = ...
    @typing.overload
    def __init__(self, profile: PySide6.QtWebEngineCore.QWebEngineProfile, /, parent: PySide6.QtWidgets.QWidget | None = ..., *, title: str | None = ..., url: PySide6.QtCore.QUrl | None = ..., iconUrl: PySide6.QtCore.QUrl | None = ..., icon: PySide6.QtGui.QIcon | None = ..., selectedText: str | None = ..., hasSelection: bool | None = ..., zoomFactor: float | None = ..., acceptDrops: bool = ..., accessibleDescription: str = ..., accessibleIdentifier: str = ..., accessibleName: str = ..., autoFillBackground: bool = ..., baseSize: PySide6.QtCore.QSize = ..., childrenRect: PySide6.QtCore.QRect = ..., childrenRegion: PySide6.QtGui.QRegion = ..., contextMenuPolicy: PySide6.QtCore.Qt.ContextMenuPolicy = ..., cursor: PySide6.QtGui.QCursor | PySide6.QtCore.Qt.CursorShape = ..., customContextMenuRequested: typing.Callable = ..., destroyed: typing.Callable = ..., enabled: bool = ..., focus: bool = ..., focusPolicy: PySide6.QtCore.Qt.FocusPolicy = ..., font: PySide6.QtGui.QFont = ..., frameGeometry: PySide6.QtCore.QRect = ..., frameSize: PySide6.QtCore.QSize = ..., fullScreen: bool = ..., geometry: PySide6.QtCore.QRect = ..., height: int = ..., iconChanged: typing.Callable = ..., iconUrlChanged: typing.Callable = ..., inputMethodHints: typing.Any = ..., isActiveWindow: bool = ..., layoutDirection: PySide6.QtCore.Qt.LayoutDirection = ..., loadFinished: typing.Callable = ..., loadProgress: typing.Callable = ..., loadStarted: typing.Callable = ..., locale: PySide6.QtCore.QLocale = ..., maximized: bool = ..., maximumHeight: int = ..., maximumSize: PySide6.QtCore.QSize = ..., maximumWidth: int = ..., minimized: bool = ..., minimumHeight: int = ..., minimumSize: PySide6.QtCore.QSize = ..., minimumSizeHint: PySide6.QtCore.QSize = ..., minimumWidth: int = ..., modal: bool = ..., mouseTracking: bool = ..., normalGeometry: PySide6.QtCore.QRect = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., palette: PySide6.QtGui.QPalette = ..., pdfPrintingFinished: typing.Callable = ..., pos: PySide6.QtCore.QPoint = ..., printFinished: typing.Callable = ..., printRequested: typing.Callable = ..., printRequestedByFrame: typing.Callable = ..., rect: PySide6.QtCore.QRect = ..., renderProcessTerminated: typing.Callable = ..., selectionChanged: typing.Callable = ..., size: PySide6.QtCore.QSize = ..., sizeHint: PySide6.QtCore.QSize = ..., sizeIncrement: PySide6.QtCore.QSize = ..., sizePolicy: PySide6.QtWidgets.QSizePolicy = ..., statusTip: str = ..., styleSheet: str = ..., tabletTracking: bool = ..., titleChanged: typing.Callable = ..., toolTip: str = ..., toolTipDuration: int = ..., updatesEnabled: bool = ..., urlChanged: typing.Callable = ..., visible: bool = ..., whatsThis: str = ..., width: int = ..., windowFilePath: str = ..., windowIcon: PySide6.QtGui.QIcon = ..., windowIconChanged: typing.Callable = ..., windowIconText: str = ..., windowIconTextChanged: typing.Callable = ..., windowModality: PySide6.QtCore.Qt.WindowModality = ..., windowModified: bool = ..., windowOpacity: float = ..., windowTitle: str = ..., windowTitleChanged: typing.Callable = ..., x: int = ..., y: int = ...) -> None: ...
    @typing.overload
    def __init__(self, page: PySide6.QtWebEngineCore.QWebEnginePage, /, parent: PySide6.QtWidgets.QWidget | None = ..., *, title: str | None = ..., url: PySide6.QtCore.QUrl | None = ..., iconUrl: PySide6.QtCore.QUrl | None = ..., icon: PySide6.QtGui.QIcon | None = ..., selectedText: str | None = ..., hasSelection: bool | None = ..., zoomFactor: float | None = ..., acceptDrops: bool = ..., accessibleDescription: str = ..., accessibleIdentifier: str = ..., accessibleName: str = ..., autoFillBackground: bool = ..., baseSize: PySide6.QtCore.QSize = ..., childrenRect: PySide6.QtCore.QRect = ..., childrenRegion: PySide6.QtGui.QRegion = ..., contextMenuPolicy: PySide6.QtCore.Qt.ContextMenuPolicy = ..., cursor: PySide6.QtGui.QCursor | PySide6.QtCore.Qt.CursorShape = ..., customContextMenuRequested: typing.Callable = ..., destroyed: typing.Callable = ..., enabled: bool = ..., focus: bool = ..., focusPolicy: PySide6.QtCore.Qt.FocusPolicy = ..., font: PySide6.QtGui.QFont = ..., frameGeometry: PySide6.QtCore.QRect = ..., frameSize: PySide6.QtCore.QSize = ..., fullScreen: bool = ..., geometry: PySide6.QtCore.QRect = ..., height: int = ..., iconChanged: typing.Callable = ..., iconUrlChanged: typing.Callable = ..., inputMethodHints: typing.Any = ..., isActiveWindow: bool = ..., layoutDirection: PySide6.QtCore.Qt.LayoutDirection = ..., loadFinished: typing.Callable = ..., loadProgress: typing.Callable = ..., loadStarted: typing.Callable = ..., locale: PySide6.QtCore.QLocale = ..., maximized: bool = ..., maximumHeight: int = ..., maximumSize: PySide6.QtCore.QSize = ..., maximumWidth: int = ..., minimized: bool = ..., minimumHeight: int = ..., minimumSize: PySide6.QtCore.QSize = ..., minimumSizeHint: PySide6.QtCore.QSize = ..., minimumWidth: int = ..., modal: bool = ..., mouseTracking: bool = ..., normalGeometry: PySide6.QtCore.QRect = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., palette: PySide6.QtGui.QPalette = ..., pdfPrintingFinished: typing.Callable = ..., pos: PySide6.QtCore.QPoint = ..., printFinished: typing.Callable = ..., printRequested: typing.Callable = ..., printRequestedByFrame: typing.Callable = ..., rect: PySide6.QtCore.QRect = ..., renderProcessTerminated: typing.Callable = ..., selectionChanged: typing.Callable = ..., size: PySide6.QtCore.QSize = ..., sizeHint: PySide6.QtCore.QSize = ..., sizeIncrement: PySide6.QtCore.QSize = ..., sizePolicy: PySide6.QtWidgets.QSizePolicy = ..., statusTip: str = ..., styleSheet: str = ..., tabletTracking: bool = ..., titleChanged: typing.Callable = ..., toolTip: str = ..., toolTipDuration: int = ..., updatesEnabled: bool = ..., urlChanged: typing.Callable = ..., visible: bool = ..., whatsThis: str = ..., width: int = ..., windowFilePath: str = ..., windowIcon: PySide6.QtGui.QIcon = ..., windowIconChanged: typing.Callable = ..., windowIconText: str = ..., windowIconTextChanged: typing.Callable = ..., windowModality: PySide6.QtCore.Qt.WindowModality = ..., windowModified: bool = ..., windowOpacity: float = ..., windowTitle: str = ..., windowTitleChanged: typing.Callable = ..., x: int = ..., y: int = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtWidgets.QWidget | None = ..., *, title: str | None = ..., url: PySide6.QtCore.QUrl | None = ..., iconUrl: PySide6.QtCore.QUrl | None = ..., icon: PySide6.QtGui.QIcon | None = ..., selectedText: str | None = ..., hasSelection: bool | None = ..., zoomFactor: float | None = ..., acceptDrops: bool = ..., accessibleDescription: str = ..., accessibleIdentifier: str = ..., accessibleName: str = ..., autoFillBackground: bool = ..., baseSize: PySide6.QtCore.QSize = ..., childrenRect: PySide6.QtCore.QRect = ..., childrenRegion: PySide6.QtGui.QRegion = ..., contextMenuPolicy: PySide6.QtCore.Qt.ContextMenuPolicy = ..., cursor: PySide6.QtGui.QCursor | PySide6.QtCore.Qt.CursorShape = ..., customContextMenuRequested: typing.Callable = ..., destroyed: typing.Callable = ..., enabled: bool = ..., focus: bool = ..., focusPolicy: PySide6.QtCore.Qt.FocusPolicy = ..., font: PySide6.QtGui.QFont = ..., frameGeometry: PySide6.QtCore.QRect = ..., frameSize: PySide6.QtCore.QSize = ..., fullScreen: bool = ..., geometry: PySide6.QtCore.QRect = ..., height: int = ..., iconChanged: typing.Callable = ..., iconUrlChanged: typing.Callable = ..., inputMethodHints: typing.Any = ..., isActiveWindow: bool = ..., layoutDirection: PySide6.QtCore.Qt.LayoutDirection = ..., loadFinished: typing.Callable = ..., loadProgress: typing.Callable = ..., loadStarted: typing.Callable = ..., locale: PySide6.QtCore.QLocale = ..., maximized: bool = ..., maximumHeight: int = ..., maximumSize: PySide6.QtCore.QSize = ..., maximumWidth: int = ..., minimized: bool = ..., minimumHeight: int = ..., minimumSize: PySide6.QtCore.QSize = ..., minimumSizeHint: PySide6.QtCore.QSize = ..., minimumWidth: int = ..., modal: bool = ..., mouseTracking: bool = ..., normalGeometry: PySide6.QtCore.QRect = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., palette: PySide6.QtGui.QPalette = ..., pdfPrintingFinished: typing.Callable = ..., pos: PySide6.QtCore.QPoint = ..., printFinished: typing.Callable = ..., printRequested: typing.Callable = ..., printRequestedByFrame: typing.Callable = ..., rect: PySide6.QtCore.QRect = ..., renderProcessTerminated: typing.Callable = ..., selectionChanged: typing.Callable = ..., size: PySide6.QtCore.QSize = ..., sizeHint: PySide6.QtCore.QSize = ..., sizeIncrement: PySide6.QtCore.QSize = ..., sizePolicy: PySide6.QtWidgets.QSizePolicy = ..., statusTip: str = ..., styleSheet: str = ..., tabletTracking: bool = ..., titleChanged: typing.Callable = ..., toolTip: str = ..., toolTipDuration: int = ..., updatesEnabled: bool = ..., urlChanged: typing.Callable = ..., visible: bool = ..., whatsThis: str = ..., width: int = ..., windowFilePath: str = ..., windowIcon: PySide6.QtGui.QIcon = ..., windowIconChanged: typing.Callable = ..., windowIconText: str = ..., windowIconTextChanged: typing.Callable = ..., windowModality: PySide6.QtCore.Qt.WindowModality = ..., windowModified: bool = ..., windowOpacity: float = ..., windowTitle: str = ..., windowTitleChanged: typing.Callable = ..., x: int = ..., y: int = ...) -> None: ...
    def back(self, /) -> None: ...
    def closeEvent(self, arg__1: PySide6.QtGui.QCloseEvent, /) -> None: ...
    def contextMenuEvent(self, arg__1: PySide6.QtGui.QContextMenuEvent, /) -> None: ...
    def createStandardContextMenu(self, /) -> PySide6.QtWidgets.QMenu: ...
    def createWindow(self, type: PySide6.QtWebEngineCore.QWebEnginePage.WebWindowType, /) -> QWebEngineView: ...
    def dragEnterEvent(self, e: PySide6.QtGui.QDragEnterEvent, /) -> None: ...
    def dragLeaveEvent(self, e: PySide6.QtGui.QDragLeaveEvent, /) -> None: ...
    def dragMoveEvent(self, e: PySide6.QtGui.QDragMoveEvent, /) -> None: ...
    def dropEvent(self, e: PySide6.QtGui.QDropEvent, /) -> None: ...
    def event(self, arg__1: PySide6.QtCore.QEvent, /) -> bool: ...
    @typing.overload
    def findText(self, subString: str, options: PySide6.QtWebEngineCore.QWebEnginePage.FindFlag, resultCallback: collections.abc.Callable[..., typing.Any], /) -> None: ...
    @typing.overload
    def findText(self, subString: str, /, options: PySide6.QtWebEngineCore.QWebEnginePage.FindFlag = ...) -> None: ...
    @staticmethod
    def forPage(page: PySide6.QtWebEngineCore.QWebEnginePage, /) -> QWebEngineView: ...
    def forward(self, /) -> None: ...
    def hasSelection(self, /) -> bool: ...
    def hideEvent(self, arg__1: PySide6.QtGui.QHideEvent, /) -> None: ...
    def history(self, /) -> PySide6.QtWebEngineCore.QWebEngineHistory: ...
    def icon(self, /) -> PySide6.QtGui.QIcon: ...
    def iconUrl(self, /) -> PySide6.QtCore.QUrl: ...
    def lastContextMenuRequest(self, /) -> PySide6.QtWebEngineCore.QWebEngineContextMenuRequest: ...
    @typing.overload
    def load(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    @typing.overload
    def load(self, request: PySide6.QtWebEngineCore.QWebEngineHttpRequest, /) -> None: ...
    def page(self, /) -> PySide6.QtWebEngineCore.QWebEnginePage: ...
    def pageAction(self, action: PySide6.QtWebEngineCore.QWebEnginePage.WebAction, /) -> PySide6.QtGui.QAction: ...
    def print(self, printer: PySide6.QtPrintSupport.QPrinter, /) -> None: ...
    def printToPdf(self, filePath: str, /, layout: PySide6.QtGui.QPageLayout = ..., ranges: PySide6.QtGui.QPageRanges = ...) -> None: ...
    def reload(self, /) -> None: ...
    def selectedText(self, /) -> str: ...
    def setContent(self, data: PySide6.QtCore.QByteArray | bytes | bytearray | memoryview, /, mimeType: str = ..., baseUrl: PySide6.QtCore.QUrl | str = ...) -> None: ...
    def setHtml(self, html: str, /, baseUrl: PySide6.QtCore.QUrl | str = ...) -> None: ...
    def setPage(self, page: PySide6.QtWebEngineCore.QWebEnginePage, /) -> None: ...
    def setUrl(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def setZoomFactor(self, factor: float, /) -> None: ...
    def settings(self, /) -> PySide6.QtWebEngineCore.QWebEngineSettings: ...
    def showEvent(self, arg__1: PySide6.QtGui.QShowEvent, /) -> None: ...
    def sizeHint(self, /) -> PySide6.QtCore.QSize: ...
    def stop(self, /) -> None: ...
    def title(self, /) -> str: ...
    def triggerPageAction(self, action: PySide6.QtWebEngineCore.QWebEnginePage.WebAction, /, checked: bool = ...) -> None: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...
    def zoomFactor(self, /) -> float: ...
