import Boost.Python
import pxr.UsdGeom
from typing import Any, ClassVar, overload

class AssetPreviewsAPI(pxr.Usd.APISchemaBase):
    class Thumbnails(Boost.Python.instance):
        __instance_size__: ClassVar[int] = ...
        defaultImage: Any
        @overload
        def __init__(self, arg1: object) -> None: ...
        @overload
        def __init__(self, arg1: object, defaultImage: AssetPath = ...) -> None: ...
        def __reduce__(self) -> Any: ...
    __instance_size__: ClassVar[int] = ...
    @overload
    def __init__(self, arg1: object) -> None: ...
    @overload
    def __init__(self, arg1: object, prim: Prim) -> None: ...
    @overload
    def __init__(self, arg1: object, schemaObj: SchemaBase) -> None: ...
    def Apply(self, prim: Prim) -> AssetPreviewsAPI: ...
    def CanApply(self, prim: Prim) -> _CanApplyResult: ...
    def ClearDefaultThumbnails(self, arg1: AssetPreviewsAPI) -> None: ...
    def Get(self, stage: Stage, path: Path) -> AssetPreviewsAPI: ...
    @overload
    def GetAssetDefaultPreviews(self, layerPath: object) -> AssetPreviewsAPI: ...
    @overload
    def GetAssetDefaultPreviews(self, layer: Layer) -> AssetPreviewsAPI: ...
    def GetDefaultThumbnails(self, arg1: AssetPreviewsAPI) -> object: ...
    def GetSchemaAttributeNames(self, includeInherited: bool = ...) -> list: ...
    def SetDefaultThumbnails(self, arg1: AssetPreviewsAPI, thumbnails: Thumbnails) -> None: ...
    def _GetStaticTfType(self) -> Type: ...
    def __bool__(self, arg1: AssetPreviewsAPI) -> object: ...
    def __reduce__(self) -> Any: ...

class SpatialAudio(pxr.UsdGeom.Xformable):
    __instance_size__: ClassVar[int] = ...
    @overload
    def __init__(self, arg1: object) -> None: ...
    @overload
    def __init__(self, arg1: object, prim: Prim) -> None: ...
    @overload
    def __init__(self, arg1: object, schemaObj: SchemaBase) -> None: ...
    def CreateAuralModeAttr(self, arg1: SpatialAudio, defaultValue: object = ..., writeSparsely: bool = ...) -> Attribute: ...
    def CreateEndTimeAttr(self, arg1: SpatialAudio, defaultValue: object = ..., writeSparsely: bool = ...) -> Attribute: ...
    def CreateFilePathAttr(self, arg1: SpatialAudio, defaultValue: object = ..., writeSparsely: bool = ...) -> Attribute: ...
    def CreateGainAttr(self, arg1: SpatialAudio, defaultValue: object = ..., writeSparsely: bool = ...) -> Attribute: ...
    def CreateMediaOffsetAttr(self, arg1: SpatialAudio, defaultValue: object = ..., writeSparsely: bool = ...) -> Attribute: ...
    def CreatePlaybackModeAttr(self, arg1: SpatialAudio, defaultValue: object = ..., writeSparsely: bool = ...) -> Attribute: ...
    def CreateStartTimeAttr(self, arg1: SpatialAudio, defaultValue: object = ..., writeSparsely: bool = ...) -> Attribute: ...
    def Define(self, stage: Stage, path: Path) -> SpatialAudio: ...
    def Get(self, stage: Stage, path: Path) -> SpatialAudio: ...
    def GetAuralModeAttr(self, arg1: SpatialAudio) -> Attribute: ...
    def GetEndTimeAttr(self, arg1: SpatialAudio) -> Attribute: ...
    def GetFilePathAttr(self, arg1: SpatialAudio) -> Attribute: ...
    def GetGainAttr(self, arg1: SpatialAudio) -> Attribute: ...
    def GetMediaOffsetAttr(self, arg1: SpatialAudio) -> Attribute: ...
    def GetPlaybackModeAttr(self, arg1: SpatialAudio) -> Attribute: ...
    def GetSchemaAttributeNames(self, includeInherited: bool = ...) -> list: ...
    def GetStartTimeAttr(self, arg1: SpatialAudio) -> Attribute: ...
    def _GetStaticTfType(self) -> Type: ...
    def __bool__(self, arg1: SpatialAudio) -> object: ...
    def __reduce__(self) -> Any: ...

class Tokens(Boost.Python.instance):
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    @property
    def AssetPreviewsAPI(self) -> Any: ...
    @property
    def SpatialAudio(self) -> Any: ...
    @property
    def auralMode(self) -> Any: ...
    @property
    def defaultImage(self) -> Any: ...
    @property
    def endTime(self) -> Any: ...
    @property
    def filePath(self) -> Any: ...
    @property
    def gain(self) -> Any: ...
    @property
    def loopFromStage(self) -> Any: ...
    @property
    def loopFromStart(self) -> Any: ...
    @property
    def loopFromStartToEnd(self) -> Any: ...
    @property
    def mediaOffset(self) -> Any: ...
    @property
    def nonSpatial(self) -> Any: ...
    @property
    def onceFromStart(self) -> Any: ...
    @property
    def onceFromStartToEnd(self) -> Any: ...
    @property
    def playbackMode(self) -> Any: ...
    @property
    def previewThumbnails(self) -> Any: ...
    @property
    def previewThumbnailsDefault(self) -> Any: ...
    @property
    def previews(self) -> Any: ...
    @property
    def spatial(self) -> Any: ...
    @property
    def startTime(self) -> Any: ...
    @property
    def thumbnails(self) -> Any: ...

class _CanApplyResult(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    def __init__(self, arg1: object, arg2: bool, arg3: object) -> None: ...
    def __bool__(self, arg1: _CanApplyResult) -> bool: ...
    @overload
    def __eq__(self, arg1: _CanApplyResult, arg2: bool) -> object: ...
    @overload
    def __eq__(self, arg1: _CanApplyResult, arg2: bool) -> object: ...
    def __getitem__(self, arg1: _CanApplyResult, arg2: int) -> object: ...
    @overload
    def __ne__(self, arg1: _CanApplyResult, arg2: bool) -> object: ...
    @overload
    def __ne__(self, arg1: _CanApplyResult, arg2: bool) -> object: ...
    def __reduce__(self) -> Any: ...
    @property
    def whyNot(self) -> Any: ...