from typing import Dict
# mypy: disable-error-code="misc, override, attr-defined, no-redef, assignment"


def exportConfiguration() -> Dict[str, str]: ...
def get(key: str) -> str: ...
def has(key: str) -> bool: ...
def set(key: str, value: str) -> None: ...