from _typeshed import Incomplete

class EnterMayaScope:
    model: Incomplete
    active: Incomplete
    def __init__(self, model) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None): ...

class EnterLightScope:
    model: Incomplete
    active: Incomplete
    def __init__(self, model) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None): ...
