from maya.app.renderSetup.views.lightEditor.node import *
from _typeshed import Incomplete

LIGHT_COLLECTION_PREFIX: str
LIGHT_COLLECTION_SUFFIX: str
ENABLE_LIGHT_SOURCE_CMD: Incomplete
kLightCollectionNameError: Incomplete

class LightAttributes(NodeAttributes):
    def __init__(self) -> None: ...

class LightSource(Node):
    updateAttrOnIdleCallbackId: int
    nodePlugDirtyCallbackId: int
    nodePreRemovalCallbackId: int
    shapeNameChangedCallbackId: int
    updateAttrName: Incomplete
    shapeHandle: Incomplete
    def __init__(self, model, transformObj, shapeObj, attributes) -> None: ...
    def __del__(self) -> None: ...
    lightType: Incomplete
    def initialize(self, shapeObj) -> None: ...
    def dispose(self) -> None: ...
    def mayaName(self): ...
    def typeId(self): ...
    def doDelete(self) -> None: ...
    def data(self, role, column): ...
    def getLightType(self): ...
    def nameChanged(self, oldName) -> None: ...
    def getShape(self): ...
    def getShapeName(self): ...
    def enable(self, value) -> None: ...
    def isolate(self, value) -> None: ...
    def flags(self, index): ...
