from ._nuke_color import *
from . import callbacks as callbacks
from typing import Any

defaultLUTMappers: Any

class ColorspaceLookupError(Exception): ...

def addDefaultColorspaceMapper(call, args=..., kwargs=..., nodeClass: str = ...) -> None: ...
def removeDefaultColorspaceMapper(call, args=..., kwargs=..., nodeClass: str = ...) -> None: ...
def defaultColorspaceMapper(colorspace, dataTypeHint): ...
def getColorspaceList(colorspaceKnob): ...
