def pluginAddPath(args, addToSysPath: bool = ...) -> None: ...
def pluginAppendPath(args, addToSysPath: bool = ...) -> None: ...
def dependencies(nodes, what=...): ...
def dependentNodes(what=..., nodes=..., evaluateAll: bool = ...): ...
def selectConnectedNodes() -> None: ...
