import maya.app.renderSetup.common.test.renderSetupTest as Test
from _typeshed import Incomplete

class proxyChildren:
    i: int
    item: Incomplete
    n: Incomplete
    def __init__(self, item) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...
    next = __next__

def getProxy(node): ...
def assertConsistency(unitTest, dataModel, proxy) -> None: ...

class ViewRenderSetupTest(Test.RenderSetupTest):
    def __init__(self, testName) -> None: ...
    @classmethod
    def setUpClass(cls) -> None: ...
    @classmethod
    def tearDownClass(cls) -> None: ...
    centralWidget: Incomplete
    def setUp(self) -> None: ...
    propertyEditor: Incomplete
    mainWindow: Incomplete
    def tearDown(self) -> None: ...
    def renderSetupWindow(self): ...
