from PySide6.QtWidgets import QLineEdit
from _typeshed import Incomplete

class CollectionFilterLineEdit(QLineEdit):
    def __init__(self, text: Incomplete | None = None, parent: Incomplete | None = None) -> None: ...
    def dragEnterEvent(self, event) -> None: ...
    def dragMoveEvent(self, event) -> None: ...
    def dropEvent(self, event) -> None: ...
