from _typeshed import Incomplete

vSpc: int
hSpc: int
buttonWidth: int
parentForm: str
red: Incomplete
black: Incomplete

def mayaImageFileExtensions(): ...
def nativeMode(): ...
def ociov2Enabled(): ...

class Rule:
    name: Incomplete
    def __init__(self, name) -> None: ...
    def canDelete(self): ...

class OpaqueRule(Rule):
    def __init__(self, name) -> None: ...
    def canDelete(self): ...
    def createUI(self) -> None: ...

class ColorSpaceRule(Rule):
    def __init__(self, name) -> None: ...
    def setColorSpace(self, colorSpace) -> None: ...
    def getColorSpace(self): ...
    colorSpace: Incomplete
    def onInputColorSpaceChangeOCIOv2(self, newInputSpace, newInputSpaceDescription, *args) -> None: ...
    def onInputColorSpaceChangeSynColor(self, *args) -> None: ...
    def onRemoveColorSpace(self, *args) -> None: ...
    def validateColorSpace(self, colorSpace): ...
    def setMenuValidColorSpace(self, valid) -> None: ...
    def createColorSpacePopupMenu(self, colorSpaces, parentMenu) -> None: ...
    def createColorSpaceMenu(self) -> None: ...
    def fileRuleLayout(self, extWidget, patternWidget) -> None: ...

class DefaultRule(ColorSpaceRule):
    def __init__(self, name) -> None: ...
    def createUI(self) -> None: ...

class FilePathRule(ColorSpaceRule):
    pattern: str
    def __init__(self, name) -> None: ...
    def setPattern(self, pattern) -> None: ...
    def getPattern(self): ...
    def setExtension(self, extension) -> None: ...
    def getExtension(self): ...
    extension: Incomplete
    def canDelete(self): ...
    def onPatternChange(self, *args) -> None: ...
    def onExtensionChange(self, *args) -> None: ...
    def createUI(self) -> None: ...

class ChainRule(Rule):
    def __init__(self, name: str = '') -> None: ...
    def isReadOnly(self): ...
    def positionToIndex(self, position): ...
    def indexToPosition(self, index): ...
    def updateScrollList(self) -> None: ...
    def appendRule(self, rule) -> None: ...
    def createHandlerRuleUI(self) -> None: ...
    def updateHandlerRuleUI(self) -> None: ...
    def selectRule(self, position) -> None: ...
    def createUI(self) -> None: ...
    def onAddRule(self, *args) -> None: ...
    def onAddFilePathRule(self, *args) -> None: ...
    def onDeleteRule(self, *args) -> None: ...
    def onUp(self, *args) -> None: ...
    def onDown(self, *args) -> None: ...
    def onSelect(self, *args) -> None: ...
    def onReapply(self, *args) -> None: ...

def build() -> None: ...
def createUI() -> None: ...
