from _typeshed import Incomplete
from maya.app.mayabullet.Trace import Trace as Trace

bulletDagPaths: Incomplete
bulletCutCopyPasteCBId: int

def handlePreCut() -> None: ...
def handlePreCopy() -> None: ...
def handlePostCopy() -> None: ...
def handlePrePaste() -> None: ...
def handlePostPaste() -> None: ...
def getScriptDir(): ...
def rawScriptResultToPath(rawResult): ...
def bulletCutCopyPasteCB(object, clientData) -> None: ...
