from _typeshed import Incomplete
from maya.app.mayabullet.Trace import Trace as Trace

solverDisplayOptionsMap: Incomplete

def attrName(attr): ...
def optionsColumnCtrl(attr): ...
def optionsFormCtrl(attr): ...
def optionsExist(attr): ...

class AEOptionsChanged:
    def __init__(self, attrName, control, optionValue) -> None: ...
    def __call__(self, *args, **kw) -> None: ...

class AEDeleteControl:
    def __init__(self, ctrl) -> None: ...
    def __call__(self) -> None: ...

def AEOptions(attr, optionsMap, deleteCB: Incomplete | None = None, replace: bool = False) -> None: ...
