from _typeshed import Incomplete

gui: Incomplete
widgets: Incomplete
CHANNELS_ALL: int
CHANNELS_CURRENT: int

def getAllChannels(): ...
def getAllUVChannels(): ...
def isPtexProject(): ...
def hasMultiChannelLayer(layer_stack): ...
def getShotsInAllChannels(): ...
def snapshotChannels(channel_list, shot_name): ...
def snapshotAllChannels(shot_name) -> None: ...
def showNewSnapshotGUI(channels=..., title: str = ...) -> None: ...
def checkForAutosnapshot() -> None: ...
def deleteAll(confirm: bool = ...) -> None: ...
def disconnectNoLogs(signal, response) -> None: ...

class SnapshotUI(widgets.QWidget):
    def __init__(self) -> None: ...

def clearOrBakePaint() -> None: ...
