import maya.app.renderSetup.lightEditor.model.item as itemModel
import maya.app.renderSetup.model.nodeList as nodeList
from _typeshed import Incomplete

kChildAttached: Incomplete
kChildDetached: Incomplete

class LightGroup(nodeList.ListBase, itemModel.LightItemBase):
    kTypeId: Incomplete
    kTypeName: str
    items: Incomplete
    firstItem: Incomplete
    lastItem: Incomplete
    @classmethod
    def creator(cls): ...
    @staticmethod
    def initializer() -> None: ...
    originalImportName: Incomplete
    def __init__(self) -> None: ...
    def dispose(self, deleteLight) -> None: ...
    def isAbstractClass(self): ...
    def activate(self) -> None: ...
    def deactivate(self) -> None: ...
    def rename(self, newName) -> None: ...
    def appendChild(self, child) -> None: ...
    def attachChild(self, pos, child) -> None: ...
    def detachChild(self, child) -> None: ...
    def getChildren(self, cls=...): ...
    def isAcceptableChild(self, model): ...
