import maya.app.renderSetup.lightEditor.model.item as itemModel
from _typeshed import Incomplete

kLightHasNoVisibilityAttribute: Incomplete
kVisibilityConnectionExists: Incomplete

class LightItem(itemModel.LightItemBase):
    kTypeId: Incomplete
    kTypeName: str
    light: Incomplete
    @classmethod
    def creator(cls): ...
    @staticmethod
    def initializer() -> None: ...
    needUIRebuildWhenChanged: bool
    def __init__(self) -> None: ...
    def dispose(self, deleteLight) -> None: ...
    def isAbstractClass(self): ...
    def registerCallbacks(self, lightShapeObj) -> None: ...
    def unregisterCallbacks(self) -> None: ...
    def setLightShape(self, lightShapeObj) -> None: ...
    def getLightShape(self): ...
    def linkedVisibility(self): ...
    def getLightTransform(self): ...
    def getLightName(self, fullPath: bool = False): ...
    def getLightTransformName(self, fullPath: bool = False): ...
    def getLightType(self): ...
    def rename(self, newName) -> None: ...
    def isAcceptableChild(self, model): ...
    def getAttrName(self, index): ...
    def getAttrPlug(self, index): ...
    def getAttrValue(self, index): ...
    def getTransformPlug(self, attrName): ...
    def getShapePlug(self, attrName): ...
    def isConnected(self, index): ...
