from _typeshed import Incomplete

def rebuild() -> None: ...
def mayaLights(): ...
def pluginLights(): ...
def lights(): ...
def isLight(mayaObj): ...
def isLightEditorItem(mayaObj): ...
def isValidLightShapeObject(mayaObj): ...
def findLightShapeObject(transformObj): ...
def isValidLightTransformObject(mayaObj): ...
def findLightTransformObject(shapeObj): ...
def findAllLightTransforms(): ...
def getCreateCmd(lightType): ...
def getIcon(lightType): ...
def getAllAttributes(): ...
def getAttributesForLightType(lightType): ...
def excludeFromUI(nodeType): ...

lightTypes: Incomplete
mayaLightTypes: Incomplete
pluginLightTypes: Incomplete
uiExcludedLightTypes: Incomplete
lightConstructionData: Incomplete
attributesForLightType: Incomplete
allLightAttributes: Incomplete
dataTypeConversionTable: Incomplete
